### ISSUE TITLE
404 page, after new repo created

### ISSUE THREAD

**Issue by renatn** [gogs/gogs#107]
Hi!

I tried to use GOGS on Windows Server 2003 with SQLITE3 storage. I use version (0.3.0.0422 Alpha) which build from sources, because official binary does not started.

After create repo it redirect me to page 404.

In log:

> [E] RepoAssignment invalid repo: '<nil>'

MsGit 1.9.2.preview20140411

**Comment by MerreM** [comment]
I've been getting this too.

It works if I add ".git" to the end of the url though.

**Comment by Unknwon** [comment]
Hi @MerreM , this has been fixed in `master` branch.
