### ISSUE TITLE
Git clone with SSH ask for password and hung up unexpectedly

### ISSUE THREAD

**Issue by laofo** [gogs/gogs#108]
Git clone with SSH ask for password and hung up unexpectedly

i want to clone the repo with ssh but it asks for the password.
Password was given but it's failed finally.

> laofo@gitlab01:~$ git clone git@10.175.28.107:laofo/shanghai.git 
> fatal: destination path 'shanghai' already exists and is not an empty directory.
> laofo@gitlab01:~$ git clone git@10.175.28.107:laofo/shanghai.git  shanghai_ssh
> Cloning into 'shanghai_ssh'...
> git@10.175.28.107's password: 
> fatal: 'laofo/shanghai.git' does not appear to be a git repository
> fatal: The remote end hung up unexpectedly
> laofo@gitlab01:~$ 

However, I could clone the repo through the full path

> laofo@gitlab01:~$ git clone git@10.175.28.107:/home/git/gogs-repositories/laofo/shanghai.git shanghai_shared
> Cloning into 'shanghai_shared'...
> git@10.175.28.107's password: 
> remote: Counting objects: 14, done.
> remote: Compressing objects: 100% (11/11), done.
> remote: Total 14 (delta 3), reused 0 (delta 0)
> Receiving objects: 100% (14/14), 5.05 KiB, done.
> Resolving deltas: 100% (3/3), done.

Here is the env and debug information:

---

2014 GoGits · Version: 0.3.0.0421 Alpha install from source code
ubuntu 14.04 LTFS
laofo@gitlab01:~$ uname -a
Linux gitlab01 3.8.0-38-generic #56~precise1-Ubuntu SMP Thu Mar 13 16:22:48 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
laofo@gitlab01:~$ ssh-add -l
2048 a3:c1:8e:5a:f5:16:c3:9b:92:65:8d:a5:c9:15:8f:22 /home/laofo/.ssh/id_rsa (RSA)
laofo@gitlab01:~$ ssh -vt git@10.175.28.107
OpenSSH_5.9p1 Debian-5ubuntu1.3, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /home/laofo/.ssh/config
debug1: /home/laofo/.ssh/config line 1: Applying options for 10.175.28.107
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 10.175.28.107 [10.175.28.107] port 22.
debug1: Connection established.
debug1: identity file /home/laofo/.ssh/id_rsa type 1
debug1: Checking blacklist file /usr/share/ssh/blacklist.RSA-2048
debug1: Checking blacklist file /etc/ssh/blacklist.RSA-2048
debug1: identity file /home/laofo/.ssh/id_rsa-cert type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6p1 Ubuntu-2ubuntu1
debug1: match: OpenSSH_6.6p1 Ubuntu-2ubuntu1 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.3
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5 none
debug1: kex: client->server aes128-ctr hmac-md5 none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA a6:4f:6f:ad:81:fd:0b:46:6f:a3:d1:bf:4c:0d:43:97
debug1: Host '10.175.28.107' is known and matches the ECDSA host key.
debug1: Found key in /home/laofo/.ssh/known_hosts:1
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/laofo/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
git@10.175.28.107's password: 
debug1: Authentication succeeded (password).
Authenticated to 10.175.28.107 ([10.175.28.107]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic i686)
- Documentation:  https://help.ubuntu.com/
  
  System information as of Wed Apr 23 04:02:11 EDT 2014
  
  System load:  0.0               Processes:           89
  Usage of /:   36.5% of 6.50GB   Users logged in:     2
  Memory usage: 14%               IP address for eth0: 10.175.28.107
  Swap usage:   0%
  
  Graph this data and manage this system at:
    https://landscape.canonical.com/

3 packages can be updated.
0 updates are security updates.

Last login: Wed Apr 23 03:48:17 2014 from 10.175.29.148
git@gogs32:~$

**Comment by chinglinwen** [comment]
I encounter the same problem ( I move gogs and gogs-repo to another server )

[root@test t]# git clone root@192.168.100.93:wen/test.git
Initialized empty Git repository in /root/t/test/.git/
fatal: 'wen/test.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

login to the admin panel, do the following will solve the problem
Rewrite '.ssh/authorized_keys' file
Rewrite all update hook of repositories

[root@test t]# git clone root@192.168.100.93:wen/test.git
Initialized empty Git repository in /root/t/test/.git/
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 34 (delta 11), reused 0 (delta 0)
Receiving objects: 100% (34/34), 14.37 KiB, done.
Resolving deltas: 100% (11/11), done.
[root@test t]#
