### ISSUE TITLE
gogs overwrite  my ssh configure  on my mac?

### ISSUE THREAD

**Issue by zhuangya** [gogs/gogs#122]
i just wanted to try gogs on my mac for fun, but after setting up the server, create a project, try to push it via cli, the `git push` freezes.

and after that, when i try to ssh myself, here is what i get:

```
> ssh localhost
PTY allocation request failed on channel 0
2014/04/25 11:51:34 [conf.go:340] [D] LDAP AUTHENTICATION NOT activated
Hi ya ! You've successfully authenticated, but Gogs does not provide shell access.
Connection to localhost closed.

```

looks like gogs overwrite my ssh config or something?

**Comment by EvWill** [comment]
Hmmm, I am getting this same error 
```PTY allocation request failed on channel 0
Hi evwill ! You've successfully authenticated, but Gogs does not provide shell access.```

Now I can't SSH into my VPS. Anyone know what I did wrong and how I can fix this?

**Comment by Unknwon** [comment]
@EvWill this is why Gogs sets default user to `git`. You may need to log in with password then kill Gogs instance.

**Comment by EvWill** [comment]
Thanks :+1: Thought so

**Comment by Unknwon** [comment]
@EvWill no problem!
