### ISSUE TITLE
Use custom configuration on install?

### ISSUE THREAD

**Issue by geerlingguy** [gogs/gogs#145]
On the [Configuration and run] page, it's recommended that users save customized config to `custom/conf/app.ini`. In the interest of easier automated deployment, (for example, see my [Gogs Ansible/Vagrant VM example](https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/gogs)), it would be good if the following could be implemented:
1. If `custom/conf/app.ini` already exists on initial installation/first run, use the values defined in that file for the install configuration (my custom settings weren't picked up until after the initial install).
2. Allow for a custom/universal app.ini location outside the application directory (outside of `/path/to/gogs`). Maybe `/etc/gogs/app.ini` or something like that?

Gogs is pretty nice, and fast—the one major hurdle I have in testing it with my own infrastructure is the required manual intervention in the install/configure process.

**Comment by fujohnwang** [comment]
any update? 
commandline or GOGS_CONFIG=${SOMEPATH} , is this done in new revision?

**Comment by Unknwon** [comment]
@fujohnwang You can use

```
--config value, -c value  Custom configuration file path (default: "custom/conf/app.ini")
```

**Comment by caiwan** [comment]
One thing that certainly unclear for me after digging the docs are how can you change or reload the config after you've already installed the app?
As far as I could get
- The config is being built into the binary
- The custom config can be placed `custom/conf/app.ini`
What I was not aware of If I change the application config at `custom/conf/app.ini` is there any chance to rebuild the config by hand?

**Comment by Unknwon** [comment]
@caiwan what is "rebuild the config"?

**Comment by caiwan** [comment]
Basically, I'd like to change the config after the the app has been installed. Is there any chance to do it so?

**Comment by fujohnwang** [comment]
config is not state, this requirement is not a proper one, in my opinion. ;0)

**Comment by Unknwon** [comment]
@caiwan restart the process will reload the config.
