### ISSUE TITLE
Public repo not navigable by anonymous user

### ISSUE THREAD

**Issue by tubia** [gogs/gogs#151]
Hi,
I created a repo with public access.
For anonymous user is possible to see the main page of the repo, for example `http://mydomain/johndoe/johndoerepo` but non to navigate through. -> request for log in.

**Comment by myfairsyer** [comment]
> What the value of https://github.com/gogits/gogs/blob/master/conf/app.ini#L58 in custom/conf/app.ini?

Permalink to the version back then: https://github.com/gogits/gogs/blob/62d23e91541550d0478c4884696e918a0e818b4f/conf/app.ini#L58
