### ISSUE TITLE
Deleting a branch crashes gogs

### ISSUE THREAD

**Issue by badboy** [gogs/gogs#155]
Hi,
I just played around with gogs. It's already looking great, but I run into a few issues.

I can crash the server by simply trying to delete a branch.
Steps to reproduce (I run gogs in a VM with a custom domain behind an nginx proxy):

```
$ git clone https://gogs.dev/jer/repo.git
$ cd repo
$ echo "gogs rocks" > README.md ; git add README.md; git commit -m init
$ git push origin master
...
$ git push origin :master
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

Console output of gogs:

```
[martini] Started POST /jer/test-repo.git/git-receive-pack
2014/05/02 12:46:34 [FATAL][github.com/gogits/gogs/models] update.go:39: runUpdate GetCommit of newCommitId: Object not found 0000000000000000000000000000000000000000
```

this should be handled more gracefully. GitHub for instance rejects deletions if it is the default branch. Non-default branches are handled as expected there.

**Comment by mkaito** [comment]
In case this ever becomes relevant again, this is what drone does to set up the workspace for testing:

```bash
+ git init
+ git remote add origin https://github.com/mkaito/dotfiles
+ git fetch --no-tags origin +refs/heads/master:
+ git reset --hard -q 10b978000779084454c93be75d629f6dc14a6930
+ git submodule update --init --recursive
```
