### ISSUE TITLE
User authentication via reverse proxy request header

### ISSUE THREAD

**Issue by qqiao** [gogs/gogs#165]
In some organizations or setups, users are managed separately by systems that does not support oauth.

Usually these setups handle user authentication with an reverse proxy and the user ids are then passed to the downstream systems via a request header.

I happen to work for such an orginazation and with some pointers and guidance, I would like to help implement this feature.

**Comment by Unknwon** [comment]
!!! Hi, everyone in this thread, please be noticed that by correction of my typo in the configuration(https://github.com/gogits/gogs/pull/1038), reverse proxy auto registration key name has been changed !!!

**Comment by warpedgeoid** [comment]
As an alternative, could we allow the reverse proxy to pass additional LDAP information as headers? Presumably, if the RP is authenticating users, it has access to the LDAP/AD tree and can pass X-User-Email, X-User-Name, etc. Why should Googs need access to the LDAP in this situation? Someone correct me if I'm wrong.

**Comment by Unknwon** [comment]
@warpedgeoid I'm not sure if I understand correctly, but only `UID` is unique and never can be changed in Gogs, this is the safest way.

**Comment by ptman** [comment]
@Unknwon The UID in gogs is internal to gogs. No LDAP server knows the UID values in gogs database. Users _must_ be identified by username, or something that can be known by the LDAP database for this to work. Maybe LDAP users should be prevented from changing their name in gogs.

**Comment by Unknwon** [comment]
@ptman ahah, sorry, forgot it was passing the user name, but yes same thing apply. And As I said i'm not quite get the point of @warpedgeoid 's comment...

**Comment by warpedgeoid** [comment]
My point was more that instead of querying LDAP to get certain user profile information (like is being requested above to compliment ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true), why not just allow the reverse proxy to pass these in the same manner as the username? Sure, this isn't as robust as querying LDAP, but it is much easier to implement. After all--we are only talking about the user's full name, email address and profile picture.

**Comment by Unknwon** [comment]
> My point was more that instead of querying LDAP to get certain user profile information (like is being requested above to compliment ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true), why not just allow the reverse proxy to pass these in the same manner as the username? Sure, this isn't as robust as querying LDAP, but it is much easier to implement. After all--we are only talking about the user's full name, email address and profile picture.

Of course there is no technical difficulties on implementing this, but what is the use case?

**Comment by warpedgeoid** [comment]
The use case, as I see it, is as a simple method of doing what @smyrman wants to do with this pseudo-code, but without having to add an LDAP layer to reverse proxy auth. It would just look for the email address as an extra header, just like it currently does the username.

```
If reverse proxy enabled and reverse proxy username set in header:
     If user exists:
          log in user
          return
    If ldap configured:
        email, error = get email from ldap.
        if error == nil:
            set user email
            return
    show a custom "register proxy user" form where the username (and password) can not be changed, but email must be provided.
```

**Comment by Unknwon** [comment]
@warpedgeoid thanks, but what you give is implementation, not use case...

can @smyrman 's comment is really old, please give explicit reference to words you're referencing to.

**Comment by bonitoDeMadrid** [comment]
Love that feature.
Is it possible to get this working with the git client, too?

	Scenario:
	git client => reverse proxy over https (doing authentication via client certificates) => gogs

	Expected:
	git init 
	' git is already configured to use the client certificate for that domain...
	git remote add https://gogs.mycomany.com 
	git fetch
	' It work's withouth asking for user credentials

Since users love to forget passwords in bigger companys, .... 
Funny: There was a press release in germany this week, that VW spend 
a million bugs a year for resetting user passwords, btw.

**Comment by Unknwon** [comment]
@bonitoDeMadrid very interesting point!

Would you mind rise another issue specifically for git HTTP?

**Comment by donbowman** [comment]
@Unknwon above you say the default password is same as username (for auto created user via ENABLE_REVERSE_PROXY_AUTO_REGISTRATION for operations such as delete-repo).
But I am finding I cannot delete a repo specifying the user name as the password.
I do see the code sets it:
https://github.com/gogits/gogs/commit/069486d169d7adac902a310e10b6580857735880
but it doesn't seem to work. Do others see this?

**Comment by Unknwon** [comment]
@donbowman based on the code it should work. Do you have any other info you may consider helpful to debug this issue?

**Comment by Kegeruneku** [comment]
Greetings @Unknwon !

I would also be interested in having a way to have a way to fill basic info about the user auto-created by ENABLE_REVERSE_PROXY_AUTO_REGISTERATION.

As said by previous commenters, it could either be passed using http headers, or if available using a configured LDAP provider (this is what others application usually do when applicable)

The use case is simple: I would love to at least have the correct mail for the user so he/she does not have to redefine profile info after initial login.

The user first name / last name would be a bonus (if possible, but the mail is more important)

I'll be around if you need precisions :)

**Comment by Unknwon** [comment]
@Kegeruneku thanks your info!

I suggest you open up another issue with same comment you posted, and name it `Fill basic info when auto-created user by reverse proxy`.

**Comment by Kegeruneku** [comment]
Can do! And thanks for that awesome software btw :-)

**Comment by mcanevet** [comment]
Has anyone managed to make this work with https://github.com/bitly/oauth2_proxy?

**Comment by msiebuhr** [comment]
@mcanevet 

Adding this to `app.ini`:

    [security]
    INSTALL_LOCK = true
    SECRET_KEY   = ...
    REVERSE_PROXY_AUTHENTICATION_USER = X-Forwarded-User
   
    [service]
    ENABLE_REVERSE_PROXY_AUTHENTICATION = true
    ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true

After starting the server on http://localhost:3000, I start up oauth2_proxy with:

    oauth2_proxy --upstream=http://localhost:3000 --client-id=`cat client_id.txt` --client-secret=`cat client_secret.txt` --cookie-secret=... --email-domain=\* --cookie-secure=false

(Yes, secrets should at least be passed in environment vars or a config file.)

**Comment by belongwqz** [comment]
When I user nginx to enable reverse proxy auth for sso, git clone (cmd is git clone http://xxxxx.git) always return http 5xx error, what I should do please ?
