### ISSUE TITLE
AUR package for Arch Linux

### ISSUE THREAD

**Issue by v9n** [gogs/gogs#176]
Hi @Unknwon 
I created a AUR package for Arch Linux https://aur.archlinux.org/packages/gogs/
So they can install use it quickly with yaourt on Arch Linux.

I packaged the app by downnloading the official binary. Creating a user in /var/lib/gogs and repository is put in /usr/share/gogs/. A systemd unit file is used to launch the app. 
The custom config file (/var/lib/gogs/custom/conf/app.ini is symlink to /etc/gogs.conf).

The package is similar to how the AUR package of https://github.com/gitlabhq/gitlabhq works.https://aur.archlinux.org/packages/gitlab/

Can we include somewhere in document to point user to it?

**Comment by lifehome** [comment]
Can someone reopen this issue?
As the repo/package on AUR is now broken, both three package is not build-able.

**Comment by edacval** [comment]
You can use https://github.com/edacval/pkgbuilds/ as starting point . Works for me perfectly.

**Comment by bkcsoft** [comment]
As I use arch on my workstation, and have extensive knowledge of pkgbuilds,
I can take at look at the package in AUR :)

**Comment by edacval** [comment]
I also started from the AUR version. Deeply rewrote and simplified PKGBUILD, package can be easily upgraded or replaced with another upstream branch version.

**Comment by fanningert** [comment]
Thanks, I will update the packages.

**Comment by fanningert** [comment]
[Gogs AUR package](https://aur.archlinux.org/packages/gogs/) - Build options "sqlite pam cert"
The current version of the gogs package is possible to build.

[Gogs-Git AUR package](https://aur.archlinux.org/packages/gogs-git/) - Build options "sqlite pam cert"
The package is updated to current commit. Build on my machine with positive result.

[Gogs-Git-Dev AUR package](https://aur.archlinux.org/packages/gogs-git-dev/) - Build options "sqlite pam cert"
gogs-git-dev package is updated to current commit. Build with error, I think this is a code problem.
```
...
cmd/cert.go:33: cannot use runCert (type func(*cli.Context) error) as type func(*cli.Context) in field value
cmd/dump.go:28: cannot use runDump (type func(*cli.Context) error) as type func(*cli.Context) in field value
cmd/serve.go:35: cannot use runServ (type func(*cli.Context) error) as type func(*cli.Context) in field value
cmd/update.go:21: cannot use runUpdate (type func(*cli.Context) error) as type func(*cli.Context) in field value
cmd/web.go:55: cannot use runWeb (type func(*cli.Context) error) as type func(*cli.Context) in field value
```

When you are not possible to build the package, can you please post the error message output of the make process.

**Comment by fanningert** [comment]
@edacval My package is not so simple, because I read the .gopmfile and load the correct commit version from the repository.

**Comment by lifehome** [comment]
@fanningert Any idea why would this always happen?

```
==> Entering fakeroot environment...
chmod: cannot access '/tmp/aur-gogs-git/gogs-git/pkg': No such file or directory
/usr/bin/fakeroot: line 181:  8920 User defined signal 1   FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS" LD_PRELOAD="$LIB" "$@"
==> ERROR: Makepkg was unable to build gogs-git.
==> Restart building gogs-git ? [y/N]
```

**Comment by fanningert** [comment]
@lifehome Please look at this post https://bbs.archlinux.org/viewtopic.php?id=160829

**Comment by lifehome** [comment]
Uh, I have not messed up my system with i686 and x86_64 libs, so thanks for your concern.
However after reading the whole post didn't really solve my question, any two cents?

**Comment by fanningert** [comment]
I test the package build (on x86_64, armv6h, armv7h) with yaourt , packer and manually with makepkg. But I don't get your error.
