### ISSUE TITLE
Pasting image from the clipboard

### ISSUE THREAD

**Issue by sloong** [gogs/gogs#1915]
In new issue page, the textbox cannot pasting image from the clipboard , such as the GitHub.
so i must save the image to file and upload it and delete the file.

**Comment by alexclifford** [comment]
+1 - This is an extremely useful feature that I'd love to see added.

**Comment by bengben** [comment]
+1 up

**Comment by faouzzz** [comment]
+1

**Comment by imxieke** [comment]
coding current is able to drag the file upload, hope gogs can also

**Comment by imxieke** [comment]
is coding.net, like china version github

**Comment by jamosch** [comment]
+1 would be a really nice feature
Helps me convincing colleagues to use gogs instead of github

**Comment by lostdj** [comment]
You can fix it easily by yourself, solution courtesy http://stackoverflow.com/a/40204676

Edit `public/js/gogs.js` in your installed Gogs, modifying Dropzone (`CTRL+F` `// Dropzone`) init func like this:
```
            init: function () {
                var thiz = this;
                document.onpaste = function(event) {
                  var items = (event.clipboardData || event.originalEvent.clipboardData).items;
                  if(items)
                    for (var _i in items) {
                      var item = items[_i];
                      if (item.kind === 'file')
                	   thiz.addFile(item.getAsFile())
                    }
                }
                this.on("addedfile", function (file) {
                    if(!file.name)
                        file.name = (""+(new Date()).getTime());
                });

                // Leave the rest of the function as is.
```

**Comment by heliomcp** [comment]
Dont know why this is closed. I can't paste images from clipboard to editor :-(

Maybe something like we have here in GitHub when posting...
![1](https://user-images.githubusercontent.com/9692595/63225794-3947b280-c1cc-11e9-9e5c-6b110363f598.png)
