### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by markuman** [gogs/gogs#194]
This hardly sucks, even if the selfsigned certificate is imported.

```
2014/05/15 21:22:04 [mailer.go:59] [E] Async sent email 0 succeed, not send emails: markuman@gmail.com, info: UID: 2, send reset password email err: x509: certificate signed by unknown authority
```

**Comment by aviddiviner** [comment]
I solved this by just replacing the CA certificate chain.
`docker run --volume /path/to/my/certs:/etc/ssl/certs/ca-certificates.crt`
