### ISSUE TITLE
Show updates to mirrored repos in timeline

### ISSUE THREAD

**Issue by lenucksi** [gogs/gogs#2017]
Is it possible to show the updates of mirrored repositories in the dashboard timeline as well?
I have a repository that I mirror from my account at another hosting site and whose commits I also would like to have shown in my dashboard.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by garygreen** [comment]
massive +1 to this. It would be nice for the acitvity feed to simulate that pushes/updates have been done on the dashboard to mirrored repositories (showing the actual time of the commits etc).

**Comment by barsanuphe** [comment]
This would be very useful indeed. I hope this idea gets picked up.

**Comment by garygreen** [comment]
@Unknwon any updates on this? I'm trying to figure out how gogs updates the activity log exactly (for even standard repositories / non mirrored)... when you add a repository to goggs does it automatically add some form of git update hook to that repository and call `gogs serv` ?

**Comment by Unknwon** [comment]
>  when you add a repository to gogs does it automatically add some form of git update hook to that repository and call gogs serv ?

Yes.

But the logic for detecting what commits are updated for mirror repositories might be different, not sure...

**Comment by garygreen** [comment]
In [this function](https://github.com/gogits/gogs/blob/19423957b17fe583e9a04f45aafe91335354d6e2/models/update.go#L68) what passes the extra parameters `userName, repoUserName, repoName string, userID` ? It seems the git hook only provides the ref, old commit id and new commit id. How does it determine what repository it was for?

I looked in https://github.com/gogits/gogs/blob/e030109b5af9015c018cdc6f18655e201f6008bf/cmd/update.go#L45 but that doesn't pass thru the userName etc either :confused:

**Comment by Unknwon** [comment]
Here you go: https://github.com/gogits/gogs/blob/e030109b5af9015c018cdc6f18655e201f6008bf/cmd/serve.go#L97

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

Screenshots:

![image](https://user-images.githubusercontent.com/2946214/40723119-b29b85ce-6450-11e8-9cc2-656fb098307d.png)
![image](https://user-images.githubusercontent.com/2946214/40723131-b86dfebe-6450-11e8-90eb-9077cb197bbb.png)
