### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by gsantner** [gogs/gogs#2025]
Would be great if users could take repo's to the archives:
- Doesn't show up on the Overview Page anymore
  - Only visible in group, or user page
- Read-only (no pushes allowed)
- Possibillity to reenable the repo
- Only allowed for users own repos, and for Team repos when User == Owner

I know there's the `REPO_PAGING_NUM` setting, but this would also provide write-protection. Maybe someone got an idea about this. I personally got many projects which I finished, but don't want to loose history, issues, or anything like that (When archivating separately).

If you think thats too hard to implement, just close the issue. Thanks for your work Unknwon!

**Comment by Unknwon** [comment]
Thanks your feedback!

> Doesn't show up on the Overview Page anymore
Only visible in group, or user page

What is the `Overview Page` you are talking?

> I know there's the REPO_PAGING_NUM setting, but this would also provide write-protection.

I don't see any connections here?

**Comment by de-live-gdev** [comment]
1) Ups. Its called Dashboard
2) I meant, that there is the above setting to set a maximum of displayed items in dashboard. But this feature should not only hide this item from Dashboard, but also make it protected.

**Comment by Unknwon** [comment]
For 2, no, it does not . In fact not for that purpose at all... 

For your purpose of this request, I think you should follow issue that request for protected branches.

**Comment by de-live-gdev** [comment]
You're right  :+1:  , but as said this can wait.

**Comment by Unknwon** [comment]
After you change the issue title, I'm more concern this is a duplication issue.

**Comment by tboerger** [comment]
Archiveing repositories is a feature I really miss on GitHub. Protected branches is a totally different story.

**Comment by Unknwon** [comment]
Archive means not able to view as well, only can know it is archived

**Comment by Unknwon** [comment]
So author of this issue need be sure and clarify it.

**Comment by tboerger** [comment]
IMHO archieve a repository sets everything to readonly and is not listed on the normal repository listing anymore.

**Comment by Unknwon** [comment]
Protected branch with no one can push and private do the exactly same thing.

**Comment by Unknwon** [comment]
Any updates on author?

**Comment by de-live-gdev** [comment]
Basically I am used to GitLabs archiveate feature, which is basically what I suggested above. All it should really do is to don't allow push to repo (not only on a branch --> is also easier to implement), and to be de facto invisible (Don't list things from repo in dashboard). But it still should be pull-able and viewable.

**Comment by Unknwon** [comment]
@de-live-gdev then the title should be changed back to `archive repo`, not protected branch/repo. 

Also, any pointer to `archive` feature of GitLab so I can get better sense?

**Comment by de-live-gdev** [comment]
<https://github.com/gitlabhq/gitlabhq/pull/5841>

**Comment by Unknwon** [comment]
Cool, thanks!

**Comment by de-live-gdev** [comment]
Thank you!

**Comment by Tmplt** [comment]
I support the implementation of this.

I write essays and the like in LaTeX which, after turn-in, are repos which I don't work on any more, but I'd still like to save the source code and git commit history and such. As mentioned above, disabling commit pushes to the repo, and hiding it from the "My repositories" list on the Dashboard should do it. But maybe a list for archived repos could be implemented instead?

**Comment by tobiashochguertel** [comment]
Yes I currently looking for such an feature also, because I don't want to delete my repositories to get them not shown in the dashboard view.

**Comment by TrAnn3l** [comment]
Github now supports archiving: https://github.com/blog/2460-archiving-repositories
