### ISSUE TITLE
Please add avatars for repositories

### ISSUE THREAD

**Issue by strahlc** [gogs/gogs#2340]
It would be great to select an avatar for a repository like in gitlab (see gitlab [merge request](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/304) for details).

This way you can identify your repositories easier.
- show repository avatar on dashboard, projects page, project page
- add a default repository avatar 
- copy the icon on repository forking

**Comment by Dasoren** [comment]
+1 Also maybe a way to add an email to the repo to pull the avatar from Gravatar, just a thought.
also (little off topic), and email option for an organization with a Gravatar for them as well.

**Comment by sergey-dryabzhinsky** [comment]
@Unknwon PR for issue #5221 
Work in progress.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5221, please help test on `develop` branch or https://try.gogs.io.
