### ISSUE TITLE
Question: How do I enable SSL (https)

### ISSUE THREAD

**Issue by LennartRoeder** [gogs/gogs#235]
hello,
I added my ssl key and crt file to the config, but can't reach my gogs via https. Unfortunally I havn't find any documentation or support forum.

Help would be appreciated 

greetings Lennart

**Comment by khatkarrohit** [comment]
How to redirect HTTP to HTTPS (SSL redirection) to avoid that small file download ?

**Comment by hypernovagama** [comment]
I think you can use nginx and redirect the http to https.

**Comment by TilmannBach** [comment]
i can still confirm this 7 byte thing in version 0.9.0

* hosted on windows server 2008 R2 64 bit

**Comment by Unknwon** [comment]
> i can still confirm this 7 byte thing in version 0.9.0 when configured to use https

I don't understand this sentence...

**Comment by TilmannBach** [comment]
Sorry, all i wanted to tell is that the bug mentioned by @thinking-aloud still exists in v0.9.0.

After using gogs for a while we wanted to configure it to use https.

* We created cert, configured the config file and restarted the service.
* problem is now:
  + when accessing the webservice via http (not https) a file with 7 byte of crap are being served
* https for the web service is working

**Comment by Unknwon** [comment]
@TilmannBach https://unknwon.io/setup-gogs-with-https/

**Comment by simeonradivoev** [comment]
I too have @thinking-aloud's bug. HTTPS works fine with a let's encrypt certificate. But when you try and connect using HTTP links a file names download with no extension is downloaded.

**Comment by denaitre** [comment]
This issue occurs when gogs' interface is accessed through **http**://\<domain\>:3000, which returns the following output :
~~~
2016/10/16 10:12:57 http: TLS handshake error from 192.168.1.79:51388: tls: first record
 does not look like a TLS handshake
~~~
Everything is fine when gogs is accessed through **https**://\<domain\>:3000

**Comment by Huang-Libo** [comment]
@inflation 
Yes, you are right, we just need to use `Nginx` to set up https, instead of modify `app.ini` file. [my  git site](https://git.huanglibo.com/) use this method.
 This is my Nginx configure file: 

```
server {
    listen 80;
    server_name git.huanglibo.com;

    location / {
        rewrite ^(.*)$  https://$host$1 permanent;
        proxy_pass http://localhost:3000;
    }
}

server {
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/git.huanglibo.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/git.huanglibo.com/privkey.pem;
  server_name git.huanglibo.com;

  location / {
        proxy_pass http://localhost:3000;
    }
}
```

**Comment by tanpengsccd** [comment]
the cert and key must be in gogs folder .and the path can't recognize '~' .

**Comment by khs1994** [comment]
@Huang-Libo 

```nginx
location / {
        proxy_pass  http://gogs;
    }
```
http 改为 https

**Comment by Huang-Libo** [comment]
@khs1994 你这样写没有重定向功能.

**Comment by khs1994** [comment]
@Huang-Libo 

什么重定向，不太明白

**Comment by khs1994** [comment]
我明白了  
我不改 80 配置，改的是 443 配置
```
server {
  listen 443 ssl;
  ssl_certificate /etc/letsencrypt/live/git.huanglibo.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/git.huanglibo.com/privkey.pem;
  server_name git.huanglibo.com;

  location / {
        proxy_pass https://localhost:3000;
    }
}
```

**Comment by hudson6666** [comment]
@Huang-Libo 请问一下你这样做了以后clone的哪个地方会变成https么 如果可以是反向代理了以后自然就可以么还是在哪设置的
就是这里
![image](https://user-images.githubusercontent.com/18373361/30510912-63882ede-9b00-11e7-90e8-a5c742ddc21b.png)

**Comment by belligerent** [comment]
[download.txt](https://github.com/gogits/gogs/files/1370131/download.txt)

我把80作为gogs的端口，443给ss用，重定向到gogs，伪装一下。
直接访问https没问题，如果访问http就会下载这个文件，trace level的日志也没有相应的输出。
可以帮忙看看这个问题吗？虽然不影响使用但是有点恼人，谢谢。

**Comment by khs1994** [comment]
@belligerent 不太明白

**Comment by ashtonhogan** [comment]
@Unknwon does this mean that you have to build your own? Isn't there an argument you can pass to `./gogs web [cert] [key]` binary instead?

**Comment by ashtonhogan** [comment]
@belligerent I searched the entire x64 tar binary and couldn't find an `app.ini` file?
