### ISSUE TITLE
Improve email security

### ISSUE THREAD

**Issue by robvdl** [gogs/gogs#249]
I have found two issues regarding exposure of email addresses to email harvesting bots.

First, on a users profile page it will display the users email address as a link, even when you are not logged in.  I think it would be best to hide the email address, until you are logged in at least, this would be the simplest way to improve security of this email address link.  I don't think any JavaScript obfuscation is necessary if you simply hide the link until you log in.

The second issue, is on the commits page, there is a link for each commit line to the authors profile page, it uses the url /user/email2user...., followed by an email address but it only really encodes the @ character (it's basically url encoded).

I had a think about the second issue, as it is still exposing the users email address how it is right now and bots can probably still parse this info quite easily. Gravatar uses an md5 hash to get around this issue, we could potentially use that however it would make the URL ugly and the hashes will probably have to be stored in the db for faster lookups which is not ideal.

I then had a look at how Bitbucket does it, they simply uses the username in the link, maybe that is a better solution as it does not expose the users email address.  I am not quite sure how to deal with commits in the repositories, where there is no user account in Gogs, that is the only problem there.

Let me know if you need help, I can implement this if you want, but need to know what direction to go with this.

**Comment by kolesar-andras** [comment]
Notification email contains email addresses of all recipients in the To: field. This can be annoying when number of watchers increase. Some SMTP servers even reject emails where number of recipients exceed a limit. These emails should be sent separately one-by-one or in configurable chunks. See Postfix configuration:

> smtpd_recipient_limit (default: 1000)
> The maximal number of recipients that the Postfix SMTP server accepts per message delivery request.

http://www.postfix.org/postconf.5.html#smtpd_recipient_limit

**Comment by linquize** [comment]
Is googlecode's approach relevant?
For example, `sya...@google.com`, `nick.l...@gmail.com`

**Comment by Unknwon** [comment]
> Notification email contains email addresses of all recipients in the To: field. This can be annoying when number of watchers increase. Some SMTP servers even reject emails where number of recipients exceed a limit. These emails should be sent separately one-by-one or in configurable chunks. See Postfix configuration:

@kolesar-andras you want to have a config option that limits the maximum recipients in a single email?

**Comment by kolesar-andras** [comment]
Yes, exactly. I would prefer to set it to 1, sending each notification individually. Others may leave it empty, keeping all recipients in a single email. Default may be 1000 or below to be compatible with at least Postfix out-of-the-box.

**Comment by kolesar-andras** [comment]
@linquize you can't obfuscate email addresses in an email. If you send email to sya...@google.com it will not reach the intended recipient.

**Comment by Unknwon** [comment]
> @kolesar-andras you want to have a config option that limits the maximum recipients in a single email?

@kolesar-andras Please rise another issue for this specific purpose.
