### ISSUE TITLE
reStructured text "README.rst" does not render when browsing repository

### ISSUE THREAD

**Issue by robvdl** [gogs/gogs#250]
reStructured text files (e.g. README.rst) will only render to HTML when viewing the actual file, but not when browsing the repository if a README.rst is in the directory, instead the plain text version is displayed.

However, this works fine for Markdown.

**Comment by lannocc** [comment]
I recently did a quick-and-dirty hack on Gogs to add some basic .rst support for our own use, but maybe you will also find it useful:

https://github.com/AlphaGriffin/gogs
