### ISSUE TITLE
Support for go-get

### ISSUE THREAD

**Issue by fzerorubigd** [gogs/gogs#277]
Repositories in gogs, are not go getable. must implement this : 
https://code.google.com/p/go/source/detail?r=0af5bcfdb4c1

to handle go get.

**Comment by Brasilikum** [comment]
Please clarify. Where do I find the settings? Should it work out of the box?

**Comment by Unknwon** [comment]
Hi @Brasilikum , yes, right now it is `work out of the box`.

**Comment by Brasilikum** [comment]
Ok. I guess if it does not work that is due to the repo being private.

**Comment by Unknwon** [comment]
> repo being private

Right, I believe so, too. :joy:

**Comment by mozey** [comment]
@brasilikum for a private repos you can install the package manually, like [this](http://stackoverflow.com/a/27501176/639133)
