### ISSUE TITLE
Static files not loaded.

### ISSUE THREAD

**Issue by nussjustin** [gogs/gogs#289]
Hi,

whilte installing gogs on my local machine (Windows 8.1 Enterprise, Gogs dev 6418caf23a) I ran into an error.

While installing all requests to assets (/css, /js, ...) are rejected with an HTTP 302 Found and an redirect to /install.

After installation I get an HTTP 404 for all assets and in prints something like this in the console:

```
2014/07/17 12:40:27 [context.go:127] [E] RepoAssignment(GetUserByName): User does not exist
```

Looking at the GetUserByName function, it tries to get the repos of users named like the directories of the assets (css, js, ...)

**Comment by JokerQyou** [comment]
I've ran into this trouble today. I installed a Gogs server using the binary downloaded from official site, and run it by user `git`. After the installation, all the static files are interpreted as resources under a user, such as `/img/favicon.png ` as `favicon.png` under user `img`, and the page lost all the status resources.

**Comment by JokerQyou** [comment]
Ok, so this is permission related issue, `git` user needs permission to enter the `public` directory to read these static files.
