### ISSUE TITLE
Github Authentication

### ISSUE THREAD

**Issue by r0kk3rz** [gogs/gogs#2927]
Github Authentication will allow people who already have a GitHub Account to create issues, edit wiki, and maybe even fork and submit pull requests on a public Gogs instance.

One of the great things about Github is the community it has, and the ease of which to contribute to existing projects once you're past the account hurdle. This feature will allow Gogs to act as a kind of distributed Github where you can get the benefits of hosting your own server without the drawbacks of losing access to the great community and low barriers to entry that hosting your project on Github gets you.

**Comment by joubertredrat** [comment]
+ 1, good feature

**Comment by ewoutp** [comment]
+1

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5340, please help test on `develop` branch.
