### ISSUE TITLE
Error 404 when trying to view a file that has been both modified and renamed

### ISSUE THREAD

**Issue by xzzv** [gogs/gogs#3289]
- Gogs version: 0.9.13.0319
- Operating system: Windows 7 SP1 x64 
- Database: SQLite
- Reproduced at http://try.gogs.io:
  https://try.gogs.io/xzzv/FileRenamingTest/commit/aaf49ca73b384cd78db78245d1bc97a2464d9d8c
  https://try.gogs.io/xzzv/FileRenamingTest/src/aaf49ca73b384cd78db78245d1bc97a2464d9d8c/file2.txt
## Description
1. Open the commit page with a file that has been modified and renamed
2. Click the "View File" button
3. Error 404 appears

**Comment by xzzv** [comment]
Also, there is no indication on the commit page that the file has been renamed. Only the old file name is shown.

**Comment by unknwon** [comment]
Fixed by https://github.com/gogs/gogs/pull/6048.
