### ISSUE TITLE
Question:it can't run when machine startup

### ISSUE THREAD

**Issue by Arylo** [gogs/gogs#342]
I wirting "nohup /opt/gogs/gogs web" into the rc.local.
When the machine startup, it dont run and return 
"2014/07/31 11:30:41 [FATAL][github.com/gogits/gogs/models] publickey.go:57: Cannot specify home directory because it's empty
"

**Comment by realhu1989** [comment]
@robvdl 's methed works perfect. Thanks a lot.

**Comment by linquize** [comment]
using sqlite?

**Comment by stevefermi** [comment]
I am using supervisor to manage the auto restart, and i met the same error, is there any solution?

**Comment by Unknwon** [comment]
Hi @stevefermi , have you looked [this file](https://github.com/gogits/gogs/blob/master/scripts/supervisor/gogs)?

**Comment by stevefermi** [comment]
@Unknwon Hi, I wrote a new config file by myself and i just looked the file you pointed out and add environment, Now problem Solved!
Thanks!

**Comment by Unknwon** [comment]
@stevefermi best news I got today!

**Comment by tosone** [comment]
@Unknwon 
i run gogs with supervisor very well. yesterday it can not be get. stop and start gogs, or quit and restart supervisor ican not solve this. after reinstall supervisor,  it runs well.

Sometime i need to reinstall supervisor.
