### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by ghTravis** [gogs/gogs#343]
Just wondering how I would be able to add the certificate authority to the mix when using SSL. I always get the "This certificate was signed by an unknown authority" message because the CA isn't used in app.ini when starting the server. I've tried the generate_cert mechanism and generating my own but I can't seem to get it trusted.

 Am I just missing something?

**Comment by robinpaulson** [comment]
@lunny startssl.com provides free certificates for non-commercial use.

**Comment by lunny** [comment]
Yes. You are right! @robinpaulson
