### ISSUE TITLE
gogs database setting is not correct: Error 1071

### ISSUE THREAD

**Issue by tobyzxj** [gogs/gogs#344]
I install gogs(in dev branch, commit id is 669552e255fb98021b779918394c65792fe6f1d2) in a clean VPS.  I got the following error:

```
Database setting is not correct: Error 1071: Specified key was too long; max key length is 1000 bytes
```

![111](https://cloud.githubusercontent.com/assets/4661855/3787356/852a638a-1a12-11e4-925c-ee3e20ac3d82.jpg)

**Comment by g000444555** [comment]
I get this exact error despite having INNODB engine enabled by default as suggested in the troubleshooting page. I use the latest Dockerfile.aarch64 docker image and the following server specs:

Server: mariadb via TCP/IP
Server type: MariaDB
Server version: 10.1.30-MariaDB-0ubuntu0.17.10.1 - Ubuntu 17.10
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

The install page manages to create a user table inside the gogs database and the table uses INNODB engine. I have tried the following two options to create the database, but am still getting the same error when trying to install through the web interface:

Option 1:

CREATE DATABASE IF NOT EXISTS gogs CHARACTER SET utf8 COLLATE utf8_general_ci;
USE gogs;
SET GLOBAL storage_engine=INNODB;

Option 2:

CREATE DATABASE IF NOT EXISTS gogs CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE gogs;
SET GLOBAL storage_engine=INNODB;
