### ISSUE TITLE
Disable Hard line breaks on the markdown parser

### ISSUE THREAD

**Issue by Gu1** [gogs/gogs#345]
Currently, the markdown parser is used with the EXTENSION_HARD_LINE_BREAK option, which is a non-standard markdown feature.

This make existing standard markdown files ugly by inserting line breaks on every line feed in the input text.

Markdown already has a feature to manually insert line break: put two spaces at the end of the previous line. Most markdown files who really want line break are most likely already using this feature, so imho the HARD_LINE_BREAK extension should be disabled.

**Comment by jcracknell** [comment]
I had an idea with regards to this: add a column to the user/repository/comment tables which can be used to store non-critical options in JSON format.

**user.options:**
```
{ "post_options": { "preserve_line_breaks": true } }
```
**repo.options:**
```
{ "markdown": { "preserve_line_breaks": false } }
```
When a user makes a comment, their `user.options.post_options` gets copied into the post to be used when rendering the post.

Repository options should default to `"preserve_line_breaks": false`.

**Comment by Unknwon** [comment]
@jcracknell thanks for the tip! But I got confused by what `options` you are providing for?

**Comment by jcracknell** [comment]
@Unknwon I am suggesting you can make the line break behavior user and repository-configurable, which you can then toggle at [modules/base/markdown.go#L211](https://github.com/gogits/gogs/blob/18c06973292a3d20b8ad72575c819fbe3287a9ad/modules/base/markdown.go#L211).

```go
type User struct {
  Id int64
  // ...
  Etc string `xorm:"TEXT"` // { "commentOptions": { 
                           //     "markdown": { "preserveLineBreaks": true }
                           //   },
                           //   "repositoryOptions": {
                           //     "markdown": { "preserveLineBreaks": false }
                           //   }
                           // }
}
```

```go
type Comment struct {
  Id int64
  Type CommentType
  PosterId int64
  // ...
  Etc string `xorm:"TEXT"` // { "markdown": { "preserveLineBreaks": true } }
}
```
```go
type Repository struct {
  Id int64
  OwnerId int64 `xorm:"UNIQUE(s)"`
  // ...
  Etc string `xorm:"TEXT"` // { "markdown": { "preserveLineBreaks": false } }
}
```
A column storing a blob of JSON would be convenient for storing this and other non-essential data without over-complicating future migrations.

**Comment by Unknwon** [comment]
@jcracknell I see.

I've created [this](https://github.com/gogits/gogs/issues/1009) issue to separate form this.
