### ISSUE TITLE
Notify when two people are editing same file in web editor

### ISSUE THREAD

**Issue by francoishill** [gogs/gogs#3554]
- Gogs version (or commit ref): 0.9.93.0829
- Git version: 2.6.6
- Operating system: CoreOS 1068.10.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

Steps:
- Browse to any gogs repository
- Pick a file and edit it in the web UI
- Open another tab and edit the same file (while keeping the first tab/file in edit-mode)
- Add a line to the file in the second tab and commit it
- Now edit the file in the first tab and also commit it

It will show the red warning with text **"File content has been changed since you started editing. Click here to see what have been changed or press commit again to overwrite those changes."**

**Comment by Unknwon** [comment]
Thanks, but I think this has quite low priority, Gogs UI is not real time at all in current stage.
