### ISSUE TITLE
why I got "sync database struct error: Default addr for network 'localhost' unknown"

### ISSUE THREAD

**Issue by zhegexiaohuozi** [gogs/gogs#39]
I set the config file 
HOST = localhost
USER = root
PASSWD = XXXX

but,I got "sync database struct error: Default addr for network 'localhost' unknown",what is the problem?
Thanks!

**Comment by exu** [comment]
for me 
```
    db, err:= sql.Open("mysql", "user:pass@tcp(localhost:3306)/scf")
```

`tcp()` works (without I have the same error)

**Comment by Unknwon** [comment]
@exu I guess it depends on how `localhost` is defined in hosts file?

**Comment by exu** [comment]
@Unknwon my is `127.0.0.1   localhost ` (arch linux) so I think it's standard definition

**Comment by Unknwon** [comment]
@exu sorry I get confused, :sob:   so do you have issue? Or just join the discussion?

**Comment by exu** [comment]
@Unknwon only join discussion

**Comment by Unknwon** [comment]
@exu I see. Cool, so exceptions happen, maybe somehow his `localhost` is modified or MySQL listens on non-default address.
