### ISSUE TITLE
Cannot push new repository in Windows

### ISSUE THREAD

**Issue by fireyang** [gogs/gogs#413]
不能使用ssh，只能用http，但是提示这样的错误：
E:\gitTest>git push -u origin master
fatal: unable to access 'http://localhost:3000/yang/test.git/': The requested UR
L returned error: 504

不知道怎么解决？

**Comment by MehSha** [comment]
Hi,

trying to send an existing repo to newly created one in 0.8.43 from windows gves me this at about 12 percent:
error: RPC failed; result=22, HTTP code = 413iB

then it continue and at the end says it failed.
trying to use ssh path gives me: fatal: 'me/myrepo.git' does not appear to be a git repository

stuck here

Please help.

**Comment by Unknwon** [comment]
@MehSha https://gogs.io/docs/intro/faqs#why-am-i-getting-errors-when-uploading-large-files%3F
