### ISSUE TITLE
Unable to invite users to teams

### ISSUE THREAD

**Issue by ptman** [gogs/gogs#414]
Hi!

I tried the latest master, and while I'm able to create an organization and make private repos in that organization, other organization members can't see the private repos. I saw that I'm the only member of the team 'Owners' of the organization. Would adding other users in this team allow them to see the private repos? I can't seem to figure out how to add members to the team.

**Comment by Unknwon** [comment]
@tvvignesh Hi, currently it is not possible to achieve that, but you can file an issue for this feature request.
