### ISSUE TITLE
Trigger webhook after mirror sync

### ISSUE THREAD

**Issue by yellowmegaman** [gogs/gogs#4528]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.7.4
- Operating system: debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2017/05/24 13:46:09 [TRACE] Session ID: f4076df1e1572bac
2017/05/24 13:46:09 [TRACE] CSRF Token: clhjvFh7MOH-hWAtMKhwuqD6L-46MTQ5NTYyODg2OTc3MzczMTY3Ng==
2017/05/24 13:46:09 [TRACE] Template: repo/settings/options
2017/05/24 13:46:11 [TRACE] Session ID: f4076df1e1572bac
2017/05/24 13:46:11 [TRACE] CSRF Token: clhjvFh7MOH-hWAtMKhwuqD6L-46MTQ5NTYyODg2OTc3MzczMTY3Ng==
2017/05/24 13:46:11 [TRACE] SyncMirrors [repo_id: 2]
2017/05/24 13:46:11 [TRACE] Session ID: f4076df1e1572bac
2017/05/24 13:46:11 [TRACE] CSRF Token: clhjvFh7MOH-hWAtMKhwuqD6L-46MTQ5NTYyODg2OTc3MzczMTY3Ng==
2017/05/24 13:46:11 [TRACE] Template: repo/settings/options
```

Hi there!
Using gogs + drone 0.6. Drone created webhook in repository, i've edited it so it is called on every change `i need everything` option. But nothing happens when i sync mirror with new push. 

If i try to "Test Delivery" manually, all is ok and webhook is called.

Thanks a lot in advance!

**Comment by yellowmegaman** [comment]
Just found lot less explained issue https://github.com/gogits/gogs/issues/4510

**Comment by appIeboy** [comment]
<p align=right><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup><sub><sup>#1798 @lunny @tboerger @sapk @cez81 @geek1011 @lafriks @ethantkoenig @andreynering @DblK @Unknwon </sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></sup></sub></p>

**Comment by Unknwon** [comment]
You're right, we need a new type of webhook for mirror repositories.

**Comment by yellowmegaman** [comment]
Oh that's going to be a part of huge milestone ;)

**Comment by nprail** [comment]
@Unknwon What is the status on this?

**Comment by pgsimpso** [comment]
Can anyone suggest a workaround for this in the mean time? I'm using drone.io with gogs, so the webhook secret is never revealed to me. Is there an easy way of hitting that "Test Delivery" button from a script?

**Comment by mattddowney** [comment]
@pgsimpso maybe try triggering the button with puppeteer?

**Comment by Unknwon** [comment]
This will be fixed by fixing https://github.com/gogits/gogs/issues/2017.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
