### ISSUE TITLE
Dashboard not updated with custom hooks

### ISSUE THREAD

**Issue by umadesign** [gogs/gogs#4536]
- Gogs version (or commit ref):  0.11.6.0407
- Git version: 1.8.3.1
- Operating system: CentOS Linux release 7.3.1611
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When using a custom post-receive hook to rsync files with a production server
the dashboard doesn't get updated. Everything else runs fine, and no error is produced.

Script follows:

~~~~~
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        echo "Master ref received.  Deploying master branch to production..."
        git --work-tree=/home/git/deploy/test/debug --git-dir=/home/git/gogs-repositories/user/test-debug.git checkout -f
        rsync -avz -O -e "ssh -p2222" /home/git/deploy/test/debug/ user@example.com:/home/project/
    else
        echo "Ref $ref successfully received.  Doing nothing: only the master branch may be deployed on this server."
    fi
done
~~~~~

Tried to add 

`"/home/git/gogs/gogs" hook --config='/home/git/gogs/custom/conf/app.ini' post-receive` 

in the end of script, but it didn't work

**Comment by vebaspect** [comment]
I have the same problem.

**Comment by vebaspect** [comment]
After upgrade _Gogs_ to **0.11.33** everything works correctly.

**Comment by Unknwon** [comment]
Is this still happening with latest Gogs release (0.11.53)?
