### ISSUE TITLE
Render markdown in emails

### ISSUE THREAD

**Issue by alexlcdee** [gogs/gogs#4552]
- Gogs version (or commit ref): 0.11.4.0405
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

It would be nice to render markdown in Email notifications which sent on new issues open. For example I have an error handler, that posts an issue to gogs on some errors. So, this issues contains markdown and looks informative with stacktraces, but email notifications look ugly.

Example of issue:
![issue](https://user-images.githubusercontent.com/9890043/26926672-3afd3c40-4c57-11e7-8ff7-0a38c187b7fd.png)
Example of email:
![email](https://user-images.githubusercontent.com/9890043/26926688-461bb1a6-4c57-11e7-9321-50d2aefd602e.png)

Stripping off markdown is also acceptable, but there must be some other way to render newlines for email.

Thanks.
Alexander.

**Comment by Unknwon** [comment]
Thanks for the feedback!

Would you mind post raw markdown content here so I can use it for testing?

**Comment by alexlcdee** [comment]
Yes, here it is:
[Example of raw markdown code](https://github.com/gogits/gogs/files/1062321/md-example.txt)
[Here is is an example of desired output HTML code to be sent by email](https://github.com/gogits/gogs/files/1062325/desired-html.txt) (cleaned up)

I suppose, not everyone wants to send HTML-emails from server, so, this feature possible can be implemented as config option.

**Comment by hochhaus** [comment]
> I suppose, not everyone wants to send HTML-emails from server, so, this feature possible can be implemented as config option.

Ideally gogs could include both plain text and html as mime attachments so those of us which still use text based email clients get readable notification emails.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5629, please help test on `master` branch or https://try.gogs.io.

**Comment by hochhaus** [comment]
Tested and confirmed working via https://try.gogs.io/. Thanks for the quick merge.
