### ISSUE TITLE
Incorrect permission of .ssh/

### ISSUE THREAD

**Issue by girvo** [gogs/gogs#458]
Hi there,

Got Gogs working on an Amazon EC2 instance, and love it. HTTP pushing and pulling works, no problem, but SSH doesn't appear to.

The users on the instance are `root`, `ec2-user`, and `git`. `git` is the user that is running Gogs, and has the correct permissions for everything. 

For my Gogs user `josh`, I've added an SSH key. It _is_ in the `/home/git/.ssh/authorized_keys` file, I have confirmed that (and can post it if required). However, when the `git@git.example.com:/josh/example` protocol is used, it won't work even though the key has been added.

It fails with the error in the title.

I'm guessing it's an SSH configuration error, or something similar? What am I missing? I can provide more info if required.

Cheers
Josh

**Comment by trektrek** [comment]
Hello people, 

here the same messages... i resolve change the permission of .ssh folder
sudo chmod -R 600 .ssh 
the message don't show anymore, i hope this help somebody, best regards
