### ISSUE TITLE
How to restrict a user to submitting merge requests only, without the right to merge. i.e. Merge request can only be merged by users with specific privilege.

### ISSUE THREAD

**Issue by sunshinev** [gogs/gogs#4595]
如何限制用户只能提交合并请求，但是无法确认合并，必须由指定权限的用户来进行合并呢?

**Comment by FlorianTaut** [comment]
Please speak English.

Chinese forum can be found here: https://discuss.gogs.io/c/getting-help/getting-help-chinese

**Comment by hudson6666** [comment]
Translation:
How to restrict a user to submitting merge requests only, without the right to merge. i.e. Merge request can only be merged by users with specific privilege.

Applogize for the trouble of Chinese speaking of our Chinese users. Wish that will help.

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogs/gogs/issues/4376.
