### ISSUE TITLE
api/v1/user/repos: NULL pointer dereference after update to 0.11.19

### ISSUE THREAD

**Issue by julianscheel** [gogs/gogs#4596]
- Gogs version (or commit ref): 0.11.19
- Git version: 2.13.2
- Operating system: Linux (Archlinux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): https://gist.github.com/julianscheel/8e5955e8af751b456b63f0b53ab20d20

## Description
After upgrading my gogs installation from 0.10.4 to 0.11.19 I get the following error when try to query repositories via API:
https://gist.github.com/julianscheel/8e5955e8af751b456b63f0b53ab20d20

**Comment by julianscheel** [comment]
Sorry, for incomplete initial post - updated now.

**Comment by duckbrain** [comment]
Is this a duplicate of #4565?

**Comment by julianscheel** [comment]
It seems not, I've just update to git revision 13cca8a66 and the api call still causes an error 500. Log does look like this now: https://gist.github.com/95eca4a4a9401a1bd22a6265a0c97800

**Comment by Unknwon** [comment]
Hi, suggest to upgrade to latest version since it has some nil pointer related issues fixed along the way. Please report back if problem still exists, thanks!
