### ISSUE TITLE
Release attachments are deleted when delete any random comment

### ISSUE THREAD

**Issue by astockwell** [gogs/gogs#4627]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.10.2
- Operating system: SLES 11 (x86_64)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): Nothing relevant in there

## Description

After cutting a new release (or editing an existing one), and uploading several binaries to go along with the release. They initially are present in the /gogs directory and displayed on the releases page (/:username/:repository/releases). But after several days, they are gone from both.

**Comment by brueggemannapollo** [comment]
Same problem here:

- Gogs version (or commit ref): 0.11.43.0330
- Git version: 2.12.3
- Operating system: SLES 12 SP3 (x86_64)
- Database: MySQL (mariadb 10.0.34)

**Comment by Unknwon** [comment]
Hi,

>they are gone from both

What do you mean by "gone", what are "they" and what is "gone"?

**Comment by brueggemannapollo** [comment]
The uploaded binaries are not longer existent in /gogs directory and not longer showing up on releases page of gogs webinterface.

**Comment by Unknwon** [comment]
@brueggemannapollo can you check if the Git tag still show in the web page? If the relevant tag no longer exist, the release will not show.

**Comment by brueggemannapollo** [comment]
The Git tag and the release and the source tar.gz/zip are still there, only the uploaded binaries are gone.

**Comment by Unknwon** [comment]
Sounds like the "link" between attachments and the release is somehow broken.

Are all releases have attachments have this behavior or just somehow one?

Would you mind do:

1. Find `repo_id` of your repository: `SELECT repo_id FROM repository WHERE lower_name = {your_repo_name_in_lower_case}`
2. Find the `release_id` that is missing the attachments: `SELECT release_id, lower_tag_name FROM release WHERE repo_id = {repo_id_you_got_in_step_1}`
3. List attachments of the release: `SELECT id, uuid, release_id, name FROM attachment WHERE release_id = {release_id_you_got_in_step_2}`

**Comment by AagitoEx** [comment]
hello, this happened to me too, i checked my attachment tables manually, and i have only 3 rows now (should have been way more than that), which definately confirms the the rows have been deleted too not just the attachment files. It seems not just release attachments but attachements from issues and comments are also deleted.

**Comment by AagitoEx** [comment]
could you please create a binary release for this in dev branch mayb ... thanks

**Comment by Unknwon** [comment]
@AagitoEx which system and arch are you looking for?

**Comment by AagitoEx** [comment]
@Unknwon Windows Server x64

**Comment by Unknwon** [comment]
Here you go (without `miniwinsvc` build tag): 
[gogs_a05c19682e_windows_amd64_cert_sqlite.zip](https://github.com/gogs/gogs/files/2363293/gogs_a05c19682e_windows_amd64_cert_sqlite.zip)
