### ISSUE TITLE
HTTP 500 on API request for issues

### ISSUE THREAD

**Issue by AzimuthPower** [gogs/gogs#4648]
- Gogs version (or commit ref): 0.11.28.0718
- Git version: 2.11.2
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): I don't know what this is.

## Description
Requesting `/api/v1/repos/<user>/<repo>/issues` results in the following json:

    '{"message":"pq: column \\"issue.created_unix\\" must appear in the GROUP BY clause or be used in an aggregate function","url":"https://github.com/gogits/go-gogs-client/wiki"}'

I think this is probably PostgreSQL-specific but I don't have an instance running against MySQL to test with.

**Comment by andresmanelli** [comment]
Same here with

- Gogs version: 0.11.29.0727
- Git version: 2.14.0
- Operating system Arch Linux

Works OK with MySQL

**Comment by mckaygerhard** [comment]
related to #4543 postgres issue due the SQL made are done like if MYSQL was the only DB in the world! maybe reproducible with sqlite too!

SQL ANSI standar define that when agroup realted all the collumns must be, to avoid subquerys can be made but hit performance

**Comment by Unknwon** [comment]
Looks identical to https://github.com/gogs/gogs/issues/4543.
