### ISSUE TITLE
[enhancement] Disable non localhost access when routing through nginx

### ISSUE THREAD

**Issue by 0xpr03** [gogs/gogs#4657]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.11.0
- Operating system: debian stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

## Description
Option to disable access outside of localhost to enforce passthrough by nginx.
I've setup gogs behind nginx as load balancing, fail2ban, https certs & co have one central point by this. So I really want gogs not to be available from domain:3000 anymore.

**Comment by dev-dsp** [comment]
So, then just bind it to 127.0.0.1 instead of 0.0.0.0 in configuration.

**Comment by 0xpr03** [comment]
ok thanks
I'll try that out, at the moment I've blocked access via ip tables

please add this to the docs as I wasn't sure if that's enough at all
