### ISSUE TITLE
Apache proxy repository 403 issue

### ISSUE THREAD

**Issue by btafoya** [gogs/gogs#4664]
Very peculiar issue and I hope someone can help.

I have Gogs behind an Apache 2.4 mod-proxy.

ProxyPass "/" "http://premadev.com:3000/"
ProxyPassReverse "/" "http://premadev.com:3000/"

Is reachable, except when you attempt to click on a repository link such as:
https://premadev.com/btafoya/144stockexchange.com

The ABOVE produces an Apache 403 error and the request is NOT logged in the Gogs log.

When you add a trailing slash, it works fine.
https://premadev.com/btafoya/144stockexchange.com/

Any help is GREATLY appreciated! I have spent hours attempting to resolve this with no luck.

- Gogs version (or commit ref):  0.11.19.0609
- Git version: git version 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

...

**Comment by fenchu** [comment]
Hi
I think you just have to change your proxypass entries:
```
ProxyPass / "http://premadev.com:3000
ProxyPassReverse / http://premadev.com:3000
```

**Comment by xmik** [comment]
@btafoya, if you use Gogs from a docker container, does it make a difference if you start the container setting such an environment variable?
```
SOCAT_LINK=false
```
