### ISSUE TITLE
Backup/restore not available on Packager.io CentOS 6 install

### ISSUE THREAD

**Issue by cuibonobo** [gogs/gogs#4669]
- Gogs version (or commit ref): 0.11.27.0718
- Git version: 1.7.1
- Operating system: CentOS release 6.8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): Not relevant

## Description

I have installed Gogs using Packager.io via `yum install gogs` and the package is listed as `0.11.19-1500397851.dc10594.centos6`. However, the actual binary at `/usr/bin/gogs` does not have the `backup` and `restore` options available. It's strange that I see those CLI commands being added in my `/opt/gogs/gogs.go` file, but those options are not available in the built binary on my system.

**Comment by Unknwon** [comment]
Hi, I think packager.io has a wrapper command set around actual gogs commands. You would have to wait until their admin to update the script. Unfortunately, this repository is not manager of that package being built.
