### ISSUE TITLE
Bare Repo: Display Quick Guide on Repository Writer

### ISSUE THREAD

**Issue by athoik** [gogs/gogs#4716]
- Gogs version (or commit ref): `0.11.29.0727`
- Git version: `2.12.2`
- Operating system: `Windows amd64`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

On a newly created bare repository, only the `IsRepositoryAdmin` allowed to see Quick Guide.

https://github.com/gogits/gogs/blob/master/templates/repo/bare.tmpl#L8

Is is possible to include the Quick Guide also on role `IsRepositoryWriter`? 

```
-				{{if .IsRepositoryAdmin}}
+				{{if .IsRepositoryWriter}}
```

An writer is possible to push a branch in a bare repo, so why not to see the Quick Quide as well?

Thanks!

**Comment by Unknwon** [comment]
I think this change has been made already.
