### ISSUE TITLE
Mirror Project Can't Add Wiki Page

### ISSUE THREAD

**Issue by 502647092** [gogs/gogs#4721]
- Gogs version (or commit ref): 0.11.19.0609
- Git version: 2.12.GIT
- Operating system: CentOs 7.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Mirror Project Can't Add Wiki Page

![image](https://user-images.githubusercontent.com/10203793/29697941-b6a40e7c-8984-11e7-9243-bf91da307db9.png)

**Comment by kwill** [comment]
I have the same issue. The original repo does not have a wiki, and I would like to add my own. **Suggestion:** If this is not permitted [1] and there is no wiki, then the wiki tab should be hidden.

[1] For example, if the logic is "leave the wiki available, in case the original repo gets a wiki and we need to start mirroring that"

**Comment by alexanderadam** [comment]
Actually you can add a wiki page. Just the buttons are hidden. I explained it [in my (duplicated) issue](https://github.com/gogits/gogs/issues/4859). 😉

**Comment by 502647092** [comment]
@alexanderadam Thinks

**Comment by Unknwon** [comment]
Hi, even though you can hack, but by design you should not modify anything for a mirror the repository. Because wiki of the mirror repository could also be mirrored.

**Comment by alexanderadam** [comment]
@Unknwon can you please explain then how the Wiki mirroring is working then? Because currently I mirror git-Wikis in separate repositories. So they aren't integrated properly in a particular mirrored repository.

Thank you in advance!

**Comment by alexanderadam** [comment]
@Unknwon I have github mirrors that fulfull this requirements but none of them got the automatic wiki mirror.

Can you tell me when this feature was introduced? Maybe my gogs installation is just too old?
And do you know any easy "hack" that is able to add it afterwards?

**Comment by Unknwon** [comment]
@alexanderadam I just did a random test of https://github.com/gogs/go-gogs-client to https://try.gogs.io/unknwon/wiki-test, works like a charm. 

>Can you tell me when this feature was introduced? Maybe my gogs installation is just too old?

I can't remember but at least last year.

>And do you know any easy "hack" that is able to add it afterwards?

You have to first make sure your version of Gogs supports mirror the main repo and the wiki (by upgrading maybe).
