### ISSUE TITLE
What happened to Gogs? Why is it no longer being developed?

### ISSUE THREAD

**Issue by rambo-vs-fonzie** [gogs/gogs#4723]
Is it dead?

**Comment by dsamarin** [comment]
Why would you be thinking that? Last commit was only 12 days ago

**Comment by rambo-vs-fonzie** [comment]
@dsamarin I don't see much activity going on. No new features are being worked on, and commits are only small fixes every 2-4 weeks. Also the bug tracker is full of unanswered issues.

**Comment by hop** [comment]
For the record: I'm quite happy with this package as is and I am grateful for any time at all the devs choose to put into this. Thank you!

**Comment by GwynethLlewelyn** [comment]
Maybe no new features are _needed_ — because Gogs already does everything it should? :-)

**Comment by jpierre03** [comment]
Le Sat, 02 Sep 2017 08:13:23 -0700,
Gwyneth Llewelyn <notifications@github.com> a écrit :

> Maybe no new features are _needed_ — because Gogs already does
> everything it should? :-)
> 

Maybe it's holidays and the developper (yes, 1 maintainer) is on
vacation ?

**Comment by phanirithvij** [comment]
can be closed

**Comment by GwynethLlewelyn** [comment]
> can be closed

No, only _if_ and _when_ the maintainer answers!

**Comment by unknwon** [comment]
LOL, thanks for asking and all the support or had supported :)

This is a fun timing to give a response to this type of issues with log4j vulnerability, I'll try my best to make the response future proof in case anyone else ends up here while searching on Google for similar questions.

Response reads below.

---

I have hundreds of GitHub notifications coming my way every week, and I look at each of them, same as emails, it is just matter of time when I get to it. I do all my OSS work for free, and I'm grateful for my current employer whom is very encouraging people to invest in personal growth not squeezing surplus value like some others do.

To be high-sounding, the [vision of the Gogs project](https://github.com/gogs/gogs#-vision) is never to be feature rich, rather providing an easy and simple way to power a Git UI through your browser.

To speak like a human being, development takes time, software engineering takes effort, and building user-aware features is not the only thing that matters.

To speak like an asshole, what's more you could expect from a usable OSS project with zero funding?

**Comment by GwynethLlewelyn** [comment]
Excellent answer! And thanks for keeping the project alive!

**Comment by GwynethLlewelyn** [comment]
... and now we have a new release and all, yay! Thanks so much!
