### ISSUE TITLE
still got 500 error on wiki when mirror setup

### ISSUE THREAD

**Issue by mckaygerhard** [gogs/gogs#4740]
- Gogs version (or commit ref): 0.11.29 or b1100b5 
- Git version: 2.1.0
- Operating system: Linux debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/mckaygerhard/tested-migrating-wiki-bug
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2017-09-01 12:00:43: Started GET /organi1/elsistema/wiki for 10.10.34.42
2017/09/01 12:00:43 [TRACE] Session ID: be7cbd998cecfcd7
2017/09/01 12:00:43 [TRACE] CSRF Token: <removed>
2017/09/01 12:00:43 [ERROR] [.../routes/repo/wiki.go:53 renderWikiPage()] GetBranchCommit: object does not exist [id: refs/heads/master, rel_path: ]
2017/09/01 12:00:43 [TRACE] Template: status/500
2017-09-01 12:00:43: Completed GET /organi1/elsistema/wiki 500 Internal Server Error in 30.653383ms
```
## Description
the issue #4464 it's still reproducible with lasted stable release, also i build development brand and still reproducible..

**IMPORTANT NOTE**: i can see at the git root path the <reponamemirrored>.git and also the <reponamemirrored>.wiki.git exist after the mirror clone operation
...

**Comment by Juma7C9** [comment]
The bug is still present as of 0.11.34.
A possible workaround is to delete the wiki (Settings -> Erase Wiki Data), and then to recreate it (Setting -> Enable wiki system).

**Comment by mckaygerhard** [comment]
yeah that's works i confirmed the workaround, but hey its not the solution.. as i posted i can see the wiki.git after the mirror clone opertaion completed

**Comment by djwgit** [comment]
with 0.11.53, sqlite3 db, the workaround by @Juma7C9 does not work on my install
erase wiki, then enable wiki, create a wiki page, still get 500 page
tried to erase the repo wiki git folder on server, it does not help either.
hope this can be fixed soon... thanks, 
very nice project ! most common github functions are here !

**Comment by Unknwon** [comment]
I can no longer reproduce this problem with new migration from GitLab. I'll close this issue in few days if no stable reproduce steps reported any more.
