### ISSUE TITLE
New Feature: API Endpoint for releases

### ISSUE THREAD

**Issue by JaniDJ** [gogs/gogs#4743]
- Gogs version (or commit ref): 0.11.29.0727
- Git version: 
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Hey Folks,

I really need the possibility to list, search and download new releases from my repositories via the API. Maybe this is a feature that can be added quickly. 

Thx in advance
Jani

**Comment by renegat4** [comment]
For me this actually was the first feature i was looking for. And then it seems to be the only one missing from the API. I know i can create a release by pushing a tag. But i want to add an archive to the release, und possibly a discription (using REST).

**Comment by JaniDJ** [comment]
@renegat4, to be honest, I switched over to gitea in the meantime. Sadly gogs isn't supported actively. Maybe I will come back in the future.
