### ISSUE TITLE
API for tokens GET and POST returns 401 

### ISSUE THREAD

**Issue by bart1ebee** [gogs/gogs#4768]
- Gogs version (or commit ref):  0.11.29.0727
- Git version: 2.8.2
- Operating system: Windows Server 2012r2
- Database (use `[x]`):
  - [ ] PostgreSQL
`[x]` MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
`[x]` Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
When running GET https://try.gogs.io/api/v1/users/bart1ebee/ returns successfully
Running GET  https://try.gogs.io/api/v1/users/bart1ebee/tokens returns a 401
Running POST  https://try.gogs.io/api/v1/users/bart1ebee/tokens 
passing 
{
    "name": "gogs"
}
returns a 401

**Comment by faizalmy** [comment]
+1

**Comment by Unknwon** [comment]
Token API is only allowed with username:password authentication. You can't generate token from token.
