### ISSUE TITLE
Cannot execute custom hooks on Linux

### ISSUE THREAD

**Issue by lidelin** [gogs/gogs#4769]
- Gogs version (or commit ref): 
- Git version: 0.11.29.0727
- Operating system: Centos 7.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Cannot execute custom hooks on Linux

error log:
2017/09/13 16:31:09 [FATAL] [...its/gogs/cmd/hook.go:259 runHookPostReceive()] Fail to execute custom post-receive hook: exit status 128
2017/09/13 17:02:20 [FATAL] [...its/gogs/cmd/hook.go:259 runHookPostReceive()] Fail to execute custom post-receive hook: exit status 128
2017/09/13 17:17:11 [FATAL] [...its/gogs/cmd/hook.go:259 runHookPostReceive()] Fail to execute custom post-receive hook: exit status 128

...

**Comment by cjk7713** [comment]
i also got this problem ,i use the docke version,and someone can solve it

**Comment by Unknwon** [comment]
@lidelin what is the content your custom hook?
