### ISSUE TITLE
Send emails as plain text instead of HTML

### ISSUE THREAD

**Issue by rambo-wears-a-pinky-thong** [gogs/gogs#4779]
- Gogs version (or commit ref):  dev
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant

## Description

Emails are only sent in HTML format. This creates problems with email clients configured to read plain text only. Possible solutions are:

- use plain text + HTML in the same email, so that both formats are sent at the same time
- add a new settings flag in `app.ini` to choose which format to use, either plain text or HTML

**Comment by Unknwon** [comment]
Hi, it is already possible via https://github.com/gogs/gogs/blob/master/conf/app.ini#L251-L252.
