### ISSUE TITLE
LDAP group verification fails

### ISSUE THREAD

**Issue by variablenix** [gogs/gogs#4792]
- Gogs version (or commit ref): 2:0.11.29.0727+4+52f383381
- Git version: 2.14.1
- Operating system: Arch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- OpenLDAP version: 2.4.45
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Before updating to the latest commit today using my distribution's package manager, I noticed group verification fails. For example, the following are perfectly valid.

Group Search Base DN: `ou=Groups,dc=example,dc=com`
Group Filter: `(&(cn=gogs-users)(objectClass=groupOfNames))`
Group Attribute Containing List of Users: `member`
User Attribute Listed in Group: `uid`

If I query the group membership manually I can see my user does get returned correctly.
```
$ lgroup '(&(cn=gogs-users)(objectClass=groupOfNames))' uid=tony
dn: cn=gogs-users,ou=Groups,dc=example,dc=com
```

Despite the group settings defined in Gogs - a trace in the logs shows the user does bind successfully, but the group membership test fails:
```
2017/09/21 23:31:17 [TRACE] Session ID: 3ae8e6b0c98b938b
2017/09/21 23:31:17 [TRACE] CSRF Token: GNEhLKpiPyFUnTW5hghXUYyl9006MTUwNjA2MTYxOTE0MjIwMDQ4Mg==
2017/09/21 23:31:17 [TRACE] LDAP: Dialing with security protocol '2' without verifying: false
2017/09/21 23:31:17 [TRACE] LDAP will use BindDN
2017/09/21 23:31:17 [TRACE] Search for LDAP user: tony
2017/09/21 23:31:17 [TRACE] LDAP: Bound as BindDN: uid=git,ou=System,dc=example,dc=com
2017/09/21 23:31:17 [TRACE] LDAP: Searching for DN using filter '(&(objectClass=posixAccount)(uid=tony))' and base 'ou=People,dc=example,dc=com'
2017/09/21 23:31:17 [TRACE] Binding with userDN: uid=tony,ou=People,dc=example,dc=com
2017/09/21 23:31:17 [TRACE] Bound successfully with userDN: uid=tony,ou=People,dc=example,dc=com
2017/09/21 23:31:17 [TRACE] Fetching attributes 'uid', 'givenName', 'sn', 'mail', 'uid' with filter '(&(objectClass=posixAccount)(uid=tony))' and base 'uid=tony,ou=People,dc=example,dc=com'
2017/09/21 23:31:17 [TRACE] LDAP: Fetching groups 'member' with filter '(&(cn=gogs-users)(objectClass=groupOfNames))' and base 'ou=Groups,dc=example,dc=com'
2017/09/21 23:31:17 [TRACE] LDAP: Group membership test failed [username: tony, group_member_uid: member, user_uid: tony
2017/09/21 23:31:17 [TRACE] Template: user/auth/login
2017/09/21 23:35:11 [TRACE] Doing: MirrorUpdate
```

I've tried making the group filter as simple as 'cn=gogs-users' to no avail.

**Comment by ecs-hk** [comment]
@variablenix , I've gone through a lot of trial and error with Gogs and its LDAP group membership test. My experience was similar to what you've described: simple BIND (authentication) no problem; group membership test (authorization) bafflingly failing.

The *only* working Gogs configuration I've come up with for this purpose is `objectClass=posixGroup` (and its `memberUid` attribute). Any other group type / attribute name seems to fail - while still showing that everything looks legit in Gogs' logging.

If you have the luxury of creating a new group just for Gogs, then this may be worth exploring and testing out. (Tangentially, I just bought a Golang book specifically to try to contribute something back to Gogs on this LDAP integration. Simply put, the authorization piece appears to be partially broken.)

My environment is:
* Gogs 0.11.29
* OpenLDAP 2.4
* CentOS 7

**Comment by variablenix** [comment]
@ecs-hk, thank you for your insightful response. After running some tests, I can also confirm Gogs only respects the `posixGroup` objectClass and `memberUid` attribute. 

Using a `groupOfNames` objectClass and `member` attribute is unsuccessful. I think this could very well be the case for the `groupOfUniqueNames` objectClass and `uniqueMember` attribute. 

For now, as you pointed out, the only working solution is to make sure Gogs LDAP group memberships are defined with `objectClass=posixGroup` and its `memberUid` attribute.

**Comment by zclod** [comment]
I think the issue is [here](https://github.com/gogits/gogs/blob/9362b9fdfe41788bc600a5bc13f2df10ec2222e6/pkg/auth/ldap/ldap.go#L282)

when cheking for group membership it compares the user uid with the attribute specified in `GroupMemberUID`.

I think the problem is that in case of object class `groupOfUniqueNames` the attribute `uniquemember` contains the full DN of the user, so the equality check with the `uid` (that is only a subset of the DN) fails.

When I have some time I'll try to fix this

**Comment by rickywu** [comment]
I got the same problem, now I disabled validate group member
But I want to use gogs with active directory, when will you fix this issue?

**Comment by aboron** [comment]
When using activedirectory, the easier way to limit users by group membership is by turning off the verify group membership function (which works best with opendirectory) and add a group filter clause into the basic "User Filter" section like:
`(&(objectClass=Person)(|(uid=%[1]s)(mail=%[1]s))(memberOf=CN=GogsAdmin,OU=Groups,DC=realistic,DC=local))`

**Comment by GMZwinge** [comment]
I was able to get group membership verification to work with Active Directory using something like this:
- Group Search Base DN: `OU=Groups,DC=myDomain,DC=com`
- Group Filter: `(|(cn=myGroup1)(cn=myGroup2))`
- Group Attribute Containing List of Users: `member`
- User Attribute Listed in Group: `distinguishedName`

**Comment by Unknwon** [comment]
Hi, have you tried latest release 0.11.53 since it includes some fixes about group membership verification (if I remember correctly)?

**Comment by ecs-hk** [comment]
@Unknwon , thanks for checking. I deployed a new 0.11.53 system and tested a couple different "Verify group membership" configurations -- all of them were unsuccessful. To be precise, authentication succeeds and then group membership verification fails (which prevents authorization).

gogs' TRACE logging (`log/gogs.log`) was helpful in seeing if/how values were getting filled.

### LDAP group

Abbreviated look at the LDAP directory side. This is our group:

```
{
  "dn": "cn=gogs-pro,ou=User Groups,ou=Groups,dc=myorg",
  "gidNumber": "888888",
  "objectClass": [
    "groupOfNames",
    "top",
    "posixGroup"
  ],
  "member": [
    "uid=myuid,ou=People,dc=myorg",
    "uid=someguy,ou=People,dc=myorg"
  ],
  "cn": "gogs-pro"
}
```

### Test 1

Gogs configuration:

- Group Search Base DN: `ou=User Groups,ou=Groups,dc=myorg`
- Group Filter: `(&(objectClass=posixGroup)(cn=gogs-pro))`
- Group Attribute Containing List of Users: `member`
- User Attribute Listed in Group: `uid`

Logging:

```
2018/08/29 17:53:37 [TRACE] LDAP: Fetching groups 'member' with filter '(&(objectClass=posixGroup)(cn=gogs-pro))' and base 'ou=User Groups,ou=Groups,dc=myorg'
2018/08/29 17:53:37 [TRACE] LDAP: Group membership test failed [username: myuid, group_member_uid: member, user_uid: myuid
```

### Test 2

Gogs configuration:

- Group Search Base DN: `ou=User Groups,ou=Groups,dc=myorg`
- Group Filter: `(&(objectClass=posixGroup)(cn=gogs-pro)(uid=%s,ou=People,dc=myorg))`
- Group Attribute Containing List of Users: `member`
- User Attribute Listed in Group: `uid`

Logging:

```
2018/08/29 18:02:09 [TRACE] LDAP: Fetching groups 'member' with filter '(&(objectClass=posixGroup)(cn=gogs-pro)(uid=%s,ou=People,dc=myorg))' and base 'ou=User Groups,ou=Groups,dc=myorg'
2018/08/29 18:02:09 [TRACE] LDAP: Group membership test failed [username: myuid, group_member_uid: member, user_uid: myuid
```

### Test 3

Gogs configuration:

- Group Search Base DN: `ou=User Groups,ou=Groups,dc=myorg`
- Group Filter: `(&(objectClass=posixGroup)(cn=gogs-pro))`
- Group Attribute Containing List of Users: `member`
- User Attribute Listed in Group: `uid=%s,ou=People,dc=myorg`

Logging:

```
2018/08/29 18:05:42 [TRACE] LDAP: Fetching groups 'member' with filter '(&(objectClass=posixGroup)(cn=gogs-pro))' and base 'ou=User Groups,ou=Groups,dc=myorg'
2018/08/29 18:05:42 [TRACE] LDAP: Group membership test failed [username: myuid, group_member_uid: member, user_uid:
```

(I ran out of ideas for more config combinations to test.)

**Comment by GMZwinge** [comment]
From the example in [Group ACLs without DN syntax](https://www.openldap.org/doc/admin24/access-control.html#Group%20ACLs%20without%20DN%20syntax), group with an `objectClass` of `posixGroup` use the member attribute `memberUid`, not `member`. Are you sure that, with your LDAP server, groups have attributes named `member` that contains the members?

**Comment by ecs-hk** [comment]
Hi @GMZwinge - in my most recent posting (under the heading **LDAP group**) I posted a look at the LDAP group I'm working with. I omitted some details for brevity. Here's the full `objectClass` attribute for the group:
```
  "objectClass": [
    "groupOfNames",
    "top",
    "myorgGroup",
    "rfc822MailGroup",
    "myorgExpire",
    "posixGroup",
    "ndsLoginProperties",
    "DirXML-EntitlementRecipient"
  ]
```
The `myorg*` entries are from schemas created in-house by our directory folks.

Anyway, to answer your question: yes, the group uses the `member` attribute.

**Comment by GMZwinge** [comment]
@ecs-hk: If I were you, I would confirm this with an LDAP client tool such as JXplorer. The server side is one thing, the client side another.

**Comment by ecs-hk** [comment]
@GMZwinge , I should have clarified. My example output was taken from (Node.js) [ldapjs](http://ldapjs.org/client.html) client sessions.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #4688, please help test on `develop` branch.

**Comment by ecs-hk** [comment]
@Unknwon , I have tested and can confirm that the issue appears to be fixed. (I checked out commit 43bca4df40b933 for the `develop` branch and built it.)

### LDAP group

Quick reminder about how our LDAP group is structured:

```
{
  "dn": "cn=gogs-pro,ou=User Groups,ou=Groups,dc=myorg",
  "gidNumber": "888888",
  "objectClass": [
    "groupOfNames",
    "top",
    "posixGroup"
  ],
  "member": [
    "uid=myuid,ou=People,dc=myorg",
    "uid=someguy,ou=People,dc=myorg"
  ],
  "cn": "gogs-pro"
}
```

### Successful test

Gogs version 0.11.68.0928

Gogs configuration:

- Group Search Base DN: `ou=User Groups,ou=Groups,dc=myorg`
- Group Filter: `(&(objectClass=posixGroup)(cn=gogs-pro))`
- Group Attribute Containing List of Users: `member`
- User Attribute Listed in Group: `dn`

I believe because of #4688 , I am able to specify `dn` (rather than `uid`) and actually have it populated with a value. Group verification is **working correctly** now, at least for my test case.

### Sanity check (re-test broken previous version)

Gogs version 0.11.53.0603

Just to compare (since my earlier post did not include this exact test), I fired this version up again and tried specifying:

- Group Search Base DN: `ou=User Groups,ou=Groups,dc=myorg`
- Group Filter: `(&(objectClass=posixGroup)(cn=gogs-pro))`
- Group Attribute Containing List of Users: `member`
- User Attribute Listed in Group: `dn`

As expected, group verification is broken. Here is the log snippet:

```
2018/10/30 23:28:07 [TRACE] LDAP: Fetching groups 'member' with filter '(&(objectClass=posixGroup)(cn=gogs-pro))' and base 'ou=User Groups,ou=Groups,dc=myorg'
2018/10/30 23:28:07 [TRACE] LDAP: Group membership test failed [username: myuid, group_member_uid: member, user_uid: 
```

**Comment by Unknwon** [comment]
@variablenix hi, would you be able to confirm the fix as well? Thanks!
