### ISSUE TITLE
mysql broken pipe [ write: broken pipe ]

### ISSUE THREAD

**Issue by goldalworming** [gogs/gogs#4812]
- Gogs version (or commit ref): Gogs version 0.11.29.0727
- Git version: git version 2.7.4
- Operating system: ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
[mysql] 2017/10/06 07:24:38 packets.go:33: unexpected EOF
[mysql] 2017/10/06 07:24:38 packets.go:124: write tcp 127.0.0.1:58574->127.0.0.1:3306: write: broken pipe
[mysql] 2017/10/06 07:24:38 packets.go:33: unexpected EOF
[mysql] 2017/10/06 07:24:38 packets.go:124: write tcp 127.0.0.1:50110->127.0.0.1:3306: write: broken pipe

## Description
...

**Comment by Unknwon** [comment]
Does this error affects anything?
