### ISSUE TITLE
Windows new repo 500

### ISSUE THREAD

**Issue by devel-pa** [gogs/gogs#482]
version 0.5 x64

2014/09/18 15:04:40 [repo.go:115 CreatePost()] [E] CreatePost: initRepository: initRepository(git clone): cygwin warning:
  MS-DOS style path detected: C:\Users\user\gogs-repositories\unos\test3.git/.git
  Preferred POSIX equivalent is: /cygdrive/c/Users/user/gogs-repositories/unos/test3.git/.git
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
Cloning into 'C:\Users\user\AppData\Local\Temp\484264900'...
fatal: '/cygdrive/d/svnroot/research/gogs/C:\Users\user\gogs-repositories\unos\test3.git' does not appear to be a git repository
fatal: Could not read from remote repository.

As you can see the repo full path is attached to the full home path of Gogs.

Thanks,
Paul

PS: tested the one from website and the one from GitHub.

**Comment by greatcl** [comment]
Good answer. It solved my problem, tkx!

**Comment by Unknwon** [comment]
@greatcl good to hear it!

**Comment by uncled1023** [comment]
I'm still running into this issue, and the solution devised does not seem to work.  I have my repos on another drive, and when I go and try to run the command like he said (sh -c "/path/to/gogs web"), it starts up, but I still get the weird path error.
