### ISSUE TITLE
Internal Server Error happened when upload an issue with  some attachment 

### ISSUE THREAD

**Issue by hobo214** [gogs/gogs#4824]
- Gogs version (or commit ref): 0.9.141.0211
- Git version: 1.8.3.1
- Operating system:  centos 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

[Macaron] 2017-10-14 20:21:15: Started POST /dingwei/multimall/issues/new for 39.181.228.35
2017/10/14 20:21:15 [TRACE] Session ID: 2debf1a80bee82e3
2017/10/14 20:21:15 [TRACE] CSRF Token: byKvDcQeMDTmMWdQK9unuP6NY5c6MTUwNzk3NTQ3ODc5MjE3NTUzNA==
2017/10/14 20:21:15 [ERROR] [.../runtime/asm_amd64.s:481 call128()] NewIssue: newIssue: getAttachmentsByUUIDs [uuids: [f770db49-908b-46bf-8219-de588969cfd6]]: Error 1054: Unknown column 'uuid' in 'where clause'
2017/10/14 20:21:15 [TRACE] Template: status/500
[Macaron] 2017-10-14 20:21:15: Completed /dingwei/multimall/issues/new 500 Internal Server Error in 24.776547ms

## Description
Commit an issue with any attachment files, it occurs.

mysql> describe attachment;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| uuid         | varchar(40)  | YES  | UNI | NULL    |                |
| issue_id     | bigint(20)   | YES  | MUL | NULL    |                |
| comment_id   | bigint(20)   | YES  |     | NULL    |                |
| release_id   | bigint(20)   | YES  | MUL | NULL    |                |
| name         | varchar(255) | YES  |     | NULL    |                |
| created_unix | bigint(20)   | YES  |     | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+

it seems everything is ok, but the error occurs

**Comment by Unknwon** [comment]
Hi, your version is way too old. Please upgrade and report back if the problem still exists. Thanks!
