### ISSUE TITLE
git repos show empty, but clone has files, pushed via https only

### ISSUE THREAD

**Issue by fdamstra** [gogs/gogs#4830]
- Gogs version (or commit ref): 0.11.29.0727 (also tried cutting edge 0.11.30.1014)
- Git version: 2.7.4
- Operating system: Linux - Ubuntu ARM64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
Despite TRACE logging, nothing useful in the logs. Output included below.

## Description
System is configured for HTTP only, but it HTTPS behind a reverse proxy.

I can initialize a new empty repository, push to it, but the Quick Guide still displays. I am, however, able to clone this repository elsewhere. If I manually update the repository and set "is_bare" to 0, files show. 

Appears to be related to the section in [troubleshooting](https://gogs.io/docs/intro/troubleshooting) called "Push succeeds, but the dashboard timeline doesn’t update", but the solution doesn't apply since I am not running SSH. 

The repos are, however, stored on a cifs mount. I've verified that the git user is able to run scripts on the mount point where the repos are stored, though it does not allow settings of the executable bit. (i.e. you can run `bash /mount/point/test.sh` but not `./mount/bpoint/test.sh`).

As far as I can tell, there is no useful output from gogs. Here is sanitized output from a successful push to one of the problematic repositories:
```
myuser@io2:~/terraform/SimpleServers$ git push -u origin master -v
Pushing to https://io.example.com/git/Terraform/SimpleServers.git
Username for 'https://io.example.com': myuser
Password for 'https://myuser@io.example.com':
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 288 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
POST git-receive-pack (440 bytes)
To https://io.example.com/git/Terraform/SimpleServers.git
   7ce37ec..7324956  master -> master
Branch master set up to track remote branch master from origin.
updating local tracking ref 'refs/remotes/origin/master'
```

gogs.log:
```
2017/10/17 21:40:29 [TRACE] Session ID: b7b77b0c27b1a106
2017/10/17 21:40:29 [TRACE] CSRF Token: dKRmBd8IKL9okoFbeDUXUgdil7w6MTUwODI5MDgyOTc5ODExMjAwMA==
2017/10/17 21:40:34 [TRACE] Session ID: 42247f33b87c7d6b
2017/10/17 21:40:34 [TRACE] CSRF Token: t5GCbbJm04Ln1weXKpoUjPkFYEI6MTUwODI5MDgzNDI4MDY0MTAwMA==
2017/10/17 21:40:35 [TRACE] Session ID: 827fb48c32c5066d
2017/10/17 21:40:35 [TRACE] CSRF Token: SXKci1HdPRz_5be3YILavkSkYLA6MTUwODI5MDgzNDI5NjQ0MTAwMA==
2017/10/17 21:40:36 [TRACE] HTTPGit - Authenticated user: myuser
2017/10/17 21:40:37 [TRACE] Session ID: dc64c1a71ed82d83
2017/10/17 21:40:37 [TRACE] CSRF Token: aedeeGievY4-6nWGlvsPCmgGd6M6MTUwODI5MDgzNjQ4NTkzOTAwMA==
2017/10/17 21:40:38 [TRACE] HTTPGit - Authenticated user: myuser
```
output of `./gogs web`
```
[Macaron] 2017-10-17 21:40:29: Started GET /Terraform/SimpleServers.git/info/refs?service=git-receive-pack for 127.0.0.1
[Macaron] 2017-10-17 21:40:29: Completed GET /Terraform/SimpleServers.git/info/refs?service=git-receive-pack 401 Unauthorized in 14.109ms
[Macaron] 2017-10-17 21:40:34: Started GET /Terraform/SimpleServers.git/info/refs?service=git-receive-pack for 127.0.0.1
[Macaron] 2017-10-17 21:40:34: Completed GET /Terraform/SimpleServers.git/info/refs?service=git-receive-pack 401 Unauthorized in 20.198ms
[Macaron] 2017-10-17 21:40:34: Started GET /Terraform/SimpleServers.git/info/refs?service=git-receive-pack for 127.0.0.1
[Macaron] 2017-10-17 21:40:36: Completed GET /Terraform/SimpleServers.git/info/refs?service=git-receive-pack 200 OK in 2.042281s
[Macaron] 2017-10-17 21:40:36: Started POST /Terraform/SimpleServers.git/git-receive-pack for 127.0.0.1
[Macaron] 2017-10-17 21:40:38: Completed POST /Terraform/SimpleServers.git/git-receive-pack 200 OK in 2.237688s
```

(Note the reverse proxy)

AFAICT, it looks like something is not being successfully run when the HTTPS push takes place, but the logs are leaving no trace of it. I'd love help solving it, but mostly, it seems like a bug that nothing is being logged on whatever is failing.

**Comment by wpywong** [comment]
I am having the same issue with Gogs 0.11.43.0330. The differences are my Gogs (HTTP only) is installed on Windows using SQLLite as database and behind a reverse proxy (the same Windows machine).

**Comment by Unknwon** [comment]
@fdamstra have you looked at log files under `log/hook`?

**Comment by EdoardoVarani** [comment]
Hi, same issue here.
I can push and pull to remote origin but i can't see any change in the UI.
post-receive.log contains this errors:
`2018/06/27 16:04:03 [ERROR] [...its/gogs/cmd/hook.go:215 runHookPostReceive()] PushUpdate: GetUserByName: user does not exist [user_id: 0, name: Moviri]
2018/06/27 16:06:40 [ERROR] [...its/gogs/cmd/hook.go:215 runHookPostReceive()] PushUpdate: GetUserByName: user does not exist [user_id: 0, name: Moviri]
2018/06/27 17:00:50 [ERROR] [...its/gogs/cmd/hook.go:215 runHookPostReceive()] PushUpdate: GetUserByName: user does not exist [user_id: 0, name: Moviri]
2018/06/27 17:22:36 [ERROR] [...its/gogs/cmd/hook.go:215 runHookPostReceive()] PushUpdate: GetRepositoryByName: repository does not exist [id: 0, user_id: 1, name: prova]
`

**Comment by Unknwon** [comment]
@EdoardoVarani SQLite3? Use absolute path for database.

**Comment by EdoardoVarani** [comment]
Hi @Unknwon , thank you very much.
Using absolute path solved my issue 👍 
Unfortunately, now i cannot start the windows service anymore..
When i start the service, the application runs for some seconds and then windows kill the service with error code 1053 (The service did not respond to the start or control request in a timely fashion).
Any hints on that?
Thanks again for your hard work ;)

**Comment by Unknwon** [comment]
@EdoardoVarani the best help comes from `path/to/gogs/log/gogs.log`, check error messages in that file.

**Comment by vi-n** [comment]
I am having this issue. 

I tried setting the path to an absolute path, but this did not solve it. I am running the gogs docker image and using SQLite 3.
