### ISSUE TITLE
can't use 'admin' when first install gogs with Admin Account Setting

### ISSUE THREAD

**Issue by yoker** [gogs/gogs#4831]
i want to use 'admin' as my admin account, but i can't install with it. i got some error like "Admin account setting is invalid: name is reserved [name: admin]".

Gogs Version: 0.11.29.0727

**Comment by Danny3** [comment]
Same problem here on
Gogs version: 0.11.29@2017-08-15
Exact message displayed:
Admin account setting is invalid: name is reserved [name: admin]

**Comment by lukalafaye** [comment]
You cannot use admin as username that's all!

**Comment by uvwild** [comment]
that really sucks!

**Comment by Unknwon** [comment]
You're absolutely right!
