### ISSUE TITLE
npm install from gogs

### ISSUE THREAD

**Issue by emerchalegre** [gogs/gogs#4836]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref):  0.9.13.0319
- Git version: 2.14
- Operating system: Windows
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Hi.

I need to install a package from my gogs repository with the npm, but it is not working.
Does anyone know how to do it?

Thank you.

**Comment by duguying** [comment]
this is a golang based software, not all the software install with npm. follow the doc https://gogs.io/docs/installation
