### ISSUE TITLE
Cannot use Gogs in Termux environment (Android)

### ISSUE THREAD

**Issue by KaMeHb-UA** [gogs/gogs#4853]
- Gogs version (or commit ref): 0.11.29.0727
- Git version: 2.15.0
- Operating system: Android 6.0 ([Termux](https://termux.com/) shell environment) [armhf(v7l), using armv5 binaries]
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- [Log gist](https://gist.github.com/KaMeHb-UA/0e79d72d6cd09f3bf87f31fcbec485ab) (usually found in `log/gogs.log`)
## Description
Seen an error 500 while creating repository (relevant to any user/repo):
`An error has occurred : initRepository: initRepoCommit: git push: fatal: cannot run hooks/pre-receive: No such file or directory To /data/data/com.termux/files/home/gogs-repositories/kamehb-ua/unwatched.git ! [remote rejected] master -> master (pre-receive hook declined) error: failed to push some refs to '/data/data/com.termux/files/home/gogs-repositories/kamehb-ua/unwatched.git'`

Screen above:

![image](https://user-images.githubusercontent.com/20382677/32370021-412e1538-c094-11e7-9164-766de20bced7.png)

**Comment by weinianhe** [comment]
look at unwatched.git/hook/update  
This is a server-side hook check. In side of the file it should be a gogs/gogs hook... 
make sure /usr/bin/env and bash are working.

**Comment by weinianhe** [comment]
Don't get confused with the hook pre-receive in the Git Hooks of gogs 

https://192.168.0.105:3000/[username]/[repo]/settings/hooks/git/pre-receive
This thing doesn't seem to work as of 0.11.53

**Comment by KaMeHb-UA** [comment]
> look at unwatched.git/hook/update
> This is a server-side hook check. In side of the file it should be a gogs/gogs hook...
> make sure /usr/bin/env and bash are working.

Thanks, @weinianhe. Issue may be closed now
