### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by bon** [gogs/gogs#486]
1. I set up a new gogs install.
2. Configured nginx reverse proxy from `myhost` to `myhost:3000`
3. Created a user
4. Made a repo
5. Generated an ssh key
6. Added the ssh key to gogs
7. I can see that it's the only key in `/home/gogs/.ssh/authorized_keys`
8. I can clone the repo from its http URL
9. I can do successfully `ssh -T gogs@myhost`
10. But when I try to clone it from its ssh URL, I get
    
    $ git clone gogs@myhost:bon/testrepo.git
    Cloning into 'testrepo'...
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    $
11. The config file `app.ini` has
    
    [repository]
    ROOT = /srv/gogs/repo
    SCRIPT_TYPE = bash
12. I can see that `/srv/gogs/repo/bon/testrepo.git` exists and that the whole
    `/srv/gogs` tree is owned by `gogs`.

Any ideas what's happening here?

**Comment by Stormwind** [comment]
Hi there,

I rushed yesterday in the same problem and was able to solve it.
The ssh-user needs a shell.

So something like
```
gogs:x:994:994:gogs daemon users:/home/gogs:/bin/false
```
doesn't work.
But
```
gogs:x:994:994:gogs daemon users:/home/gogs:/bin/sh
```
works for me.

Hope that helps.

**Comment by fanningert** [comment]
@Stormwind Thanks, I will include the hint into the AUR packages in the next days.

**Comment by klausenbusk** [comment]
It won't work, as it can't find the config file..

Btw: You said earlier that you will implement this, so it should be implemented now?
"@klausenbusk: Ok, in the next version of the AUR gogs package I add the chsh gogs -s /usr/bin/bash to the pre_install. This will be execute for the install and upgrade process."

**Comment by fanningert** [comment]
@klausenbusk I add it add the moment only at the git-dev version. I updated now in the git and the release version.

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/pull/905 for updates.
