### ISSUE TITLE
Emoji's do not work in a repo's Wiki

### ISSUE THREAD

**Issue by caffeineaddiction** [gogs/gogs#4869]
- Gogs version: 0.11.24.0627
- Operating system: Ubuntu 16.04
- Database: MySQL
- Can you reproduce the bug at https://try.gogs.io: https://try.gogs.io/ca/emoji/wiki/Home
- Log gist (usually found in `log/gogs.log`): Not relevant

Discussion: https://discuss.gogs.io/t/emojis-do-not-work-in-a-repos-wiki/1575

## Description
Emoji's do not work in a repo's Wiki

attempted to use :pencil: and it displayed as `:pencil:`

**Comment by xv1t** [comment]
Join us, also waiting this feature

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
