### ISSUE TITLE
Run Binary GOGS with HTTPS

### ISSUE THREAD

**Issue by madduci** [gogs/gogs#487]
Hi

I'm trying to set up a binary executable of GOGS with the usage of self signed certificates (with custom/conf/app.ini), using OpenSSL, but I get the following message error:

[web.go:379 runWeb()] [E] Fail to start server: crypto/tls: failed to parse private key

How can I enable it?
Perhaps, you should include the script crypto/tls/generate_cert.go in the binary package as well.

**Comment by badoet** [comment]
tried to run  ./gogs cert -ca=true -duration=8760h0m0s -host=mysite.com
but i get this error: Incorrect Usage.
i run it in the github.com/gogits/gogs folder.. 
did i do anything wrong?
i have openssl-1.0.1e installed on my server.
running on centos 7

**Comment by Unknwon** [comment]
Hi @badoet , from the info you provided there is nothing wrong, maybe there are some hidden special characters in your command line somehow occurred when you copy or type the command?

**Comment by KevinHivert** [comment]
HI,
I just installed a gogs server on my vps (installation  from source) and I get the exact same message as @badoet. 
I tried to run ./gogs cert and got : 

```
Command cert not available, please use build tags 'cert' to rebuild.
```

I'm currently trying to do so but it seems not explained how to do it in the docs. Any clue about that ?

**Comment by Unknwon** [comment]
Hi @KevinHivert , use `go build -tags "cert"` will build Gogs with this subcommand. Hope helps!

**Comment by badoet** [comment]
i somehow resolved my issue a few months back, but i forgot what was the solution that i used...

**Comment by Unknwon** [comment]
@badoet :joy: OK, this is what we called life...
