### ISSUE TITLE
Use login password to bind user on LDAP

### ISSUE THREAD

**Issue by codecrafting-net** [gogs/gogs#4884]
- Gogs version (or commit ref): 0.11.33
- Git version: 2.15.0
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

The issue #2526 has solved the problem to use LDAP with BindDN accepting %s but, would be nice to get the password from the login form and use it as the password to bind the ldap. When I provide no password (on the authentication config screen) gogs will perform a anonymous search, which on my organization is not allowed. My account don't have write permissions, so I can't create a user for the gogs. On the authentication menu could have a checkbox like "use login password to bind". This way I am using my own AD account to bind to the LDAP. All users on my corp domain have read permissions, but you must be authenticated first to do so.

**Comment by danieldjewell** [comment]
As noted, I referenced this in #5025 -- I think that using the credentials of the user themselves would be an excellent solution. Needing to create & manage a special bind DN account to read the directory is, in and of itself, extra work and opens another vector for attack. 

## Thoughts

1. Doing an LDAP bind *before* a user has authenticated might not be possible (how do you know the DN of the user to bind to based on just a username?) without some kind of LDAP sync module. 
 * In this case, it would be nice to have the LDAP sync limit itself to users that *are* in the group.
 * I've seen other implementations do periodic or manually triggered syncs to create the user accounts in the local app DB based on group membership. (I don't want to sync the entire directory - just the users that have access!) 
 * I've also seen implementations do the update upon a successful login by an existing user. 

2. There could be performance benefits on high-volume systems. Right now, unless your server only serves one OU or all of your GOGS users are located some OU structure, the Base DN for the search needs to be pretty wide (possibly the whole directory). Searching the whole directory upon every user login could be slow. Contra, performing a manual or scheduled sync of users (e.g. every hour, nightly, etc.) would allow new users to be created in the GOGS DB and their DNs discovered. Then, as suggested by @codecrafting-net, the user's DN would be referenced based on username and the bind could be performed directly against that. 

3. As referenced in #5024 it seems to me to be completely unnecessary to store passwords locally in the GOGS DB for LDAP synced users. Especially if you're doing a Bind DN. 

I *could* be missing something here with LDAP ... as far as I can remember, you need the DN to do the bind. No DN, no bind for the user. Right?

**Comment by cl63** [comment]
We use gogs in our company and have the same problem with LDAP authentication because there is no bind user available :-(
Our LDAP server acceps only COMPANY\USERNAME for authentication. So the bind DN looks like this: COMPANY\%s
User Search Base is: DC=COMPANY,DC=local

So if i could pass the login password as bindpassword it should work.

I'm no go developer, but after a look at the code i have maybe a simple solution for my problem.
in File
pkg/auth/ldap/ldap.go
on lines:

204
--userDN, found = ls.findUserDN(l, name)
++userDN, found = ls.findUserDN(l, name, passwd)


95
--func (ls *Source) findUserDN(l *ldap.Conn, name string) (string, bool) {
++func (ls *Source) findUserDN(l *ldap.Conn, name string, passwd string) (string, bool) {


100
--err := l.Bind(bindDN, ls.BindPassword)
++var bindPass string = ls.BindPassword
++if strings.Compare(ls.BindPassword, "%s") == 0 {
++	bindPass = passwd
++}
++err := l.Bind(bindDN, bindPass)

I hope someone can use my thoughts

**Comment by zwets** [comment]
Excellent suggestion! 

There is another benefit to authenticating with the BindDN of the user, which is that it (in most LDAP configurations) this gives access to attributes of the user being authenticated (such as `mail`).

**Comment by zwets** [comment]
@unknwon I think this issue can be closed, as @codecrafting-net's request is already implemented, namely in the "direct bind" connector.

When going through the code to prepare a PR fixing this issue, I noticed that the first thing the "direct bind" authenticator does is bind with the user's DN and password.

It subsequently retrieves the attributes of the user object while being bound with the user account, thus covering the concern in https://github.com/gogs/gogs/issues/4884#issuecomment-531769395.

What distinguishes the "Bind DN authenticator" from this is that (a) it performs a search for the user DN _before_ it attempts the user bind, and (b) it can be told to retrieve the user attributes while bound as the Bind DN (by ticking "Fetch attributes in Bind DN context").

AFAICS the "direct bind" authenticator then exactly covers the use case of @codecrafting-net.

**Comment by unknwon** [comment]
Thanks @zwets for informing this!
