### ISSUE TITLE
PR: source and destination clarification

### ISSUE THREAD

**Issue by jin78** [gogs/gogs#4906]
Hi

I find Gogs confusing when creating a PR.

Apparently it's [Destination branch] => [Branch to merge] but there's no clear indication in the UI of that information.

I would find it easier to be Source > Destination.

2. things:
1. clarify the UI: From [Source branch] to [Destination]
2. make it customizable?

**Comment by Unknwon** [comment]
>make it customizable?

Fork and and check the template file... and you already have ability to use custom template file.
