### ISSUE TITLE
Hash in branch name is not correctly URL escaped

### ISSUE THREAD

**Issue by mqudsi** [gogs/gogs#4928]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: n/a
- Operating system: n/a
- Database (use `[x]`): n/a
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: https://try.gogs.io/mqudsi/branch-name-fail/branches
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): n/a

## Description

Creating a branch with a `#` in the name and pushing it to gogs results in the branch appearing correctly, but linking to an unescaped version of the branch name in the URL everywhere.

Example: 
https://try.gogs.io/mqudsi/branch-name-fail/branches links to https://try.gogs.io/mqudsi/branch-name-fail/src/gogs-#test which is a bad link (404) when it should instead link to https://try.gogs.io/mqudsi/branch-name-fail/src/gogs-%23test (works)

**Comment by Unknwon** [comment]
Seems like fixed already! :grin:
