### ISSUE TITLE
Submodule with 'ssh:// method' and alternate port breaks hyperlink in webui

### ISSUE THREAD

**Issue by zefie** [gogs/gogs#4941]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.11.0
- Operating system: debian 9.3 amd64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/zefie/gogs_custom_ssh_port_submodule_test)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
(nothing related)
## Description
Adding a submodule that uses an alternate port ('ssh:// method') causes the hyperlink to the submodule's git to be broken.

I guess this wouldn't normally be used (realized I was doing mine wrong) but at the same time, it could be useful in some private environments.

**Comment by Unknwon** [comment]
Hi, can you point out in try.gogs.io/zefie/gogs_custom_ssh_port_submodule_test, which part is wrong and what is expected?

**Comment by zefie** [comment]
Check the link to the module and .gitmodules.
My git is down so the link wouldn't work anyway, but the issue is gogs is linking the ssh port (even tho my git is down, the link is the issue).

The link should be "http://git.zefie.net/zefie/lge_g6_kernel_scripts" but is linked as "http://git.zefie.net/2222/zefie/lge_g6_kernel_scripts", because the module used "ssh://git.zefie.net:2222/"

**Comment by psyciknz** [comment]
I've just created a submodule link also using ssh (to port 8022).
My main project is:
`ssh://git@git.domain:8022/Docker/Docker.git`
my submodule is
```
[submodule "openhab/conf"]
url = ssh://git@git.8022/HomeAutomation/OpenHAB.git
```
In the web UI of Gogs the link for the `conf` folder in the `openhab` directory is for
https://git.domain/8022/HomeAutomation/OpenHAB/commit/f49efa46370da23ec34055d568a6b8401755516a

So it's taken the :8022 port and made a folder as part of the link.

**Comment by swearl** [comment]
same issue.... 2 years neved fix?

**Comment by chill1n** [comment]
This is still a problem with the latest version:
Application version
    0.13.0+dev
Git version
    2.24.3

In my case I have in app.ini:
[server]
SSH_PORT = 8022
OFFLINE_MODE = true

In .gitmodules I have:
[submodule "generic"]
    path = generic
    url = ssh://git@<DOMAIN>:8022/<repo_name>
In the gogs UI the submodule link reads:
http://<DOMAIN>:8022/<repo_name>
but it should read:
http://<DOMAIN>/<repo_name>

**Comment by zefie** [comment]
I am not familiar with the go language but this seems fairly trivial:

if (first 3 letters of repo = ssh)  then do not include port in URL
else include port in url

**Comment by TheDarkUndoing** [comment]
If someone finds the section in the codebase, I'll write a patch for it. I have intermediate experience with Go.

**Comment by unknwon** [comment]
> If someone finds the section in the codebase, I'll write a patch for it. I have intermediate experience with Go.

This is the function that infers the URL for submodule.

**Comment by bioinformatist** [comment]
@juning98 @unknwon I also met this problem. When creating submodule with ssh link, the repo will also direct wrongly to ssh port with webUI. So could you fix it since all of us seems not familar with Go language...

Thanks in advance!:smile:

**Comment by unknwon** [comment]
> > > If someone finds the section in the codebase, I'll write a patch for it. I have intermediate experience with Go.
> > 
> > 
> > This is the function that infers the URL for submodule.
> 
> I might be missing something but I dont see the function.

Sorry! 😂 did not realize I didn't paste the link in: https://github.com/gogs/gogs/blob/fb6693f6123c0a176097e8213b0aaaa7cef34187/internal/gitutil/submodule.go#L23

**Comment by TheDarkUndoing** [comment]
> > > > If someone finds the section in the codebase, I'll write a patch for it. I have intermediate experience with Go.
> > > 
> > > 
> > > This is the function that infers the URL for submodule.
> > 
> > I might be missing something but I dont see the function.
> 
> Sorry! 😂 did not realize I didn't paste the link in: https://github.com/gogs/gogs/blob/fb6693f6123c0a176097e8213b0aaaa7cef34187/internal/gitutil/submodule.go#L23

Thank you, I think the logic would go in here somewhere. I need to figure out how to test this though.

**Comment by unknwon** [comment]
> I need to figure out how to test this though.

I think you can get very far by just add a test case and check the result: https://github.com/gogs/gogs/blob/fb6693f6123c0a176097e8213b0aaaa7cef34187/internal/gitutil/submodule_test.go

**Comment by TheDarkUndoing** [comment]
I would like to get some eyes on the patch I added. https://github.com/gogs/gogs/pull/7383
