### ISSUE TITLE
Deployment Key support write access

### ISSUE THREAD

**Issue by atomi** [gogs/gogs#4972]
Feature Request for write support for #334 Deployment keys. 

Sometimes I have repos on cloud servers that I don't want my global ssh key on and would prefer to use a _per repo_ ssh key.

**Comment by mikeperalta1** [comment]
+1

For certain projects, I prefer to push/pull to a private non-gogs repo host, but have a hook installed such that the repo then pushes a mirror out to a public gogs installation. At the moment I'm stuck using per-account ssh keys, but I would love to be able to use per-repo ssh keys (with write access) for that purpose.

**Comment by Unknwon** [comment]
Realized this is same as https://github.com/gogs/gogs/issues/3880, merging to that thread.
