### ISSUE TITLE
public access to issues and wiki doesn't work

### ISSUE THREAD

**Issue by JamesGKent** [gogs/gogs#4973]
currently running gogs 0.11.34 on raspbian jessie.
I have gogs configured to require the user to log on before anything is visible (Require Sign In View)  
However in this setting if a repo is set to private then other users cannot see the repo, the issue tracker or the wiki, even when public access to issue tracker and wiki is enabled

**Comment by JamesGKent** [comment]
correction, they can be accessed by trying the URL, but searching through the site will not show the repo at all, this is not how i would expect this combination of settings to behave

**Comment by Fastidious** [comment]
Can you replicate (as the original issue template requests) on https://try.gogs.io/, and share the link, please? Disregarding the original issue template has caused many issues to simply be closed.

**Comment by JamesGKent** [comment]
its a bit more complicated than sharing a link, but as an example i have a repo here: https://try.gogs.io/JamesGKent/test  
the repo is private and public access to wifi and wiki are turned on.
if you go directly to that url without commit permissions (not logged in or as a user other than me) you should only be able to access the issues or wiki tab and not the files or pull requests tab.
that part works fine.

however try finding that repo through either the search or explore and you can't.
it's only accessible via direct link, i'm not saying that is an undesirable feature (in some cases i'd say thats preferable), however i'd argue that hiding the repo from search or explore should be a separate setting (in same location as private maybe?)

I've tried to look through the codebase to work out where the list of repos is created to try work out how to influence that behavior, but i'm new to go and so far can't seem to work out where the list is made or how the code decides which repos to include and which to leave out.

**Comment by Fastidious** [comment]
@JamesGKent the name you picked for your repo makes it hard to test (no pun intended). A repo that is set as private should not show under a search, nor whilst using explore. That is by design.

I see more like a bug the ability to be able to see a private repo issues, and wiki. If you search around, I think that has been on the issues before.

**Comment by JamesGKent** [comment]
you say it's by design but in the repo settings, there are options to enable the issue tracker and the wiki, and along with those options is the option to make either of those public.
these are the settings to which i'm referring:
![settings issue](https://user-images.githubusercontent.com/11315221/34577475-239c05a0-f179-11e7-8ab8-1e192cf12491.png)

as per the name, new repo here:
https://try.gogs.io/JamesGKent/PublicWikiPrivateCode

to my way of thinking if the issue tracker and the wiki are supposed to be publicly accessible (as per those settings) then the repo (minus the code) should also appear in public searches (but not if private and those settings are not enabled)

**Comment by JamesGKent** [comment]
and yes i am seeing the same thing as in issue #4356 however i do see this as a bug, if anything the option to have it only accessible by direct link should be (yet another) setting and not the default when they are set to public.

**Comment by Fastidious** [comment]
@JamesGKent yes, the settings allow public access to wiki and issues *if* you have the URL, but I don't think it implies "and make them searchable."

Certainly something more friendlier could be done, as your last sentence makes sense. Maybe @Unknwon can chime in, when he is back from his yearly sabbatical. 😂

**Comment by JamesGKent** [comment]
I'm quite happy to look into it myself, I've already been hacking away at some of the templates to suit my own ends (but no pull req's as probably not desirable for most) such as adding issue labels to the issue feeds page (https://try.gogs.io/issues) adding colour coded icons on the dashboard and adding the number of issues to the lists of repos that appear on both the dashboard and organisation pages.

but i'm struggling to understand where the list of repos shown in the search is generated.
i'm not sure if the list is generated by a common function or if there are multiple functions?
the only `Repos` function i can find is here: https://github.com/gogits/gogs/blob/master/routes/admin/repos.go

but as that appears to be part of admin i'm not sure i'm looking in the right place...

**Comment by Unknwon** [comment]
@JamesGKent here you go: https://github.com/gogits/gogs/blob/master/routes/home.go#L45

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5234 please help test on `develop` branch or https://try.gogs.io.

**Comment by JamesGKent** [comment]
@Unknwon #5234 is my fix for this issue. I've tested (and am still running my patched version) on my system since i made that PR and have not found any side effects.

Thanks for merging.

**Comment by Unknwon** [comment]
@JamesGKent FYI, your patch has one SQL syntax issue (extra parentheses) that I've fixed in `develop` branch.

**Comment by JamesGKent** [comment]
when you say syntax issue, its more a stylistic thing if i got that right, in that they aren't needed, but it does still work?  
I didn't realize I had added them (probably a holdover from how I write python) but this seems to indicate it would be valid:
https://stackoverflow.com/questions/16122695/are-brackets-in-the-where-clause-standard-sql

**Comment by JamesGKent** [comment]
I see what I did, I effectively kept them from the original first query when they weren't needed anymore due to the changes. Thanks for letting me know.

**Comment by Unknwon** [comment]
Nope, extra parentheses are fine, look very carefully to the line I highlighted, you have open without close parentheses. To trigger that, go explore page and search without sign in.

**Comment by JamesGKent** [comment]
Ah thank you, I missed that... I have gogs configured to require sign on, so I didn't hit that part.

**Comment by Unknwon** [comment]
LOL.
