### ISSUE TITLE
Invalid character in Access-Control-Allow-Credentials

### ISSUE THREAD

**Issue by faizalmy** [gogs/gogs#4983]
When I set enabled ACCESS_CONTROL_ALLOW_ORIGIN = *
I got below response in the web server (Apache) log:

Response header name ''Access-Control-Allow-Credentials' ' contains invalid characters, aborting request

https://github.com/gogits/gogs/blob/9362b9fdfe41788bc600a5bc13f2df10ec2222e6/pkg/context/context.go#L268

**Comment by jbg** [comment]
This prevents Gogs from being used behind an AWS ALB with HTTP/2 due to the invalid HTTP header returned by Gogs.

**Comment by unknwon** [comment]
Closing this one since already fixed by #6381 on the `main` branch.

**Comment by unknwon** [comment]
The 0.12.7 has been released that includes the patch of the reported issue.
