### ISSUE TITLE
Can't change profil picture after commit

### ISSUE THREAD

**Issue by mietzen** [gogs/gogs#4999]
- Gogs version (or commit ref): docker Latest 
- Git version: docker Latest 
- Operating system: Ubuntu xenial LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ x ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

I can't change my profile picture after committing to a shared repo. After uploading the picture stays the same.

**Comment by Unknwon** [comment]
You need a browser force refresh.
