### ISSUE TITLE
.Owner.Website with rel="me" ?

### ISSUE THREAD

**Issue by mro** [gogs/gogs#5008]
so that e.g. https://indieweb.org/ sees the back-link. Test e.g. with https://indiewebify.me/

https://github.com/gogits/gogs/blob/6f2347fc71f17b5703a9b1f383a2d3451f88b741/templates/user/profile.tmpl#L34

Or maybe `rel="me nofollow"` like github does.

What do you think?

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5485, please help test on `develop` branch or https://try.gogs.io.

**Comment by federicoculloca** [comment]
Works for the given testcase.

See https://indiewebify.me/validate-rel-me/?url=https%3A%2F%2Ftry.gogs.io%2Funknwon - it found the link but then gogs.io doesn't (obviously) link back.

**Comment by mro** [comment]
awesome, tested with https://try.gogs.io/issue-5008
