### ISSUE TITLE
Page generation time is smaller than the wall time

### ISSUE THREAD

**Issue by march1993** [gogs/gogs#5017]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.11.0
- Operating system: Debian stretch/9.3
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Gogs says the page is generated within 30ms, but the true wall time is almost 150ms. I can't find out what causes so much time.

**Comment by Unknwon** [comment]
Hi, can you explain what is "true wall time"?

**Comment by march1993** [comment]
Time measured from my clock

**Comment by Unknwon** [comment]
Sorry, I cannot figure the relation.

Page generation time is what starting accepting the request to rendering the template. It is not equivalent to response the accept the request to finish responding the request.

I think this thread should moved to the forum https://discuss.gogs.io
