### ISSUE TITLE
API error list-issues-for-a-repository for PostgreSQL

### ISSUE THREAD

**Issue by 502647092** [gogs/gogs#5022]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: git version 2.8.0.GIT
- Operating system: CentOs7.3
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

```
[Macaron] 2018-01-31 16:54:49: Started GET /api/v1/repos/WeChatApp/enquiryService/issues for 192.168.3.234
[Macaron] 2018-01-31 16:54:49: Completed GET /api/v1/repos/WeChatApp/enquiryService/issues 500 Internal Server Error in 17.627963ms
```

## Description

https://github.com/gogits/go-gogs-client/wiki/Issues#list-issues-for-a-repository
Use This API gogs return error
request
```
curl -X GET \
  http://192.168.0.18:3000/api/v1/repos/WeChatApp/enquiryService/issues \
  -H 'Authorization: token ce9d9dfb84d9c354ae111f268ea356795ccb000a' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
```
response
```
{
    "message": "pq: column \"issue.created_unix\" must appear in the GROUP BY clause or be used in an aggregate function",
    "url": "https://github.com/gogits/go-gogs-client/wiki"
}
```

**Comment by Unknwon** [comment]
Merge thread to https://github.com/gogs/gogs/issues/4543.
