### ISSUE TITLE
Fail to initialize ORM engine: sync database struct error

### ISSUE THREAD

**Issue by sprders** [gogs/gogs#5032]
- Gogs version (or commit ref):  0.11.34.1122
- Git version:  2.15.1
- Operating system:  win10 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

- 2018/02/04 17:16:33 [TRACE] Log Mode: File (Trace)
- 2018/02/04 17:16:33 [ INFO] Gogs 0.11.34.1122
- 2018/02/04 17:16:33 [ INFO] Cache Service Enabled
- 2018/02/04 17:16:33 [ INFO] Session Service Enabled
- 2018/02/04 17:16:33 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: sync database struct error: sql: Scan error on column index 2: unsupported Scan, storing driver.Value type <nil> into type *string

---

**Comment by Unknwon** [comment]
Hi, what is your MySQL version?

**Comment by marno2703** [comment]
I was able to reproduce this issue four times now, but I could not find a workaround.

**Comment by junmaqiang** [comment]
me too
```
2019/04/06 00:48:21 [ INFO] Gogs 0.11.88.0220
2019/04/06 00:48:21 [ INFO] Cache Service Enabled
2019/04/06 00:48:21 [ INFO] Session Service Enabled
2019/04/06 00:48:21 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: sync structs to database tables: sql: Scan error on column index 2, name "TABLE_ROWS": unsupported Scan, storing driver.Value type <nil> into type *string
2019/04/06 00:48:22 [ INFO] Gogs 0.11.88.0220
2019/04/06 00:48:22 [ INFO] Cache Service Enabled
2019/04/06 00:48:22 [ INFO] Session Service Enabled
2019/04/06 00:48:22 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: sync structs to database tables: sql: Scan error on column index 2, name "TABLE_ROWS": unsupported Scan, storing driver.Value type <nil> into type *string

```

**Comment by teknofile** [comment]
And also with MariaDB 10.4.12

`# mariadb --version
mariadb  Ver 15.1 Distrib 10.4.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
`
