### ISSUE TITLE
.cpp listed as binary file but can read by click view file(查看文件)

### ISSUE THREAD

**Issue by RightFS** [gogs/gogs#5036]
- Gogs version (or commit ref):  0.11.29.0727
- Git version: vs2017 addin
- Operating system: ubuntu server 16.04 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [y] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
1 changed files with 0 additions and 0 deletions Split View Show Diff Stats
BIN EstWfp/EstWfp.cpp   | View File|

when I click the View File button I can read this file in the browser.but Gogs tells me it's a BIN. 

...

**Comment by rexdf** [comment]
github seems working like this,too. git seems only supporting utf-8 without BOM.

Any other encoding seems to be considered as binary.

But you can use filter to do auto conversion checkout and commit
