### ISSUE TITLE
When a file is modified and renamed within the same commit the rename does not display in the pull request.

### ISSUE THREAD

**Issue by JonLundy** [gogs/gogs#5056]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 1.9.2
- Operating system: Linux x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) https://try.gogs.io/xuu/filename-example2/pulls/1/files
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
In some cases when viewing diffs on files for a pull request it does not show the change in file name. 
It appears to happen when the file is renamed and some lines are added or modified. 

the commands performed to recreate:
- Create a new repository with the README.md included.
- Checkout the repository: `git clone repourl .`
- Rename file: `git mv README.md README2.md`
- Modify file: `echo "update content" >> README2.md`
- Commit changes: `git commit -am 'update and rename file'`
- Push to a new branch: `git push origin master:devel`
- Create a pull request of the `devel` branch compared to `master` 

Additionally if you try to click the View File button it will take you to a 404 page because README.md is now README2.md

I have found that the above issue does not always appear. 
See https://try.gogs.io/xuu/filename-example/pulls/1/files
where nearly the same steps were taken but it does not display the error. 
...

**Comment by hemani19** [comment]
I am facing the same issue. Renaming of `.md` is not showing and rendering returning 404 page.

**Comment by joyartoun** [comment]
Same problem for me using:
Gogs Version: 0.11.86.0130
5.5.60-MariaDB
git version 1.8.3.1
CentOS Linux release 7.6.1810 (Core)

**Comment by unknwon** [comment]
Should be fixed by https://github.com/gogs/gogs/pull/6048.
