### ISSUE TITLE
Public key is not synced to the authorized_keys file inside Docker container upon successful adding

### ISSUE THREAD

**Issue by sinlov** [gogs/gogs#5087]
- Gogs version (0.11.36.0306): 
- Git version: client `2.7.4`
- Operating system: `Docker 17.12.1-ce in Ubuntu 5.4.0-6ubuntu1~16.04.4`
- git ssh version in docker container: `OpenSSH_7.4p1, LibreSSL 2.4.4`
- Database :
  - [x] MySQL
- Can you reproduce the bug at https://try.gogs.io:
  - [x] No
- Log gist (usually found in `log/gogs.log`):

```log
2018/03/09 00:01:41 [TRACE] Template: user/settings/sshkeys
2018/03/09 00:04:57 [TRACE] Log Mode: File (Trace)
2018/03/09 00:04:57 [ INFO] sinlov'git 0.11.36.0306
2018/03/09 00:04:57 [ INFO] Cache Service Enabled
2018/03/09 00:04:57 [ INFO] Session Service Enabled
2018/03/09 00:04:57 [ INFO] Mail Service Enabled
2018/03/09 00:04:57 [ INFO] Git Version: 2.11.3
2018/03/09 00:04:57 [ INFO] SQLite3 Supported
2018/03/09 00:04:57 [ INFO] Run Mode: Production
2018/03/09 00:04:57 [ INFO] SSH server started on 0.0.0.0:10022
2018/03/09 00:04:57 [TRACE] SSH server cipher list: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128]
```

## Description

- Non-administrator user can not add authorized_keys at `/home/git/.ssh/authorized_keys`
- `bug` in  Non-administrator user at page`http://gogshost/user/settings/ssh` UI show add success!
- `simple fix` only administrator user do `Rewrite '.ssh/authorized_keys' file` can write authorized_keys

in path `/home/git/.ssh`

```sh
bash-4.3# ls -alh
total 16
drwx------    2 git      git         4.0K Mar  9 02:48 .
drwxr-xr-x    4 git      git         4.0K Mar  9 02:45 ..
-rw-------    1 git      git         1.1K Mar  9 02:48 authorized_keys
-rwx------    1 git      git           23 Mar  8 23:53 environment
```

this issues same as https://github.com/gogits/gogs/issues/2409

## Wants

- UI bug must be fix
- Non-administrator user can add authorized_keys in `docker sshd server`

**Comment by Unknwon** [comment]
Just to be clear, when editing the file, the only matter is the permission of user `git` that runs Gogs. Gogs's internal user role does not matter.

**Comment by webignorant** [comment]
@unknwon 
I have the same problem in docker.
Fuck the authorized_keys  never write.
restorecon -R -v .ssh cannot fix it, but the command not found in docker image.
God please save me, this problem has been reproduced many times.

**Comment by sinlov** [comment]
@webignorant 
1. check gogs container uid or gid, when entrypoint script run
1. If use volumes, must let container can write file at taget volume.

-------------
see uid or gid use shell
```bash
# uid
$ id -u
# gid
$ id -g
```
