### ISSUE TITLE
[ERROR] ... wrong sequence of bytes for the encoding "UTF8": 0xd0

### ISSUE THREAD

**Issue by vixfree** [gogs/gogs#5093]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: version 2.11.0
- Operating system: Debian GNU/Linux 9.3 (stretch)
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): [ERROR] [.../routes/repo/repo.go:102 handleCreateError()] CreatePost: initRepository: updateRepository: update: pq: wrong sequence of bytes for the encoding "UTF8": 0xd0

## Description
I'm using your gogs program. My country is Russia and I use local = RU. If I create a new repository and immediately write in Russian in the "description" field - I get an error of the form (see log file) 
If the description field is left blank, the error does not appear and everything passes successfully.
After that I can add the text in Russian and there are no problems either.
The error appears only when I create a new repository and immediately fill in the description field.
...
The database I use is: postgresql.
database:
...
Name   |  Owner         | Codepage  | LC_COLLATE  |  LC_CTYPE   |  
-----------+-------------------+----------------+-----------------------+--------------------+
gogs     | git               | UTF8         | ru_RU.UTF-8    | ru_RU.UTF-8 |

go version go1.8.1 linux/amd64
...
locale
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
...
the error is certainly not critical, but if you do not guess to clear the field when creating a repository, you can break your head for a long time ...
...
can I fix it, at least in the next version?
Thanks.

**Comment by s12chung** [comment]
@vixfree I tried locally with my install with postgres 9.5.2 on macOS. the description "Росси́я" (or that multiple times) works for me.

![desc](https://user-images.githubusercontent.com/263394/41879070-e9ba0a3a-78a5-11e8-897f-7ba6adb77ea8.gif)

might be related to db settings? or the exact description you typed.

**Comment by vixfree** [comment]
wow! I just received your message and immediately repeated what you showed me ... and the error did not appear! Since I designated this problem postgresql at me at least - 1 time it was updated. Conclusion: Most likely the problem was in the database. Thank you for paying attention to this problem.
