### ISSUE TITLE
Windows: An error has occurred : GetCommitByPath(xxxxxxx): chdir xxxx

### ISSUE THREAD

**Issue by xamix** [gogs/gogs#5100]
Hello,

Find below my settings:

- Gogs version (or commit ref): 
        0.9.141.0211
- Git version:
        git version 2.16.2.windows.1
- Operating system:
        Windows Small Business Server 2011 Standard
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

I'have installed GOGS on a Windows 2011 SBS server and I'm encountering a problem with my setup:

All works good if I put all my repositories in the same folder as default, for exemple on E:/gogs-repos.

However for my need, each project which are stored in a specific directory path in my system must contain the repository for the current project. Say for example at E:/project1/p1.git

So in order to make GOGS works, I created a hardlink (also tryed symlink) from the GOGS root repo folder (E:/gogs-repos/p1.git) to my project folder (E:/project1/p1.git).
The problem is now I get very often (about 9/10 time) the following error when I try to display the repository (translated from french):

An error has occurred : GetCommitByPath (/xxxxxxxxx): chdir xxxxxxxxxxxxxxxxxxxxxx.git: The process can not access the file because this file is used by another process.
Application Version: 0.9.141.0211

I tried to disable Indexing in those folder but nothing change, I checked if folder was open by another process but nothing is displayed, I used some Windows utilities like "handle"

Sometime the load works but it's very rare.

Please do you have some suggestion to make it works?
Otherwise do you have another solution to keep the repository of each repo in a different root folder for each project?

Regards.

**Comment by xamix** [comment]
Hello,

I finally failed to make it works as I firstly needed it.

Finally I was forced to use a common repository for all project even if it was not my goal....
For information, I also used a Debian VM with cifs mount for access my windows network disk.

For the moment it works well.

Regards.

**Comment by Unknwon** [comment]
Hmm... OK. Though I don't know much details, but glad it at least worked.

Closing the thread since it's a deployment issue.
