### ISSUE TITLE
Drone get wrong clone URL of projects on docker containers

### ISSUE THREAD

**Issue by bestplay** [gogs/gogs#5105]
- Gogs version (or commit ref): 

Gogs version 0.11.34.1122 (docker image)

- Git version: 

git version 2.11.3 (docker image)

- Operating system: 

(docker image)

host system is 

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core
```

- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```

2018/03/15 14:50:08 [TRACE] Session ID: d3456d5052872005
2018/03/15 14:50:08 [TRACE] CSRF Token: MKsjEFLUeD7-ej92Mom9MJd9s786MTUyMTA5NjYwODQ1MTY1NTU0OA==
2018/03/15 14:50:08 [TRACE] Session ID: d25444cb9f28b474
2018/03/15 14:50:08 [TRACE] CSRF Token: 1Y4ugjHdqkFWO8ete3_4UZDJFI06MTUyMTA5NjYwODgyOTg4NzU2Mw==
2018/03/15 14:50:09 [TRACE] Session ID: 63d414fcb9154927
2018/03/15 14:50:09 [TRACE] CSRF Token: FDur6A6eSQ8bEw42Uu35WNT4gZM6MTUyMTA5NjYwOTU5NDM3MzgzMQ==
2018/03/15 14:50:09 [TRACE] Session ID: 7f7ab927e60118eb
2018/03/15 14:50:09 [TRACE] CSRF Token: KMJvQok6F2TPO02-DSwv_iiRnKY6MTUyMTA5NjYwOTY1ODM4ODQ4MA==
2018/03/15 14:50:09 [TRACE] HTTPGit - Authenticated user: richard
2018/03/15 14:50:09 [TRACE] Session ID: 6d940f3e98b27281
2018/03/15 14:50:09 [TRACE] CSRF Token: Xhje_4zHPUB1E870HHAgD3cGSUs6MTUyMTA5NjYwOTkwNTUxNzI0Ng==
2018/03/15 14:50:09 [TRACE] TriggerTask '*******/master' by 'richard'
2018/03/15 14:50:09 [TRACE] DeliverHooks [repo_id: 15]
2018/03/15 14:50:09 [TRACE] AddTestPullRequestTask [head_repo_id: 15, head_branch: master]: finding pull requests
2018/03/15 14:50:09 [TRACE] AddTestPullRequestTask [base_repo_id: 15, base_branch: master]: finding pull requests
2018/03/15 14:50:09 [TRACE] Session ID: f758c25abd25b780
2018/03/15 14:50:09 [TRACE] CSRF Token: ZVtBCSWij0BbkadjYva87qYqBgs6MTUyMTA5NjYwOTkyMzUwMDM1Ng==
2018/03/15 14:50:10 [TRACE] Hook delivered: 6feed6a8-6907-4b89-b3f0-077c874d65c1

```
## Description

#1541 

Both Gogs and Drone run in docker containers.

Drone is able to login  and access my repositories in Gogs.

And  `git push` is able to  trigger Drone CI task.

It fails when the task `git clone` the project.

Because `git clone` using the wrong address `localhost:3000`

**Comment by Lunik** [comment]
Have you tried to change the `ROOT_URL` in the  Gogs `app.ini` ?

**Comment by bestplay** [comment]
Sorry, It have been a while. I will try when i have time. Thank you @Lunik

**Comment by Unknwon** [comment]
I think @Lunik has given the correct solution.

**Comment by lk0606** [comment]
> Have you tried to change the `ROOT_URL` in the Gogs `app.ini` ?

i did this, but nothing changed
<img width="417" alt="image" src="https://user-images.githubusercontent.com/43233310/160323110-26d9589d-74f6-403d-ac13-d51dd1fbdff5.png">
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/43233310/160323177-316f747c-b91d-4b5b-8495-297790f56c3c.png">

**Comment by unknwon** [comment]
@lk0606 In 0.13, you’d want EXTERNAL_URL, accordingly to the CHANGELOG.

**Comment by lk0606** [comment]
> @lk0606 In 0.13, you’d want EXTERNAL_URL, accordingly to the CHANGELOG.
<img width="314" alt="image" src="https://user-images.githubusercontent.com/43233310/160328368-6c97a524-c098-4874-9804-b205f74ea930.png">

set app.ini EXTERNAL_URL, but nothing change

**Comment by lk0606** [comment]
> > @lk0606 In 0.13, you’d want EXTERNAL_URL, accordingly to the CHANGELOG.
> 
> <img alt="image" width="314" src="https://user-images.githubusercontent.com/43233310/160328368-6c97a524-c098-4874-9804-b205f74ea930.png">
> 
> set app.ini EXTERNAL_URL, but nothing change

@unknwon

**Comment by unknwon** [comment]
@lk0606 What are you trying to archive? What's the context? Please use [issue form](https://github.com/gogs/gogs/issues/new?assignees=&labels=%F0%9F%92%8A+bug&template=bug_report.yml) to include more details.

**Comment by lk0606** [comment]
> @lk0606 What are you trying to archive? What's the context? Please use [issue form](https://github.com/gogs/gogs/issues/new?assignees=&labels=%F0%9F%92%8A+bug&template=bug_report.yml) to include more details.

ROOT_URL or EXTERNAL_URL is work
but, I found new question.
drone runner in 0.12.6, has cache.
when I delete repo and new,
that is resolved
