### ISSUE TITLE
Error on posgtresql 10 after post /install form

### ISSUE THREAD

**Issue by codem4ster** [gogs/gogs#5107]
System: Ubuntu 16.04.4 LTS
Db: Postgresql 10
Locale: tr_TR.UTF-8

Description:
I installed gogs into my server and run it on 6002 port. I set reverse proxy on nginx and successfully connect to gogs. It opened /install and I fill the forms missing parts and submit. I got 502 error on submitted page. I inspect that gogs has been shutted down and logs says;

`2018/03/17 12:04:52 [xorm] [warn]  2018/03/17 12:04:52.089165 Table user Column max_repo_creation db default is '-1'::integer, struct default is -1`

Db tables had been created and I can see max_repo_creation column with default value '-1'::integer. My custom app.ini is;

```
APP_NAME = Gogs
RUN_USER = root
RUN_MODE = prod

[server]
PROTOCOL         = http
DOMAIN           = gogs.************.net
ROOT_URL         = http://gogs.***********.net/
HTTP_PORT        = 6002
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = true
OFFLINE_MODE     = false

[database]
DB_TYPE  = postgres
HOST     = 127.0.0.1:5432
NAME     = gogs
USER     = ********
PASSWD   = **********
SSL_MODE = disable
PATH     = data/gogs.db

[service]
DISABLE_REGISTRATION   = true
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
ENABLE_CAPTCHA         = true
REQUIRE_SIGNIN_VIEW    = false

[repository]
ROOT = /root/gogs-repositories

[mailer]
ENABLED = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /opt/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = ***********
```
When I tried to run the gogs again it stops with the same error.

**Comment by Unknwon** [comment]
XORM [warn] is not real error, please provide errors in `gogs.log` file.
