### ISSUE TITLE
Duplicate key value violates unique constraint "UQE_issue_REPO_INDEX"

### ISSUE THREAD

**Issue by AlexKrumov** [gogs/gogs#5114]
- Gogs version (or commit ref):  0.10.8.0307
- Git version: 
- Operating system: CentOS
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
[ERROR] [...s/context/context.go:98 Handle()] NewPullRequest: newIssue: pq: duplicate key value violates unique constraint "UQE_issue_REPO_INDEX"
## Description
When I try to pull I receive error: 500.

Pull Request -1 ???
![giterror](https://user-images.githubusercontent.com/5180183/37656797-b9ddc144-2c51-11e8-8b10-32d49ed6021a.PNG)

**Comment by AlexKrumov** [comment]
Git Database selects:
 SELECT MAX(id) FROM issue;
 max
------
 1703
(1 row)
 SELECT nextval('issue_id_seq');
 nextval
---------
    1722
(1 row)

**Comment by Unknwon** [comment]
Hi,

please consider upgrade your Gogs and report again if issue still exists.
