### ISSUE TITLE
Reverse Proxy Authentication User Name 

### ISSUE THREAD

**Issue by ozzi-** [gogs/gogs#5165]
- Gogs version (or commit ref):  0.11.43
- Git version: 2.7.4
- Operating system: Ubuntu Server 16.04 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):
2018/04/13 15:49:29 [ INFO] Mail Service Enabled
2018/04/13 15:49:29 [ INFO] Git Version: 2.7.4
2018/04/13 15:49:29 [ INFO] SQLite3 Supported
2018/04/13 15:49:29 [ INFO] Run Mode: Production
2018/04/13 15:49:29 [TRACE] Doing: CheckRepoStats
2018/04/13 15:49:29 [ INFO] Listen: http://0.0.0.0:3000
2018/04/13 15:51:52 [TRACE] Log Mode: File (Trace)
2018/04/13 15:51:52 [ INFO] Gogs 0.11.43.0330
2018/04/13 15:51:52 [ INFO] Cache Service Enabled
2018/04/13 15:51:52 [ INFO] Session Service Enabled
2018/04/13 15:51:52 [ INFO] Mail Service Enabled
2018/04/13 15:51:52 [ INFO] Git Version: 2.7.4
2018/04/13 15:51:52 [ INFO] SQLite3 Supported
2018/04/13 15:51:52 [ INFO] Run Mode: Production
2018/04/13 15:51:52 [TRACE] Doing: CheckRepoStats
2018/04/13 15:51:52 [ INFO] Listen: http://0.0.0.0:3000
2018/04/13 15:51:53 [TRACE] Session ID: 2f928deb7731c176
2018/04/13 15:51:53 [TRACE] CSRF Token: hVOzyE_-H_VzQmlfae0eBbdEW0Q6MTUyMzYyNzUxMzg4NDQ2NDk5OQ==
2018/04/13 15:51:53 [TRACE] Template: user/dashboard/dashboard
2018/04/13 15:51:59 [TRACE] Session ID: 2f928deb7731c176
2018/04/13 15:51:59 [TRACE] CSRF Token: hVOzyE_-H_VzQmlfae0eBbdEW0Q6MTUyMzYyNzUxMzg4NDQ2NDk5OQ==

## Description

I am using the following config:
ENABLE_REVERSE_PROXY_AUTHENTICATION = true
ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true
[security]
REVERSE_PROXY_AUTHENTICATION_USER = X-LOGIN-NAME

When I send a header like such:
X-LOGIN-NAME: test

The user created is called "test, test" instead of "test"

**Comment by unknwon** [comment]
Hi, is this still a problem?

**Comment by ozzi-** [comment]
It works with 0.11.91.0811 - nice!
https://i.imgur.com/mZjh5jb.png

**Comment by unknwon** [comment]
Nice, thanks for confirming!
