### ISSUE TITLE
404 For No Permission

### ISSUE THREAD

**Issue by wyatt-herkamp** [gogs/gogs#5167]
- Gogs version (or commit ref): Gogs Version: 0.11.34.1122
- Git version: git version 2.7.4
- Operating system: Ubuntu(Linux)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
I don't think that is Relevant Either 
## Description
You go here what error is thrown? 404. https://git.kingtux.me/wherkamp/PrivateTest
The project exists however, you lack the permission. I think this should be changed to error 403 https://en.wikipedia.org/wiki/HTTP_403
Thank you for the support. Also this is a awesome project.

**Comment by wherkamp** [comment]
Ok, I was kinda thinking that. I just kinda wanted  to know. This should be configurable. Thank you :) 👍
