### ISSUE TITLE
JS vulnerability via .ipynb

### ISSUE THREAD

**Issue by rokuu** [gogs/gogs#5170]
- Gogs version (or commit ref): 0.11.44.0409
- Can you reproduce the bug at https://try.gogs.io: YES
  - [x] Yes : https://try.gogs.io/testbbar/test-ipynb/src/master/Untitled.ipynb

JS code is executed, not just parsed as markdown

If this is a vulnerability, whats a quick fix for disabling parsing of .ipynb files altogether for the time being?

**Comment by GramThanos** [comment]
A temporary fix could be to block the content that may contain javascript code and let the user run it on demand.

![image](https://user-images.githubusercontent.com/14858959/69077612-a9213f80-0a3e-11ea-9f3e-7e374caed4ef.png)


```javascript
/** notebook.js patch to block vulnerable content */
nb.display.blocked = function (data, type) {
	var el = $('<div>');
	el.css({'text-align' : 'center', 'padding' : '20px'});
	el.text('Unsafe ' + type + ' blocked.').append('<br>');
	var load = $('<a>').addClass('ui tiny button').html('<i class="fa fa-exclamation-triangle"></i> Load unsafe content');
	load.click(function() {
		$(nb.display[type](data)).insertAfter(el);
		el.remove();
	});
	el.append(load);
	return el[0];
};
nb.display.blocked_html = function (html) {
	return this.blocked(html, 'html');
};
nb.display.blocked_svg = function (svg) {
	return this.blocked(svg, 'svg');
};
nb.display.blocked_latex = function (latex) {
	return this.blocked(latex, 'latex');
};
nb.display.blocked_javascript = function (javascript) {
	return this.blocked(javascript, 'javascript');
};
nb.display["text/html"] = nb.display.blocked_html;
nb.display["text/svg+xml"] = nb.display.blocked_svg;
nb.display["image/svg+xml"] = nb.display.blocked_svg;
nb.display["text/latex"] = nb.display.blocked_latex;
nb.display["application/javascript"] = nb.display.blocked_javascript;
```

To try it you can load
https://try.gogs.io/gramthanos/TestRepositoryForDebugging/src/master/test.ipynb

Run it on the console, and then reload the file with

```javascript
/** Reload ipynb **/
$(".nb-notebook").remove()
var raw_file_url = $('#repo-read-file a.ui.button')[2].href;
$.getJSON(raw_file_url, null, function(notebook_json) {
	var notebook = nb.parse(notebook_json);
	rendered = notebook.render();
	$("#ipython-notebook").append(rendered);
	$("#ipython-notebook code").each(function(i, block) {
		$(block).addClass("py").addClass("python");
		hljs.highlightBlock(block);
	});

	var renderer = new marked.Renderer();
	var context = raw_file_url;
	context = context.substring(0, context.lastIndexOf("/"));
	renderer.image = function (href, title, text) {
		return `<img src="${context}/${href}"`
	}
	$("#ipython-notebook .nb-markdown-cell").each(function(i, markdown) {
		$(markdown).html(marked($(markdown).html(), {renderer: renderer}));
	});
});
```

But it looks like that there are more parts on the library code that use `innerHTML` to display unsafe code.

**Comment by unknwon** [comment]
Thanks! I have a solution in mind (send the final HTML to Gogs backend for sanitizing). I'll give it a try this week.

**Comment by GramThanos** [comment]
An other idea to explore is to load the preview inside a sandboxed iframe.

**Comment by unknwon** [comment]
OK, finally found a way to reuse the backend HTML sanitizer, it is good now: https://try.gogs.io/testbbar/test-ipynb/src/master/Untitled.ipynb
