### ISSUE TITLE
Attempt to fix UI responsiveness

### ISSUE THREAD

**Issue by rokuu** [gogs/gogs#5179]
>The smallest resolution officially supported is 1024*768, however the UI may still look right in smaller resolutions, but no promises or fixes.

Well, a few edits might fix the UI in resolutions under 1024*768.

Such as https://github.com/gogits/gogs/pull/5169/commits/48309d04c9c86e7270d562b48b767471c1f42299, which solves the code editor responsiveness.

Leaving the remaining pages yet to be fixed as follows : 
- [x] Repo file/dir list
- [x] Repo commit history
- [x] Admin panel

https://imgur.com/a/HqmOF

**EDIT** : The Repo file/dir list is fixed by changing https://github.com/gogits/gogs/blob/9e3c83372f19853ac1dc164e2fcf58d9779ac0f0/templates/repo/view_list.tmpl#L1 to
``` <table id="repo-files-table" class="ui unstackable fixed single line table"> ```

**Comment by rokuu** [comment]
The remaining pages need some more work. ```unstackable``` variation of the tables won't work because they are all attached segements.

**Comment by rokuu** [comment]
@Unknwon Fixed by https://github.com/gogits/gogs/pull/5182

**Comment by rokuu** [comment]
Just realized, this is an easier fix for the view_file.tmpl instead of https://github.com/gogits/gogs/pull/5169.

All it needs is another unstackable variation.

https://github.com/gogits/gogs/blob/master/templates/repo/view_file.tmpl#L38

to

```	<div class="ui unstackable attached table segment">```

**Comment by unknwon** [comment]
I think this is addressed long time ago, closing.
