### ISSUE TITLE
Gogs fails to start with MySQL 8.0

### ISSUE THREAD

**Issue by hassanwaqar00** [gogs/gogs#5187]
- Gogs version (or commit ref): 0.11.43.0330
- Git version: 
- Operating system: Windows 10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):
2018/04/21 01:25:29 [TRACE] Log Mode: File (Trace)
2018/04/21 01:25:29 [ INFO] XYZ : Git Service 0.11.43.0330
2018/04/21 01:25:29 [ INFO] Cache Service Enabled
2018/04/21 01:25:29 [ INFO] Session Service Enabled
2018/04/21 01:25:29 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: sync: this authentication plugin is not supported

## Description
MySQL version 8.0.11

Previously closed but relevant issue: https://github.com/gogits/gogs/issues/4045
...

**Comment by 0x9c** [comment]
the same situation with mysql 8.0.11 on ubuntu 18.04

**Comment by rokuu** [comment]
```In MySQL 8.0, caching_sha2_password is the default authentication plugin rather than mysql_native_password.```

**Comment by ndebeiss** [comment]
if you connect with user gogs :
ALTER USER 'gogs'@'%' IDENTIFIED WITH mysql_native_password BY 'password value'

**Comment by Unknwon** [comment]
Vendor has been updated as well by https://github.com/gogs/gogs/commit/93f3a7f96a1bc99ba17f02c5fb8e2e5b21671c3c. 

Things should work now after running:

```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password value'
```
