### ISSUE TITLE
Organization repository list pagination does not work

### ISSUE THREAD

**Issue by atom0s** [gogs/gogs#5225]
- Gogs version (or commit ref): 0.11.43.0330
- Git version: 2.17.0.windows.1
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
N/A - This is not log related.

## Description

When browsing an organizations repository list, if the list is multiple pages, the page selection bar does not work at all. For example, if you navigate to, say:
http://git.ashita.atom0s.com/Plugins/

We have 23 repositories in this specific Organization. However, none of the page buttons at the bottom work. It simply refreshes the current page.

I had this issue on the old v0.9.x branch and have updated to the latest v0.11 branch and still have this issue. 

Strangely, the other organizations on my Gogs install do not see this issue, for example:
http://git.ashita.atom0s.com/Addons/

**Comment by atom0s** [comment]
On a side note, monitoring how the link redirect works, it appears to be getting a '302 Found' HTTP code and being redirected back to the base /Plugins/ organization page vs going to the proper paging. The other organization pages do not see this issue and navigate properly.

I do not have any custom setups in place to handle the organization paging manually via any type of redirects or similar in IIS or any web.config files. 

I do use Cloudflare for DDoS protection but only for its caching and DNS protections. I do not use any redirections on their end.

**Comment by Unknwon** [comment]
How many repositories does **Plugins** organization have?

**Comment by Unknwon** [comment]
Any private repositories?

**Comment by atom0s** [comment]
Nope, all 23 repos are public.

**Comment by Unknwon** [comment]
How did you get the count? What is somehow the count is wrong?...
