### ISSUE TITLE
Crash upon merge pull request

### ISSUE THREAD

**Issue by 502647092** [gogs/gogs#5228]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 1.9.2
- Operating system: Linux
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes https://try.gogs.io/502647092/CrashTest/pulls/3
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

create three branch dev release master

first create pr release -> master
Second create pr dev -> release 
third merge dev -> release 
the server will crash

**Comment by 502647092** [comment]
@Unknwon

**Comment by Unknwon** [comment]
Hi,

1. https://try.gogs.io/502647092/CrashTest/pulls/3 gives no information related to this thread as far as I notice.
2. I can't help you without logs, "crash" means nothing.

**Comment by 502647092** [comment]
@Unknwon you can do this step

create three branch dev release master

first create pr release -> master
Second create pr dev -> release
third merge dev -> release
the server will crash

**Comment by 502647092** [comment]
![game](https://user-images.githubusercontent.com/10203793/40266515-18c2fbdc-5b7f-11e8-81e5-b4f8d7874f59.gif)

**Comment by Unknwon** [comment]
Why it is so hard to provide your crash log?

**Comment by 502647092** [comment]
```
2018/05/21 10:26:13 [TRACE] AddTestPullRequestTask [head_repo_id: 482, head_branch: dev]: finding pull requests
2018/05/21 10:26:13 [TRACE] AddTestPullRequestTask [base_repo_id: 482, base_branch: dev]: finding pull requests
2018/05/21 10:26:13 [TRACE] Session ID: fd9c4c771338fc3b
2018/05/21 10:26:13 [TRACE] CSRF Token: SK0Z8g9YW6A4rN0TW6lHqpVuQLY6MTUyNjg2NjA4NjMxOTI5NjEzNw==
2018/05/21 10:26:13 [TRACE] Detected encoding: UTF-8 (fast)
2018/05/21 10:26:13 [TRACE] Template: repo/pulls/compare
2018/05/21 10:26:20 [TRACE] Session ID: bd6773c769474349
2018/05/21 10:26:20 [TRACE] CSRF Token: fQuEhyIUH7nMOClhSg5ZHI43FKs6MTUyNjg2OTU4MDkyNDg1MjkwNA==
2018/05/21 10:26:25 [TRACE] Session ID: fd9c4c771338fc3b
2018/05/21 10:26:25 [TRACE] CSRF Token: SK0Z8g9YW6A4rN0TW6lHqpVuQLY6MTUyNjg2NjA4NjMxOTI5NjEzNw==
2018/05/21 10:26:25 [TRACE] PullRequest[0].testPatch (patchPath): /home/sixigit/jtb/git.git/pulls/2.patch
2018/05/21 10:26:25 [TRACE] Session ID: 24b492dd4aac1296
2018/05/21 10:26:25 [TRACE] CSRF Token: jbTr8e5O8rQcIHq0F0GEf5G9XbU6MTUyNjg2OTU4NTIzODMyNTg2NA==
2018/05/21 10:26:25 [TRACE] Template: status/404
2018/05/21 10:26:25 [TRACE] PushToBaseRepo[482]: pushing commits to base repo 'refs/pull/2/head'
2018/05/21 10:26:25 [TRACE] Pull request created: 482/8993
2018/05/21 10:26:25 [TRACE] Session ID: fd9c4c771338fc3b
2018/05/21 10:26:25 [TRACE] CSRF Token: SK0Z8g9YW6A4rN0TW6lHqpVuQLY6MTUyNjg2NjA4NjMxOTI5NjEzNw==
2018/05/21 10:26:25 [TRACE] Template: repo/issue/view
2018/05/21 10:26:29 [TRACE] Session ID: fd9c4c771338fc3b
2018/05/21 10:26:29 [TRACE] CSRF Token: SK0Z8g9YW6A4rN0TW6lHqpVuQLY6MTUyNjg2NjA4NjMxOTI5NjEzNw==
2018/05/21 10:26:29 [TRACE] Pull request merged: 8828
2018/05/21 10:26:29 [TRACE] DeliverHooks [repo_id: 482]
2018/05/21 10:26:29 [TRACE] AddTestPullRequestTask [head_repo_id: 482, head_branch: release]: finding pull requests
2018/05/21 10:26:29 [TRACE] Log Mode: File (Trace)
2018/05/21 10:26:29 [ INFO] 四喜技术中心 0.11.34.1122
2018/05/21 10:26:29 [ INFO] Cache Service Enabled
2018/05/21 10:26:29 [ INFO] Session Service Enabled
2018/05/21 10:26:29 [ INFO] Git Version: 2.8.0.GIT
2018/05/21 10:26:32 [ INFO] SQLite3 Supported
2018/05/21 10:26:32 [ INFO] Run Mode: Production
2018/05/21 10:26:32 [TRACE] Doing: CheckRepoStats
2018/05/21 10:26:32 [ INFO] Listen: http://0.0.0.0:3000
2018/05/21 10:26:34 [TRACE] Session ID: fe67d6bea19dbe37
2018/05/21 10:26:34 [TRACE] CSRF Token: 76s5SMcwjsuztt8VkhmfV3A5s286MTUyNjg2OTU5NDU0MDMwMzkyMA==
```

**Comment by Unknwon** [comment]
If there is an error, there are logs, no exceptions.

**Comment by Unknwon** [comment]
I'll try to reproduce when I have time.

**Comment by jmiedzinski** [comment]
Here you have a log from crash

[gogs-15-r97f7.log](https://github.com/gogs/gogs/files/2102969/gogs-15-r97f7.log)

**Comment by 502647092** [comment]
@Unknwon i use docker image to reproduce this bug and get some log

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc419d6]

goroutine 2732 [running]:
github.com/gogs/gogs/models.(*Repository).getOwner(0x0, 0x1284b00, 0xc0008fa750, 0x100000000000034, 0x0)
	/go/src/github.com/gogs/gogs/models/repo.go:399 +0x26
github.com/gogs/gogs/models.(*Repository).mustOwner(0x0, 0x1284b00, 0xc0008fa750, 0xc00341a2e8)
	/go/src/github.com/gogs/gogs/models/repo.go:412 +0x43
github.com/gogs/gogs/models.(*Repository).repoPath(0x0, 0x1284b00, 0xc0008fa750, 0x2, 0x2)
	/go/src/github.com/gogs/gogs/models/repo.go:532 +0x43
github.com/gogs/gogs/models.(*Repository).RepoPath(0x0, 0x44, 0xc00060dd00)
	/go/src/github.com/gogs/gogs/models/repo.go:536 +0x43
github.com/gogs/gogs/models.(*PullRequest).PushToBaseRepo(0xc0000aca80, 0x0, 0x0)
	/go/src/github.com/gogs/gogs/models/pull.go:639 +0x110
github.com/gogs/gogs/models.addHeadRepoTasks(0xc002b2bdd0, 0x1, 0x2)
	/go/src/github.com/gogs/gogs/models/pull.go:721 +0x144
github.com/gogs/gogs/models.AddTestPullRequestTask(0xc002ac1000, 0x1, 0xc002ed69e8, 0x7, 0xc000a36400)
	/go/src/github.com/gogs/gogs/models/pull.go:766 +0x558
created by github.com/gogs/gogs/models.(*PullRequest).Merge.func1
	/go/src/github.com/gogs/gogs/models/pull.go:199 +0xc4

```
full log
[2019-03-05-gogs-0.11.88.0220.log](https://github.com/gogs/gogs/files/2929560/2019-03-05-gogs-0.11.88.0220.log)

**Comment by Unknwon** [comment]
Possible cause: `pr.HeadRepo` is nil at line **models/pull.go:639**.

But in this case, you should see a log line contains:

```
.UpdatePatch: ignored cruppted data
```

**Comment by lpotherat** [comment]
Hello, 
I'm having the same issue, with the same crash and back trace but on a newer version.

* Gogs version (or commit ref): 0.11.91.0811
* Git version: 1.8.3.1
* Operating system: Linux
* Database (use `[x]`):
  * [ ]  PostgreSQL
  * [x]  MySQL (MariaDb)
  * [ ]  MSSQL
  * [ ]  SQLite
* Can you reproduce the bug at https://try.gogs.io:
  * [x]  Yes https://try.gogs.io/502647092/CrashTest/pulls/3
  * [ ]  No
  * [ ]  Not relevant

`Jan 7 10:20:19 vm-gitpb01 gogs: panic: runtime error: invalid memory address or nil pointer dereference
Jan 7 10:20:19 vm-gitpb01 gogs: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc94cf7]
Jan 7 10:20:19 vm-gitpb01 gogs: goroutine 32334 [running]:
Jan 7 10:20:19 vm-gitpb01 gogs: github.com/gogs/gogs/models.(*Repository).getOwner(...)
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:399
Jan 7 10:20:19 vm-gitpb01 gogs: github.com/gogs/gogs/models.(*Repository).mustOwner(0x0, 0x13664a0, 0xc000178b60, 0xff8dc0)
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:412 +0x27
Jan 7 10:20:19 vm-gitpb01 gogs: github.com/gogs/gogs/models.(*Repository).repoPath(0x0, 0x13664a0, 0xc000178b60, 0x44, 0xc002137d10)
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:532 +0x43
Jan 7 10:20:19 vm-gitpb01 gogs: github.com/gogs/gogs/models.(*Repository).RepoPath(...)
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:536
Jan 7 10:20:19 vm-gitpb01 gogs: github.com/gogs/gogs/models.(*PullRequest).PushToBaseRepo(0xc0001de460, 0x0, 0x0)
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:639 +0x127
Jan 7 10:20:19 vm-gitpb01 gogs: github.com/gogs/gogs/models.addHeadRepoTasks(0xc0032c8170, 0x1, 0x2)
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:721 +0x14d
Jan 7 10:20:19 vm-gitpb01 gogs: github.com/gogs/gogs/models.AddTestPullRequestTask(0xc00068e200, 0x6, 0xc00404c810, 0x3, 0xc00329a700)
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:766 +0x704
Jan 7 10:20:19 vm-gitpb01 gogs: created by github.com/gogs/gogs/models.(*PullRequest).Merge.func1
Jan 7 10:20:19 vm-gitpb01 gogs: /home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:199 +0xba
Jan 7 10:20:19 vm-gitpb01 systemd: gogs.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 7 10:20:19 vm-gitpb01 systemd: Unit gogs.service entered failed state.
Jan 7 10:20:19 vm-gitpb01 systemd: gogs.service failed.
`

Thanks for your support !

**Comment by lpotherat** [comment]
> 
> 
> Possible cause: `pr.HeadRepo` is nil at line **models/pull.go:639**.
> 
> But in this case, you should see a log line contains:
> 
> ```
> [TRACE] PullRequest[xx].UpdatePatch: ignored cruppted data
> ```

There is a line like this in the log provided by @jmiedzinski , is this of any help ?
