### ISSUE TITLE
Error when deploying Gogs with Docker - start.sh: exec: line 73: -e: not found

### ISSUE THREAD

**Issue by Korpsian** [gogs/gogs#5235]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: Ubuntu Server 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
When trying to deploy the Gogs Container I get the following error:

`/app/gogs/docker/start.sh: exec: line 73: -e: not found`

Docker Command I'm using:
```
docker run -it --link mariaDB:mysql \
--name gogs -p 10022:22 -p 84:3000 \
-v /gogs/data:/data gogs/gogs  \
-e "LETSENCRYPT_HOST=<MyDomain>" \
-e "VIRTUAL_HOST=<MyDomain>" \
--expose=84 gogs/gogs
```

These commands are used for my nginx reverse proxy for handeling the SSL Certs and subdomains:

> -e "LETSENCRYPT_HOST=<MyDomain>" \
> -e "VIRTUAL_HOST=<MyDomain>" \
> --expose=84 

...

I tried to deploy the container without these commands but I still get the same  error.

**Comment by suksit** [comment]
I think you have to remove the first `gogs/gogs` (where I put the stars)

```bash
docker run -it --link mariaDB:mysql \
--name gogs -p 10022:22 -p 84:3000 \
-v /gogs/data:/data ***gogs/gogs***  \
-e "LETSENCRYPT_HOST=<MyDomain>" \
-e "VIRTUAL_HOST=<MyDomain>" \
--expose=84 gogs/gogs

**Comment by Korpsian** [comment]
Ok found the problem (sorry for bothering it was my problem) 
It looks like I exposed the wrong port because i'm dumb.
