### ISSUE TITLE
Installation error: Command in array or slice literal

### ISSUE THREAD

**Issue by welljsjs** [gogs/gogs#5248]
- Operating system: `Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux`
- Git version: 2.11.0
- Gogs version (or commit ref): 0.11.49.0521
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): Not available.

## Description
During the installation of gogs as [described here](https://gogs.io/docs/installation/install_from_source), the installation aborts and the following errors are thrown: 

(When running `go get -u github.com/gogits/gogs`):

```
# github.com/gogits/gogs
src/github.com/gogits/gogs/gogs.go:31:6: cannot use cmd.Web (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
src/github.com/gogits/gogs/gogs.go:32:6: cannot use cmd.Serv (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
src/github.com/gogits/gogs/gogs.go:33:6: cannot use cmd.Hook (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
src/github.com/gogits/gogs/gogs.go:34:6: cannot use cmd.Cert (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
src/github.com/gogits/gogs/gogs.go:35:6: cannot use cmd.Admin (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
src/github.com/gogits/gogs/gogs.go:36:6: cannot use cmd.Import (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
src/github.com/gogits/gogs/gogs.go:37:6: cannot use cmd.Backup (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
src/github.com/gogits/gogs/gogs.go:38:6: cannot use cmd.Restore (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
```

I think #4893 is about the same issue, but unfortunately, my `$GOPATH` variable is set correctly to `/home/git/go` and this already happens before building. 
...

**Comment by Unknwon** [comment]
What is your Go version?

**Comment by welljsjs** [comment]
That was this version: go1.10.2.linux-armv6l.tar.gz, so 1.10.2. 
I now successfully installed gogs from binary from GitHub instead of an installation from source.

**Comment by Unknwon** [comment]
I think the problem is Gogs now uses `gogs/gogs` instead of `gogits/gogs`. I'll update the docs.

**Comment by Unknwon** [comment]
Done.

**Comment by gotounix** [comment]
Goto admin panel ``/admin`` -> ``Resync pre-receive, update and post-receive hooks of all repositories``.
