### ISSUE TITLE
Resource interpreted as Stylesheet but transferred with MIME type text/html

### ISSUE THREAD

**Issue by maximeozenne** [gogs/gogs#5253]
- Gogs version (or commit ref): 0.11.27.0718
- Git version: 1.7.10.4
- Operating system: Raspbian Wheezy
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

2018/05/30 10:06:48 [TRACE] Log Mode: File (Trace)
2018/05/30 10:06:48 [ INFO] Gogs 0.11.27.0718
2018/05/30 10:06:48 [ INFO] Cache Service Enabled
2018/05/30 10:06:48 [ INFO] Session Service Enabled
2018/05/30 10:06:48 [ INFO] Mail Service Enabled
2018/05/30 10:06:48 [ INFO] Register Mail Service Enabled
2018/05/30 10:06:48 [ INFO] Notify Mail Service Enabled
2018/05/30 10:06:52 [ INFO] Git Version: 1.7.10.4
2018/05/30 10:06:52 [ INFO] Run Mode: Production
2018/05/30 10:06:52 [TRACE] Doing: CheckRepoStats
2018/05/30 10:06:56 [ INFO] Listen: http://0.0.0.0:[PORT][IP][PORT]
2018/05/30 10:16:52 [TRACE] Doing: MirrorUpdate
2018/05/30 10:23:07 [TRACE] Session ID: c72e2792da8cd7c2
2018/05/30 10:23:07 [TRACE] CSRF Token: epE6yguyZcn7EHMeGFEN8tiCHdc6MTUyNzY2Njc2OTk1NTc4NjA0NA==
2018/05/30 10:23:07 [TRACE] Template: home
...
2018/05/30 10:26:52 [TRACE] Doing: MirrorUpdate
...

## Description

I updated the app.ini file : go/src/github.com/gogits/gogs/custom/conf/app.ini to change the [server] ROOT_URL. The roor url was my DNS name but I added a VPN on my server so I just changed the ip:port.

After that I rebooted then I made pull/push for testing purpose and all was working great except for one thing : my web interface stylesheet isn't working anymore. Here is a capture of the problem :

![gogs error](https://user-images.githubusercontent.com/12842987/40728427-61f3f528-642a-11e8-97e7-6cee175e2395.png)

As you can see on the right side of the screen, the browser console is telling me that I have the following error : 

> Resource interpreted as Stylesheet but transferred with MIME type text/html

It seems that it's the error related to the css.

I wasn't able to find an issue or a forum thread talking about it, have you some tips to fix it up ?

**Comment by maximeozenne** [comment]
I just updated gogs, the problem disappeared.

**Comment by ianharrigan** [comment]
Hi, i think im facing the same problem:

![image](https://user-images.githubusercontent.com/3024242/89406520-96aa7b80-d71d-11ea-86b4-071107f31ae4.png)

This is from source, latest git version,

Any idea how to fix this?

**Comment by ianharrigan** [comment]
FYI - this worked for me:

```
Error: Resource interpreted as Stylesheet but transferred with MIME type application/x-css
Causes: wrong value in the Windows registry
Solution: Find .css in HKEY_CLASSES_ROOT in registry and change its Content Type to text/css.
```
