### ISSUE TITLE
Get error if the Description is set for a repository

### ISSUE THREAD

**Issue by PCFung** [gogs/gogs#5255]
- Gogs version (or commit ref): 0.11.50.0530
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/pcfung/test2)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Steps to reproduce the problem 
1. Create a new repository in gogs
2. Fill in the necessary fields and input some text in the description.
3. Push a local repository to this newly created gogs repository.
4. Clicks the repository link in the dashboard
5. You will get the following error
>template: repo/home:8:111: executing "repo/home" at <Str2html>: wrong type for value; expected string; got template.HTML

...

A workaround is to remove the Description in the settings. But since the GUI for the repository is not showing at all, it could be difficult for a new user (like me...)

**Comment by Unknwon** [comment]
Thanks for the report, fixed by https://github.com/gogs/gogs/commit/e25fe22f9d6ce8a74ce205f9c1fae1c5506c2611.
