### ISSUE TITLE
File source view line numbers include extra line

### ISSUE THREAD

**Issue by mzmcbride** [gogs/gogs#5261]
A file such as <https://git.legoktm.com/legoktm/gogs-mirror/src/48a5f0b74c381121542571e4d11db3588cbc2be8/requirements.txt> has the content "requests\n". This is traditionally counted as a single line. When using Gogs version 0.11.43.0330, the file source view shows two line numbers instead. This seems like a bug.

**Comment by Unknwon** [comment]
Hi, although #5270 "fixes" the current problem, I don't think it is a bug, it tells user there is newline character because Gogs does not show an icon if there is no newline character at the end of file currently.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5270, please help test on `develop` branch or https://try.gogs.io.
