### ISSUE TITLE
Skip the /install page

### ISSUE THREAD

**Issue by greyarch** [gogs/gogs#5263]
- Gogs version (or commit ref): 0.11.43
- Git version: 
- Operating system: Linux (CentOS)/Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I'd like to be able to skip the initial /install page. Essentially, I want to put all relevant config in the custom app.ini file and start GOGS. This issue https://github.com/gogs/gogs/issues/1084 seems to suggest that `[security] INSTALL_LOCK = false` "does the magic", but it does not work - I still see the /install page. I am starting GOGS in Docker container if this is relevant. All help is much appreciated :)

**Comment by Unknwon** [comment]
`[security] INSTALL_LOCK = true`, not `false`.
