### ISSUE TITLE
Time set to current after restored from backup

### ISSUE THREAD

**Issue by Isolus** [gogs/gogs#5264]
- Gogs version (or commit ref): 0.11.44.0409
- Git version: 2.1.4
- Operating system: Debian 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

After restoring a backup the date and time of every issue, push etc. is the current date and time. The dates in the backup files are fine.

**Comment by Isolus** [comment]
I had a quick lock at the code.

It seems restoring the database calls the insert function of the corresponding struct and the insert function has a before insert hook:
```
func (issue *Issue) BeforeInsert() {
	issue.CreatedUnix = time.Now().Unix()
	issue.UpdatedUnix = issue.CreatedUnix
}
```

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by Isolus** [comment]
I get some `[ERROR] [...ogs/models/models.go:369 ImportDatabase()] Failed to reset 'created_unix': Error 1054: Unknown column 'created_unix' in 'field list'` errors, but it finishes and seems to work (can't find a place with a wrong date).

**Comment by Isolus** [comment]
If I remove `Milestone.json` from the backup it works without errors. It looks like the entries in this file don't have a `created_unix` field.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch.

**Comment by Isolus** [comment]
Errors are gone but `deadline_unix' of all milestones is set to -62135596800 after import.

**Comment by Isolus** [comment]
```
{"ID":1,"RepoID":65,"Name":"Version 1.0","Content":"","IsClosed":false,"NumIssues":12,"NumClosedIssues":7,"Completeness":58,"DeadlineUnix":1527976800,"ClosedDateUnix":0}
{"ID":2,"RepoID":65,"Name":"Version 1.1","Content":"","IsClosed":false,"NumIssues":2,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":1529100000,"ClosedDateUnix":0}
{"ID":3,"RepoID":65,"Name":"ideas for later","Content":"","IsClosed":false,"NumIssues":2,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":253402210800,"ClosedDateUnix":0}
{"ID":4,"RepoID":66,"Name":"Version 1.0","Content":"","IsClosed":false,"NumIssues":2,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":253402210800,"ClosedDateUnix":0}
{"ID":5,"RepoID":66,"Name":"Version 2.0","Content":"","IsClosed":false,"NumIssues":0,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":253402210800,"ClosedDateUnix":0}
{"ID":6,"RepoID":66,"Name":"ideas for later","Content":"","IsClosed":false,"NumIssues":0,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":253402210800,"ClosedDateUnix":0}
{"ID":7,"RepoID":67,"Name":"Version 1.0","Content":"","IsClosed":false,"NumIssues":1,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":253402210800,"ClosedDateUnix":0}
{"ID":8,"RepoID":67,"Name":"Version 2.0","Content":"","IsClosed":false,"NumIssues":0,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":253402210800,"ClosedDateUnix":0}
{"ID":9,"RepoID":67,"Name":"ideas for later","Content":"","IsClosed":false,"NumIssues":0,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":253402210800,"ClosedDateUnix":0}
{"ID":10,"RepoID":70,"Name":"Version 1.0","Content":"","IsClosed":false,"NumIssues":2,"NumClosedIssues":0,"Completeness":0,"DeadlineUnix":1526076000,"ClosedDateUnix":0}
```

**Comment by Unknwon** [comment]
Thanks! Patch has been pushed to `master` branch, please help test.

**Comment by Isolus** [comment]
The patch works for me.

**Comment by Unknwon** [comment]
:+1: thanks for the confirmation, any other noticeable issues?
