### ISSUE TITLE
Misspelled in the v0.11.53 release notes

### ISSUE THREAD

**Issue by sheng** [gogs/gogs#5266]
> Changed import path from "gogs/gogs" to "gogs/gogs"

Should be `Changed import path from "gogits/gogs" to "gogs/gogs"`.

**Comment by Unknwon** [comment]
What are you saying...?

**Comment by sheng** [comment]
@Unknwon 

???

I don't know why you closed this issue arbitrarily without further communication.

However, **out of courtesy**, I think I should explain to you what I am saying.

<img width="890" alt="0" src="https://user-images.githubusercontent.com/5037285/40976289-3c3c8eaa-6900-11e8-8819-a15b4fe47fb9.png">

**Comment by Unknwon** [comment]
LOL. my bad, didn't read carefully enough.
