### ISSUE TITLE
gogs 负载均衡的问题

### ISSUE THREAD

**Issue by ruoxiaojie** [gogs/gogs#5268]
我想在多台部署 
但是遇到repository 存储问题
默认是存在本地的
有好的方法解决吗

谢谢

**Comment by Unknwon** [comment]
木有。。。NFS？

**Comment by fduxiao** [comment]
@ruoxiaojie 考虑架集群然后访问同一个数据库集群(postgres、mysql之类)？默认sqlite[不太能并发](https://stackoverflow.com/questions/1063438/sqlite3-and-multiple-processes)
