### ISSUE TITLE
Mirror Repo Can't New Release

### ISSUE THREAD

**Issue by 502647092** [gogs/gogs#5271]
- Gogs version (or commit ref): 0.11.53.0603
- Git version: 
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Mirror Repo Can't New Release
![image](https://user-images.githubusercontent.com/10203793/41011508-c8abe650-696f-11e8-9895-488d391f73ed.png)

**Comment by Unknwon** [comment]
Hi, that's on purpose.
