### ISSUE TITLE
[Feature Request] Kanban Project Management

### ISSUE THREAD

**Issue by jonorozcoc** [gogs/gogs#5272]
The issue tracker is a useful system to track bugs, features and incompatibilities. But it doesn't help to organize how you're gonna make or fulfill those issues. For that reason I think if Gogs could have a Kanban Board integrated with the issue tracker (like Github) could be more useful and convenient for project management.

Thanks for all your effort to make this awesome piece of software!

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogs/gogs/issues/3716.
