### ISSUE TITLE
gogs_0.11.53_darwin_amd64 start fail

### ISSUE THREAD

**Issue by leegilon** [gogs/gogs#5273]
- Gogs version (or commit ref): gogs_0.11.53_darwin_amd64
- Git version: 2.17.1
- Operating system: MacOS 10.13.4
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist (usually found in `log/gogs.log`):

2018/06/06 11:49:57 [ INFO] Cache Service Enabled
2018/06/06 11:49:57 [ INFO] Session Service Enabled
2018/06/06 11:49:57 [ INFO] Mail Service Enabled
2018/06/06 11:49:57 [ INFO] Register Mail Service Enabled
2018/06/06 11:49:57 [ INFO] Notify Mail Service Enabled
2018/06/06 11:49:57 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: Fail to connect to database: This binary version does not build support for SQLite3.

## Description
run `./gogs web` got fail 
...

**Comment by Unknwon** [comment]
Binaries updated!
