### ISSUE TITLE
Reverse proxy support

### ISSUE THREAD

**Issue by onknows** [gogs/gogs#5275]
- Gogs version (or commit ref): docker gogs/gogs with tag 0.11.43
- Git version: 2.11.3
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I noticed in this version that authentication only works when using http://localhost:10080/ When I access Gogs via reverse proxy authentication does not work. Admin account can be created but login will always fail with message that username / password is not correct.
...

**Comment by Unknwon** [comment]
That's your proxy config problem, Gogs does not care if you use proxy or not.
