### ISSUE TITLE
Gogs: Internal error on SSH git clone

### ISSUE THREAD

**Issue by aaronellington** [gogs/gogs#5278]
- Gogs version (or commit ref): 
- Git version: 2.17.1
- Operating system: Ubuntu 18.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): https://gist.github.com/aaronellington/7c398806e7d3acb331330dbe85896ec2

## Description

Fresh install, git clone via https works but not ssh. This is what happens when I try to clone the repo via ssh:
```
git clone -v git@fuzzingbits.com:aaron/secrets.git                                                                                [128]
Cloning into 'secrets'...
Gogs: Internal error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
it is a private repo but I created a private repo on try.gogs.io and added the same public key to my account and it works so I don't think it is a ssh issue on my system

Also here is my config: https://gist.github.com/aaronellington/73722ae1616f4382725a63832c648b97

**Comment by aaronellington** [comment]
I just spun up a 16.04 server with the same setup and having the same issues.

**Comment by aaronellington** [comment]
I also tried downloading a pre-built binary for my OS and having the same issues. (Originally built from source)

**Comment by Unknwon** [comment]
Please check logs in `log/hooks`.

**Comment by vamenard** [comment]
Try using the internal ssh.

`START_SSH_SERVER = false`

**Comment by aaronellington** [comment]
@vamenard That does work, but I would like to use the internal one.

**Comment by Unknwon** [comment]
Ignoring my comments doesn't help you.

**Comment by aaronellington** [comment]
@Unknwon Sorry, not ignoring. Just have not had a chance to get it. Working on it now.

**Comment by aaronellington** [comment]
So I must have done something wrong with my server setup. I just wiped the server and started over and now it works. Thanks for looking into this.

**Comment by Unknwon** [comment]
.....
