### ISSUE TITLE
Reply to issue / pull-request e-mail notification

### ISSUE THREAD

**Issue by Ambrevar** [gogs/gogs#5283]
- Gogs version (or commit ref): notabug.org

## Description

Would it be possible to answer issues and comments directly by replying to the notification e-mail? (GitHub supports that.)

If so, would it be possible to disable the "edit" feature on a per-repo basis, so that notification e-mails don't become outdated? (GitHug does not support that :p)
Indeed, editable comments force the person reading the e-mail notification to go check upstream if the content of the message hasn't changed since then.

**Comment by Unknwon** [comment]
Duplicated https://github.com/gogs/gogs/issues/1272.

>If so, would it be possible to disable the "edit" feature on a per-repo basis, so that notification e-mails don't become outdated? (GitHug does not support that :p)

You should file an issue about disable edits.

**Comment by Unknwon** [comment]
Duplicated https://github.com/gogs/gogs/issues/1272.

>If so, would it be possible to disable the "edit" feature on a per-repo basis, so that notification e-mails don't become outdated? (GitHug does not support that :p)

You should file an issue about disable edits.

**Comment by Ambrevar** [comment]
Done: #5285.
