### ISSUE TITLE
warnings or errors

### ISSUE THREAD

**Issue by deepdad** [gogs/gogs#5286]
- Gogs version (or commit ref): 1.10.3
- Git version: latest
- Operating system: ubuntu 16 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
This is during installation following an (old?) tutorial (https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04)
~/go/src/github.com/gogits/gogs$ go build
# github.com/gogits/gogs
./gogs.go:31:6: cannot use cmd.Web (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
./gogs.go:32:6: cannot use cmd.Serv (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
./gogs.go:33:6: cannot use cmd.Hook (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
./gogs.go:34:6: cannot use cmd.Cert (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
./gogs.go:35:6: cannot use cmd.Admin (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
./gogs.go:36:6: cannot use cmd.Import (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
./gogs.go:37:6: cannot use cmd.Backup (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal
./gogs.go:38:6: cannot use cmd.Restore (type "github.com/gogs/gogs/vendor/github.com/urfave/cli".Command) as type "github.com/gogits/gogs/vendor/github.com/urfave/cli".Command in array or slice literal

**Comment by Unknwon** [comment]
Hi, this repository has changed "gogits/gogs" to "gogs/gogs" recently, so you need to replace every place as that.
