### ISSUE TITLE
getaddrinfow: The specified class was not found (and workaround)

### ISSUE THREAD

**Issue by bbalet** [gogs/gogs#5290]
- Gogs version (or commit ref): 0.11.53 (precompiled binary with service support)
- Git version: 2.17.1.windows.2
- Operating system: Windows 2012 Server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):

2018/06/12 14:36:36 [ERROR] [.../runtime/asm_amd64.s:2361 goexit()] Fail to send emails [benjamin.balet@gmail.com]: UID: 4, registration notify - gomail: could not send email 1: dial tcp: lookup tcp///smtp.gmail.com: getaddrinfow: The specified class was not found.

## Description

On Windows, the following settings in app.ini doesn't work:

    HOST    = smtp.gmail.com:587

However, when I add a double quote it works fine:

    HOST    = "smtp.gmail.com:587"

What is odd is that I don't need to use a double quote for the DB host:

    [database]
    DB_TYPE  = mysql
    HOST     = 127.0.0.1:3306

By digging a bit, it looks like the delimiter is included by `ReadString`, cf. https://github.com/golang/go/issues/25553
So your underlying mail lib understands `smtp.gmail.com:587\n`

Please note that this issue is not related to #4310 as it is a configuration parsing issue.

Sorry, my Go is too rusty to submit a PR, but great project for our NGO (we are an IT school for underprivileged children in Cambodia. We have a poor Internet connection and old servers, so gogs is a perfect match).
...

**Comment by Unknwon** [comment]
Hi, Gogs uses https://github.com/go-ini/ini, it could be a bug in it, I'm looking into it.

**Comment by Unknwon** [comment]
I've checked code that INI definitely trims all white spaces (including \r\n). So this must be something else.

Since this is not a Gogs problem, I'm going to close this issue. You are welcome to report to https://github.com/go-ini/ini, or live with adding `""` around value.
