### ISSUE TITLE
bug: cannot enable email notifications

### ISSUE THREAD

**Issue by sirber** [gogs/gogs#5292]
- Gogs version (or commit ref): 0.11.43.0330
- Git version: 2.17.1
- Operating system: Ubuntu Server 18.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
if I set in app.ini:
[service]
ENABLE_NOTIFY_MAIL     = true

it is not checked in the UI after a service restart.
![screenshot from 2018-06-13 08-15-54](https://user-images.githubusercontent.com/3911428/41350726-0adc1172-6ee2-11e8-8234-ba692a3bb58f.png)

**Comment by Unknwon** [comment]
Hi, possibly you changed wrong configuration file.

**Comment by sirber** [comment]
there is only one...

`git@sirber-hosting:~/gogs$ find ./ -name app.ini
./custom/conf/app.ini
`

**Comment by Unknwon** [comment]
Or, because you can only enable this by config `[mailer]` first.

>also, thanks for closing the ticket while the issue is still going on.

No problem, don't be so welcome.

![image](https://user-images.githubusercontent.com/2946214/41354757-5bd72ca4-6f52-11e8-891b-bc2df1ee2f67.png)

**Comment by sirber** [comment]
Alright, it was [mailer] that wasn't active and configured proprely.

I thought it was a bug and not a configuration problem as [mailer] section was kinda empty. 
I found the missing property here: https://gogs.io/docs/advanced/configuration_cheat_sheet#serveur-de-messagerie-(-mailer-)

works now, thank you!

**Comment by Unknwon** [comment]
The log should have warned you that you enabled notify but mail service is not available.
