### ISSUE TITLE
Checking a renamed repo's commit history in dashboard results in 404

### ISSUE THREAD

**Issue by POTION4** [gogs/gogs#5295]
- Gogs version (or commit ref): 0.11.44.0409
- Git version: unknown
- Operating system: Ubuntu 16.04LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Here's the way to reproduce it:
1. Open a repo and do some commit 
2. Rename the repo and commit some more
3. Now go to dashboard and click on some old commits which you did before you rename the repo. 

Thanks :P

**Comment by Unknwon** [comment]
Hi, yes, currently Gogs does not handle renamed repository link, that's on purpose. It is very hard to fix based on current data store design and little gain compare to the effort to fix it.
