### ISSUE TITLE
Layout misalignment in Firefox for Linux

### ISSUE THREAD

**Issue by whry** [gogs/gogs#5299]
- Gogs version (or commit ref): 0.11.56.0613 (docker gogs/gogs)
- Git version: 2.11.3
- Operating system: Ubuntu 16.04, Ubuntu 18.04, CentOS 7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (The view repository files page.  e.g. https://try.gogs.io/tigefa/nvm)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
Not relevant

## Description
When using Firefox in Ubuntu, the `clone-panel` layout is out of alignment as shown in the image below.

![screenshot from 2018-06-19 05-10-15](https://user-images.githubusercontent.com/22613611/41588292-4f6f4ad4-73ec-11e8-9542-42396cd9ba77.png)
(from Ubuntu 16.04)

![screenshot from 2018-06-19 08-29-24](https://user-images.githubusercontent.com/22613611/41588379-88897dda-73ec-11e8-920f-a43bb87f40c7.png)
(from Ubuntu 18.04)

And, when viewed from the other Linux distributions, this layout is beyond 5px.
![screenshot from 2018-06-19 05-28-01](https://user-images.githubusercontent.com/22613611/41589359-4b49d412-73ef-11e8-97a1-5ecb19b93f56.png)
(from CentOS 7)

This is only a problem with firefox on some Linux distributions.
Firefox for Windows will display properly.

**Comment by Unknwon** [comment]
Hi, what are the screen resolutions on each screenshot?

**Comment by whry** [comment]
First image (Ubuntu 16.04)

- Screenshot: 1348 * 744
- Content area(w/o scrollbar): 1338 * 642

---

Second image (Ubuntu 18.04)

- Screenshot: 1386 * 688
- Content area(w/o scrollbar): 1374 * 584

---

Third image (CentOS 7)

- Screenshot: 1024 * 768
- Content area(w/o scrollbar): 1012 * 583

**Comment by Unknwon** [comment]
Looks like enough to hold the content...

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5317, please help test on `develop` branch or https://try.gogs.io.

**Comment by GramThanos** [comment]
I seems fixed.

Test repo on an older Gogs version (v0.11.66.0916) where the bug exists.
![image](https://user-images.githubusercontent.com/14858959/50424495-92458d80-086d-11e9-967a-4dbf83b25d63.png)

[Test repo](https://try.gogs.io/gramthanos/TestRepositoryForDebugging) on newer Gogs version (v0.11.85.1225) no bug.
![image](https://user-images.githubusercontent.com/14858959/50424531-3deedd80-086e-11e9-9ca1-da8e24a1cd15.png)

Firefox Quantum 64.0 (64-bit)
Ubuntu 18.04.1 LTS (VM on Windows 10)
