### ISSUE TITLE
connecting with GitLab runner

### ISSUE THREAD

**Issue by HalisCz** [gogs/gogs#5301]
## Type
Feature request

## Description

It would be nice to allow gitlab-runners to work with gogs server instead of gitlab server. Do you think it is even doable? I am not much of a programmer, and Go is very low-level for me to trust my estimates on this one.
...

**Comment by Unknwon** [comment]
Hi... nice idea, but since the gitlab-runners are for the very purpose of GitLab itself, they don't maintain compatible just because somehow Gogs or any other Git service connects to it. SO... better fork the project.

**Comment by farss** [comment]
gitlab ci 确实好用 在这里有什么好的替代方案吗
