### ISSUE TITLE
Allow prefilling the title and body of new issues using query parameters

### ISSUE THREAD

**Issue by Radiergummi** [gogs/gogs#5302]
- Git version: not relevant
- Operating system: Debian
- Gogs version (or commit ref): `0.11.29.0727 `
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/Radiergummi/test-directory-slashes/issues/new?title=foo&body=bar
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
not relevant 

## Description
On Github, you can set the issue title and content using query parameters, like so:

https://github.com/gogs/gogs/issues/new?title=foo&body=bar

If you open that URL, you'll land at the new issue page with the issue title set to *foo* and the body to *bar*. This is especially helpful for issue reporting links that I'd like to implement in my applications development mode (Exception messages will contain a link to the new issue page, prefilled with all relevant debugging details).  
Would it be possible to integrate this into Gogs? *Maybe* one could even go further and allow to set labels, milestones and assignments this way.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5521, please help test on `develop` branch or https://try.gogs.io.
