### ISSUE TITLE
Error 500 exit status 129

### ISSUE THREAD

**Issue by Fireant456** [gogs/gogs#5304]
- Gogs version (or commit ref): 0.11.58.0618
- Git version: 2.1.4
- Operating system: Debian Jessie
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

2018/06/21 10:53:55 [TRACE] Log Mode: File (Trace)
2018/06/21 10:53:55 [ INFO] MMichaels Private Git 0.11.58.0618
2018/06/21 10:53:55 [ INFO] Cache Service Enabled
2018/06/21 10:53:55 [ INFO] Session Service Enabled
2018/06/21 10:53:56 [ INFO] Git Version: 2.1.4
2018/06/21 10:53:56 [ INFO] Run Mode: Production
2018/06/21 10:53:56 [TRACE] Doing: CheckRepoStats
2018/06/21 10:53:56 [ INFO] First-time run install finished!
2018/06/21 10:54:29 [TRACE] Log Mode: File (Trace)
2018/06/21 10:54:29 [ INFO] MMichaels Private Git 0.11.58.0618
2018/06/21 10:54:29 [ INFO] Cache Service Enabled
2018/06/21 10:54:29 [ INFO] Session Service Enabled
2018/06/21 10:54:29 [ INFO] Git Version: 2.1.4
2018/06/21 10:54:29 [ INFO] Run Mode: Production
2018/06/21 10:54:29 [TRACE] Doing: CheckRepoStats
2018/06/21 10:54:29 [ INFO] Listen: http://0.0.0.0:2468
2018/06/21 10:54:35 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:54:35 [TRACE] CSRF Token: UvYBMgOwzaDHF3iMLn-MuO1pVX06MTUyOTU5NjQ3NTU0MTA0NzI5OA==
2018/06/21 10:54:35 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:54:35 [TRACE] CSRF Token: UvYBMgOwzaDHF3iMLn-MuO1pVX06MTUyOTU5NjQ3NTU0MTA0NzI5OA==
2018/06/21 10:54:35 [TRACE] Template: user/auth/login
2018/06/21 10:54:51 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:54:51 [TRACE] CSRF Token: UvYBMgOwzaDHF3iMLn-MuO1pVX06MTUyOTU5NjQ3NTU0MTA0NzI5OA==
2018/06/21 10:54:51 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:54:51 [TRACE] CSRF Token: SE1pgKrgmrJvRMiNW-MJSzyuA3s6MTUyOTU5NjQ5MTQxMTE4MjIwNg==
2018/06/21 10:54:51 [TRACE] Template: user/dashboard/dashboard
2018/06/21 10:54:54 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:54:54 [TRACE] CSRF Token: SE1pgKrgmrJvRMiNW-MJSzyuA3s6MTUyOTU5NjQ5MTQxMTE4MjIwNg==
2018/06/21 10:54:54 [TRACE] Template: repo/create
2018/06/21 10:54:59 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:54:59 [TRACE] CSRF Token: SE1pgKrgmrJvRMiNW-MJSzyuA3s6MTUyOTU5NjQ5MTQxMTE4MjIwNg==
2018/06/21 10:54:59 [ERROR] [.../routes/repo/repo.go:103 handleCreateError()] CreatePost: initRepository: initRepository: path already exists: /home/ftc/gogs-repositories/max32268/test.git
2018/06/21 10:54:59 [TRACE] Template: status/500
2018/06/21 10:55:05 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:55:05 [TRACE] CSRF Token: SE1pgKrgmrJvRMiNW-MJSzyuA3s6MTUyOTU5NjQ5MTQxMTE4MjIwNg==
2018/06/21 10:55:05 [TRACE] Template: user/dashboard/dashboard
2018/06/21 10:55:42 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:55:42 [TRACE] CSRF Token: SE1pgKrgmrJvRMiNW-MJSzyuA3s6MTUyOTU5NjQ5MTQxMTE4MjIwNg==
2018/06/21 10:55:42 [TRACE] Template: repo/create
2018/06/21 10:55:45 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:55:45 [TRACE] CSRF Token: SE1pgKrgmrJvRMiNW-MJSzyuA3s6MTUyOTU5NjQ5MTQxMTE4MjIwNg==
2018/06/21 10:55:45 [TRACE] Repository created [2]: max32268/test
2018/06/21 10:55:45 [TRACE] Session ID: 695b0dcef4580d77
2018/06/21 10:55:45 [TRACE] CSRF Token: SE1pgKrgmrJvRMiNW-MJSzyuA3s6MTUyOTU5NjQ5MTQxMTE4MjIwNg==
2018/06/21 10:55:45 [ERROR] [...g/context/context.go:175 ServerError()] GetTags '/home/ftc/gogs-repositories/max32268/test.git': exit status 129 - error: unsupported sort specification 'taggerdate'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [--contains <commit>] [--points-at <object>] 
		[<pattern>...]
   or: git tag -v <tagname>...

    -l, --list            list tag names
    -n[<n>]               print <n> lines of each tag message
    -d, --delete          delete tags
    -v, --verify          verify tags

Tag creation options
    -a, --annotate        annotated tag, needs a message
    -m, --message <message>
                          tag message
    -F, --file <file>     read message from file
    -s, --sign            annotated and GPG-signed tag
    --cleanup <mode>      how to strip spaces and #comments from message
    -u, --local-user <key-id>
                          use another key to sign the tag
    -f, --force           replace the tag if exists
    --column[=<style>]    show tag list in columns
    --sort <type>         sort tags

Tag listing options
    --contains <commit>   print only tags that contain the commit
    --points-at <object>  print only tags of the object

2018/06/21 10:55:45 [TRACE] Template: status/500

## Description
After installation I receive this error on any type of new repository (new blank or mirror).
...

**Comment by Isolus** [comment]
The issue was introduced here: gogs/git-module#36
`cmd.AddArguments("--sort=-v:refname")` was guarded by a version check against git version 2.0.0. But it seems the new `taggerdate` was introduced later. (After git 2.1.4)
Reverting this change fixes the problem.

**Comment by Fireant456** [comment]
So any advice to fix the issue for my install?

**Comment by Isolus** [comment]
At he moment you can upgrade your git binary to a current version, compile gogs on your own (reverting the commit) or use an older version of gogs (the issue was introduced 16 days ago).

**Comment by Unknwon** [comment]
Hi, according to https://git-scm.com/docs/git-for-each-ref/2.1.4, looks like 2.4.9 has support of `taggerdate` as sort type, but it might be some earlier version and I haven't figured out how to view way older documentation on git-scm.com yet.

**Comment by Unknwon** [comment]
Anyway, I'll change version check to 2.4.9 just to be safe.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `master` branch.

**Comment by Isolus** [comment]
The patch works for me.
