### ISSUE TITLE
Error entering repository management

### ISSUE THREAD

**Issue by zyh001** [gogs/gogs#5308]
- Gogs version (or commit ref): 0.11.53.0603
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When I enter Repositories in the Admin Panel. I get this error :

> template: admin/repo/list:34:44: executing "admin/repo/list" at <.Owner.Name>: can't evaluate field Name in type *models.User

**Comment by Unknwon** [comment]
Hi, can you provide robust reproduce steps, I'm not able to reproduce.

**Comment by zyh001** [comment]
@Unknwon I don't know how to reproduce this problem. I am not sure if this is related to my configuration of load balancing. Because this is normal in previous releases. But when I updated to the latest version, I got this error.

**Comment by Unknwon** [comment]
Have you ever edited database manually? Feels like one owner of a repository is no longer exists, check `log/gogs.log` right before the template error.

**Comment by zyh001** [comment]
@Unknwon I can't find any exceptions in the log. I also think it might have something to do with the database. There was a loss of the database last week, but fortunately I recovered the backup in time. I think there are still some problems in the accident. But I can't think of a better solution. I'm not sure if the gogs database was damaged in the accident.

**Comment by Unknwon** [comment]
I think... must be it.

Unfortunately there is no automatic solution right now, but what you can do:

Loop over `repository` table and check if `owner_id`(equivalent to `user.id`) exists in `user` table. If not, create a user with that `id`.

**Comment by zyh001** [comment]
@Unknwon I have checked the database but have not found the problem you described.

**Comment by zyh001** [comment]
@Unknwon Because there are fewer users and repositories, I simply list the `user` and `repository` tables for comparison

**Comment by Unknwon** [comment]
Can you post results from following two SQLs?

1. `SELECT id, owner_id FROM repository`
2. `SELECT id FROM user`

**Comment by zyh001** [comment]
@Unknwon Thank you very much for your help. The problem has been solved. I found an empty `owner.id` item in the `repository` table. The error disappeared when I deleted the item.
