### ISSUE TITLE
Gogs is very slow

### ISSUE THREAD

**Issue by aimuz** [gogs/gogs#5312]
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

```
2018/06/25 16:45:03 [ WARN] AvatarLink.LibravatarService.FromEmail [sunqi@xxx.com]: lookup _avatars-sec._tcp.xxx.com on 114.114.114.114:53: read udp 192.168.0.188:42163->114.114.114.114:53: i/o timeout
2018/06/25 16:45:04 [ WARN] AvatarLink.LibravatarService.FromEmail [ekko@xxx.com]: lookup _avatars-sec._tcp.xxx.com on 114.114.114.114:53: read udp 192.168.0.188:56169->114.114.114.114:53: i/o timeout

```

My initial suspicion is that this DNS operation resulted in the death of gogs. When I started the intranet mode, the speed quickly improved.

**Comment by aimuz** [comment]
<img width="628" alt="qq20180625-0" src="https://user-images.githubusercontent.com/17666471/41841164-298a5b4e-789a-11e8-9128-9e8a6250bdcb.png">

**Comment by Unknwon** [comment]
Disable gravatar.
