### ISSUE TITLE
After failing to delete repo, can't delete without clicking to another page

### ISSUE THREAD

**Issue by s12chung** [gogs/gogs#5314]
- Gogs version (or commit ref): 029b33c6508b9f320300e68e38184b2eb17ee1d5 (master, right now)
- Git version: git version 2.15.2 (Apple Git-101.1)
- Operating system: macOS 10.13.5
- Database (use `[x]`):
  - [ x] PostgreSQL 9.5.2
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ x] Yes (provide example URL) https://try.gogs.io/s12chung/test-delete (you need to delete your own repo)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

After failing to delete repo, can't delete without clicking to another page--clicking again and refresh failed---because the delete repo button is disabled (probably due to validation error).

![delete-repo](https://user-images.githubusercontent.com/263394/41879314-184c0398-78a7-11e8-8f9a-20ce69057b78.gif)

I can try to fix.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5315, please help test on `develop` branch.

**Comment by s12chung** [comment]
tested on `develop` locally, looks fixed.
