### ISSUE TITLE
Very slow container startup using Gogs’ Docker image on chown command

### ISSUE THREAD

**Issue by guilhox** [gogs/gogs#5316]
- Gogs version (or commit ref): 0.11.53.0603 (and earlier)
- Git version: Any
- Operating system: Docker version 17.03.1-ce on Ubuntu 16.04.2
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

As discussed [here](https://discuss.gogs.io/t/very-slow-start-using-gogs-docker-image/2007), when using Gogs with Docker (current image: gogs/gogs:0.11.53), whenever the container is restarted or upgraded, it takes a huge amount of time to finish the starting process. The bigger the repository, the longer it takes.
I believe that it happens because of a [chown process](https://github.com/gogs/gogs/blob/master/docker/s6/gogs/setup#L22) that takes place when the container is starting:

`chown -R git:git /data /app/gogs ~git/`

I’m assuming that Gogs already creates files and directories with the correct permissions without depending on that command, but not sure. It might be good to run that line on the container’s first run, if necessary or if the correct owner/group is not already set on specific files, but not on every restart.

Some additional information, for reference: our environment sets the `/data` directory as a volume on the Docker machine, and it's some hundreds of gigabytes large, as of today.

**Comment by kreischweide** [comment]
Recursive chown can cause a very heavy load on certain filesystems. Maybe just do a preliminary check on any files in the directory if anything exists that does not belong to the git user. Maybe do a `find /data /app/gogs ~git/ \! -user git | wc -l` and check if its > 0 do the chown as a repair measure?

**Comment by guilhox** [comment]
We tested stopping the `chown` process in our container after an upgrade, and executing that `find` command. The `find` itself still took a while (less that `chown`, at least), and returned a very big number. Afterwards, we executed the `chown` manually, and after that, the same `find` returned 0. So apparently, the container's startup really generates files that are not owned by the `git` user.
Apparently, though, after we stopped the chown, gogs was running with no problems. Although we didn't make any long-term tests to be sure if it would remain like that.

**Comment by cesargomezvela** [comment]
#4271

**Comment by Unknwon** [comment]
I think this problem has been fixed by just chwon on the first time start of the container.

**Comment by D-T-Y** [comment]
这个解决了吗？我发现依然存在这个问题呢
