### ISSUE TITLE
Upgrade jQuery to 3.x

### ISSUE THREAD

**Issue by Vladet0** [gogs/gogs#5318]
- Gogs version (or commit ref): 0.11.53.0603 and earlier
- Git version: Any
- Operating system: Any Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
The jQuery version used in the latest and the earlier releases of GOGS is 1.11.3
Do you have any plans of updating it in future releases as this specific version is considered to be vulnerable? More information can be found here: https://www.cvedetails.com/vulnerability-list/vendor_id-6538/Jquery.html

**Comment by Unknwon** [comment]
Yes, sure, PR is welcome.

**Comment by cezar97** [comment]
Just for the record, searching for `closeText` on Gogs repository doesn't return any results and regarding cross domain Ajax request it doesn't use any either. Ajax is only used internally.
So not really that vulnerable in our case :-).

**Comment by unknwon** [comment]
Thanks again for your feedback! It has been upgraded to the latest 3.4.1 in https://github.com/gogs/gogs/commit/e99f43f59cb25582c85e748d42c1367113d66c31.
