### ISSUE TITLE
Installing from Source in MacOS or Ubuntu doesn't show SQLite option in Database Options

### ISSUE THREAD

**Issue by PhaneendraGoutham** [gogs/gogs#5320]
Installing from source in MacOS or Ubuntu, followed the below link

https://gogs.io/docs/installation/install_from_source

Checked out Tags v0.11.53.

- Gogs version (or commit ref): 0.11.53
- Git version: 
- Operating system: MacOS and Ubuntu Tried on Both
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite(Missing)
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When Installing from source SQLite option is missing. But when downloaded from https://dl.gogs.io/0.11.53/ i can see SQLite option 

go env 
--------
GOARCH="amd64"
GOBIN=""
GOCACHE="/var/root/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/var/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build255775046=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by Unknwon** [comment]
Hi, https://gogs.io/docs/installation/install_from_source#build-with-tags
