### ISSUE TITLE
Gogs 0.11.53 with MySQL 8.0.11  have problem

### ISSUE THREAD

**Issue by vic-feng** [gogs/gogs#5323]
- Gogs version (or commit ref): 
- Git version: 0.11.53
- Operating system: Ubuntu 18.04 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I can't use Gogs 0.11.53 with MySQL 8.0.11 when I open the http://0.0.0.0:3000/install
mysql> select host,user,plugin from mysql.user;
+-----------+------------------+-----------------------+
| host      | user             | plugin                |
+-----------+------------------+-----------------------+
| localhost | gogs             | mysql_native_password |

![2018-07-02t08-17-08 716z](https://user-images.githubusercontent.com/34942652/42152828-eadccc54-7e13-11e8-9fc5-99d40b135e3e.png)

...

**Comment by Unknwon** [comment]
Hi, this is a fixed issue after 0.11.53 but in master branch according to https://github.com/gogs/gogs/issues/5187.

**Comment by qwertyhup** [comment]
Hi,
It doesn't appear to be fixed. I am still getting the same error.
