### ISSUE TITLE
i can't start gogs...

### ISSUE THREAD

**Issue by MainGuo** [gogs/gogs#5326]
2018/07/03 12:57:16 [TRACE] Log Mode: File (Trace)
2018/07/03 12:57:16 [ INFO] Gogs 0.11.53.0603
2018/07/03 12:57:16 [ INFO] Cache Service Enabled
2018/07/03 12:57:16 [ INFO] Session Service Enabled
2018/07/03 12:57:16 [ INFO] Git Version: 1.8.3.1
2018/07/03 12:57:16 [ INFO] SQLite3 Supported
2018/07/03 12:57:16 [ INFO] Run Mode: Production
2018/07/03 12:57:16 [TRACE] Doing: CheckRepoStats
2018/07/03 12:57:16 [ INFO] Listen: http://0.0.0.0:3000
2018/07/03 12:57:16 [FATAL] [...rfave/cli/command.go:193 Run()] Failed to start server: listen tcp 0.0.0.0:3000: bind: address already in use

i can't start gogs...   I don't know why cause this...

**Comment by PhaneendraGoutham** [comment]
Hi Your logs shows what is the issue. port 3000 is already in use. Based on your OS try to kill port 3000 and start gogs server. Hope this resolves

**Comment by MainGuo** [comment]
thanks for your help
