### ISSUE TITLE
help...When I was installing gogs, gogs prompted a database setup error.

### ISSUE THREAD

**Issue by MainGuo** [gogs/gogs#5328]
数据库设置不正确：Error 1071: Specified key was too long; max key length is 767 bytes

**Comment by thombou** [comment]
See #5327 
I had exactly the same problem

**Comment by duanebc** [comment]
https://stackoverflow.com/a/43403017

Solved for me.  Further

https://github.com/frappe/bench/issues/681#issuecomment-398984706

Seems these are deprecated values, so maybe only needed for install?
