### ISSUE TITLE
Fail to add a Team-Repo

### ISSUE THREAD

**Issue by KEANO89** [gogs/gogs#533]
While trying to assign a repository to a team I got the following error:
{"err":"Team does not exist","ok":false}

Enviroment:
Ubuntu 14.04 
Gogs installed from binary Version: 0.5.2.0917 Beta 

Log: 
2014/10/06 19:44:32 [T] Organization created: blub
2014/10/06 19:44:53 [T] Team created: blub/bla
2014/10/06 19:45:14 [T] action.NewRepoAction: blub/blahaaaa
2014/10/06 19:45:14 [T] Repository created: blub/blahaaaa
2014/10/06 19:45:27 [teams.go:136 TeamsRepoAction()] [E] Action(add): Team does not exist

**Comment by dromer** [comment]
I run in to this trying to add an existing repository.
Using: gogs_v0.5.9_linux_amd64.zip

**Comment by Unknwon** [comment]
@dromer what if you create a new organization?

**Comment by dromer** [comment]
Hah. Indeed now it does. That's odd.

To recap:
So I created a new orga. Made a repo for this orga. Then created the team, and added the existing repo to the team.

**Comment by dromer** [comment]
Ok, I found out how to do it: it's (currently) only possibly to add repos to _empty_ teams.
So, removing all users from a team, then adding an existing repo, then adding members. Works.

**Comment by Unknwon** [comment]
@dromer great! Glad to hear it!

**Comment by dromer** [comment]
Well, it still is a bug.

Hope to see it resolved in 0.6.0 ;)

**Comment by Unknwon** [comment]
I see what you mean now... So if you try to add repository to non-empty teams, this bug will be reproduced?

**Comment by dromer** [comment]
Yup, that seems to be the current behaviour in 0.5.9

**Comment by Unknwon** [comment]
https://github.com/gogits/gogs/issues/831 I created a new issue here to keep a record. @dromer
