### ISSUE TITLE
Deleting a branch after merging a PR does not trigger webhook

### ISSUE THREAD

**Issue by LBlaboon** [gogs/gogs#5331]
- Gogs version (or commit ref): 0.11.53.0603
- Git version: 2.18.0
- Operating system: Arch Linux
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (https://try.gogs.io/lb.laboon/webhook-delete-test)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

After merging a branch from a PR, if you delete the branch from the web interface then any webhooks configured to trigger on the "Delete" event will not be triggered. The webhook is only triggered when deleting a branch remotely (via `git push origin :branch`).

In the example repo from the URL above, there is one webhook configured to trigger on the "Delete" event. One PR has been created and merged, and the original branch was deleted via the web interface. In the screenshot below, you can see that the webhook was not triggered.

![webhook-delete-test](https://user-images.githubusercontent.com/8608488/42383085-3ae9bdfe-8104-11e8-8cbc-eb2239e0135f.png)

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by LBlaboon** [comment]
Great! The issue appears to be fixed on https://try.gogs.io
Thanks for the patch.
