### ISSUE TITLE
Gogs won't start anymore

### ISSUE THREAD

**Issue by leonhelmle** [gogs/gogs#5335]
At some time my Gogs stopped working and gave out an error 500.
So I stopped Gogs (Strg+C) and now it won't start anymore. The console only puts out: 

`git@git:~/gogs$` ./gogs web
2018/07/10 10:04:24 [TRACE] Custom path: /home/git/gogs/custom
2018/07/10 10:04:24 [TRACE] Log path: /home/git/gogs/log
2018/07/10 10:04:24 [TRACE] Build Time: 2018-06-05 12:58:53 UTC
2018/07/10 10:04:24 [TRACE] Build Git Hash: 91441c3fb29d8ead645d8fffa4658d749d5b3fc3

``
But it isn't startet after that. It goes back to git@git:~/gogs$ and the website isn't reachable.

- Gogs version (or commit ref): Gogs version 0.11.53.0603
- Operating system: Debian Stretch 64 Bit
- Git version: git version 2.11.0
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
2018/07/10 10:11:25 [TRACE] Log Mode: File (Trace)
2018/07/10 10:11:25 [ INFO] Leon's GIT 0.11.53.0603
2018/07/10 10:11:25 [ INFO] Cache Service Enabled
2018/07/10 10:11:25 [ INFO] Session Service Enabled
2018/07/10 10:11:25 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: sync: Error 1045: Access denied for user 'git'@'2001:41d0:700:254::2' (using password: YES)

## Description

...

**Comment by StevenPolley** [comment]
Perhaps just backup your custom folder, reinstall it, then drop your custom folder back in.  

I've just tested the current commit (which has been out for 13 days) and it is working fine.

**Comment by Unknwon** [comment]
From the log, I see the MySQL thinks you're using the wrong password. Make sure the remote DB you're connecting didn't change the password for user "git".
