### ISSUE TITLE
fork repository not check of the limit of users

### ISSUE THREAD

**Issue by geekcomb** [gogs/gogs#5345]
- Gogs version (or commit ref): 0.11.53.0603
- Git version: 1.7.1
- Operating system: centos 6.7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No try.gogs.io site Can't visit
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
When a user fork a repository, it does not carry out the check of the limit of users in the save operation. The result is beyond the limit and can also be save successfully.
...

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5346, please help test on `develop` branch.
