### ISSUE TITLE
Web editor bypasses protected branch whitelist

### ISSUE THREAD

**Issue by al2k4** [gogs/gogs#5347]
- Gogs version (or commit ref): 0.11.53.0603
- Git version: 2.14.1
- Operating system: Windows Server 2008 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description

A user with write access to a repo but not on the whitelist for a protected branch can still make commits to a protected branch via the Gogs web editor.

### Expected Result

Commit failure - as the user is not on the protected branch's whitelist.

### Actual Result

Commit success - the branch is written to even though the user is not on the protected branch's whitelist.

**Comment by unknwon** [comment]
After auditing and testing locally, I think users are not able to use web editor to edit files on protected branch at all (at least on `0.12.0+dev`).
