### ISSUE TITLE
Deleted Repository still appear in the Dashboard

### ISSUE THREAD

**Issue by ahmadpi** [gogs/gogs#535]
I just deleted a repository but it is still appear in the dashboard. If I click on that repository, error 505 come out.

Gogs Version: v0.5.4.1004
System Type: Windows 7 32-bit

**Comment by slothbag** [comment]
I deleted the git repo manually via the file system.. now there is no way in Gogs to forcefully remove the repo from the Gui.  Maybe another job in the dashboard for cleaning up missing repos?

**Comment by lokeshrathore** [comment]
I have also deleted directory,but still show account

**Comment by joaofl** [comment]
Same here!
I deleted a repo from the admin dashboard, but the repo is still listed for the users, and once they click it, they get the error 500.
