### ISSUE TITLE
How can I change the images in issues

### ISSUE THREAD

**Issue by cjk87927** [gogs/gogs#5353]
- Gogs version (or commit ref): 0.11.53.0603
- Operating system: Centos 7.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
I can't find any button to operater it

![image](https://user-images.githubusercontent.com/6744728/43178421-02fbca80-9000-11e8-974c-03cf47b4fe90.png)

**Comment by Unknwon** [comment]
Hi, currently it is not possible. You can turn this into a feature request if you wish.
