### ISSUE TITLE
Pull request permission prompt misleading

### ISSUE THREAD

**Issue by iSamMahoozi** [gogs/gogs#5359]
- Gogs version: 0.11.53.0603
- Git version: Not relevant
- Operating system: Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [] MySQL
  - [x] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): Not relevant

## Description
In repository settings > Advanced Settings
The option to enable pull requests is: "Enable pull requests to accept *public* contributions.
This is either a misleading prompt, or a missing functionality; I have a *private* repository with a protected master branch, there are no *public* contributions, and I do not want to enable pull requests publicly, but only for contributors who already have access to the repository (on other branches than master). Without enabling this option there is no way to merge into the protected branch.

I think at the very least the wording should be modified, but also if the users adds a protected branch an alert should notify that this permission is needed to create the pull requests. I spent quite a lot of time searching for "How to create a pull request on Gogs" because of this, only finding references to the green button (which I couldn't see since the permission was not enabled).

**Comment by Unknwon** [comment]
You're right, the prompt should be adjusted.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
