### ISSUE TITLE
built docker images fails

### ISSUE THREAD

**Issue by daozhu** [gogs/gogs#5360]
- Gogs version (or commit ref):  97fb9d283f45f8ff68b6f56d397fc2cb8af1fbf0
               the latest source ( i built docker images by dockerfile.aarch64 file )
- Git version: 2.11.0
- Operating system: Linux rancher 4.9.80-hypriotos-v8 #1 SMP PREEMPT Thu Apr 26 17:51:07 UTC 2018 aarch64 GNU/Linux

- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

when i run the cmd:  
```
docker build -f Dockerfile.aarch64 -t daozhu/aarch64-gogs .
```
and fails with an error in the end :
```
+ apk add --no-cache --no-progress --virtual build-deps-go gcc musl-dev openssl go
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/aarch64/APKINDEX.tar.gz
fetch http://dl-2.alpinelinux.org/alpine/edge/community/aarch64/APKINDEX.tar.gz
WARNING: This apk-tools is OLD! Some packages might not function properly.
(1/20) Upgrading musl (1.1.15-r6 -> 1.1.15-r8)
(2/20) Installing binutils-libs (2.27-r1)
(3/20) Installing binutils (2.27-r1)
(4/20) Installing gmp (6.1.1-r0)
(5/20) Installing isl (0.17.1-r0)
(6/20) Installing libgomp (6.2.1-r1)
(7/20) Installing libatomic (6.2.1-r1)
(8/20) Installing libgcc (6.2.1-r1)
(9/20) Installing pkgconf (1.0.2-r0)
(10/20) Installing mpfr3 (3.1.5-r0)
(11/20) Installing mpc1 (1.0.3-r0)
(12/20) Installing libstdc++ (6.2.1-r1)
(13/20) Installing gcc (6.2.1-r1)
(14/20) Installing musl-dev (1.1.15-r8)
(15/20) Installing libcrypto1.0 (1.0.2o-r1)
(16/20) Installing libssl1.0 (1.0.2o-r1)
(17/20) Installing openssl (1.0.2o-r1)
(18/20) Installing go (1.10.3-r0)
ERROR: Failed to create usr/lib/go/bin/go: No space left on device
ERROR: go-1.10.3-r0: No space left on device
(19/20) Installing build-deps-go (0)
(20/20) Upgrading musl-utils (1.1.15-r6 -> 1.1.15-r8)
Executing busybox-1.25.1-r0.trigger
Executing ca-certificates-20161130-r1.trigger
1 errors; 132 MiB in 50 packages
The command '/bin/sh -c ./docker/build-go.sh     && ./docker/build.sh     && ./docker/finalize.sh' returned a non-zero code: 1
```
...

**Comment by ronnicek** [comment]
I think you dont have enough space in /var/lib/docker folder.

**Comment by Unknwon** [comment]
I think @ronnicek has pointed out the root cause According to:

>ERROR: Failed to create usr/lib/go/bin/go: No space left on device
ERROR: go-1.10.3-r0: No space left on device

**Comment by daozhu** [comment]
but i check the space of SD card like this 

```
docker info 
```
and it shows that:  **/mnt/docker**
```
- Docker Root Dir: /mnt/docker
```
then i run the **df -ah** cmd:
```
df -ah 
```
it shows that:

| Filesystem  |  Size | Used |  Avail | Use%  | Mounted on |
| ------ | ------ |  ------ | ------ | ------ | ------ |
| /dev/mmcblk0p3 | 27G | 2.0G  | 23G  | 8%  |  /mnt/docker |

and 

| Filesystem |  Size | Used  |   Avail | Use%  | Mounted on
| ------ | ------ |  ------ | ------ | ------ | ------ |
| /dev/root |  2.0G | 1009M | 865M | 54% | /var/lib/docker

and the **df -ih** are that:
```
Filesystem                       Inodes IUsed IFree IUse% Mounted on
overlay                            127K   29K   98K   23% /
devtmpfs                           114K   314  114K    1% /dev
tmpfs                              115K    15  115K    1% /sys/fs/cgroup
/dev/root                          127K   29K   98K   23% /mnt
none                               115K   402  115K    1% /run
shm                                115K     1  115K    1% /dev/shm
/dev/mmcblk0p3                     1.7M   78K  1.7M    5% /mnt/docker
```

is that ??

and can you show me what i should to do next ?

**Comment by daozhu** [comment]
wow, i tried two times.  one failure, one success . but i didn't do anything. 

like you said: i  opened two windows to run the shell cmd, but there were no changes during the built , except the **/mnt/docker** bigger 0.3G than before , and built it success one time. 

maybe the network is slow ? timeout ?  

It took a long time when run into the step **(18/20)** :
```
(18/20) Installing go (1.7.3-r0)   -- this time , built success, the go version is 1.7.3-r0
```
but , the failure time was that : 
```
(18/20) Installing go (1.10.3-r0)   -- this time , built failure, the go version is 1.10.3-r0
ERROR: Failed to create usr/lib/go/bin/go: No space left on device
ERROR: go-1.10.3-r0: No space left on device
```
and the 1.10.3-r0 version  took a much longger time  than the 1.7.3-r0 version.

why the Installing go version is difference ? 

what is the go version base on ?

---
and that when the install version was 1.7.3-r0 , there were two warinings left
```
WARNING: Ignoring http://dl-2.alpinelinux.org/alpine/edge/community/aarch64/APKINDEX.tar.gz: BAD signature
WARNING: This apk-tools is OLD! Some packages might not function properly.
```
but when the intall version was 1.10.3-r0 , there was only one warning and failure in the end:
```
WARNING: This apk-tools is OLD! Some packages might not function properly.
```

**Comment by daozhu** [comment]
i change the command in **docker/built-go.sh** like this 
```
apk add --no-cache --no-progress --virtual build-deps-go gcc musl-dev openssl go=1.7.3-r0
```

i point the go version is 1.7.3-r0 :  **go=1.7.3-r0**

and it works well
