### ISSUE TITLE
Error 400 on opening readme.md files

### ISSUE THREAD

**Issue by ozzi-** [gogs/gogs#5361]
- Gogs version (or commit ref):  0.11.53.0603
- Git version: Integrated with Gogs
- Operating system: Ubuntu Server 16.04 LTS
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No (it seems to work with  0.11.58.0617 which try.gogs.io is using)
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
2018/08/03 14:37:44 [TRACE] Session ID: 2edfe3e279cfcbdf
2018/08/03 14:37:44 [TRACE] CSRF Token: Wyug3QniOQuTTefZUbQC925CedM6MTUzMzI5OTcwODUyMjM2Njg4NQ==

## Description
Since Updating to 0.11.53.0603 I get an error 400 "bad request" when clicking on a readme.md file.
However it renders fine on the repository page itself.

**Comment by Unknwon** [comment]
Hi, if you can't reproduce on demo site, usually means you have custom settings (mostly related to your proxy software, e.g. NGINX, Apache). In other words, I can't take this as a valid bug report.

**Comment by ozzi-** [comment]
I only get 400 when file ending is .md, .markdown works. So yes its not Gogs but my setup. Thanks

**Comment by Unknwon** [comment]
@ozzi- it is possible that any URL ending with `.md` could somehow matched one of your other sites.

**Comment by ozzi-** [comment]
lighthttpd has a default url.access-deny including "md" 😆

**Comment by Unknwon** [comment]
:joy: First thing I learned today
