### ISSUE TITLE
custom app.ini should be placed outside the '/data' directory

### ISSUE THREAD

**Issue by xgz123** [gogs/gogs#5362]
自定义的`app.ini`如果和数据放在一起，用docker的时候很不方便，不能预先打包进去（配置文件必须放在可能由程序创建的子目录中）。希望能分开防止，另外文档中对于custom文件夹的定义也模糊不清。

> 任何修改都是发生在 custom/conf/app.ini 自定义配置文件中，该文件的具体位置与您的设置有关

到底custom怎么设置，是相对于根目录，还是任何一个子目录都可以。。。一头雾水

看官方的docker制作流程，放app.ini也是挺费劲的。

**Comment by xgz123** [comment]
能否稍作解答？

**Comment by Unknwon** [comment]
Custom "app.ini" can be put anywhere you wish.
