### ISSUE TITLE
Slow repo page rendering; Cache in context.go unused?

### ISSUE THREAD

**Issue by Siesh1oo** [gogs/gogs#5363]
## Description

Rendering the repository page for large repos takes a long time (8-10seconds typical, on slow disks even more), and every new HTTP request or page reload seems to re-spawn many new git commands.

Is there a technical reason why the go-macaron cache in context.go is not used to cache the rendered page until the repo is updated?

**Comment by Unknwon** [comment]
Hi, Gogs currently does not use any cache in terms of repository data, and calculates everything on the fly. That's why for large repos the page load is not very ideal.

**Comment by Siesh1oo** [comment]
@unknwon : What is the approach you would prefer to see in a patch or PR? Those come to mind, others are surely possible:

1. modify the macaron HTML method in the template renderer to optionally cache the rendered content into a file in the public/ folder with the same name, so that his file will then get picked up for the next load. Cache purging can happen using outside tools, like `find -delete`
2. Like (1.), but do store the rendered HTML in the macaron cache using the URL as key, (requires additional logic in the router). Cache purging not really needed here, since LRU replacement will keep cache size bounded.
3. Do not cache the rendered HTML, but the template dictionary with the output of the (slow) git commands and re-render for each request.

What do you think?

**Comment by Unknwon** [comment]
@Siesh1oo thanks for the good writing! In my opinion, cache layer is a big thing and not for a specific feature in Gogs, but yes, caching results of a Git command is definitely a must have.
