### ISSUE TITLE
Webhook commit limit?

### ISSUE THREAD

**Issue by furai** [gogs/gogs#5368]
- Gogs version (or commit ref): 0.11.53
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Hello,

there's something I can't figure out about webhooks. It seems that webhook push event list only 5 latest commits in a push and says there were 5. But there were way more in a push. I can't find anywhere any limit that would affect that.

What's funy also is if you click that link with 5 commits then it shows you git compare page with actual number of commits.

Is there a way to up that limit? Is that a bug? 

Cheers,
Furai

**Comment by Unknwon** [comment]
Hi, how did you trigger the webhook and where does webhook sent to?

**Comment by furai** [comment]
It was triggered on push event to the repo, it was sending the message to the discord server.

**Comment by Unknwon** [comment]
>It seems that webhook push event list only 5 latest commits in a push and says there were 5.

Do you have screenshot?

**Comment by furai** [comment]
https://file.furai.pl/2018-08-18-10-49-05.png << discord message
https://file.furai.pl/2018-08-18-10-49-19.png << after clicking the link to these 5 commits

**Comment by Unknwon** [comment]
It is possible that discord allows at most 5 lines, can you check webhook delivery history?

**Comment by furai** [comment]
Did some rudimentary tests on discord - only limit I hit was character limit (2000). There was no limit for multiline messages.

Request headers:
```
Request URL: https://discordapp.com/api/webhooks/453979364795875339/Qm9gCCcYEFo1tUdE5yyYHc6q20lO0rGHfdBYEEk_SGIkz5aKxz4jUfvjhSw6E9MG2raI
Request method: POST
Content-Type: application/json
X-Gogs-Delivery: 428d7c8a-59ba-481e-9d82-29a8f54a8805
X-Gogs-Event: push
X-Gogs-Signature: 
```
Redacted payload:
```
{
  "content": "",
  "username": "CommitBot",
  "avatar_url": "https://i.imgur.com/HrYPYjh.png",
  "embeds": [
    {
      "title": "",
      "description": "Pushed [5 new commits](https://<snip>/compare/a20e3a03554444e1a77f54ca6c6a2e5445fc738e...75a8c4e8b3c67e532335a2fc4cbdb4061c46a134) to [soldat](https://<snip>)/[develop](https://<snip>/src/develop)\n[`75a8c4e`](https://<snip>/commit/75a8c4e8b3c67e532335a2fc4cbdb4061c46a134) Added AutoUpdater unit - helloer\n[`32855f5`](https://<snip>/commit/32855f501c2b922b59311915f4b3aadbef5fa7b1) Extract game configs from the game archive on first run - helloer\n[`94e7c08`](https://<snip>/commit/94e7c080515d0662235fc22a005bb03527e89602) Fixed radio messages - helloer\n[`11020cc`](https://<snip>/commit/11020cc80eb9a6385ef4b0b506721d7b48bdf09f) Renamed Player.Color1,Color2 to ShirtColor,PantsColor - helloer\n[`ce360cc`](https:/<snip>/ce360cc07b780f33cdb15cadcfdcb323ece9a268) Fixed wrong netchannel for ServerSendVoteOn/Off - helloer",
      "url": "https://<snip>/helloer",
      "color": 6750003,
      "footer": null,
      "author": {
        "name": "helloer",
        "url": "",
        "icon_url": "https://<snip>/avatars/47"
      },
      "fields": null
    }
  ]
}
```
Response headers:
```
Alt-Svc: clear
Cf-Ray: 44639896797e6463-FRA
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Mon, 06 Aug 2018 18:34:10 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d4cbc5baff33e1d13e744e2ab7fc8187d1533580450; expires=Tue, 06-Aug-19 18:34:10 GMT; path=/; domain=.discordapp.com; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
Via: 1.1 google
X-Ratelimit-Limit: 5
X-Ratelimit-Remaining: 4
X-Ratelimit-Reset: 1533580453
```

**Comment by Unknwon** [comment]
Thanks for the valuable info!

>can you check webhook delivery history?

But to make sure Gogs only fires 5 commits (at most), the webhook delivery history is the key to find out.

**Comment by furai** [comment]
I'm not sure what you meant with the last message.

https://file.furai.pl/2018-08-18-11-30-29.png << this is the recent delivered webhooks. The one on top is the one in question - 7 commits total, only 5 were sent/shown. Response was 204.

**Comment by Unknwon** [comment]
Yes that's the right one. Thanks, I'll look into it.

**Comment by furai** [comment]
I've just tried recreating the issue on try.gogs.io, got this error on push:

```
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
remote: Gogs: Internal error
To try.gogs.io:Furai/Delphi-tests.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@try.gogs.io:Furai/Delphi-tests.git'
```

**Comment by Unknwon** [comment]
I found the limit, it was set by the number of commits show in dashboard:

https://github.com/gogs/gogs/blob/77275a9b311ed126f887628f33fbd917750420cd/conf/app.ini#L440-L441

So if you want to display more, you can rise up this value.

**Comment by furai** [comment]
Can it be set to 0 for unlimited?

**Comment by Unknwon** [comment]
>Can it be set to 0 for unlimited?

No, because it could break dashboard UI looking.

For the error you have, because the repository you owned has (somehow) incorrect custom Git hook setting, and I have fixed it.

**Comment by furai** [comment]
Ok, thank you for your time and help. :)
