### ISSUE TITLE
Gogs container fails when "/"  filesystem is mounted read-only

### ISSUE THREAD

**Issue by archmangler** [gogs/gogs#5377]
- Gogs version (or commit ref): (gogs/gogs:0.11.53 ) / all 
- Git version:   2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): none

## Description

Regarding the GOGS docker container: To implement the Docker CIS security benchmark (item 5.12 in the benchmark) we need to be able to run the GOGS container with read-only root "/" filesystem. However, it appears gogs requires "/" to be mounted rw on container startup, or else it fails as follows:

```
root@vm:/var/GOGS# docker run --read-only --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
groupmod: /etc/group.5: Read-only file system
groupmod: cannot lock /etc/group; try again later.
usermod: no changes
touch: /app/gogs/docker/s6/crond/down: Read-only file system
s6-svscan: fatal: unable to mkfifo .s6-svscan/control: Read-only file system
```

a) Can the GOGS docker container be configured to work with read-only "/" (i.e docker run with --read-only) flag?
b) If not, what are the technical reasons for this (which can be used to justify it under a security analysis)?

**Comment by Unknwon** [comment]
Hi, I think Gogs won't work with read-only file system because Gogs needs to write data out to the file system. So... not going to work as expected anyway.

**Comment by archmangler** [comment]
Can gogs container be rebuilt to write out data to a bind-mounted volume instead of the "/" filesystem? That way we can keep the rootfs read-only.

**Comment by Unknwon** [comment]
Gogs writes data to relative locations (i.e. "./data/xxx"), it does not care where it is. You can config it in your custom "app.ini" file.

Just one example:

https://github.com/gogs/gogs/blob/cc95d251d62903d6e96d9cf9c6ce426bec26556f/conf/app.ini#L68

But there are many more.
