### ISSUE TITLE
can't push through http (neither web interface). stuck on "Writing objects: 100%"

### ISSUE THREAD

**Issue by jartigag** [gogs/gogs#5378]
- Gogs version (or commit ref): 0.11.53.0603
- Git version: 2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2018/08/15 14:37:04 [TRACE] CSRF Token: 3n8F7UhqLDdjxWdVYLk5uUiCEbI6MTUzNDMzNjYyNDc5NTI0NzAwOA==
2018/08/15 14:37:04 [TRACE] Template: user/auth/login
2018/08/15 14:37:10 [TRACE] Session ID: 4e76270680ffb431
2018/08/15 14:37:10 [TRACE] CSRF Token: 3n8F7UhqLDdjxWdVYLk5uUiCEbI6MTUzNDMzNjYyNDc5NTI0NzAwOA==
2018/08/15 14:37:10 [TRACE] Session ID: 4e76270680ffb431
2018/08/15 14:37:10 [TRACE] CSRF Token: 7X3dHHAPjyB-qJrxk_HdqNft-7M6MTUzNDMzNjYzMDY2NjgzMjU5OQ==
2018/08/15 14:37:10 [TRACE] Template: user/dashboard/dashboard
2018/08/15 14:37:13 [TRACE] Session ID: 4e76270680ffb431
2018/08/15 14:37:13 [TRACE] CSRF Token: 7X3dHHAPjyB-qJrxk_HdqNft-7M6MTUzNDMzNjYzMDY2NjgzMjU5OQ==
2018/08/15 14:37:14 [TRACE] Template: repo/home
2018/08/15 14:37:16 [TRACE] Session ID: 4e76270680ffb431
2018/08/15 14:37:16 [TRACE] CSRF Token: 7X3dHHAPjyB-qJrxk_HdqNft-7M6MTUzNDMzNjYzMDY2NjgzMjU5OQ==
2018/08/15 14:37:16 [TRACE] Template: repo/editor/upload
2018/08/15 14:37:19 [TRACE] Session ID: 4e76270680ffb431
2018/08/15 14:37:19 [TRACE] CSRF Token: 7X3dHHAPjyB-qJrxk_HdqNft-7M6MTUzNDMzNjYzMDY2NjgzMjU5OQ==
2018/08/15 14:37:19 [TRACE] New file uploaded: f9e9539d-b494-4600-a1ce-dcf59e30a51a
2018/08/15 14:37:21 [TRACE] Session ID: 4e76270680ffb431
2018/08/15 14:37:21 [TRACE] CSRF Token: 7X3dHHAPjyB-qJrxk_HdqNft-7M6MTUzNDMzNjYzMDY2NjgzMjU5OQ==
```

## Description

yesterday i installed gogs on my raspberrypi (raspbian 9) and i could push to master branch without problem. today i'm trying to push some little changes to another branch, but it hangs on this:
```
Username for 'http://tfg.jartigag.me:3000': jartigag
Password for 'http://jartigag@tfg.jartigag.me:3000': 
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 814 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
```
can't push through the web interface (http://tfg.jartigag.me:3000/jartigag/myreponame/_upload/theotherbranch/) neither. 

what can be failing?

**Comment by Unknwon** [comment]
I think it is possible the the post-update hook hangs on requesting back to the web server, by default, the request URL is (in your case) `http://0.0.0.0:3000/`, to verify this is the problem, you can change the following setting to `http://tfg.jartigag.me:3000`:

https://github.com/gogs/gogs/blob/cc95d251d62903d6e96d9cf9c6ce426bec26556f/conf/app.ini#L23

**Comment by jartigag** [comment]
after yesterday's push i had to change the `RUN_USER=pi` to `RUN_USER=git`, so it could be a matter of permissions. i've just changed the owner of the repo dir to `git` too, and now i see this error on web interface:
```
remote: hooks/pre-receive: line 2: /home/pi/gogs/gogs: No such file or directory To /var/www/myrepodir/myrepo.git ! [remote rejected] theotherbranch -> theotherbrand (pre-receive hook declined) error: failed to push some refs to '/var/www/myrepodir/myrepo.git'
```
now `/home/pi/gogs/gogs` is in `/home/git/gogs/gogs`. where should i change this "hooks/pre-receive line 2" error?

**Comment by Unknwon** [comment]
OK... you can regenerate all hooks in `/admin` panel:

![image](https://user-images.githubusercontent.com/2946214/44152354-e7b215de-a0d7-11e8-8cab-d840d511a860.png)

**Comment by jartigag** [comment]
great! now i can push from web interface (i pushed it to the wrong branch, but that's a minor problem :sweat_smile:).

but pushing from terminal keeps unavailable..

this is the [reporitory] and [server] part of my `custom/conf/app.ini` file now:

```
[repository]
ROOT = /var/www/myrepodir

[server]
PROTOCOL         = http
DOMAIN           = tfg.jartigag.me
HTTP_PORT        = 3000
ROOT_URL         = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
LOCAL_ROOT_URL   = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/
DISABLE_SSH      = true
SSH_PORT         = 228
START_SSH_SERVER = false
OFFLINE_MODE     = false
```

**Comment by Unknwon** [comment]
>but pushing from terminal keeps unavailable..

Please define “unavailable”.

**Comment by jartigag** [comment]
if i do `git push` or `pull`, it asks me for my username and password, and gets stuck there (it even validate if user-passwd is correct)

**Comment by Unknwon** [comment]
Please define “there” or show logs.

You can try SSH push just to make sure it isn’t caused by HTTP related settings.

**Comment by jartigag** [comment]
"there" is:
```
$ git pull origin master
Username for 'http://tfg.jartigag.me:3000': asdfghjkl
Password for 'http://asdfghjkl@tfg.jartigag.me:3000':
```
can't try it with ssh, although i set `DISABLE_SSH=false`, `SSH_PORT=228`, `START_SSH_SERVER=true` and restarted gogs:
```
$ git pull origin master
ssh: connect to host tfg.jartigag.me port 228: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Unknwon** [comment]
I think the HTTP connection not even reached to Gogs based on your log.

**Comment by Unknwon** [comment]
Try apply “-v” flag when you do git pull.

Looks like a very slow network connection to your Gogs instance.

**Comment by jartigag** [comment]
right! if i start a new repo with `git remote add origin http://192.168.1.1/myrepo.git`, it works perfectly. sometimes i had trouble with dns and domains that point my raspberrypi (not nat loopback support, i think)..
thank you very much!
