### ISSUE TITLE
Maybe it's a bug of avatar in the webpage of organization's members list.

### ISSUE THREAD

**Issue by Thonnn** [gogs/gogs#5384]
The user's avatar unable to display in the webpage of organization's members list. The webpage url would like 'http://localhost:3000/org/myorgnization/members'.  
 It looks like below:  
![figure1](https://user-images.githubusercontent.com/29172396/44300210-ed9ec680-a335-11e8-85ab-b7825dd1d9bd.png)  
I checked the html:  
![figure2](https://user-images.githubusercontent.com/29172396/44300224-2b9bea80-a336-11e8-89f6-65ce9d6377f0.png)  
The img url is https://secure.gravatar.com/avatar/7c25458935ccab24b6073c26b5d04aac?d=identicon?s=48 There is a '?' after 'identicon'. It should be '&'.
The html source in the file of gogs/templates/org/member/members.tmpl,  line 17 is:  
![figure3](https://user-images.githubusercontent.com/29172396/44300268-c8f71e80-a336-11e8-8879-6fd38051cf24.png)
The '?' should be '&'.  
  
------
In addition, I would like to ask what is the difference between private and public members? What is the difference between activated and not activated user?

**Comment by Unknwon** [comment]
Hi, if I remember correctly this is a fixed bug, please upgrade your Gogs.
