### ISSUE TITLE
Performance Issue with large Pull Requests, files tab - 

### ISSUE THREAD

**Issue by lpotherat** [gogs/gogs#5386]
Hi, I haven't found issue here, so I post it : 

When you browse a PR with many files, the browser make too much work on the files tab (https://git.my.biz/MY/project/pulls/152/files) , maybe the syntax coloring should be done lazy, or the file details should be folded by default.

The performance issue is the same when creating the PR.

Thanks for your work on Gogs !

**Comment by Unknwon** [comment]
Thanks for the feedback!

How many changes and files you have in the PR?

**Comment by lpotherat** [comment]
We may be not be great at co-working ;) but we get sometimes PR like that : 
![image](https://user-images.githubusercontent.com/380424/44518218-ff7fc100-a6c9-11e8-9a18-878b9958c771.png)

**Comment by lpotherat** [comment]
And what if the files details was folded and not loaded by default, loaded via ajax query only when the user unfold the files detail section ?

**Comment by Unknwon** [comment]
>loaded via ajax query only when the user unfold the files detail section ?

Yes, you are welcome to file an issue for this feature request.

**Comment by Unknwon** [comment]
Closing as objective of this thread is not clear. But you can always do what I suggest in my previous comment.
