### ISSUE TITLE
undefined: cloneTLSConfig

### ISSUE THREAD

**Issue by tschallacka** [gogs/gogs#5387]
I followed the exact steps on https://gogs.io/docs/installation/install_from_source

With go 1.10.3 the latest version I got

```
git@LAPTOP-KU1F5PNU:~/go/src/github.com/gogs/gogs$ go build
\# runtime
/home/git/local/go/src/runtime/cgo.go:9:3: //go:cgo_export_static main only allowed in cgo-generated code
```

With go 1.9.7 I got

```
git@LAPTOP-KU1F5PNU:~/go/src/github.com/gogs$ go get -u github.com/gogs/gogs
\# github.com/gogs/gogs/vendor/github.com/go-sql-driver/mysql
gogs/vendor/github.com/go-sql-driver/mysql/utils.go:83:12: undefined: cloneTLSConfig
```

with both main and dev branch

So, what steps/runtime do I need to perform extra be able to run/build gogs?

My git version is 2.7.4
running on Ubuntu 16.04.5 LTS

**Comment by Unknwon** [comment]
Hi,

According to CI, Gogs is able to build from Go 1.7.x to latest Go master branch:

https://travis-ci.org/gogs/gogs/builds/416790589?utm_source=github_status&utm_medium=notification

Maybe helpful: https://github.com/hashicorp/consul/issues/3896#issuecomment-381562928

**Comment by stdupp** [comment]
May be you should check the go command is $GOROOT/bin/go
