### ISSUE TITLE
Access-Control-Allow-Origin at try.gogs.io

### ISSUE THREAD

**Issue by sustrik** [gogs/gogs#5389]
I am creating a browser-based application that would access Gogs API and I am trying to test it on try.gogs.io. However, it doesn't work because Access-Control-Allow-Origin is not specified. Would it be possible to set it to * ?

**Comment by cupen** [comment]
How about nginx  `add_header`?
https://stackoverflow.com/questions/11973047/adding-and-using-header-http-in-nginx

**Comment by sustrik** [comment]
This a browser-based application, trying to access try.gogs.io directly.

More generally, is not supporting browser-based applications an intent? I can imagine it may be so because of security. However, both GitHub and GitLab allow that, so it's not clear.

**Comment by SimonXianyu** [comment]
You are requiring one _**insecure**_ way to use try.gogs.io.  It will allow many **JS attack.**

If just testing API , you can use proxy to avoid cross domain access.
Those web servers such as Webpack-webserver, apache, nginx support.

**Comment by sustrik** [comment]
Given that GitHub/GitLab allow that kind of thing, I assume it's fixable. Is this what OAuth fixes? And is so, is there OAuth support in Gogs? (Sorry, if I'm being naive, I have no web development experience.)

**Comment by SimonXianyu** [comment]
There are client api which is still in progress.  https://github.com/gogs/go-gogs-client/wiki

**Comment by Unknwon** [comment]
Hi @sustrik, I do not think it is a good idea, you can always setup a dummy instance and allow `*` locally.
