### ISSUE TITLE
Can WebHook send mail?(WebHook能不能发送邮件?)

### ISSUE THREAD

**Issue by sotex** [gogs/gogs#5392]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 1.8.3.1
- Operating system: CentOS 7.5.1804 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I want to be able to send emails to collaborators of this project when some events happen, so that I can notify members in a timely manner. But I only found related operations in WebHook, but did not see the settings sent by email. Is there any support for this feature?

我想能够在一些事件发生的时候能够发送邮件给这个项目的协作者，以便能够及时的通知到各个成员。但是我只找到了WebHook中有相关的操作，但是没有见到邮件发送的设置，请问这个功能是不是有支持？

**Comment by SimonXianyu** [comment]
Send mail is not supported by WebHook.
You should write another service to receive WebHook invoke to send mail.

**Comment by Unknwon** [comment]
Sorry, as @SimonXianyu said, it is not the purpose of a webhook.

**Comment by sotex** [comment]
@SimonXianyu @Unknwon 
Thanks, I have already done this.
谢谢，我已经这么做了。
