### ISSUE TITLE
[Proposal] CSRF Checks on GET Routes

### ISSUE THREAD

**Issue by beeonthego** [gogs/gogs#5394]
I have just created an issue on Gitea repo to propose CSRF checks on some GET routes. The CSRF vulnerabilities may exist on gogs too, since gitea has inherited the code from gogs. 

[csrf on GET routes and proposal](https://github.com/go-gitea/gitea/issues/4838)

I would like to have feedback on the best strategies from the gogs community. Since the code base of the two repos are similar, I will submit a pull request to gogs after the strategy is decided. 

Update:

Just in case someone will be reading this issue in the future, we have opted for using a separate cookie and token on vulnerable GET routes. The token is signed with a separate key dedicated for this purpose. It is cheap and fast to generate and verify a token. Loss of POST route tokens (if used as query string on GET routes) has serious consequences. It is a risk not worth taking.

**Comment by cezar97** [comment]
After the discussion on changing routes to POST instead of GET, should this issue and others similar you made both on Gitea and here on Gogs be closed as deprecated?
Details at https://github.com/go-gitea/gitea/issues/4838.

**Comment by beeonthego** [comment]
thanks. I will close this one.
