### ISSUE TITLE
Proposal: Restrict API access to token only

### ISSUE THREAD

**Issue by beeonthego** [gogs/gogs#5398]
As the researcher @cezar97 reported before and mentioned in issue #5355 , CSRF vulnerabilities existed in API routes. 

Currently CSRF middleware handler only checks POST requests and skips checks on API routes. The reqToken middleware on API routes accepts user's logged in status (including token and cookie). This leaves API routes vulnerable to CSRF attacks.  A malicious person may use a victim's cookie to authenticate and do mischief by using API routes. If the malicious person finds a way to embed and execute code on issue/profile page, the script will bypass browser's same origin security policy adn be able to make POST requests because it is on the same domain. At the very least, an attacker can leave a link on issue/profile page to a malicious external page, and when logged in victims visit that page, the malicious page can make calls to API GET routes using victims' cookie. 

The solution is to restrict API access to token only. It is a good practice to access API routes with token only. Accepting cookie on API routes leads to troubles and difficulty in code maintenance. The test suites may need review and update to reflect this logic. It will also help to reduce errors if the access rule is simple.  

I am preparing a PR to address this vulnerability and will submit shortly. The CI tests may fail if the current tests accept cookies in API routes (they shouldn't). 

Update. All tests have passed. The logic in test suites are correct.

**Comment by cezar97** [comment]
Thanks for helping in fixing. And yeah, this issues has already been reported to Unknwon. It was https://github.com/gogs/gogs/issues/5355, even if doesn't have public details.

**Comment by beeonthego** [comment]
@cezar97 Great. Now you are back and you know the history of vulnerabilities, reporting and tracking issue number. The full credit goes to you for researching and reporting the issue, persistently 👍

**Comment by unknwon** [comment]
After some digging, I think this is already addressed in the recent releases.
