### ISSUE TITLE
Green "compare" button not visible on mirror repositories or their forks

### ISSUE THREAD

**Issue by mattreeve** [gogs/gogs#5405]
- Gogs version (or commit ref):  0.11.63.0817 
- Git version: 2.11.0
- Operating system: Debian Stretch
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL) https://try.gogs.io/mreeve/u-boot.git
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): Nothing of relevance that I can see

## Description

When I migrate and mirror a repository, the big green "compare changes" button is not visible.

Also if I fork this mirrored repository, the green button is not visible there either.

I'm not sure if this is intentional behaviour or not, but surely at least on the fork I want to be able to do comparisons I would think?

Note that I cannot create the fork repository on try.gogs.io as I am not allowed to fork to the same owner.

**Comment by Unknwon** [comment]
Hi, mirror repository is not meant to be edit in Gogs's design. So you can't push/edit or whatever.

Also, "migrate" is not "fork", no upstream it could compare to.
