### ISSUE TITLE
GOGS: PAM doesn't work

### ISSUE THREAD

**Issue by edgarm1964** [gogs/gogs#5406]
- Gogs version (or commit ref): 0.11.53.0603
- Git version: 0.11.53.0603
- Operating system: Centos7.5
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

Nothing is really logged (although I've set Level to Trace in custom/conf/app.ini):
2018/09/07 16:18:45 [ INFO] Listen: http://0.0.0.0:3000
2018/09/07 16:18:57 [TRACE] Session ID: af3783cda6b45b77
2018/09/07 16:18:57 [TRACE] CSRF Token: rklREQv_Q9a0qaHjR5tRvg6xbfU6MTUzNjMyOTc1MDgwOTY5NTg1NQ==
2018/09/07 16:18:59 [TRACE] Template: user/auth/login
2018/09/07 16:19:16 [TRACE] Session ID: af3783cda6b45b77
2018/09/07 16:19:16 [TRACE] CSRF Token: rklREQv_Q9a0qaHjR5tRvg6xbfU6MTUzNjMyOTc1MDgwOTY5NTg1NQ==
2018/09/07 16:19:18 [TRACE] Template: user/auth/login

## Description

I've set up a PAM authentication source with:
Type: PAM
Name: PAM
Service name: system-auth

All I get is is "Username or password incorrect" in the webpage. No further information is provided.
And nothing is logged in log file(s). And of course, the user exists. And gogs is running with as user not allowed to read /etc/shadow.

Local accounts, such as the gogs administrator, work.
...

**Comment by mattreeve** [comment]
Which PAM  backend source is the account you're trying to use coming from? Is it a local account on the Unix box, in /etc/passwd and /etc/shadow and the backend is pam_unix?

If so, my understanding this won't work if gogs can't read /etc/shadow. pam_unix is basically just an interface onto /etc/passwd and /etc/shadow. Things like sshd run as root for the login phase, so they can read it that way.

**Comment by edgarm1964** [comment]
Ahh, OK.
