### ISSUE TITLE
 standard_init_linux.go:178: exec user process caused "exec format error"   

### ISSUE THREAD

**Issue by liwei00wade** [gogs/gogs#5410]
docker run -itd  -v /home/docker-data/gogs-data/:/data --name git-server-work  -p  8022:22 -p 3000:3000 hypriot/rpi-gogs-raspbian
36c722fae42af31b6e16842d93fc444429ef04da84aa9027ea035483eef4a11f

standard_init_linux.go:178: exec user process caused "exec format error"
standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by Unknwon** [comment]
Locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
