### ISSUE TITLE
Why have all my projects been erased

### ISSUE THREAD

**Issue by abas619** [gogs/gogs#5412]
- Gogs version (or commit ref): 0.11.62.0817
- Git version: 2.18.0-64-bit
- Operating system: Windows 10 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): unknown

## Description

Hello
Some time ago, my entire project was cleared of Gogs without reason
I did not do anything, just one day I wanted to put the project in your Gogs saying that you have no Repositories.
My whole project has been deleted from Gogs
I wanted to check this out

**Comment by Unknwon** [comment]
If you mean your repositories on try.gogs.io, yes that's expected because periodically my script cleans some relatively large repositories to save server disk space.
