### ISSUE TITLE
Web editor does not save changes on Windows run as service

### ISSUE THREAD

**Issue by marioja** [gogs/gogs#5414]
- Gogs version (or commit ref): 
0.11.53.0603
- Git version: 
2.18.0
- Operating system: 
Windows 10 x64
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite 
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):
```
2018/09/10 13:55:15 [TRACE] Template: repo/editor/edit
2018/09/10 13:55:38 [TRACE] Session ID: 737827ee2a379a82
2018/09/10 13:55:38 [TRACE] CSRF Token: (snip)==
2018/09/10 13:55:44 [TRACE] AddTestPullRequestTask [head_repo_id: 6, head_branch: master]: finding pull requests
2018/09/10 13:55:44 [TRACE] AddTestPullRequestTask [base_repo_id: 6, base_branch: master]: finding pull requests
2018/09/10 13:55:44 [TRACE] Session ID: 737827ee2a379a82
2018/09/10 13:55:44 [TRACE] CSRF Token: (snip same as previous)==
2018/09/10 13:55:46 [TRACE] Template: repo/home

```

## Description
I create a new repository.  Then I navigate to the readme.md and click the edit button.  I add text "hello world" then click commit.
I do not see the changes and there is no new commit on that branch.
...

**Comment by marioja** [comment]
I tried on try.gogs.io but it worked there.  Can this be a result of using sqllite?

**Comment by Unknwon** [comment]
>Can this be a result of using sqllite?

I don't think so, commits are saved directly in the standard Git repository format on your server (managed by Gogs).

Maybe make a GIF or short video to show your steps would be helpful.

**Comment by marioja** [comment]
I cannot create a demo or GIF on the office computer.  However, here are the simple steps:

1. Logon to my gogs installation (not accessible to internet) and create a new repository called a2
2. Click the check box "Initialize this repository with selected files and template"
3. Click the readme.md file
4. Click the pencil icon to edit the file
5. Type "Hello world" after the #a2 line
6. Click the commit changes green button
7. The readme.md file is redisplayed without the added "Hello world" text.
8. I click on the a2 repository and there is only 1 commit (the Initial commit) when there should be 2

**Comment by Unknwon** [comment]
@marioja you chosen "commit directly" or "create a new branch"?

**Comment by marioja** [comment]
1. Is there some detailed debugging I could turn on?
1. Can you show me the gogs.log of a working gogs case to see what it should look like?

**Comment by Unknwon** [comment]
>Can you show me the gogs.log of a working gogs case to see what it should look like?

There is no log upon successful "commit" operation.

Does it only happens on your office computer or any computer have access to your Gogs instance?

**Comment by marioja** [comment]
It occurs on someone else desktop accessing the same gogs instance.  Is there some detailed debugging I can turn on as obviously the commit is not working?

**Comment by Unknwon** [comment]
>Is there some detailed debugging I can turn on as obviously the commit is not working?

If that's the case, error message will be directly report back to web interface.

**Comment by Unknwon** [comment]
You haven't answer my question posted https://github.com/gogs/gogs/issues/5414#issuecomment-420044215

**Comment by marioja** [comment]
I leave the default which is commit directly to master branch

**Comment by marioja** [comment]
If I select commit to new branch "nb" and click commit I get a Compare Changes window that says 
`There is nothing to compare because base and head branches are even. ` and I am unable to create a pull request.   The branch, however is created.

**Comment by Unknwon** [comment]
Since we couldn't reproduce on demo site, there are two possible reasons I can think of right now:

1. There was bug but fixed after your version released
2. The way you setup Gogs is somewhat unusual and some disk-level problem just doesn't report back

I think 2. is unlikely, so maybe you want to try to upgrade Gogs first (no binary release at the moment, so you would have to upgrade by source).

**Comment by marioja** [comment]
Would it be possible for you to try the last binary version to see if the problem exist?  I am not sure I can do the source upgrade as I do not have any dev tools available.  Also, do you know when the next binary version would be available?

**Comment by marioja** [comment]
The install from source requires linux (sudo command, wget) which I do not have.

**Comment by Unknwon** [comment]
Maybe the problem is Windows, I'll try again on see if I can reproduce.

**Comment by Unknwon** [comment]
Hi, I just tested a clean install on Windows 7 64bit with 0.11.53, and is able to commit via web editor by using Chrome 69.

**Comment by marioja** [comment]
I did new install on Windows 10 64bit with 0.11.53 and the commit via web editor also works using Microsoft Edge. 
I went to the other production install that is not working and stopped it and restarted it from the command line using an admin command prompt and it also worked.  When I stopped and restarted it as a Windows service it also failed.  My window service is configured to start:
`C:\apps\gogs\gogs.exe" web --config "C:\apps\gogs\custom\conf\app.ini"`
When I use this command in an admin command prompt it works.  Can you see if your clean install also works as a service?  I am running the version with mws (https://dl.gogs.io/0.11.53/gogs_0.11.53_windows_amd64_mws.zip)

**Comment by marioja** [comment]
When I tried to web edit a file that was edited successfully using the non service run backed running as a service I got this error
![gogs-web-edit-error](https://user-images.githubusercontent.com/49068/45386365-336f4780-b5e1-11e8-8744-5609634a4249.png)

**Comment by Unknwon** [comment]
I think there are two problems here:

1. Run as windows service has relative path problem
2. User permission problem

It is really a problematic system. I will try again when I have time.

**Comment by Unknwon** [comment]
I'm still using Windows 7 64bit and 0.11.53 mws version. Started as service (followed steps [here](https://gogs.io/docs/installation/run_as_windows_service)).

I'm able to use web editor and commit changes.
