### ISSUE TITLE
webhook的推送数据能否在repository中增加一个 url参数？

### ISSUE THREAD

**Issue by maopanfeng** [gogs/gogs#5415]
使用gogs的webhook向packagist.org提交自动更新时，repository参数中缺少 url参数，导致推送失败。
packagist.org中composer包 自动更新需要的格式是：
{"repository":{"url":"PACKAGIST_PACKAGE_URL"}}

**Comment by Unknwon** [comment]
Locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
