### ISSUE TITLE
When commiting to a new repository, is_bare field is not updated

### ISSUE THREAD

**Issue by vi-n** [gogs/gogs#5417]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [中文](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please do not end your title with a question mark or period.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):

2018/09/11 21:54:47 [TRACE] HTTPGit - Authenticated user: 
2018/09/11 21:54:49 [TRACE] Session ID: 27a21f5cc743a97a
2018/09/11 21:54:49 [TRACE] CSRF Token: sWwpHOL1IwQECI1pzTA-bmJ8grI6MTUzNjY5NTYzNT
g0NzA5ODE4Nw==
2018/09/11 21:54:49 [TRACE] Template: repo/bare
2018/09/11 21:55:47 [TRACE] Session ID: 27a21f5cc743a97a
2018/09/11 21:55:47 [TRACE] CSRF Token: sWwpHOL1IwQECI1pzTA-bmJ8grI6MTUzNjY5NTYzNT
g0NzA5ODE4Nw==

## Description
When I create a repository using the web interface, and then pushing an existing repository to this repository it will remain shown as a new repository.
When I update the is_bare field in the repository this problem is fixed.
This problem occurs with both MySQL and SQLite
I use the linuxserver/gogs docker

**Comment by Unknwon** [comment]
Hi, that's because your push operation bypassed Gogs delegation, and this repository is not responsible for non-official resources.
