### ISSUE TITLE
Enable HTTP authentication for push or pull remote git (Gogs Server)

### ISSUE THREAD

**Issue by essivision** [gogs/gogs#5418]
- Gogs version (or commit ref): 
- Git version: 0.11.53.0603
- Operating system:  Windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
Hi,
I m sorry to answer question in this place. I installed Gogs on windows 7 and run it. For web UI I configured `Require Sign In View` and every things is ok, but I want to access to repository only authenticated user with login credential that define in web user management. I don't want use LDAP or other auth service. I want to use local database user credential to work with remote git. 

What should I do? Please help me. I can't find any documentation about this.

**Comment by Unknwon** [comment]
Hi,

>For web UI I configured Require Sign In View and every things is ok, but I want to access to repository only authenticated user with login credential that define in web user management.

Based on your description, you should have already achieved what you want.

**Comment by essivision** [comment]
I resolve problem with enable SSH built-in server and generate `ssh-keygen` and use in in my key in web panel like `Github`

**Comment by Salmakis** [comment]
is this possible without ssh?
repo is on private inside a team and still everybody can clone and push.

**Comment by Unknwon** [comment]
@Salmakis I think your installation has serious problem in configuration, recommend reading https://discuss.gogs.io/t/how-to-config-ssh-settings/34.
