### ISSUE TITLE
关于gogs无法发送邮件问题反馈

### ISSUE THREAD

**Issue by coding1618** [gogs/gogs#5421]
gogs发送邮件时提示
```
发送测试邮件至 'git@applo.club' 时失败：gomail: could not send email 1: Auth: unencrypted connection
```
上面说是什么不安全连接，官方大佬有什么办法解决一下吗？如图所示
![2018-09-15_194838](https://user-images.githubusercontent.com/38412458/45586006-e2818b00-b921-11e8-8c06-e0420c3382cb.png)
![2018-09-15_194853](https://user-images.githubusercontent.com/38412458/45586007-e44b4e80-b921-11e8-8f1c-1e67b0c9b83b.png)
配置都是正确为什么发不出去，希望官方大佬尽快回复我，谢谢
而且还不能使用中文，请官方快点解决这些问题，用中文就报错~
![2018-09-15_161839](https://user-images.githubusercontent.com/38412458/45586005-e01f3100-b921-11e8-8ead-32087c673781.png)

**Comment by Unknwon** [comment]
Sorry about the issue you encountered.

However I need to locking this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
