### ISSUE TITLE
Chown removal breaks fresh installs

### ISSUE THREAD

**Issue by Immortalin** [gogs/gogs#5422]
This https://github.com/gogs/gogs/commit/068e6ce2c995445f0ce1c10ee11816600b12a5fd breaks fresh installs of gogs (i.e. not upgrading) in docker. Permission denied error.

**Comment by Unknwon** [comment]
Thanks for the report!

The patch has been pushed to the `develop` branch, and the new "develop" tag image is building, should take about 15-20 minutes before you can pull.
