### ISSUE TITLE
the word "git" in the domain causes problems

### ISSUE THREAD

**Issue by misaon** [gogs/gogs#5426]
- Gogs version (or commit ref): 0.11.66 latest
- Git version: Gogs docker version
- Operating system: Gogs docker version
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
...
hello, I came across a problem with the docker version of gogs. I have a container docker pointing through the NGINX reverse proxy. I used the subdomain git.shdev.cz. Gogs started and seemed to work properly. However, after signing in and displaying any repository, Gogs has logged off. This happened even after a clean installation.

I accidentally tried changing the domain name to gogs.shdev.cz on the same configuration. Now everything is working properly.

I wondered if there was an error in Gogs, which when he detects the word "git" in the domain, begins to log out of the user spontaneously.

It's a bug.

**Comment by Unknwon** [comment]
Gogs does not care or know what domain you use, it only care requests to the port it listens on. Please check your proxy setting.
