### ISSUE TITLE
send test email fail

### ISSUE THREAD

**Issue by fengzidk** [gogs/gogs#5428]
![image](https://user-images.githubusercontent.com/22466765/45746442-e40ac600-bc35-11e8-9a3c-2589987d0751.png)
![image](https://user-images.githubusercontent.com/22466765/45746466-f422a580-bc35-11e8-9bcb-175fb8b76e5e.png)

What should I do? emmmm........

**Comment by ibearth2025** [comment]
Really simple just , go to your mail and set option `ACCES TO NOT SECURE APPS` to TRUE
![screen shot 2018-09-19 at 3 43 28 pm](https://user-images.githubusercontent.com/42680071/45747382-54f4b280-bc23-11e8-864b-4ef8aa763264.png)

and use gmail HOST as shown in above picture

**Comment by Unknwon** [comment]
Closing this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
