### ISSUE TITLE
Cannot start ssh server

### ISSUE THREAD

**Issue by YuxuanWang-CHINA** [gogs/gogs#5434]
- Operating system: manjaro
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
## Description
my user:wyx

panic: SSH: Fail to parse private key

goroutine 1 [running]:
github.com/gogs/gogs/pkg/ssh.Listen(0xc0000387f1, 0x7, 0xbd4, 0xc0002b4ea0, 0x6, 0x6)
	/home/wyx/go/src/github.com/gogs/gogs/pkg/ssh/ssh.go:182 +0x3a9
github.com/gogs/gogs/routes.GlobalInit()
	/home/wyx/go/src/github.com/gogs/gogs/routes/install.go:93 +0x233
github.com/gogs/gogs/cmd.runWeb(0xc000285b80, 0x0, 0xc000285b80)
	/home/wyx/go/src/github.com/gogs/gogs/cmd/web.go:171 +0x6b
github.com/gogs/gogs/vendor/github.com/urfave/cli.HandleAction(0xe51700, 0xfe8cf8, 0xc000285b80, 0xc0002b4c00, 0x0)
	/home/wyx/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:483 +0xad
github.com/gogs/gogs/vendor/github.com/urfave/cli.Command.Run(0xf9886d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfab313, 0x10, 0x0, ...)
	/home/wyx/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/command.go:193 +0x98e
github.com/gogs/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc0000c11e0, 0xc0000b8000, 0x2, 0x2, 0x0, 0x0)
	/home/wyx/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:250 +0x647
main.main()
	/home/wyx/go/src/github.com/gogs/gogs/gogs.go:40 +0x273

**Comment by Unknwon** [comment]
Closing this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
