### ISSUE TITLE
Cannot start builtin SSH server

### ISSUE THREAD

**Issue by YuxuanWang-CHINA** [gogs/gogs#5435]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.18.0
- Operating system: linux manjaro
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):
2018/09/23 16:20:54 [TRACE] Log Mode: File (Trace)
2018/09/23 16:20:54 [ INFO] Gogs 0.11.66.0916
2018/09/23 16:20:54 [ INFO] Cache Service Enabled
2018/09/23 16:20:54 [ INFO] Session Service Enabled
2018/09/23 16:20:54 [ INFO] Git Version: 2.18.0

## Description

```
panic: SSH: Fail to parse private key

goroutine 1 [running]:
github.com/gogs/gogs/pkg/ssh.Listen(0xc000481661, 0x7, 0xbd4, 0xc000080360, 0x6, 0x6)
	/home/wyx/go/src/github.com/gogs/gogs/pkg/ssh/ssh.go:182 +0x3a9
github.com/gogs/gogs/routes.GlobalInit()
	/home/wyx/go/src/github.com/gogs/gogs/routes/install.go:93 +0x233
github.com/gogs/gogs/cmd.runWeb(0xc0003012c0, 0x0, 0xc0003012c0)
	/home/wyx/go/src/github.com/gogs/gogs/cmd/web.go:171 +0x6b
github.com/gogs/gogs/vendor/github.com/urfave/cli.HandleAction(0xe51700, 0xfe8cf8, 0xc0003012c0, 0xc0000b2a00, 0x0)
	/home/wyx/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:483 +0xad
github.com/gogs/gogs/vendor/github.com/urfave/cli.Command.Run(0xf9886d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfab313, 0x10, 0x0, ...)
	/home/wyx/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/command.go:193 +0x98e
github.com/gogs/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc0003349c0, 0xc0000b6000, 0x2, 0x2, 0x0, 0x0)
	/home/wyx/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:250 +0x647
main.main()
	/home/wyx/go/src/github.com/gogs/gogs/gogs.go:40 +0x273
```

**my user:wyx**

**Comment by Unknwon** [comment]
Seems like the actual error message is forgot to print.

Could you try to delete the file `/path/to/gogs/ssh/gogs.rsa` and restart Gogs see if it works?

**Comment by YuxuanWang-CHINA** [comment]
It does not work.

**Comment by Unknwon** [comment]
Are you able to find `/path/to/gogs/ssh/gogs.rsa` this file and delete it, and then see it is recreated?

**Comment by YuxuanWang-CHINA** [comment]
Yes

**Comment by Unknwon** [comment]
1. Are you using the binary or build from source code?
2. What if you roll back to previous version you were using, will it work?

**Comment by YuxuanWang-CHINA** [comment]
Build from source

**Comment by Unknwon** [comment]
I had two questions, please answer both.

**Comment by YuxuanWang-CHINA** [comment]
I use gogs for the first time.I directly used 'go get' command 2 days ago.

**Comment by Unknwon** [comment]
I tested on go1.10.4 without problem, I suggest you could also try one of the pre-compiled binary and see it works: https://github.com/gogs/gogs/releases

If for some reasons it still does not work, then you can turn off (set to `false`) the built in SSH server:

https://github.com/gogs/gogs/blob/3a4c981e3167875a3b60d0cee00ee85272608439/conf/app.ini#L26-L27

**Comment by YuxuanWang-CHINA** [comment]
I will try. Thanks.

**Comment by YuxuanWang-CHINA** [comment]
@Unknwon 
I use binary version

panic: SSH: Fail to parse private key

goroutine 1 [running]:
github.com/gogs/gogs/pkg/ssh.Listen(0xc420039a91, 0x7, 0xc0a, 0xc42009c2a0, 0x6, 0x6)
	/home/vagrant/gopath/src/github.com/gogs/gogs/pkg/ssh/ssh.go:182 +0x3ae
github.com/gogs/gogs/routes.GlobalInit()
	/home/vagrant/gopath/src/github.com/gogs/gogs/routes/install.go:93 +0x22d
github.com/gogs/gogs/cmd.runWeb(0xc42040d040, 0x0, 0xc42040d040)
	/home/vagrant/gopath/src/github.com/gogs/gogs/cmd/web.go:171 +0x6a
github.com/gogs/gogs/vendor/github.com/urfave/cli.HandleAction(0xed81e0, 0x107e108, 0xc42040d040, 0xc42009c700, 0x0)
	/home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:483 +0xad
github.com/gogs/gogs/vendor/github.com/urfave/cli.Command.Run(0x102db1e, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10406af, 0x10, 0x0, ...)
	/home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/command.go:193 +0xa35
github.com/gogs/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc42028e4e0, 0xc42000c080, 0x2, 0x2, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:250 +0x700
main.main()
	/home/vagrant/gopath/src/github.com/gogs/gogs/gogs.go:40 +0x2b8

**Comment by YuxuanWang-CHINA** [comment]
I wonder if START_SSH_SERVER = false , how can i use SSH in git server?

**Comment by Unknwon** [comment]
Every major Linux distro comes with OpenSSH server daemon suite, or if not, you can install via https://www.tecmint.com/install-openssh-server-in-linux/.

**Comment by mikeperalta1** [comment]
+1 This is happening for me on Fedora 28, but not two other servers running CentOS 7

I have also tried deleting the ssh keys. Same error after they regenerated. ssh-keygen verifies they seem valid.

$ yum list installed | grep -i ssh
libssh.x86_64                               0.8.3-1.fc28                @updates
libssh2.x86_64                              1.8.0-7.fc28                @fedora 
openssh.x86_64                              7.8p1-2.fc28                @updates
openssh-clients.x86_64                      7.8p1-2.fc28                @updates
openssh-server.x86_64                       7.8p1-2.fc28                @updates

$ uname --all
Linux services.azazel 4.18.9-200.fc28.x86_64 #1 SMP Thu Sep 20 02:43:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ ./gogs -v
Gogs version 0.11.66.0916

$ ./gogs web
2018/09/27 21:41:46 [TRACE] Custom path: /home/gogs/app/custom
2018/09/27 21:41:46 [TRACE] Log path: /home/gogs/log
2018/09/27 21:41:46 [TRACE] Log Mode: Console (Trace)
2018/09/27 21:41:46 [TRACE] Log Mode: File (Trace)
2018/09/27 21:41:46 [ INFO] Azazel Private Gogs 0.11.66.0916
2018/09/27 21:41:46 [ INFO] Cache Service Enabled
2018/09/27 21:41:46 [ INFO] Session Service Enabled
2018/09/27 21:41:46 [ INFO] Mail Service Enabled
2018/09/27 21:41:46 [ INFO] Register Mail Service Enabled
2018/09/27 21:41:46 [ INFO] Notify Mail Service Enabled
2018/09/27 21:41:47 [ INFO] Git Version: 2.17.1
panic: SSH: Fail to parse private key

goroutine 1 [running]:
github.com/gogs/gogs/pkg/ssh.Listen(0xc4203634e1, 0x7, 0xbce, 0xc42016cd20, 0x6, 0x6)
	/home/gogs/go/src/github.com/gogs/gogs/pkg/ssh/ssh.go:182 +0x3ae
github.com/gogs/gogs/routes.GlobalInit()
	/home/gogs/go/src/github.com/gogs/gogs/routes/install.go:93 +0x22d
github.com/gogs/gogs/cmd.runWeb(0xc42031fe00, 0x0, 0xc42031fe00)
	/home/gogs/go/src/github.com/gogs/gogs/cmd/web.go:171 +0x6a
github.com/gogs/gogs/vendor/github.com/urfave/cli.HandleAction(0xe11040, 0xfb26e8, 0xc42031fe00, 0xc42016ca00, 0x0)
	/home/gogs/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:483 +0xad
github.com/gogs/gogs/vendor/github.com/urfave/cli.Command.Run(0xf62bfc, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf75699, 0x10, 0x0, ...)
	/home/gogs/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/command.go:193 +0xa35
github.com/gogs/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc420354b60, 0xc4200b2000, 0x2, 0x2, 0x0, 0x0)
	/home/gogs/go/src/github.com/gogs/gogs/vendor/github.com/urfave/cli/app.go:250 +0x700
main.main()
	/home/gogs/go/src/github.com/gogs/gogs/gogs.go:40 +0x2b8

**Comment by Unknwon** [comment]
Someone has found the solution as follows:

1. Use `ssh-keygen` to generate a pair of key in PEM format:

		ssh-keygen -t rsa -m PEM

2. Replace `data/ssh/gogs.rsa` and `data/ssh/gogs.rsa.pub` to private and public keys just generated.
3. Restart Gogs.

Please try and see if it works.

**Comment by macro7** [comment]
C:\gogs>gogs web
2019/11/28 23:53:08 [TRACE] Custom path: C:/gogs/custom
2019/11/28 23:53:08 [TRACE] Log path: C:/gogs/log
2019/11/28 23:53:08 [TRACE] Log Mode: Console (Trace)
2019/11/28 23:53:08 [TRACE] Log Mode: File (Trace)
2019/11/28 23:53:08 [ INFO] Gogs 0.11.29.0727
2019/11/28 23:53:08 [ INFO] Cache Service Enabled
2019/11/28 23:53:08 [ INFO] Session Service Enabled
2019/11/28 23:53:08 [ INFO] Git Version: 2.23.0
panic: SSH: Fail to parse private key

goroutine 1 [running]:
github.com/gogits/gogs/pkg/ssh.Listen(0xc042258401, 0x7, 0x16, 0xc0421745a0, 0x6
, 0x6)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits
/gogs/pkg/ssh/ssh.go:182 +0x254
github.com/gogits/gogs/routes.GlobalInit()
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits
/gogs/routes/install.go:88 +0x1d7
github.com/gogits/gogs/cmd.runWeb(0xc04221b180, 0x0, 0xc04221b180)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits
/gogs/cmd/web.go:163 +0x71
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xdcdce0, 0xf32
6d8, 0xc04221b180, 0xc042144d00, 0x0)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits
/gogs/vendor/github.com/urfave/cli/app.go:483 +0xc0
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xee90a2, 0x3, 0
x0, 0x0, 0x0, 0x0, 0x0, 0xefce34, 0x10, 0x0, ...)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits
/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb79
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc04201ba00, 0xc
0420363e0, 0x2, 0x2, 0x0, 0x0)
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits
/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d7
main.main()
        C:/Users/Unknwon/Desktop/Applications/Luban/gopath/src/github.com/gogits
/gogs/gogs.go:41 +0x3f1

**Comment by unknwon** [comment]
Have you tried the latest version?

**Comment by rosscdh** [comment]
tried suggested fixes still no joy.. openssh is already running on 22, but changing the ssh port to another does not seem to help.

```
Gogs Version: 0.9.48.0722
```
