### ISSUE TITLE
.cs后缀的代码，无法浏览

### ISSUE THREAD

**Issue by jmk92** [gogs/gogs#5437]
类型为.NET，打开其他的都没问题，但所有的cs后缀的均无法打开。
404 - 找不到文件或目录。
您要查找的资源可能已被删除，已更改名称或者暂时不可用。

**Comment by Unknwon** [comment]
Closing this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
