### ISSUE TITLE
Cron Mirror Sync Not Start

### ISSUE THREAD

**Issue by t133** [gogs/gogs#5439]
- Gogs version : 0.11.53.0603
- Git version: 2.1.4
- Operating system: Raspbian GNU/Linux 8 (jessie)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

```
2018/09/25 01:45:32 [TRACE] Session ID: 965b8c08174ed5e8
2018/09/25 01:45:32 [TRACE] CSRF Token: 863PCUxO04K4_pnDrCTmIWIxJ_Y6MTUzNzgyMDE3MTI5MTA2OTYwMQ==
2018/09/25 01:45:33 [TRACE] Detected encoding: UTF-8 (fast)
2018/09/25 01:45:33 [TRACE] Template: repo/home
2018/09/25 01:45:37 [TRACE] Session ID: 965b8c08174ed5e8
2018/09/25 01:45:37 [TRACE] CSRF Token: 863PCUxO04K4_pnDrCTmIWIxJ_Y6MTUzNzgyMDE3MTI5MTA2OTYwMQ==
2018/09/25 01:45:37 [TRACE] Template: repo/editor/delete
2018/09/25 01:45:40 [TRACE] Session ID: 965b8c08174ed5e8
2018/09/25 01:45:40 [TRACE] CSRF Token: 863PCUxO04K4_pnDrCTmIWIxJ_Y6MTUzNzgyMDE3MTI5MTA2OTYwMQ==
2018/09/25 01:45:41 [TRACE] AddTestPullRequestTask [head_repo_id: 3, head_branch: master]: finding pull requests
2018/09/25 01:45:41 [TRACE] AddTestPullRequestTask [base_repo_id: 3, base_branch: master]: finding pull requests
2018/09/25 01:45:41 [TRACE] Session ID: 965b8c08174ed5e8
2018/09/25 01:45:41 [TRACE] CSRF Token: 863PCUxO04K4_pnDrCTmIWIxJ_Y6MTUzNzgyMDE3MTI5MTA2OTYwMQ==
2018/09/25 01:45:41 [TRACE] Template: repo/home
2018/09/25 01:45:45 [TRACE] Session ID: 965b8c08174ed5e8
2018/09/25 01:45:45 [TRACE] CSRF Token: 863PCUxO04K4_pnDrCTmIWIxJ_Y6MTUzNzgyMDE3MTI5MTA2OTYwMQ==
2018/09/25 01:45:45 [TRACE] Template: repo/home
```

## Description
Hello , i have in my raspberry Gogs installed. 
When i create a mirror  repo from another user  in gogs/rpi doesnt sync new commits.
steps to create mirror was : +(create) > New Migration > clone_address_http , Migration_type mirror .

app.ini :
```ini
[cron]
ENABLED =true
RUN_AT_START = true
[cron.update_mirrors]
SCHEDULE = @every 2m
[cron.repo_health_check]
SCHEDULE = @every 24h
TIMEOUT = 60s
```

In Repo Settings when i click to sync all works fine.
But Last Sync is : 1970-01-01 02:00:00 +0200 EET in first place. (maybe default tmestamp ?)
My problem is in cron jobs.
I set timeout to 2 minutes to see if working..
in admin panel i checked and no task is fired at all.

this affected me in first place when running gogs as root.
then i create user `git`.
so : app.ini look like

```ini
APP_NAME = Gogs
RUN_USER = git
RUN_MODE = dev
WORKINGDIR=/home/git/gogs
[database]
DB_TYPE  = mysql
HOST     =127.0.0.1:3306
NAME     =gogs
USER     =root
PASSWD   =******
SSL_MODE = disable
PATH     = data/gogs.db
```

i included only crusial parts of  app.ini for smaller doc.
also i start service gogs as root with gogs.service located in /etc/systemd/system/gogs.service
```
[Unit]
Description=Gogs
After=syslog.target
After=network.target
#After=mariadb.service mysqld.service postgresql.service memcached.service redis.service
After=mysqld.service

[Service]
LimitMEMLOCK=infinity
LimitNOFILE=65535
Type=simple
User=root
Group=root
WorkingDirectory=/home/git/gogs
ExecStart=/home/git/gogs/gogs web
Restart=always
Environment=USER=git HOME=/home/git/
RestartSec=5
[Install]
WantedBy=multi-user.target
```
Many thanks who takes time to see that.
Also i want to say i loved gogs from first time i saw.Very nice project.
Thank You !!

**Comment by Unknwon** [comment]
Hi, one thing to keep in mind is that you have set a cron job to check who needs to be updated every 2m, not update regardlessly every 2m. The minimum update interval is 1 hour (in current version) and you can see what's the value of your mirror repository in the repository settings page.

**Comment by t133** [comment]
Hm thanks i will change that to one hour and report back .

**Comment by t133** [comment]
Unknwon youre right !
default i think is 8h right?
in most recent versions  can we add values smaller tha 1h ?
i will close this issue..

**Comment by Unknwon** [comment]
>in most recent versions can we add values smaller than 1h ?

Currently it is not possible, but can file an issue for this feature request.

**Comment by t133** [comment]
its not so important but it could be nice for user to have freedom to change that as well :+1:

**Comment by Unknwon** [comment]
It was designed intentionally to not sync too often to reduce server work load.
