### ISSUE TITLE
Set branch protection failed when branch name contains #

### ISSUE THREAD

**Issue by Cat7373** [gogs/gogs#5442]
- Gogs version (or commit ref): 0.11.66.0916
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.1
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Bower: Safari 12.0(MacOS 10.14)

---

![](https://user-images.githubusercontent.com/9296576/46240062-69c80780-c3d4-11e8-92ec-59a3d945f771.png)

---

![](https://user-images.githubusercontent.com/9296576/46240066-6f255200-c3d4-11e8-97ac-343df7aaf33b.png)

**Comment by Unknwon** [comment]
Hi, can you reproduce on demo site?

**Comment by Cat7373** [comment]
@Unknwon 

https://try.gogs.io/Cat73/issus-5442

https://try.gogs.io/Cat73/issus-5442/settings/branches/test%23123

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Cat7373** [comment]
Test pass, thanks.
