### ISSUE TITLE
Remember login does not work

### ISSUE THREAD

**Issue by CWempe** [gogs/gogs#5444]
When I log into Gogs (web) every couple of days, I need to input my credentials even I check `Remember Lgin` (or is it `stay logged in` in english?) everytime.

I have 2FA enabled, but I think this should work anyway.

Is this an issue with Gogs or could the problem be with my setup?

    Server:
    Gogs Version: 0.11.59.0627
    docker container

    Client:
    Win 10
    Chrome 69

**Comment by Unknwon** [comment]
Closing this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
