### ISSUE TITLE
ssh 的链接地址不可以使用

### ISSUE THREAD

**Issue by DrayChou** [gogs/gogs#545]
ssh 的地址显示的为： 
git@192.168.0.135:gdop/client_bin.git ，
但实际应该是 
git@192.168.0.135:gogs-repositories/gdop/client_bin.git ，
而且 必须要输入 git 用户的密码，而不是 gogs 的用户名密码，请问这个要怎么修改下呢？

谢谢

**Comment by DrayChou** [comment]
通过 ln-s 建立软连接的方法暂时解决这个问题了

**Comment by harry91** [comment]
I met exactly the same problem. Nothing useful from troubleshooting page :-(

**Comment by Unknwon** [comment]
Hi @harry91 

> I met exactly the same problem. Nothing useful from troubleshooting page :-(

So many people says that and turns out they didn't config SSH server right or manually added public keys to `.ssh/authorize_keys` file.

**Comment by harry91** [comment]
I haven't modified .ssh/authorize_keys manually. Maybe you can write a wiki about how to generate public/private keys and add public key instead of a simple link to github wiki. I'm still working on it. Clone through HTTP works fine.

**Comment by Unknwon** [comment]
>  Maybe you can write a wiki about how to generate public/private keys and add public key instead of a simple link to github wiki.

SSH key generate process is all the same, and there is a operation on URL `/admin` allows you to completely rewrite SSH auth file based on Gogs database.

Also, what is the error message you get when you say `cannot push` or whatever it is?

**Comment by harry91** [comment]
Sorry, I didn't say cannot push. I cannot clone.
**Key creating process(under cygwin):**
$ ssh-keygen -t rsa -b 4096 -C "330737668@qq.com"
Generating public/private rsa key pair.
Enter file in which to save the key (/home/Guangyu/.ssh/id_rsa):
/home/Guangyu/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/Guangyu/.ssh/id_rsa.
Your public key has been saved in /home/Guangyu/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:uDeN5Evxqz........wpChyjZLLfhJIk 330737668@qq.com
The key's randomart image is:
+---[RSA 4096]----+
balabala......
|    o.oo+..      |
+----[SHA256]-----+

**Clone procedure:**
Guangyu@GY91 /cygdrive/c/Users/Guangyu/Desktop/abcdefg
$ git clone guangyu@120.26.69.11:gogsadmin/gogo_park.git
Cloning into 'gogo_park'...
guangyu@120.26.69.11's password:
Permission denied, please try again.
guangyu@120.26.69.11's password:
Permission denied, please try again.
guangyu@120.26.69.11's password:
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**No log from logs under log/ folder or console.**

**Comment by harry91** [comment]
I'm checking with the auth.log and there's something wrong inside. I'll give you a feedback later.

**Comment by Unknwon** [comment]
Well... based on the error, there are two possible known situations:

1. You doesn't run Gogs by correct user, e.g. you config as git but actually run as root.
2. Your `.ssh/authorize_keys` file permission isn't 0600.

**Comment by harry91** [comment]
Good news~! I've finally solved the problem.
I noticed the error information in /var/log/auth.log. It says " Authentication refused: bad ownership or modes for directory /home/guangyu/.ssh"
So I changed the .ssh/ folder to 0700 and .ssh/authorize_keys to 0600. It works.
**Sorry, it was my incorrect configuration. Thank you very much~!**

**Comment by Unknwon** [comment]
@harry91 no problem, good to hear!
