### ISSUE TITLE
[Feature] Ability to search files in Repo

### ISSUE THREAD

**Issue by UnicornCodes** [gogs/gogs#5450]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Ability to search files in Repo

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogs/gogs/issues/2346.
