### ISSUE TITLE
[Feature] Able to Limit Repo size by admin

### ISSUE THREAD

**Issue by UnicornCodes** [gogs/gogs#5456]
- Gogs version (or commit ref): master
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Able to Limit Repo size by admin in terms of memory for example 1GB Soft Limit and 2GB Hard Limit

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogs/gogs/issues/1294.
