### ISSUE TITLE
[Enhancement] Limit Number of Repos displayed in sidebar

### ISSUE THREAD

**Issue by UnicornCodes** [gogs/gogs#5457]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] MySQL
  - [x] PostgreSQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Limit Number of Repos displayed in the sidebar

![screenshot](https://user-images.githubusercontent.com/43472149/46668421-00bd6c80-cbea-11e8-9f02-472bb396ff1a.png)

**Comment by Unknwon** [comment]
It is controlled by this value:

https://github.com/gogs/gogs/blob/3a4c981e3167875a3b60d0cee00ee85272608439/conf/app.ini#L459-L461
