### ISSUE TITLE
gogs vs gitea

### ISSUE THREAD

**Issue by pjebs** [gogs/gogs#5462]
Can you explain the difference between this project and `gitea` (eg features etc)
Also the history behind why you believe `gitea` diverged.

It would be awesome if that info was in the readme so potential users can understand the difference.

**Comment by kolbma** [comment]
See https://blog.gitea.io/2016/12/welcome-to-gitea/

**Comment by Unknwon** [comment]
Closing this thread according to [policy](https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md).
