### ISSUE TITLE
Monitor Page Running Processes not working getting errors

### ISSUE THREAD

**Issue by UnicornCodes** [gogs/gogs#5464]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Monitor Page Running Processes not working getting errors

`.template: admin/monitor:52:15: executing "admin/monitor" at <.Pid>: can't evaluate field Pid in type *process.Process`

## Steps to Reproduce
- Mirror any Repo from Github/Gitlab
- Go to http://example.com/admin/monitor **Immediately** 
- You can see the Error

**Comment by Unknwon** [comment]
I think this is duplicated to https://github.com/gogs/gogs/issues/4933.
