### ISSUE TITLE
Customize existing .gitignore

### ISSUE THREAD

**Issue by LukeMauldin** [gogs/gogs#5471]
- Gogs version (or commit ref): 0.11.66.0916

## Description
Need a way to add new .gitignore configurations for custom language types OR override existing .gitignore configurations.  Example: would like to modify `https://github.com/gogs/gogs/blob/master/conf/gitignore/C%20Sharp` to add ignores for Intellij Rider files and other specialized custom project dependency folders.

**Comment by Unknwon** [comment]
Currently you can put new (non-conflict) file under `custom/conf/gitignore/<xx>`

**Comment by LukeMauldin** [comment]
This worked as expected. Thank you. Was this in any documentation? If so I could not find it.

**Comment by Unknwon** [comment]
Hmm... I think it is not documented.
