### ISSUE TITLE
Webhook not triggering when new branch pushed to mirrored repository

### ISSUE THREAD

**Issue by lukatera** [gogs/gogs#5473]
- Gogs version (or commit ref): 0.11.66
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Webhook is not triggering after sync when new branch is pushed to mirrored repository.
I believe that this piece of code is responsible: https://github.com/gogs/gogs/blob/a1098384c09bc0d569ec82d19c26415e00cc364b/models/mirror.go#L406-L412

Expected behaviour would be to trigger webhooks on all changes. However, current implementation triggers webhook on new branches only on second push.

...

**Comment by Unknwon** [comment]
Hi,

>However, current implementation triggers webhook on new branches only on second push.

How do you get this conclusion?

**Comment by lukatera** [comment]
That's the behaviour we observed in our local setup. If you push the first time and mirror sync occurs, no webhooks will be triggered for that branch. Even if you commit multiple times before the first sync of the new branch occurs, still no webhooks will be triggered for that branch. Only after Gogs syncs the branch for the first time, then it can trigger webhooks on new commits for that branch.

**Comment by Unknwon** [comment]
I think I got the point.

Currently no branch-create webhook of mirror supported, but you mean you want "push" event of commits of a new branch, correct?

**Comment by lukatera** [comment]
> I think I got the point.
> 
> Currently no branch-create webhook of mirror supported, but you mean you want "push" event of commits of a new branch, correct?

Correct. Because all new commits should be treated as push events.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5508, please help test on `develop` branch or https://try.gogs.io.
