### ISSUE TITLE
https with sub domain error

### ISSUE THREAD

**Issue by edmundhei** [gogs/gogs#5474]
- Gogs version (or commit ref): 0.11.68.1023
- Git version: 
- Operating system: ubuntu
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X] Not relevant
- Log gist (usually found in `log/gogs.log`):
c
## Description

I am trying to run gogs with the subdomain and https I manage to ran it with the sub domain with http but not https. 

**app.ini**
```
[server]
DOMAIN           = git.domain.com
HTTP_PORT        = 8443
ROOT_URL         = https://git.domain.com
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = false
OFFLINE_MODE     = false
PROTOCOL         = https
CERT_FILE        =/home/git/go/src/github.com/gogs/gogs/cert.pem
KEY_FILE         =/home/git/go/src/github.com/gogs/gogs/privkey.pem


```

and my apache2 config

```
<VirtualHost *:80>
        ServerName git.domain.com
        redirect / https://git.domain.com
        ProxyPreserveHost On
        ProxyRequests off
        ProxyPass / http://127.0.0.1:8443
        ProxyPassReverse / http://127.0.0.1:8443
</VirtualHost>
```

and all i get from gogs is 
```

`2018/10/24 21:59:14 http: TLS handshake error from 127.0.0.1:48388: tls: first record does not look like a TLS handshake
`
```

**Comment by Unknwon** [comment]
If you use reverse proxy, enable HTTPS in your proxy setting, not on Gogs side.
