### ISSUE TITLE
Repo API is not available for non logged in users

### ISSUE THREAD

**Issue by Unicorn0x1** [gogs/gogs#5475]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.17.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Currently, the Repo API is not available for non logged in users

https://try.gogs.io/api/v1/unknwon/grafana

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Unicorn0x1** [comment]
Yeah Thanks, It works fine

Example Link: https://try.gogs.io/api/v1/repos/yoginth/hooks
