### ISSUE TITLE
Move /app/gogs/docker/sshd_config file to /data/gogs/conf difrectory

### ISSUE THREAD

**Issue by sokoow** [gogs/gogs#5477]
It'd be easier for dockerized/kubernetes deployments if this file was moved for convenience - all configs should be together.

**Comment by Unknwon** [comment]
sshd_config config is for SSHD standalone service, it is not part of Gogs config suite.

**Comment by sokoow** [comment]
so why are you reading from this file, not from /etc/ssh/sshd_config ?

**Comment by Unknwon** [comment]
Because SSHD needs it, not Gogs self.

**Comment by sokoow** [comment]
well then it is a config that is part of gogs right ?
