### ISSUE TITLE
[security] change insecure storage of credentials in /data/gogs/conf/app.ini

### ISSUE THREAD

**Issue by sokoow** [gogs/gogs#5478]
Currently, your https://github.com/gogs/gogs/blob/master/conf/app.ini file contains following sensitive fields:

```
[server]
CERT_FILE = custom/https/cert.pem
KEY_FILE = custom/https/key.pem

[database]
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD =

[security]
COOKIE_USERNAME = gogs_awesome
COOKIE_REMEMBER_NAME = gogs_incredible

[mailer]
HOST =
HELO_HOSTNAME =
CERT_FILE = custom/mailer/cert.pem
KEY_FILE = custom/mailer/key.pem
USER =
PASSWD =

[cache]
HOST =
```

SOLUTION:

Ideally, build vault client into gogs code: https://github.com/hashicorp/vault/blob/master/api/client.go , and operate on vault secret paths as an alternative to ini file values.

More universal solution would be to make it possible to overlay these ini values with environmental variables.

WHY ?

In case somebody owns the box or container with gogs running in it, it's very easy to escalate further and gain access to caches and databases.

**Comment by sokoow** [comment]
add:

```
[session]
PROVIDER_CONFIG = data/sessions
```

field to that

**Comment by Unknwon** [comment]
Hi, I think this is same as https://github.com/gogs/gogs/issues/3682.

**Comment by sokoow** [comment]
yeah it is, thanks :)
