### ISSUE TITLE
Since last update UI looks broken

### ISSUE THREAD

**Issue by agherzan** [gogs/gogs#5480]
- Gogs version (or commit ref): 0.11.66.0916
- Git version: 
- Operating system: docker in container https://hub.docker.com/r/gogs/gogs/ tag 0.11.66
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): nothing relevant

## Description
Since last update, the UI looks broken. See git.gherzan.com . Console logs:
```
Loading failed for the <script> with source “https://git.gherzan.com/js/semantic-2.2.13.min.js”. git.gherzan.com:42:1
TypeError: $(...).dropdown is not a function[Learn More] gogs.js:1167:23
<anonymous>
https://git.gherzan.com/js/gogs.js:1167:23
j
https://git.gherzan.com/js/jquery-1.11.3.min.js:2:27304
fireWith
https://git.gherzan.com/js/jquery-1.11.3.min.js:2:28122
ready
https://git.gherzan.com/js/jquery-1.11.3.min.js:2:29954
J
h
```ttps://git.gherzan.com/js/jquery-1.11.3.min.js:2:30320

**Comment by Unknwon** [comment]
Hi, if you cannot reproduce on demo site, this will most likely not be considered as valid.

**Comment by agherzan** [comment]
I'm not sure how I can reproduce this on an instance already deployed.

**Comment by Unknwon** [comment]
Try

1. Disable all browser extensions
2. Force fresh the page

If still not working, back up your data and make a new container from image.

**Comment by agherzan** [comment]
@Unknwon both done with the same result. What did seems to have fixed it is downgrading to .34. See it running now just fine: https://git.gherzan.com/ .

**Comment by Unknwon** [comment]
I think you have modified default HTML, and https://git.gherzan.com/js/semantic-2.2.13.min.js is **loading failed** from your log. Gogs has been using Semantic 2.3.1

**Comment by agherzan** [comment]
Right. It was due to templates I had in place.
