### ISSUE TITLE
Import repo from local Gogs server to new local Gitlab server 

### ISSUE THREAD

**Issue by hero9** [gogs/gogs#5483]
Hi there!

- Gogs Version: 0.11.61.0816
- Go 1.10.3 

## Description

I have task to migrate whole repository from our Gogs server to newly installed Gitlab server!

Before considering to forget my repositories history (comments, issues, etc...), do one know of a way to export a repository data from a Gogs server to Gitlab Server ?

I just failed to found anything on the documentation for exporting/migrating the whole project data (not just the git repository and its wiki).

**Comment by Unknwon** [comment]
Hi, you should look for help from GitLab community, this repository is not responsible for this.

**Comment by hero9** [comment]
> Hi, you should look for help from GitLab community, this repository is not responsible for this.

Is it possible, at least?
