### ISSUE TITLE
Synology DSM - Change run_user to git instead of root

### ISSUE THREAD

**Issue by Petmics** [gogs/gogs#5484]
Hello,
i run gogs on my Synology with the spk package.
Does anyone know how can I start the package as non root User, for example git?
I only get this error: The executing user is not the current user: git -> root
Gogs is running, when I enter root, but I want to change it to git-User.

This things I did:
I created git-User in DSM
Change Ownerships in SSH with chmod -R for Gogs & Git
Nothing works.

Any Idea or tutorial?

Best regards
Petmic

**Comment by Unknwon** [comment]
Hi, you should look for help from publisher of the spk package you use, this repository is not responsible for that.
