### ISSUE TITLE
System requierements for running Gogs with PostgreSQL

### ISSUE THREAD

**Issue by chortels** [gogs/gogs#5487]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 
- Operating system: Linux
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X ] Not relevant
- Log gist (usually found in `log/gogs.log`):

Hi, 

I'm deploying in OpenShift a Gogs image that uses another PostgreSQL image as database. According to what I have read in "Hardware Requirements" section: https://github.com/gogs/gogs, Gogs can operate normally using 2 CPUs and 512MB RAM. But, what about the requirements of the not-embedded PostgreSQL database? Which are the requierements that I need?

Regards.

**Comment by Unknwon** [comment]
>But, what about the requirements of the not-embedded PostgreSQL database? Which are the requierements that I need?

It really depends on how busy your Gogs instance will be.

For personal use, I think the minimum tier would be enough?

To be safe, 1CPU and 1GB for your PostgreSQL should be more than enough (provider ops limit is another story which I don't have any idea yet).
