### ISSUE TITLE
API status or health endpoint

### ISSUE THREAD

**Issue by koaps** [gogs/gogs#5494]
- Gogs version (or commit ref): 0.11.68.1023
- Git version: 1.8.3.1
- Operating system: Red Hat Enterprise Linux Server release 7.5 (Maipo) in Docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X ] Not relevant
- Log gist (usually found in `log/gogs.log`): none needed, feature request

I'm working on spinning up Gogs via Ansible in Docker and there's a timing delay needed to allow Gogs to startup before I attempt to add the admin account, it would be great to have a /status or /heath API endpoint to use to check for ok status in a loop, ideally without needing auth.

**Comment by Unknwon** [comment]
Try `/healthcheck` endpoint.
