### ISSUE TITLE
LDAP error: "too many colons" when configuring authentication

### ISSUE THREAD

**Issue by chortels** [gogs/gogs#5495]
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 
- Operating system: Linux
- Database (use `[x]`):
  - [x ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

Hi, 

When configuring authentication against an Active Directory and trying to log in with an user that is registered in said AD, I'm obtaining this error that I'm not able to discover: 

2018/11/04 09:54:20 [ERROR] [...kg/auth/ldap/ldap.go:188 SearchEntry()] LDAP connect failed for <my_address>: Dial: LDAP Result Code 200 "": dial tcp: address <my_address>:389: too many colons in address

_In the log that I show you, I changed the actual URL by <my_address> for security reasons._

Can anybody help me with this issue? I'm very confused about the meaning of this error. 

Regards.

**Comment by Unknwon** [comment]
Can you post your configuration with mask of sensitive information?

**Comment by robi-wan** [comment]
@chortels Make sure the hostname in your LDAP configuration contains just the hostname of the LDAP server (no protocol, no port). I made the mistake of adding the complete LDAP url into the hostname field and got the same error.
