### ISSUE TITLE
can not  initRepository in windows10 x64 

### ISSUE THREAD

**Issue by pbpf** [gogs/gogs#5496]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [中文](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please do not end your title with a question mark or period.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
[Macaron] 2018-11-05 10:04:28: Completed GET /repo/create 200 OK in 109.4728ms
[Macaron] 2018-11-05 10:04:45: Started POST /repo/create for 127.0.0.1
2018/11/05 10:04:45 [TRACE] Session ID: e0db14d1a3c9fdbb
2018/11/05 10:04:45 [TRACE] CSRF Token: NDKBo95CxTWVB1N8maotpI_N5046MTU0MTM4MzM3ODc4NzUwNjUwMA==
2018/11/05 10:04:52 [ERROR] [.../routes/repo/rep[Macaron] 2018-11-05 10:04:52: Started GET /img/500.png for 127.0.0.1
[Macaron] [Static] Serving /img/500.png
[Macaron] 2018-11-05 10:04:52: Completed GET /img/500.png 200 OK in 7.9951ms
o[Macaron] 2018-11-05 10:04:52: Completed POST /repo/create 500 Internal Server Error in 7.4109999s
.go:103 handleCreateError()] CreatePost: initRepository: initRepoCommit: git push: remote: hooks/pre-receive: line 2: H:/Download/gogs/gogs/gogs.exe: No such file or directory
To H:\temp\gogs-repositories\connor\test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'H:\temp\gogs-repositories\connor\test.git'

2018/11/05 10:04:52 [TRACE] Template: status/500
...

**Comment by Unknwon** [comment]
I think you have moved Gogs binary location after some use, do "Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)" in your admin dashboard.

**Comment by pbpf** [comment]
>           I think you have moved Gogs binary location after some use, do "Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)" in your admin dashboard.

Thank you, I solve it. My "touch.exe" is not in my %path%,which cause the problem. This is surely not a bug,but maybe we could make the error message more precise.
