### ISSUE TITLE
Deleted issue comment still it is on dashboard

### ISSUE THREAD

**Issue by Unicorn0x1** [gogs/gogs#5501]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.19.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Deleted issue comment still it is on dashboard

**Comment by Unknwon** [comment]
Hi, since activity feeds do not have bind constraint to a specific issue comment (only contains a link to it), it is not possible/worth to delete the feed when you delete a comment.
