### ISSUE TITLE
Large Issue comment exceeds dashboard section

### ISSUE THREAD

**Issue by Unicorn0x1** [gogs/gogs#5502]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.19.1
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Large Issue comment(the word without space) exceeds dashboard section

![screenshot](https://user-images.githubusercontent.com/43472149/48070285-82121a00-e1fd-11e8-96d6-b2a9ae500c41.png)

**Comment by Unicorn0x1** [comment]
What about `word-break: break-all;`

**Comment by Unknwon** [comment]
> What about `word-break: break-all;`

Sounds good!

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5507, please help test on `develop` branch or https://try.gogs.io.

**Comment by Unicorn0x1** [comment]
It's working fine!
