### ISSUE TITLE
Support for multiple domain names

### ISSUE THREAD

**Issue by Cat7373** [gogs/gogs#5503]
- Gogs version (or commit ref): 0.11.66.0916
- Git version: 2.17.1
- Operating system: Ubuntu 18.04.1
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Want to support multiple primary domain names

The URLs in the page are also generated based on the domain name currently accessed, such as the clone address

---

such as configuring `try1.gogs.io` and `try2.gogs.io`

When I visit `try1.gogs.io`, the clone address of the project will be `https://try1.gogs.io/gogs/gogs.git`,SSH address will be `git@try1.gogs.io:gogs/gogs.git`

And when I visit `try2.gogs.io`, the clone address of the project will be `https://try2.gogs.io/gogs/gogs.git`,SSH address will be `git@try2.gogs.io:gogs/gogs.git`

**Comment by Unknwon** [comment]
Hi, what is the use case of this?

Generally, Gogs itself does not care or know how are requests coming in, it serves as long as they come. I think this kind of work should better be done in a reverse proxy in front of Gogs instance. Or fork this repository to have your custom version.

**Comment by Cat7373** [comment]
For example, when we work together in two companies, the other person may want to use their domain name.

such as `gogs.google.com` and `gogs.microsoft.com`

**Comment by Unknwon** [comment]
Though it is an interesting feature, but I do not think it will ever be implemented in this repository ...

**Comment by Cat7373** [comment]
ok, thanks~
