### ISSUE TITLE
I cannot access the new server after migrating it

### ISSUE THREAD

**Issue by liu578101804** [gogs/gogs#5505]
1. I used docker to build the gogs warehouse and mapped the dada folder to local.
2. I now need to migrate this git server to another server.
3. I copy the data to the new server
4. At the same time, the `[server]` configuration in the `app.ini` file was changed to the new server IP

The result is that the IP to access the new server appears, which shows that it cannot be accessed, and the logs in docker I see have no access records.

**Comment by Unknwon** [comment]
>which shows that it cannot be accessed, the logs in docker I see have no access records.

I think you should Google for how to make your network of Docker container work first.

**Comment by liu578101804** [comment]
ok, thank you.
