### ISSUE TITLE
only IE can access gogs after installation

### ISSUE THREAD

**Issue by KenMercusLai** [gogs/gogs#5510]
**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 0.11.66.0916
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 on VM workstation on Win 10 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I installed gogs on a VM as shown above. The only weird thing is that I can only access it with IE on win10. other browsers like edge, firefox, chrome (without any plugin) were not working and stuck when they try to connect.

From the gogs.log, I didn't see any entry related to the connection from these browsers.

**Comment by Unknwon** [comment]
Hi, it sounds like VM workstation is setting some proxy for you to be able to access program inside it. And unfortunately, only IE reads the proxy, others somehow do not care.
