### ISSUE TITLE
Cyrillic symbols in repository description translating to ????

### ISSUE THREAD

**Issue by geqo** [gogs/gogs#5512]
- Gogs version (or commit ref): 0.11.66
- Git version: 2.1.4
- Operating system: Debian 9
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

Cyrillic symbols in repository description translating to ????, changing table character set and collation to utf8_mb4 doesn't help.

**Comment by Unknwon** [comment]
Hi, if you cannot reproduce on demo site (also using MySQL), I can't take this a valid bug report.

**Comment by Unknwon** [comment]
Thanks for the update but it does not answer my question: https://github.com/gogs/gogs/issues/5512#issuecomment-441328136

**Comment by geqo** [comment]
1. Yep, correctly.
2. Charset - utf8mb4, collation utf8mb4_general_ci, changed manually from latin. Didn't help.

**Comment by geqo** [comment]
> 1. Yep, correctly.
> 2. Charset - utf8mb4, collation utf8mb4_general_ci, changed manually from latin. Didn't help.

Changed description field charset and collation helperd.

**Comment by Unknwon** [comment]
> > 1. Yep, correctly.
> > 2. Charset - utf8mb4, collation utf8mb4_general_ci, changed manually from latin. Didn't help.
> 
> Changed description column charset and collation to utf8mb4 helperd.

so... the problem solved?

**Comment by geqo** [comment]
Yes, i can't believe that I didn't guess before.
