### ISSUE TITLE
Import repos by scanning folders

### ISSUE THREAD

**Issue by wirmachenbunt** [gogs/gogs#5513]
i'm moving from gitblit to gogs and i'm very used to just copy/paste my all my repos (name.git) to the repository folder and hit "clear cache" in the UI to simply import all repos in one go.

is there a similar way in gogs ? it seems impractical to migrate each repo, one by one as i have like over 200 repos.

i have searched all issues but i could not find a method to import  a collection of repos instead of just one repo.

**Comment by Unknwon** [comment]
You can write a script that calls the migrate API: https://github.com/gogs/go-gogs-client/wiki/Repositories#migrate, just to make sure the account (`uid`) has proper permission to import a repository by local path (admin grants this permission automatically).

**Comment by zaphod-42** [comment]
In case anyone else stumbles across this, the new docs are here:

https://github.com/gogs/docs-api/tree/master/Repositories#migrate
