### ISSUE TITLE
mirror_prune_desc 当远程追踪的引用被删除时本地也同步删除

### ISSUE THREAD

**Issue by chenyanmo** [gogs/gogs#5522]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. what dose “mirror_prune_desc ” mean，is it mean delete repositories?
2. “当远程追踪的引用被删除时本地也同步删除”是什么意思,是指本地镜像的仓库会同步删除吗？还是只是仓库里面的文件。

## Description

...

Look forward to your reply ：）
期待您的回复 😊

**Comment by Unknwon** [comment]
TL;DR yes

http://blog.plataformatec.com.br/2013/05/how-to-properly-mirror-a-git-repository/
