### ISSUE TITLE
Download link with cdn on gogs.io(Chinese version) is broken

### ISSUE THREAD

**Issue by Trim21** [gogs/gogs#5525]
![](https://ws1.sinaimg.cn/large/bd69bf14ly1fxjgvoul49j20o40bhmyk.jpg)

cdn download link  is `http://gogs.dn.qbox.me/gogs_0.11.66_windows_amd64.zip` here.

but browser can't download zip file beacuse response body is `{"error":"no such domain"}`

network: China Education and Research Network

**Comment by GramThanos** [comment]
Non of the CDN links on the gogs.io look like the one you describe.
All the links are `https` and all the CDN links are under the `cdn.gogs.io` domain.
example : `https://cdn.gogs.io/0.11.66/gogs_0.11.66_linux_amd64.zip`

**Comment by Unknwon** [comment]
Because the CDN provider in China recycles the domain and just no way for anyone outside mainland China to get a verify one. 

I have updated Chinese version to use same download links, but the speed is not very good as expected.
