### ISSUE TITLE
show info when mysql is offline

### ISSUE THREAD

**Issue by hmzlam** [gogs/gogs#5528]
- Gogs version (or commit ref): All
- Git version: All
- Operating system: All
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description

It would be nice to add a message on the terminal when gogs can't conntect to database, rather than add it to the log

**Comment by Unknwon** [comment]
Hi, I think this is same as https://github.com/gogs/gogs/issues/2305.
