### ISSUE TITLE
Clone URLs incorrect

### ISSUE THREAD

**Issue by barryspearce** [gogs/gogs#5548]
I have two issues with the SSH clone URL being shown.

app.ini

[repository]
ROOT = /Repo/data/git

Using external SSH server.

With organisation JohnHanning, creating a new project called "new-project"
Creating a repository creates it the correct directory but lower cases the name:

/Repo/data/git/johnhanning/new-project

The clone url displayed is:

ssh://git@gitserver.example/JohnHanning/new-project.git

The correct URL is:

ssh://git@gitserver.example/Repo/data/git/johnhanning/new-project.git

**Comment by Unknwon** [comment]
Please be respectful to issue template.

And as far as I see, the URL is correct.

**Comment by wei417** [comment]
I had the same problem

[repository]
ROOT = /var/data/gogs-repositories
The clone url displayed is:
ssh://git@liuw.vip:40022/liuwei/test.git
The correct URL is:
ssh://git@liuw.vip:40022:gogs-repositories/liuwei/test.git
