### ISSUE TITLE
Composite issue ID in commit message

### ISSUE THREAD

**Issue by trejjam** [gogs/gogs#5551]
**Describe the bug**
I found in Gogs log attempt (ended with error) to parse an issue ID which is written for an external issue tracker (YouTrack in my case). The issue ID is the composition of a project name "dash" ID (eg. project-42). Gogs expect only integer identifier of an issue (we have configured external issue tracker with aplhanumeric naming style in Gogs).

**To Reproduce**
1. Create commit message `Throw exception if confirmation contact was parsed incorrectly #IN2-1433`
2. Push
3. See Gogs log (server side)

**Expected behavior**
Handle error (silently?)

**Additional context**

- Gogs version (or commit ref):  0.11.79.1211
- Git version: 2.17.1
- Operating system: Centos 7
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist `hooks/post-receive.log`:

```log
[ERROR] [...ogs/models/action.go:496 CommitRepoAction()] UpdateIssuesCommit: strconv.ParseInt: parsing "IN2-1433": invalid syntax
```

**Comment by Unknwon** [comment]
Hi, "alphanumeric" looks very similar to the YouTrack style, have you tried that?

![image](https://user-images.githubusercontent.com/2946214/49963575-5eba4900-fee6-11e8-9921-be1765ba031a.png)

**Comment by Unknwon** [comment]
I see. Can you create a reproduce repository on demo site so I can have failing cases to test against?

**Comment by Unknwon** [comment]
I see, I'll look into it.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch.

**Comment by trejjam** [comment]
Error message no longer appears, thank you
