### ISSUE TITLE
Dockerhub image "gogs-rpi" (armhf) not working

### ISSUE THREAD

**Issue by kinglike1337** [gogs/gogs#5552]
Since the release of the new version 0.11.79 the dockerhub image "gogs-rpi" (armhf) is not working anymore. After I pulled the new image the container fails to start.

The docker logs contains many repeated errors.

![gogs](https://user-images.githubusercontent.com/23118073/49957741-0b0d2700-ff09-11e8-85ba-6c9921860252.jpg)

The gosu executable seems to be broken.

**Comment by Unknwon** [comment]
Thanks for the report! I used the wrong Dockerfile, rebuilding it now.

**Comment by Unknwon** [comment]
Images for gogs/gogs-rpi has been updated, please reported back if same problem remains!

**Comment by kinglike1337** [comment]
Thank you very much for the quick fix.
The container is now working again.
