### ISSUE TITLE
Mirror Sync API always returns 401 Unauthorized

### ISSUE THREAD

**Issue by luhaixun** [gogs/gogs#5553]
**Describe the bug**
After upgrade to new version, gogs API doesn't work. This worked for previous version. I tried both password and token

**To Reproduce**

Post API call with curl, for example:
curl -vvv -X POST -u username:password -H "Content-Type: application/json" http://<host>/api/v1/org/repos/owner1/repo1/mirror-sync

**Expected behavior**
 a 202 HTTP status is returned

**Screenshots**

**Additional context**

- Gogs version (or commit ref): 0.11.79.1211 
- Git version: 2.18.0
- Operating system: Docker container provided by Gogs
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

**Comment by Unknwon** [comment]
Hi, I cannot reproduce on demo site.

**Comment by luhaixun** [comment]
@Unknwon could you provide that curl example to me? which API endpoint to check?

Thanks,
Tim

**Comment by Unknwon** [comment]
... Shouldn't you prove it to me it is not working? https://github.com/gogs/go-gogs-client/wiki/Repositories#mirror-sync

**Comment by luhaixun** [comment]
@Unknwon  the command example I provided in the question side doesn't work. Put it again here, it returns 401.

curl -vvv -X POST -u username:password -H "Content-Type: application/json" http:///api/v1/org/repos/owner1/repo1/mirror-sync

**Comment by Unknwon** [comment]
@luhaixun You must use access token since 0.11.79 because of potential XSS attack.

**Comment by Unknwon** [comment]
It is described here: https://github.com/gogs/docs-api#basic-authentication

**Comment by luhaixun** [comment]
Thanks, it works. I didn't aware of this change when upgrading to a new version as of security concern. @Unknwon

**Comment by Unknwon** [comment]
@luhaixun :sweat_smile: I only realized after wrote new API documents yesterday, but I figure it is better to use access token anyway, thus didn't "fix" the basic auth.
