### ISSUE TITLE
Can't git push but can git clone via https

### ISSUE THREAD

**Issue by JefferyKu** [gogs/gogs#5554]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [中文](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please do not end your title with a question mark or period.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: hypriot/rpi-gogs-raspbian 
- Operating system: raspberry 2 ARMv7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [*] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [*] No: explain why
- Log gist (usually found in `log/gogs.log`):
## Description
I run with Nginx with http auth. I can use git clone to download the repo. It shows up the prompt and I fill the right http auth account/password for downloading well.

But, I want to use git push. It shows up prompt and I fill http auth account/passowrd. It shows up this message.

> fatal: Authentication failed for 'https://example.com/user/gogs.git/'

This is I run git push with GIT_CURL_VERBOSE=1. The output is as below.

> ```
> $ GIT_CURL_VERBOSE=1 git push
> * Couldn't find host example.com in the .netrc file; using defaults
> *   Trying XX.XXX.XX.XX...
> * TCP_NODELAY set
> * Connected to example.com (XX.XXX.XX.XX) port 443 (#0)
> * found 151 certificates in /etc/ssl/certs/ca-certificates.crt
> * found 611 certificates in /etc/ssl/certs
> * ALPN, offering http/1.1
> * SSL connection using TLS1.2 / ECDHE_RSA_CHACHA20_POLY1305
> * 	 server certificate verification OK
> * 	 server certificate status verification SKIPPED
> * 	 common name: example.com (matched)
> * 	 server certificate expiration date OK
> * 	 server certificate activation date OK
> * 	 certificate public key: RSA
> * 	 certificate version: #3
> * 	 subject: CN=example.com
> * 	 start date: Sun, 09 Dec 2018 06:24:04 GMT
> * 	 expire date: Sat, 09 Mar 2019 06:24:04 GMT
> * 	 issuer: C=US,O=COMODO,CN=COMODO
> * 	 compression: NULL
> * ALPN, server accepted to use http/1.1
> > GET /user/gogs.git/info/refs?service=git-receive-pack HTTP/1.1
> Host: example.com
> User-Agent: git/2.11.0
> Accept: */*
> Accept-Encoding: gzip
> Accept-Language: C, *;q=0.9
> Pragma: no-cache
> 
> < HTTP/1.1 401 Unauthorized
> < Server: nginx/1.10.3
> < Date: Sat, 15 Dec 2018 14:22:39 GMT
> < Content-Type: text/html
> < Content-Length: 195
> < Connection: keep-alive
> < WWW-Authenticate: Basic realm="Restricted Content"
> < 
> * Curl_http_done: called premature == 0
> * Connection #0 to host example.com left intact
> Username for 'https://example.com': king
> Password for 'https://king@example.com': 
> * Couldn't find host example.com in the .netrc file; using defaults
> * Found bundle for host example.com: 0x10a4be0 [can pipeline]
> * Hostname example.com was found in DNS cache
> *   Trying XX.XXX.XX.XX...
> * TCP_NODELAY set
> * Connected to example.com (XX.XXX.XX.XXX) port 443 (#1)
> * found 151 certificates in /etc/ssl/certs/ca-certificates.crt
> * found 611 certificates in /etc/ssl/certs
> * ALPN, offering http/1.1
> * SSL re-using session ID
> * SSL connection using TLS1.2 / ECDHE_RSA_CHACHA20_POLY1305
> * 	 server certificate verification OK
> * 	 server certificate status verification SKIPPED
> * 	 common name: example.com (matched)
> * 	 server certificate expiration date OK
> * 	 server certificate activation date OK
> * 	 certificate public key: RSA
> * 	 certificate version: #3
> * 	 subject: CN=example.com
> * 	 start date: Sun, 09 Dec 2018 06:24:04 GMT
> * 	 expire date: Sat, 09 Mar 2019 06:24:04 GMT
> * 	 issuer: C=US,O=COMODO,CN=COMODO
> * 	 compression: NULL
> * ALPN, server accepted to use http/1.1
> > GET /user/gogs.git/info/refs?service=git-receive-pack HTTP/1.1
> Host: example.com
> User-Agent: git/2.11.0
> Accept: */*
> Accept-Encoding: gzip
> Accept-Language: C, *;q=0.9
> Pragma: no-cache
> 
> < HTTP/1.1 401 Unauthorized
> < Server: nginx/1.10.3
> < Date: Sat, 15 Dec 2018 14:22:53 GMT
> < Content-Type: text/html
> < Content-Length: 195
> < Connection: keep-alive
> < WWW-Authenticate: Basic realm="Restricted Content"
> < 
> * Ignoring the response-body
> * Curl_http_done: called premature == 0
> * Connection #1 to host example.com left intact
> * Issue another request to this URL: 'https://example.com/user/gogs.git/info/refs?service=git-receive-pack'
> * Couldn't find host example.com in the .netrc file; using defaults
> * Found bundle for host example.com: 0x10a4be0 [can pipeline]
> * Re-using existing connection! (#1) with example.com
> * Connected to example.com (XX.XXX.XX.XX) port 443 (#1)
> * Server auth using Basic with user 'king'
> > GET /user/gogs.git/info/refs?service=git-receive-pack HTTP/1.1
> Host: example.com
> Authorization: Basic Y2J13mF03WF3Mzk5Omt5d2F03jY9
> User-Agent: git/2.11.0
> Accept: */*
> Accept-Encoding: gzip
> Accept-Language: C, *;q=0.9
> Pragma: no-cache
> 
> < HTTP/1.1 401 Unauthorized
> < Server: nginx/1.10.3
> < Date: Sat, 15 Dec 2018 14:22:53 GMT
> < Content-Type: text/html; charset=UTF-8
> < Transfer-Encoding: chunked
> < Connection: keep-alive
> < Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
> < Set-Cookie: i_like_gogits=7ece83c4c4dd390f; Path=/; HttpOnly
> < Set-Cookie: _csrf=zVoePizVfFQ2dqcdH5QGroIonUc6MTU0NDg4Mzc3MzI3MDk3MjQ1NA%3D%3D; Path=/
> < 
> * Curl_http_done: called premature == 0
> * Connection #1 to host example.com left intact
> fatal: Authentication failed for 'https://example.com/user/gogs.git/'
> ```
> 

The http auth account is "king". In addition, if I make the http auth account/password same as a user's gogs account/passowrd, I can use git push successfully. 

.

**Comment by Unknwon** [comment]
Please be respectful to the issue template.
