### ISSUE TITLE
Plans for using Go 1.11 modules feature

### ISSUE THREAD

**Issue by hamidfzm** [gogs/gogs#5559]
Lots of awesome Go projects started using Go 1.11 modules feature. Are there any plans using this in Gogs? from keeping `vendor` directory to using `go.mod` and `go.sum`?

**Comment by hamidfzm** [comment]
@Unknwon I tried using go.mod with Gogs and everything was fine and worked perfectly as expected. I can create a pull request for using go modules. Also, we can keep the `vendor` directory and update it using go modules feature so old go version can compile this project too.

**Comment by Unknwon** [comment]
Sounds good to me, adopt while make sure existing approach still works.

**Comment by unknwon** [comment]
I think this is implemented already!
