### ISSUE TITLE
Can not push on Windows2012 data center

### ISSUE THREAD

**Issue by FalconWu2017** [gogs/gogs#5560]
- Gogs version (or commit ref): gogs_0.11.79_windows_amd64
- Git version: git version 2.20.1.windows.1
- Operating system: Windows2012 data center
- Database (replace `[ ]` with `[x]`):
  - [ x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
   -  No: It is work at https://try.gogs.io and my local computer.but is is not right work at the server.
- Log gist (usually found in `log/gogs.log`):

gogs/log/gogs.log  file:
2018/12/19 14:51:39 [TRACE] Session ID: 464799b277298a63
2018/12/19 14:51:39 [TRACE] CSRF Token: uuoPlSnFupGRxESnv6dY31zgY0M6MTU0NTIwMjI5OTQzNTA3NjMwMA==
2018/12/19 14:51:39 [TRACE] Session ID: 046a684af0f0e5de
2018/12/19 14:51:39 [TRACE] CSRF Token: TIG4NQ_5_lhTBqMEanfWF3FgNJU6MTU0NTIwMjI5OTU3NDY4OTgwMA==
2018/12/19 14:51:40 [TRACE] Session ID: 9ba9bb603cca3d45
2018/12/19 14:51:40 [TRACE] CSRF Token: nlo5whJFAAtNUNLGrFjqm3J6M7Y6MTU0NTIwMjMwMDAxNzI5NzMwMA==
2018/12/19 14:51:40 [TRACE] Session ID: 23d81ee4cf2df981
2018/12/19 14:51:40 [TRACE] CSRF Token: hubwfx5tyFq4i4zut9eCPV-p3Dw6MTU0NTIwMjMwMDA0MzUwMDUwMA==
2018/12/19 14:51:40 [TRACE] HTTPGit - Authenticated user: Falcon

Another gogs/gogs.log file:
[Macaron] 2018-12-19 14:51:39: Started GET /Falcon/test.git/info/refs?service=git-receive-pack for 116.226.74.231
[Macaron] 2018-12-19 14:51:39: Completed GET /Falcon/test.git/info/refs?service=git-receive-pack 200 OK in 22.4511ms
[Macaron] 2018-12-19 14:51:39: Started POST /Falcon/test.git/git-receive-pack for 116.226.74.231
[Macaron] 2018-12-19 14:51:39: Completed POST /Falcon/test.git/git-receive-pack 401 Unauthorized in 15.6717ms
[Macaron] 2018-12-19 14:51:40: Started POST /Falcon/test.git/git-receive-pack for 116.226.74.231
[Macaron] 2018-12-19 14:51:40: Completed POST /Falcon/test.git/git-receive-pack 401 Unauthorized in 0s
[Macaron] 2018-12-19 14:51:40: Started POST /Falcon/test.git/git-receive-pack for 116.226.74.231
[Macaron] 2018-12-19 14:51:40: Completed POST /Falcon/test.git/git-receive-pack 200 OK in 143.4602ms

git bash output:
$ git push origin HEAD:master
Enumerating objects: 4, done. 
Counting objects: 100% (4/4), done. 
Delta compression using up to 4 threads 
Compressing objects: 100% (2/2), done.                                                                                   
 Writing objects: 100% (3/3), 332 bytes \| 332.00 KiB/s, done.                                                              
Total 3 (delta 0), reused 0 (delta 0)                                                                                    
 To http://XXX.XXX.XXX.XXX:8000/Falcon/test.git                                                                              
 ! [remote rejected] HEAD -> master (pre-receive hook declined)                                                           error: failed to push some refs to 'http://XXX.XXX.XXX.XXX:8000/Falcon/test.git'
--

**Comment by Unknwon** [comment]
Please provide logs in `log/hooks/pre-receive.log`.

**Comment by FalconWu2017** [comment]
There is nothing in the log/hooks/pre-receive.log.
There are three files in  log/hooks/(post-receive.log,pre-receive.log and update.log) but there is nothing in all of them.

**Comment by Unknwon** [comment]
Without actual error log I will not consider this as a valid report. Have you ever changed Gogs binary location? Try regenerate all hooks in admin dashboard.

**Comment by FalconWu2017** [comment]
It is really nothing in log/hooks/pre-receive.log.I dont know why.
And I have not changed binary location before。
About try regenerate all hooks,Do you mean
Admin Panel --> Operatins --> Resync pre-receive, update and post-receive hooks of all repositories -->Run ?    I did it and useless。

C:\Services\gogs\repositories\falcon\test.git\hooks\pre-receive:
```
#!/usr/bin/env bash
"C:/Services/gogs/gogs.exe" hook --config='C:/Services/gogs/custom/conf/app.ini' pre-receive
```
C:\Services\gogs\repositories\falcon\test.git\hooks\post-receive:
```
#!/usr/bin/env bash
"C:/Services/gogs/gogs.exe" hook --config='C:/Services/gogs/custom/conf/app.ini' post-receive
```

**Comment by Unknwon** [comment]
I’m not familiar with windows, maybe it’s permission issue. Do you have git-bash installed?

**Comment by FalconWu2017** [comment]
Yes  of course。I have installed git-bash at my clent and the server.
Git version: git version 2.20.1.windows.1
What kind of permission do I need? The windows service is working with local_system account.
And I can use the Files-->Branch master--> new file  commit directly to the master branch.so I think there is not windows permission problem。mayby comes from any permission of gogs?

**Comment by Unknwon** [comment]
Are you able to execute pre-receive hook manually via git-bash? Post results here.

**Comment by Unknwon** [comment]
```
C:\Services\gogs\repositories\falcon\test.git\hooks\pre-receive
```

Or maybe `\` should be replaced with `/`.

**Comment by FalconWu2017** [comment]
Execute `"C:/Services/gogs/gogs.exe" hook --config='C:/Services/gogs/custom/conf/app.ini' pre-receive` ?

There is nothing result.

**Comment by Unknwon** [comment]
Execute the hook file: `C:\Services\gogs\repositories\falcon\test.git\hooks\pre-receive`

**Comment by FalconWu2017** [comment]
Execute  `C:/Services/gogs/repositories/falcon/test.git/hooks/pre-receive` in git bash.
Nothing result and did not find any log at `gogs/gogs.log` `gogs/log/gogs.log` `gogs/log/hooks/pre-receive.log`

**Comment by Unknwon** [comment]
Are you able to edit file content via web editor?

**Comment by FalconWu2017** [comment]
Do you want me edit `httok/pre-receive` file content? Yes,I am.

**Comment by Unknwon** [comment]
No, use Gogs web editor to edit any repository file.

**Comment by FalconWu2017** [comment]
Files-->Branch master--> new file commit ?
Yes I can

**Comment by Unknwon** [comment]
After you commit the change via web editor, are you able to see the commit activity just made by you in your dashboard(`/`)? Post a screenshot.

**Comment by FalconWu2017** [comment]
A screenshot? How to uoload a image?
this is the text I copy form Dashboard.
```
Falcon pushed to master at Falcon/test

 4cbc44a949 Add file Add test file
3 seconds ago
```

**Comment by Unknwon** [comment]
1. Google: how to upload image in GitHub comments
2. Looks like no problem at all. Currently no idea.

**Comment by FalconWu2017** [comment]
![Uploading 
![aaaa](https://user-images.githubusercontent.com/34147999/50274394-21226680-0478-11e9-9b97-4da63e46e414.png)
aaaa.png…]()
Test upload image!

**Comment by FalconWu2017** [comment]
![aaaa](https://user-images.githubusercontent.com/34147999/50274463-4ca55100-0478-11e9-950e-fe1553870ee3.png)

**Comment by FalconWu2017** [comment]
OK  I found it

**Comment by Unknwon** [comment]
Is your instance possible to be accessed publicly? Currently no clue of the problem you reported.

**Comment by FalconWu2017** [comment]
Yes my instance is public.Can you visit my site to try to fix this.I can give you the IP address.
Login sercive is Possible .
I will be here  tomorrow,for now I have to get out ,the office door will be closed.

**Comment by Unknwon** [comment]
Yes, please send IP address to my email u#gogs.io . I’ll see if I can reproduce tomorrow.

**Comment by FalconWu2017** [comment]
Are you sure your email is u#gogs.io?
I post a message got you at discuss.gogs.io with title "About #5560 bug report."

**Comment by FalconWu2017** [comment]
邮件没有到达某些或全部的预定收件人。

      主题:	About gogs error 
      发送时间:	2018/12/24 10:00

无法到达以下收件人:

      'u@gogs.io'，时间为 2018/12/24 10:00
            550 5.7.1 Unable to relay

**Comment by FalconWu2017** [comment]
I post a email use my emial 9504402@qq.com.

**Comment by Unknwon** [comment]
I have reproduced the error you encounter with your Gogs instance.

How did you start your Gogs? By service, or by command line?

**Comment by FalconWu2017** [comment]
By service. Setup service through gogs/scripts/windows with nssm-2.24-101-g897c7ad.
and I've tried by command `gogs.exe web`, just the same.

**Comment by FalconWu2017** [comment]
@Unknwon Can you log on to my server and reinstall the Gogs instance? Maybe there was a mistake in the installation process.

**Comment by FalconWu2017** [comment]
After a period of testing, I found that the hook script `pre-receive` and `update ` could not be executed. If I remove these two scripts, it will work good.
What will be heppend without these two scripty?

**Comment by Unknwon** [comment]
>What will be heppend without these two scripty?

Deleting these two scripts causes no guarantee of proper functioning.

**Comment by FalconWu2017** [comment]
I think it is good work after I replace `#!/usr/bin/env bash` to `#!/bin/bash` at the 1st line of the hook scripty.
But I'm not sure if it works properly.What's the difference between them?

**Comment by Unknwon** [comment]
>I think it is good work after I replace #!/usr/bin/env bash to #!/bin/bash at the 1st line of the hook scripty.
But I'm not sure if it works properly.What's the difference between them?

I think it only defines how the system finds the "bash" to execute the script.

Can you confirm things like dashboard feeds, webhook, etc all works after you change this 1st line of every script in your repository?
