### ISSUE TITLE
registration success shows 500, internal server error

### ISSUE THREAD

**Issue by Huholoman** [gogs/gogs#5565]
When I submit registration, it ends up with 500 internal server error. When I take a look to database, user table is empty.

**To Reproduce**
1. Go to 'registration'
2. Click on 'fill inputs'
3. Click on 'register'

**Expected behavior**
I would expect some "your registration was successful with new record in user table.

**Screenshots**
You can see my error on screenshot below.

**Additional context**

- Installed from: package (https://packager.io/gh/pkgr/gogs)
- Gogs version (or commit ref): 0.11.66.0916
- Git version: git version 2.11.0
- Operating system: Debian Stretch
- Database (replace `[ ]` with `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: it works
- Log gist (usually found in `log/gogs.log`): empty (well there are some errors, but i was able to solve them)
![snimek z 2018-12-21 19-58-14](https://user-images.githubusercontent.com/3115935/50365500-30d3a500-0575-11e9-9db0-bef0043a0c70.png)

**Comment by batouy** [comment]
check if the user running gogs have the right permission

**Comment by Huholoman** [comment]
Ok, sorry, my bad, there was actualy record in error log saying it does not have permission to create directory for the user.
