### ISSUE TITLE
保护分支master 丢失了，但是保护分支还有提示

### ISSUE THREAD

**Issue by xluohome** [gogs/gogs#5567]
你好，

master 之前一直是设置为保护分支的，今天上午同事告诉我master分支 莫名其妙不见了。 

试将本地的master push 上去，提示 如下：
remote: Gogs: Branch 'master' is protected and commits must be merged through pu ll request

另外。执行 
git push --delete origin master    

提示 ： error: unable to delete 'master': remote ref does not exit

之前安装的 gogs 是 17个月前的gogs docker版本， 下午拉了最新的gogs docker镜像更新了一下。  这个是老版本的bug 吗？ 

我如何在gogs上恢复master这个分支。  

谢谢。

**Comment by Unknwon** [comment]
Please be respectful to the issue template.
