### ISSUE TITLE
Auto-login after signup

### ISSUE THREAD

**Issue by ghost** [gogs/gogs#5569]
**Is your feature request related to a problem? Please describe.**

When the user signup the user is navigated to the login page which wastes some time to log in again

**Describe the solution you'd like**

When user create an account it can be navigated to the dashboard

**Additional context**

It will increase UX

**Comment by jimist** [comment]
@unknwon 
Hi there,
is this feature still needed? if so I could give it a go.

**Comment by unknwon** [comment]
@jimist: If you still have time, yes, please go ahead!

**Comment by unknwon** [comment]
@jimist: On a second thought, I don't think this is a good idea to have auto-login after signup. With email-verify-required instance, user should first verify the email they've used to sign up, which auto-login would defeat the purpose.
