### ISSUE TITLE
Wrong AvatarLink in member list

### ISSUE THREAD

**Issue by phpgao** [gogs/gogs#5570]
please review 

[tool.go](https://github.com/gogs/gogs/blob/master/pkg/tool/tool.go#L202)

and 

[members.tmpl](https://github.com/gogs/gogs/blob/master/templates/org/member/members.tmpl#L17)

both will make AvatarLink looks like this:

```
https://secure.gravatar.com/avatar/c3b4ec5d225b431c085d915892219ca3?d=identicon?s=48
```

should be:

```
https://secure.gravatar.com/avatar/c3b4ec5d225b431c085d915892219ca3?d=identicon&s=48
```

Just change `?` to '&'

**Comment by Unknwon** [comment]
Please be respectful to the issue template.
