### ISSUE TITLE
When cloning: fatal: Could not read from remote repository. Please make sure you have the correct access rights

### ISSUE THREAD

**Issue by GAZ082** [gogs/gogs#5571]
**Describe the bug**
Cant do a git clone of my GOGs project.

**To Reproduce**
git clone ssh://gogs@xxxx.me:50022/gaz/project.git

**Expected behavior**
Repo cloned :+1: 

**Additional context**
Reinstalled Arch and started to get this wrong. As i can clone a repo in the Gogs test server, I'm pretty sure there is something wrong somewhere in my side. I did not touch the server configuration, regenerated the ssh keys and loaded manually my own pub key.

![image](https://user-images.githubusercontent.com/100194/50498120-b85d6000-0a1c-11e9-9bf2-3afadeadbb94.png)

- Gogs version (or commit ref): 0.11.66.0916
- Git version: 2.11.0
- Operating system: Gogs server in Linux 4.14.79-v7+ #1159 SMP (Raspbian in a pi3)
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [] Yes: provide example URL
  - [x] No: explain why
Created a repo, loaded the public key and could clone it with no issues.
- Log gist (usually found in `log/gogs.log`):
```
2018/12/27 21:02:04 [ INFO] Gogs 0.11.66.0916
2018/12/27 21:02:04 [ INFO] Cache Service Enabled
2018/12/27 21:02:04 [ INFO] Session Service Enabled
2018/12/27 21:02:04 [ INFO] Git Version: 2.11.0
2018/12/27 21:02:04 [ INFO] SQLite3 Supported
2018/12/27 21:02:04 [TRACE] Doing: CheckRepoStats
2018/12/27 21:02:04 [ INFO] Run Mode: Production
2018/12/27 21:02:04 [ INFO] SSH server started on 0.0.0.0:50023
2018/12/27 21:02:04 [TRACE] SSH server cipher list: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128]
2018/12/27 21:02:05 [ INFO] Listen: https://0.0.0.0:53000
```

**Comment by Unknwon** [comment]
Hi, based on your log, your builtin SSH server is listening on port 50023 not 50022, try:

    git clone ssh://gogs@xxxx.me:50023/gaz/project.git

**Comment by GAZ082** [comment]
Thank you! Excellent catch! Feel so silly! :D
