### ISSUE TITLE
Token required for API has to be manually created via WebUI

### ISSUE THREAD

**Issue by koaps** [gogs/gogs#5583]
Gog's requires an API token to be able to use the API as a user (Basic Auth used to work)

The issue is there's no way to generate the token outside of the WebUI (since you can't make API calls as a user without the token) and the gog's CLI doesn't have an option.

This breaks automated installation and setup of Gog's in a CICD setup.

There should be a way to create the token either when the user is created via the API by the Admin or using the gogs CLI tool.

- Gogs Version: 0.11.85.1225 
- Git version: 2.18.1
- Operating system:  Alpine 3.8
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X ] SQLite

**Comment by luhaixun** [comment]
You can use https://github.com/gogs/docs-api/tree/master/Users#create-a-access-token to create a token based on basic authentication. It returns the token as the sha1 value if HTTP status code is 201.

**Comment by koaps** [comment]
@luhaixun thanks, I was able to get that to work
