### ISSUE TITLE
Create user token API allows creating tokens with the same name

### ISSUE THREAD

**Issue by koaps** [gogs/gogs#5587]
Posting to the user token API (`/users/:username/tokens`) endpoint multiple times with the same required name creates multiple tokens.

```
for i in {1..5}; do curl -X POST -H "content-type: application/json" -d '{"name":"test_api_token"}' http://builder:builder@127.0.0.1:10080/api/v1/users/builder/tokens -s | jq .sha1; done


curl http://builder:builder@127.0.0.1:10080/api/v1/users/builder/tokens -s | jq .

[
  {
    "name": "test_api_token",
    "sha1": "7f5a82226a2b01abbf60e648a7553d98879be5f5"
  },
  {
    "name": "test_api_token",
    "sha1": "e617c6a60b31695cd73d5b93b257b540bfaefe1b"
  },
  {
    "name": "test_api_token",
    "sha1": "12f79d7e61945dd6959701e7d0877b68819c7611"
  },
  {
    "name": "test_api_token",
    "sha1": "b7bf07c5341e61342bcc1068b34f5fe75d5a885a"
  },
  {
    "name": "test_api_token",
    "sha1": "f40728c529c01e236bb72a8c2da4cbbab32fa9bf"
  }
]
```

I would think this should throw a `HTTP/1.1 422 Unprocessable Entity` error like the repos do

`{"message":"repository already exists [uname: builder, name: builder]","url":"https://github.com/gogs/docs-api"}`

- Gogs Version: 0.11.85.1225
- Git version: 2.18.1
- Operating system: Alpine 3.8
- Database (replace [ ] with [x]):
  - PostgreSQL
  - MySQL
  - MSSQL
  - [X ] SQLite

**Comment by unknwon** [comment]
This is claimed to be fixed by merging #5820, please help test on `develop` branch or https://try.gogs.io.
