### ISSUE TITLE
Can you provide Pages like Github?

### ISSUE THREAD

**Issue by caifenglin** [gogs/gogs#5588]
Can you provide Pages like Github?

1. Like Wikipedia, you can choose whether to enable it or not.

2. Provide configurable IP + port + warehouse name to access web pages

It would be perfect if we could.I'm looking forward to this feature because it's very useful. It's best to integrate it into gogs. Similar to github, it's easy to use. You can also configure custom domain names to be the ideal git repository.

**Comment by Unknwon** [comment]
Hi, thanks for the feedback! But Gogs itself is not meant to be a publish platform. Better to find a product works with Git repositories to make sure you have the best experience.

**Comment by weituotian** [comment]
@Unknwon but i need a pages service to help quickly review the html files for others!

**Comment by Unknwon** [comment]
Ref: https://cloudconvert.com/md-to-html

**Comment by weituotian** [comment]
@Unknwon You're wrong！i mean there are js, css ,html file in my repo, and i want to serve this repo branch

**Comment by Unknwon** [comment]
What I meant is to find or build another tool. Gogs can't and won't do everything.
