### ISSUE TITLE
HTTPS and apache

### ISSUE THREAD

**Issue by tubia** [gogs/gogs#559]
Hi,
I'm trying to enable SSL support.

Following [this](http://gogs.io/docs/intro/faqs.html#how-to-setup-https%3F) in the FAQ, I added the path to my cert files but, due to permission problems, was unable to resolve in this way.  
Certs have root permissione and the gogs user isn't in the root group.  
Copying certs in the gogs directory is not a safe solution.  
Actually, I have gogs in a subdomain _git.example.org_, so I tried to use `./gogs cert -ca=true -duration=8760h0m0s -host=git.example.org` fixing the path in the app.ini properly.
gogs then starts properly but I'm unable to access _https://git.example.org_, I suppose it overlap with the https apache conf.
Here is how my apache configuration manage the normal http request for _git.example.org_

```
<VirtualHost *:80>
  ProxyVia On  
  ProxyRequests off
  ProxyPreserveHost On
   ServerName git.example.org
    <Location />
        ProxyPass http://example.org:3000/
        ProxyPassReverse http://example.org:3000/
        Order allow,deny
        Allow from all
   </Location>

</VirtualHost>
```

I need a possible solution to:
- get apache manage the https requests for gogs
- get gogs manage the https requests without the interference of apache for the subdomain _git.example.org_

P.s.: the apache config above could be added in the docs besides the nginx config, maybe. :)

**Comment by Sispheor** [comment]
Hi, I'm trying to configure apache as reverse proxy with SSL.

Here is the vhost
```
<VirtualHost *:443>
    ServerAlias sub.domain.com
    ServerName sub.domain.com
    SSLCertificateFile /path/to/cert.crt
    SSLCertificateKeyFile /path/to/cert.key
 
    SSLEngine On
    ProxyRequests off
    ProxyPreserveHost on
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>

    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```

And the gogs config
```
[server]
PROTOCOL               = http
DOMAIN                 = sub.domain.com
#ROOT_URL = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/
ROOT_URL               = https://sub.domain.com/
```

And I get a 503 unavailable.

What I'm doing wrong?

**Comment by emrahcom** [comment]
Hi Sispheor,

The same config works for me. 

I get 503, if apache run while gogs service is stopped.

Did you check gogs' status and port?
netstat -taunp | grep LISTEN | grep gogs
systemctl status gogs.service

**Comment by Sispheor** [comment]
Sorry I forgot to add something. This config is indeed functional. I was behind a proxy which it has is own DNS and was redirecting me on a wrong server.
Apologize for any inconvenience.
