### ISSUE TITLE
Error:  Fail to initialize ORM engine: migrate: do migrate: Error 1071: Specified key was too long; max key length is 767 bytes 

### ISSUE THREAD

**Issue by leninloganathan** [gogs/gogs#5591]
We haven’t face any issue with accessing gogs in my environment.
After we did restart the machine and gogs service is not started. When we checked the error, it shows below one 

CentOS Linux release 7.5.1804 (Core) 
gogs-0.11.34-1537459444.12680616.centos7.x86_64
mariadb-server-5.5.60-1.el7_5.x86_64

Error:
[FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: do migrate: Error 1071: Specified key was too long; max key length is 767 bytes 

Can you help me to fix this issue

**Comment by onigm** [comment]
I also encountered this problem when I use mysql5.6
Upgrade  mysql to 5.7
or
Add the following to my.cnf and restart mysql
innodb_file_format=BARRACUDA
innodb_large_prefix=1
innodb_file_per_table=1

**Comment by Unknwon** [comment]
Try to upgrade Gogs.

**Comment by tttlkkkl** [comment]
升级到Gogs 0.11.86.0130时同样遇到了这个问题
