### ISSUE TITLE
Closing issue through commits

### ISSUE THREAD

**Issue by cricri** [gogs/gogs#5593]
**Describe the bug**
Issues not closed through commits.
I dont know if something in my workflow is wrong. And congratulations for your work!

**To Reproduce**
create a git repository:
```bash
cd /tmp; rm -rf /tmp/x;
cd /tmp; mkdir x; cd x; git init;
echo 1 > a; g add a; g cm 'import'
```
do the migration in gogs:
visit http://localhost.gogs/repo/migrate and proceed with "clone address" /tmp/x

then adjust remote:
```bash
cd /tmp/x
g remote add origin /opt/gogs-repositories/christophe/x.git
```
Then create the first issue in gogs
and fix it in your code:
```bash
echo 1 >> a; g add a; g cm 'test (fix #1)'
g push -f origin master
```

**Expected behavior**
I expect the issue to be closed by gogs after the push

**Additional context**

- Gogs version (or commit ref): 0.11.79.1211
- Git version: 2.17.2
- Operating system: Fedora release 28
- Database (replace `[ ]` with `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: not allowed to import local repositories.

**Comment by zeandrade** [comment]
Hi, I use  "closes #NUM"  in the commit message and works fine.

**Comment by cricri** [comment]
Hi,
Thanks for your support (and your work).
Without importing, I can close the issue through commits.

**Comment by Unknwon** [comment]
Thanks for the update!

>Without importing, I can close the issue through commits.

In this case, I cannot consider this is a bug of Gogs because importing seems has nothing to do with smart commits.

**Comment by Unknwon** [comment]
I think I know what is going on here. The way you push, it directly goes into the Git raw data without delegation from Gogs, so the push is unaware to Gogs (more specifically, `gogs serv` not called as it would push via SSH/HTTP).
