### ISSUE TITLE
git clone https authentication failure

### ISSUE THREAD

**Issue by LukeMauldin** [gogs/gogs#5597]
**Describe the bug**
Gogs version 0.11.66.0916
Setup Gogs with a custom authentication source (LDAP server).  I can login to the Gogs web interface with the local "adminuser" I created and I can login to the web interface with the username and password of an LDAP user.  I have created a repository and I can clone via SSH using the key associated with my LDAP user username.  However, when I try to clone that repository using HTTPS and the LDAP username/password I receive access denied.  I can clone the repository via HTTPS using the local "adminiuser"

**Expected behavior**
Expect authorization for SSH and HTTPS to be applied consistently for LDAP users.

**Additional context**
- SSL termination for HTTPS is handled by HaProxy in front of Gogs
- Gogs version (or commit ref): 0.11.66.0916 - using docker container from docker hub
- Git version: 2.18
- Operating system: Verified on linux and Windows
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [ ] No: explain why
- Log gist (usually found in `log/gogs.log`):
```
[Macaron] 2019-01-18 21:58:54: Started GET /docs/workstations.git/info/refs?service=git-upload-pack for XXX.XXX.XXX.XXX
[Macaron] 2019-01-18 21:58:54: Completed GET /docs/workstations.git/info/refs?service=git-upload-pack 401 Unauthorized in 421.934358ms
```

app.ini
```
APP_NAME = Gogs

RUN_USER = git

RUN_MODE = prod

 

[database]

DB_TYPE = mssql

HOST = XXX

NAME = Gogs

USER = gogs

PASSWD = XXX

SSL_MODE = disable

 

[repository]

ROOT = /data/gitrepos

 

[server]

DOMAIN           = XXX

HTTP_PORT        = 3000

ROOT_URL         = XXX

DISABLE_SSH      = false

SSH_DOMAIN       = XXX

SSH_PORT         = 22

START_SSH_SERVER = false

OFFLINE_MODE     = true

PROTOCOL = http

 

[mailer]

ENABLED = false

 

[service]

REGISTER_EMAIL_CONFIRM = false

ENABLE_NOTIFY_MAIL     = false

DISABLE_REGISTRATION   = false

ENABLE_CAPTCHA         = false

REQUIRE_SIGNIN_VIEW    = true

 

[picture]

DISABLE_GRAVATAR        = true

ENABLE_FEDERATED_AVATAR = false

 

[session]

PROVIDER = file

 

[log]

MODE      = file

LEVEL     = Info

ROOT_PATH = /data/logs

 

[security]

INSTALL_LOCK = true

SECRET_KEY   = XXX
```

**Comment by LukeMauldin** [comment]
It was an error with my LDAP account being locked.

**Comment by sanger89** [comment]
I have the same questions. And i trying in the https://try.gogs.io , it isn't work, So I think gogs don't support clone the HTTPS objects.
