### ISSUE TITLE
client Sending env LANG but SSH on Windows not support

### ISSUE THREAD

**Issue by sinlov** [gogs/gogs#5604]
- Gogs version (0.11.79.1211): 
- Git version: client 2.20.1
- Operating system: Remote win10(10.0.17134.523)
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: https://github.com/gogs/gogs/issues/4591
  - [ ] No:
- Log gist (usually found in `log/gogs.log`):

```log
2019/01/28 10:49:19 [ERROR] [.../runtime/asm_amd64.s:2361 goexit()] env: exec: "env": executable file not found in %PATH%
2019/01/28 10:50:43 [ERROR] [.../runtime/asm_amd64.s:2361 goexit()] env: exec: "env": executable file not found in %PATH%
2019/01/28 10:50:51 [ERROR] [.../runtime/asm_amd64.s:2361 goexit()] env: exec: "env": executable file not found in %PATH%
2019/01/28 10:52:13 [ERROR] [.../runtime/asm_amd64.s:2361 goexit()] env: exec: "env": executable file not found in %PATH%
2019/01/28 10:52:53 [ERROR] [.../runtime/asm_amd64.s:2361 goexit()] env: exec: "env": executable file not found in %PATH%
2019/01/28 11:09:35 [ERROR] [.../runtime/asm_amd64.s:2361 goexit()] env: exec: "env": executable file not found in %PATH%
```

Here is my ssh verification from macOS client

```sh
$ ssh -vT 192.168.2.3
OpenSSH_7.8p1, LibreSSL 2.6.2
debug1: Reading configuration data [HOME].ssh/config
debug1: [HOME].ssh/config line 77: Applying options for 192.168.2.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to 192.68.2.3 [192.68.2.3] port 10022.
debug1: Connection established.
debug1: identity file [HOME].ssh/[hide-key] type 0
debug1: identity file [HOME].ssh/[hide-key]-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.8
debug1: Remote protocol version 2.0, remote software version Go
debug1: no match: Go
debug1: Authenticating to 192.68.2.3:10022 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:F5Bp1ycXNjPmTTZyaPugzzzkIxJJXAuVAf6o7EAUyas
debug1: Host '[192.68.2.3]:10022' is known and matches the RSA host key.
debug1: Found key in [HOME].ssh/known_hosts:51
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:[hide info] [HOME].ssh/[hide-key]
debug1: Server accepts key: pkalg ssh-rsa blen 151
debug1: Authentication succeeded (publickey).
Authenticated to 192.68.2.3 ([192.68.2.3]:10022).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending env LC_CTYPE = zh_CN.UTF-8
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2392, received 1464 bytes, in 0.2 seconds
Bytes per second: sent 11620.5, received 7112.2
debug1: Exit status -1
```

- solution this can change client `/etc/ssh/ssh_config`

```
# comment or delete
SendEnv LANG LC_*
```

but this configuration will affect another git server connect

`I want change the configuration of the remote in gogs-windows with inner ssh server`

like `/etc/ssh/sshd_config` on the linux remote machine

```
AcceptEnv LANG LC_*
```

**Comment by Unknwon** [comment]
Hi, if you have git-bash (Git for Windows) correctly installed, there should be no problem. Have you installed it?

Which SSH server are you using?

**Comment by sinlov** [comment]
@Unknwon 
-----
SSH server use gogs inner
SSH Configuration
- Enabled `true`
- Start Builtin Server `true`
------
git client

version 2.20.1 at macOS, which use most of time
also, windows git-bash client error

git-bash info
- download at https://git-scm.com/downloads
- version `2.17.1.2`, also download at [git release tag v2.17.1.windows.2](https://github.com/git-for-windows/git/releases/tag/v2.17.1.windows.2)

**Comment by Unknwon** [comment]
Hi, by "git-bash", I mean the git-bash installed on the server side (where you run your Gogs application).

**Comment by sinlov** [comment]
so set git-bash server `AcceptEnv LANG LC_*`

Thanks!

**Comment by HugoRh** [comment]
Hi,

I wonder how you managed to set this parameter in git-bash?
In my case, modifying /etc/ssh/sshd_config in my git-bash install did not change anything..
I agree with @sinlov that we shouldn't modify /etc/ssh/ssh_config on client side ( and this file belong to root, it's impossible to modify for most users.

As a workaround, i did unset the LANG env variable from the client side and it works fine.

`
$ git clone user@some.server.domain:repo/test-mirror.git
Cloning into 'test-mirror'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ unset LANG
$ git clone user@some.server.domain:repo/test-mirror.git
Cloning into 'test-mirror'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3/3), done.
`
