### ISSUE TITLE
Reporting Security Issues?

### ISSUE THREAD

**Issue by Dor-Tumarkin** [gogs/gogs#5611]
Hi,
There is currently no e-mail address or form to send any security related issues to.
Can you please provide a means for a timely disclosure?
Thanks.

**Comment by Unknwon** [comment]
Hi, if you have read README, you'll find the email very easily.

![image](https://user-images.githubusercontent.com/2946214/52244751-f9168780-28ac-11e9-8352-4371f078ae51.png)
