### ISSUE TITLE
Personal access token last used timestamp isn't updated

### ISSUE THREAD

**Issue by imcdona** [gogs/gogs#5615]
**Describe the bug**
Using your personal access token to clone a repo e.g. `git clone https://{token}@try.gogs.io/user/repo.git` doesn't update the tokens last used timestamp.

**To Reproduce**
1. Go to 'Your Settings'
2. Click on 'Applications'
3. Click on 'Generate New Token'
4. Enter a token name and then click 'Generate Token'
5. Use the generated token to clone a private repo e.g.  `git clone https://{token}@try.gogs.io/user/repo.git`
6. Navigate to 'Your settings --> Applications'
7. Note that the token you used to clone the git repo doesn't show as ever being used.

**Expected behavior**
Any use of the token should be reflected in the tokens last used timestamp.

**Additional context**
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes
  - [ ] No: explain why

**Comment by evalsocket** [comment]
@unknwon Would like to work on this. Can this be assigned to me.

**Comment by unknwon** [comment]
@evalsocket Yes, please go ahead!

**Comment by unknwon** [comment]
I believe this is now resolved in `master`.
