### ISSUE TITLE
Why my docker gogs always pause by itself?

### ISSUE THREAD

**Issue by woshiamiaojiang** [gogs/gogs#5632]
Hi, there. 

I try to install Docker gogs in my Azure CentOS 7.5 version.

I follow these procedures:

docker pull gogs/gogs

docker run -di ‐‐name=gogs ‐p 10022:22 ‐p 3000:3000 ‐v /var/gogsdata:/data gogs/gogs

And it will be up for several minutes. And soon it will be paused by itself. I can't figure out why. I would appreciate a lot if you could give me some hints.

**Comment by woshiamiaojiang** [comment]
![image](https://user-images.githubusercontent.com/12020661/53235052-e1703900-36cb-11e9-8264-916274f89b21.png)

**Comment by woshiamiaojiang** [comment]
![image](https://user-images.githubusercontent.com/12020661/53235095-fcdb4400-36cb-11e9-9453-0c3fafb8fccf.png)

**Comment by woshiamiaojiang** [comment]
![image](https://user-images.githubusercontent.com/12020661/53235164-26946b00-36cc-11e9-9c94-24e90c2c31b9.png)

**Comment by Unknwon** [comment]
Please be respectful to the issue template.

Ask your server provider.
