### ISSUE TITLE
Error 500 when trying to create a Repo or Organization

### ISSUE THREAD

**Issue by valentinAlkan** [gogs/gogs#5635]
**Describe the bug**
Trying to create a new repo or organization produces error code 500. 

Create Repo error text: 
An error has occurred : initRepository: InitRepository: chdir /usr/home/git/gogs-repositories/username/dfg.git: no such file or directory

Application Version: 0.11.86.0130

Create Organization error text:
An error has occurred : create directory: mkdir /usr/home/git/gogs-repositories/test: read-only file system

Application Version: 0.11.86.0130

File system is not mounted read only, git user (where gogs is installed) has full read/write access and can create files and folders from a terminal in the gogs-repositories directory without any issue. However, doing so produces a 'file or folder already exists error' if you try to manually create the organization/repo from a terminal and then again in the web interface.

**To Reproduce**
1. Go to 'Create Repository' or 'Create Organization'
2. Give name
3. Click on 'Create repository/organization'

**Expected behavior**
Repo and organization creation

- Gogs version: 0.11.86.0130
- Git version: 
    2.11.0
- Operating system: raspi2_armv6
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: works as normal
- Log gist (usually found in `log/gogs.log`):

```
2019/02/24 21:45:24 [ERROR] [.../routes/repo/repo.go:103 handleCreateError()] CreatePost: initRepository: InitRepository: chdir /usr/home/git/gogs-repositories/username/test.git: no such file or directory
2019/02/24 21:53:22 [ERROR] [.../routes/repo/repo.go:103 handleCreateError()] CreatePost: initRepository: InitRepository: chdir /usr/home/git/gogs-repositories/username/test.git: no such file or directory
2019/02/24 22:09:57 [ WARN] Fail to health check repository '/usr/home/git/gogs-repositories/someproject/someproject.git': execution is timeout [duration: 1m0s]
2019/02/24 22:12:33 [ WARN] Fail to health check repository '/usr/home/git/gogs-repositories/projects/anotherproject.git': execution is timeout [duration: 1m0s]
```

**Comment by Unknwon** [comment]
Hi, I think the way you mount did not give Gogs permission to create anything.

**Comment by valentinAlkan** [comment]
Sorry just saw this. I dont understand how that's possible, it used to work fine. It's been running for months, and git user (where gogs is installed and run from) still has write access. It just stopped working all of a sudden, without even having been restarted. 

![image](https://user-images.githubusercontent.com/19651331/53610176-06671f00-3b98-11e9-8672-b87a624f56fe.png)

![image](https://user-images.githubusercontent.com/19651331/53610113-be47fc80-3b97-11e9-9312-943890a3fa50.png)

**Comment by Unknwon** [comment]
>It just stopped working all of a sudden, without even having been restarted.

Maybe that is the problem, try restart?

**Comment by valentinAlkan** [comment]
I tried that many times. No change.

**Comment by Unknwon** [comment]
Try not using mount directory?

**Comment by valentinAlkan** [comment]
sorry I dont understand what you mean. Do you mean change the directories I'm using?

**Comment by Unknwon** [comment]
Yes, to make sure it is a problem of mount.

**Comment by valentinAlkan** [comment]
ok that worked. I will move my default directory.

thanks for the suggestion. I dont understand how or why this works (seems like it should be able to write to any directory that the git user has write access to), but a fix is a fix.

**Comment by Unknwon** [comment]
I remember someone had similar problem and found a special mount flag must be applied but I couldn’t find right now.

**Comment by valentinAlkan** [comment]
No worries. Thank you for your help, sorry I didn't reply sooner. I had my gogs-repositories folder mounted under /usr/home/git for some reason, I thought it was the default but I looked at the installation procedure and dint' see that directory mentioned, so I'm not sure how I arrived on that. I moved it under /home/git and that's where it should be anyway in my opinion.
