### ISSUE TITLE
consider adding 'able to create webhooks' permission please

### ISSUE THREAD

**Issue by sokoow** [gogs/gogs#5637]
**Is your feature request related to a problem? Please describe.**
It might be related to https://github.com/gogs/gogs/issues/4734

Consider following scenario:

1. I have a non-administrator user, let's call him demo-user
2. There's a repo that I want to add this user to as a collaborator, with write access
3. That demo-user is becoming a collaborator, but when he's trying to create a webhook for CI for that repo, it fails with 403. 

What's the problem here ? Lack of self service for CI currently in gogs, cause admins need to create webhooks. 

**Describe the solution you'd like**
It might make sense to add 3rd level of perms that might be "Write and webhooks" that would be allowing not only to write to git, but also create webhooks. 

**Describe alternatives you've considered**
Can you think of any ?

**Comment by Unknwon** [comment]
Thanks your feedback!

But add new webhook is not a frequent thing, and I think it is part of "administration" section, then why not only allow admin to create/edit/delete webhooks?

**Comment by sokoow** [comment]
I agree it's not a frequent thing, but if you wanted to make your CI self-service, it's essential. Right now, when using gogs, developer that had non-admin write access to repo can't turn on CI himself, he needs to ask gogs site admin to do so, and it's a single point of failure on these people. 

One more thing is that I don't see webhook creation/deletion registered in logs - is there such option ?

**Comment by Unknwon** [comment]
He does not need to ask Gogs site admin, just repository admin.

**Comment by sokoow** [comment]
Ah, so this is just a case for shared repos then. But still there can be only one repository admin right? There's no way to make additional account repository admins ?

**Comment by Unknwon** [comment]
Set as admin level collaborator.

**Comment by sokoow** [comment]
Ok, this makes sense now. Xie xie :)
