### ISSUE TITLE
Can not Login out !

### ISSUE THREAD

**Issue by jianboy** [gogs/gogs#5642]
**Describe the bug**
Browser : chrome
gogs version : 0.11.86

I cannot login out success . you can see the gif blow:

![9](https://user-images.githubusercontent.com/11532015/53595740-00ddf900-3bd9-11e9-9ee2-5e2105f663e4.gif)

I had try many time , then I sometime can logout .

I find the code is error:
![image](https://user-images.githubusercontent.com/11532015/53595855-50242980-3bd9-11e9-8552-087e37fb782a.png)

```
								<form id="logout-form" class="item" action="{{AppSubURL}}/user/logout" method="POST">
													{{.CSRFTokenHTML}}
													<div class="submit-button" data-form="#logout-form">
														<i class="octicon octicon-sign-out"></i> {{.i18n.Tr "sign_out"}}
													</div>
												</form>
```

**Comment by Unknwon** [comment]
Thanks for the feedback!

Please be respectful to the issue template.
