### ISSUE TITLE
Possible for running Gogs as a repository proxy?

### ISSUE THREAD

**Issue by BioEvo** [gogs/gogs#5644]
**Describe the solution you'd like**
Run gogs as a proxy of upstream repository(just like github、gitbutcket). Every collaboration of gogs can push codes to proxy repository, but only owner of proxy repository can push codes or create PR to upstream repository.

**Describe alternatives you've considered**
Gogs supports mirror repository, but mirror repository is read only. Proxy repository could be treated as a update of mirror repository.

**Additional context**
A proxy repository can have a origin branch and a local master branch. Origin branch could be fetch automatically in resonable interval.

**Comment by Unknwon** [comment]
Hi, thanks for the feedback!

But I think it is not something Gogs would do (unless you hack it until it works).
