### ISSUE TITLE
Deprecation Notice OpenSSH

### ISSUE THREAD

**Issue by mvrahden** [gogs/gogs#5647]
**Describe the bug**
Starting the docker container gives me the following output on my console:
```[bash]
/app/gogs/docker/sshd_config line 14: Deprecated option UsePrivilegeSeparation
```

**To Reproduce**
1. Run docker image in attached (without `-d` flag) mode
(Empty Volume mounted in my case. So clean default configuration.)
2. Observe console output

**Expected behavior**
Didn't expect that Deprecation Warning.

**Additional context**
After searching a bit, I found that this Option has been effectively deprecated with OpenSSH Version 7.5.
Statement in OpenSSH Release Note:
```
This release includes a number of changes that may affect existing
configurations:

 * This release deprecates the sshd_config UsePrivilegeSeparation
   option, thereby making privilege separation mandatory. Privilege
   separation has been on by default for almost 15 years and
   sandboxing has been on by default for almost the last five.
```
For further detail see: [OpenSSH Release Note v.7.5](https://www.openssh.com/txt/release-7.5)

- Gogs version (or commit ref): `v0.11.86`
- Gogs Docker Hub image
- Operating system: Ubuntu Bionic, amd64 Architecture (Host System)

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #5650, please help test on `develop` branch.

**Comment by mvrahden** [comment]
@Unknwon I think this can be closed. The pull request was initiated by me. I haven't tried to clone and build. But I only removed one line as the OpenSSH spec suggests. So I'm pretty confident, that this works out well :)
It's a micro-fix after all...
So herewith I'm closing this issue.
Thanks for your support and thanks for maintaining this amazing project 🥇 💯

**Comment by mvrahden** [comment]
closing
