### ISSUE TITLE
Restore backup fails when running from partition other than system's

### ISSUE THREAD

**Issue by jpincho** [gogs/gogs#5655]
- Gogs version (or commit ref): 0.11.79.1211
- Git version: 2.11.0
- Operating system: debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: hardware configuration dependent
- Log gist (usually found in `log/gogs.log`):

I have gogs v0.11.79.1211, running on a raspberry pi. 
For performance reasons, /home is mounted from an external hard drive, gogs is running as user git, and git's home is at /home/git.
While running a restore operation, I am faced with this error:

~/gogs $ ./gogs restore --from ../gogs-backup-20190321020003.zip 
2019/03/21 14:38:49 [ INFO] Restore backup from: ../gogs-backup-20190321020003.zip
2019/03/21 14:40:28 [FATAL] Failed to import 'custom': rename /tmp/gogs-backup/custom /home/git/gogs/custom: invalid cross-device link

It appears it attempts to move the folder from /tmp to the final destination which, unfortunately is on another partition, and as such, fails.

**Comment by jpincho** [comment]
EDIT: Can be solved using the --temp option for setting a restore temporary path on the same partitioncd ..

**Comment by Unknwon** [comment]
Thanks for the feedback!

I think this is same root case (thus same fix procedure) as https://github.com/gogs/gogs/issues/4339.
