### ISSUE TITLE
Web interface doesn't start in last docker image

### ISSUE THREAD

**Issue by dorianboulch** [gogs/gogs#5662]
**Describe the bug**
After upgrading docker image (as described in the doc), the web interface doesn't start at container booting.
If I enter the container and I execute `./gogs web`, it works.

**Additional context**

- Gogs version (or commit ref): 0.11.88.0220
- Operating system: Docker
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite

**Comment by linquize** [comment]
Can you post log message to here?

**Comment by dorianboulch** [comment]
There is nothing revelant in logs...
```
usermod: no changes
Mar 30 11:54:39 syslogd started: BusyBox v1.29.3
Mar 30 11:54:39 sshd[27]: Server listening on :: port 22.
Mar 30 11:54:39 sshd[27]: Server listening on 0.0.0.0 port 22.
```
And then there is the connection log from git clients, nothing else.

**Comment by dorianboulch** [comment]
@linquize any idea about where the issue comes from ?

**Comment by Unknwon** [comment]
Try connect to your container and find Gogs logs, there should have some error logs. (I think it is located at `/app/gogs/logs`)

**Comment by linquize** [comment]
```bash
docker exec gogs-container /bin/bash
ls /app/gogs/logs
```
Then `cat` the log files
