### ISSUE TITLE
LDAP issue: impossible to log in twice in 0.11.86.0130

### ISSUE THREAD

**Issue by HugoRh** [gogs/gogs#5663]
**Describe the bug**
After 1st successful login / creation of Active directory user, all is working fine.
But when, this user have logged out, and try to login again it fails with a 500 error page

**To Reproduce**
1. login/create with Active directory user
2. logout
3. try login again

**Expected behavior**
Being able to login again after 1st login.

**Screenshots**

**Additional context**

- Gogs version (or commit ref):  0.11.86.0130
- Git version: 2.21.0.windows.1
- Operating system: Windows 2012 server
- Database :
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [X] No: Can't plug my domain to internet :)
- Log gist (usually found in `log/gogs.log`):
```
2019/04/02 00:48:06 [TRACE] LDAP will use BindDN
2019/04/02 00:48:06 [TRACE] Search for LDAP user: user@place.org
2019/04/02 00:48:06 [TRACE] LDAP: Bound as BindDN: CN=USER,OU=Service Accounts,OU=Admins,DC=place,DC=org
2019/04/02 00:48:06 [TRACE] LDAP: Searching for DN using filter '(&(objectClass=person)(objectClass=user)(userPrincipalName=user@place.org))' and base 'DC=org'
2019/04/02 00:48:07 [TRACE] Binding with userDN: CN=Surname\, Given_name,OU=Departments,OU=Users,DC=place,DC=org
2019/04/02 00:48:07 [TRACE] Bound successfully with userDN: CN=Surname\, Given_name,OU=Departments,OU=Users,DC=place,DC=org
2019/04/02 00:48:07 [TRACE] Fetching attributes 'sAMAccountName', 'givenName', 'sn', 'mail', '' with filter '(&(objectClass=person)(objectClass=user)(userPrincipalName=user@place.org))' and base 'CN=Surname\, Given_name,OU=Departments,OU=Users,DC=place,DC=org'
2019/04/02 00:48:07 [ERROR] [...g/context/context.go:191 ServerError()] UserLogin: e-mail has been used [email: valid.email@correct-name.com]
```

**Comment by Unknwon** [comment]
I think because the `mail` attribute fetched from active directory is always the same ("valid.email@correct-name.com"). It should be unique for each user.
