### ISSUE TITLE
local git push cause remote error with a old repo

### ISSUE THREAD

**Issue by kinfen** [gogs/gogs#5666]
**Describe the bug**
I create the repos a month ago, now I can pull repo successly but occur error when i push commit, local git will show me follow message:
![image](https://user-images.githubusercontent.com/3425337/55549366-390cb600-5708-11e9-9b44-9cb121e16ef7.png)
sourcetree show me like this:
![image](https://user-images.githubusercontent.com/3425337/55549459-7d985180-5708-11e9-8e6e-5b104f6a81e4.png)

gogs start currect with the config file:
![image](https://user-images.githubusercontent.com/3425337/55549612-d7008080-5708-11e9-81da-9ee036681125.png)

gogs.log
![image](https://user-images.githubusercontent.com/3425337/55549663-f8fa0300-5708-11e9-92d4-e897a4b6829c.png)

I can do all success if I create a new repo, but never success with the old repo now.
I build gogs with docker image base alpine, volume /home/gogs/go/custom

**Additional context**

- Gogs version (or commit ref): 0.11.88.0220
- Git version: 2.18.1
- Operating system: alpine 3.8
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: explain why
- Log gist (usually found in `log/gogs.log`):

**Comment by Unknwon** [comment]
Try these two things in admin panel:

![image](https://user-images.githubusercontent.com/2946214/55798048-f8ac8f80-5a9b-11e9-907f-02a1d5c426bd.png)
