### ISSUE TITLE
css regression at japanese font

### ISSUE THREAD

**Issue by paichi81** [gogs/gogs#5667]
**Describe the bug**
regression CSS (PR  #2816 , #3266)

**To Reproduce**
Adding japanese Font. already added this PR #2816, #3266
but, currently removed.

**Additional context**
- Gogs version (or commit ref):  fd3b9ca3aa4fe5cdb5b4cf08b663c28fb731112f

**Comment by Unknwon** [comment]
Hi, I think the font was removed because it breaks rendering under some Linux systems (there is an issue about this but it was very old I couldn't reall)

**Comment by paichi81** [comment]
You were right.
It was Windows only and did not consider Linux, Mac and other.
I think what to do.
