### ISSUE TITLE
Why did I use SSH to clone code before? The next day when I used SSH to clone code, there was an error.

### ISSUE THREAD

**Issue by pengqiangsheng** [gogs/gogs#5669]
1. I use gogs installed by docker.
2 .In the installation interface, I turned on SSH mode cloning code.
3. At first, I could use SSH to clone code, or submit changes and push code through ssh.
4. But the next day, for some reason, it was impossible to clone the code by ssh.
5 .The error message is as follows:
***
 $ git clone ssh://git@47.100.35.33:8087/web/webApp.git
Cloning into 'webApp'...
ssh: connect to host 47.100.35.33 port 8087: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
****
I'll publish the docker gogs information about the server configuration later.

**Comment by Unknwon** [comment]
Please be respectful to the issue template.
