### ISSUE TITLE
Wrong custom app.ini path when pushing a commit

### ISSUE THREAD

**Issue by nfam** [gogs/gogs#5670]
**Describe the bug**
I had working gogs on macOS, then I moved the `app.ini` to another location (in order to share gogs binary between Macs), with all path in `app.ini` being corrected (including those from the `embedded app.ini`, see **To Reproduce step 4**. Gogs can start and I can view repos, but when I attempted to push a modified repo, gogs tried to read the old and default config `custom/conf/app.ini` at gogs binary directory which did not exist anymore.

**To Reproduce**
1. Having a working gogs on macOS at `/Volumes/data/macos/gogs` (**binary directory**), with at least one repo, using PostgreSQL (or any other than the default MySQL)
2. Clone the active repo via SSH.
3. Stop gogs, move `custom/conf/app.ini`, `data`, and `log` directories to `/Volumes/data/appdata/gogs` (**data directory**). 
4. Modify `app.ini` to point to the new location
```conf
APP_NAME = Gogs
RUN_USER = ninh
RUN_MODE = prod

[database]
DB_TYPE  = postgres
HOST     = 127.0.0.1:5432
NAME     = gogs
USER     = dogs
PASSWD   = gogs
SSL_MODE = disable

[repository]
ROOT = /Volumes/code/gogs

[server]
DOMAIN           = gogs.test
HTTP_ADDR        = 127.0.0.1
HTTP_PORT        = 13000
ROOT_URL         = http://gogs.test/
DISABLE_SSH      = false
SSH_LISTEN_HOST  = 0.0.0.0
SSH_PORT         = 22
START_SSH_SERVER = true
OFFLINE_MODE     = true
APP_DATA_PATH    = /Volumes/data/appdata/gogs/data

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = true
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR              = true
ENABLE_FEDERATED_AVATAR       = false
AVATAR_UPLOAD_PATH            = /Volumes/data/appdata/gogs/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /Volumes/data/appdata/gogs/data/repo-avatars

[attachment]
PATH = /Volumes/data/appdata/gogs/data/attachments

[release.attachment]
PATH = /Volumes/data/appdata/gogs/data/attachments

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /Volumes/data/appdata/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = 6mCljAKkZxe9pOb
```
5. Start gogs with `gogs web -c /Volumes/data/appdata/gogs/custom/conf/app.ini`.
6. Go to gogs web, confirm seeing all repos.
6. Modify the cloned repo, then commit and push.
7. See failed error with the message
```log
Pushing to ninh@gogs.test:setup/localdev.git
remote: 2019/04/06 17:46:26 [ WARN] Custom config '/Volumes/data/macos/gogs/custom/conf/app.ini' not found, ignore this if you're running first time        
remote: Gogs: Internal error        
remote: GetProtectBranchOfRepoByName [repo_id: 1, branch: master]: dial tcp 127.0.0.1:3306: connect: connection refused        
To gogs.test:setup/localdev.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ninh@gogs.test:setup/localdev.git'
```

**Expected behavior**
Expect Gogs to read the correct config path provided by the arg `--config`

**Screenshots**
See `To Reproduce step 8`.

**Additional context**

- Gogs version (or commit ref): 0.11.86.0130
- Git version: 2.20.1 (Apple Git-117)
- Operating system: macOS Mojave 10.14.4
- Database:
  - [x] PostgreSQL
- Can you reproduce the bug at https://try.gogs.io:
  - [x] No: It is a config problem.
- Log gist (at `/Volumes/data/appdata/gogs/log/gogs.log`):
```log
2019/04/06 17:07:49 [ INFO] Gogs 0.11.86.0130
2019/04/06 17:07:49 [ INFO] Cache Service Enabled
2019/04/06 17:07:49 [ INFO] Session Service Enabled
2019/04/06 17:07:49 [ INFO] Git Version: 2.20.1
2019/04/06 17:07:49 [ INFO] SQLite3 Supported
2019/04/06 17:07:49 [ INFO] Run Mode: Production
2019/04/06 17:07:49 [ INFO] SSH server started on 0.0.0.0:22
2019/04/06 17:07:49 [ INFO] Listen: http://127.0.0.1:13000
```

**Further information**
To verify that gogs read correct path when starting, I deleted `log`, and `ssh` directories at `/Volumes/data/appdata/gogs`. After restart gogs, I see `log` and `ssh` generated again at the expected location. But when I pushed commit, I see another log at `/Volumes/data/macos/gogs` where the gogs binary is located. I think that is the result when gogs tried to read `custom/conf/app.ini` at the gogs binary directory, which did not exist, then assumed the default value.

**Comment by Unknwon** [comment]
I think it is because you didn't run these two things in the admin panel:

![image](https://user-images.githubusercontent.com/2946214/55797639-fac21e80-5a9a-11e9-90d1-c2a51c5bbe77.png)

SSH delegation and Git hooks are still seeing the previous custom config path.

**Comment by nfam** [comment]
Resync pre-receive, update and post-receive hooks fix the issue. Thank you.
