### ISSUE TITLE
Copyright is behind the times

### ISSUE THREAD

**Issue by lukeawyatt** [gogs/gogs#5674]
**Describe the bug**
The footer copyright year is still coded for 2018.  Lets put this to an end along with Fortnite dancing in real life.  Maybe change the markup to grab the value from the server time instead to save effort in future years to come?

**Additional context**

None needed

**Comment by unknwon** [comment]
Forget to update, it is now corrected. Thanks!

**Comment by chshouyu** [comment]
I think this can be done automatically by some `get current year` method in template

**Comment by unknwon** [comment]
@chshouyu that's how it is done currently:

https://github.com/gogs/gogs/blob/c154721f4a8f3e24d2f6fb61e74b4b64529255c2/templates/base/footer.tmpl#L10
