### ISSUE TITLE
Closing/Opening milestone causes 404

### ISSUE THREAD

**Issue by philjohnstone** [gogs/gogs#5677]
**Describe the bug**
When closing or opening an issue milestone, the 302 redirection uses `milestones%3Fstate=closed` and `milestones%3Fstate=open` instead of `milestones?state=closed` and `milestones?state=open`. The milestone is correctly opened or closed though.

**To Reproduce**
1. Go to 'A repository'
1. Click on 'Issues'
1. Click on 'Milestones'
1. Click on 'New Milestone'
1. Set the title and click on 'Create Milestone'
1. Scroll down to 'the new milestone'
1. Click 'Close'
1. Error 404 is displayed

**Expected behavior**
When a milestone is closed or opened, the redirection to the closed or opened milestone page should display the filtered milestones

**Additional context**

- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: provide example URL https://try.gogs.io/pj6/test/milestones
  - [ ] No: explain why
- Log gist (usually found in `log/gogs.log`):

Issue experienced in Chrome 70.0.3538.77 and Firefox 66.0.2

**Comment by philjohnstone** [comment]
Issue not present in 0.11.34.1122

**Comment by unknwon** [comment]
This is claimed to be fixed by merging #5903, please help test on `master` branch. I'm on a laptop that does not have SSH access to https://try.gogs.io's server, so will update that later.

**Comment by philjohnstone** [comment]
Sorry for the late reply. Yes, it's working fine now on try.gogs.io. Thanks for fixing!

**Comment by jeffersondesmond** [comment]
please I'm trying to login but forgot my password and resting is creating
problems too.

I need to help me unsubscribe.
