### ISSUE TITLE
Gogs loses network binding when network is lost.

### ISSUE THREAD

**Issue by tschallacka** [gogs/gogs#5683]
**Describe the bug**
We had a power failure in our server room due a PSU blowing up, this caused our switches to go offline and internet/network connectivity to be lost.
When power was restored and the network ran again, gogs didn't pick up on the signal that there was a network assigned again and lost it's port binding. I had to `sudo service gogs restart` to get it working again.

**To Reproduce**
Have gogs running.
Turn off your router
Turn on your router
try to pull from repo

    git pull origin master
    fatal: unable to access 'http://repo.domain.com:6000/tschallacka/csstemplates.git/': Failed to connect to repo.domain.com port 6000: Connection refused

**Expected behavior**
When network connectivity is lost and then regain, gogs should rebind itself to it's ports.

**Additional context**

- Gogs version (or commit ref):  0.11.86.0130
- Git version:  2.7.4
- Operating system: Ubuntu 16.04.6 LTS
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: explain why: Private company repo.
- Log gist (usually found in `log/gogs.log`): https://gist.github.com/tschallacka/137a23b3c90691ed7cb8859c10e84b09

**Comment by longnguyen2306** [comment]
`Fail to initialize ORM engine: migrate: sync: dial tcp [::1]:3306: getsockopt: connection refused `

Any chance that your database runs on a container?

**Comment by tschallacka** [comment]
The username and password for the database were correct, the database was up and running(I was in the php my admin just before finding out my gogs didn't run)

The only thing needed to resolve this was to restart gogs. I didn't need to restart the database server or anything else.

**Comment by jjhoo** [comment]
> **Describe the bug**
> We had a power failure in our server room due a PSU blowing up, this caused our switches to go offline and internet/network connectivity to be lost.
> When power was restored and the network ran again, gogs didn't pick up on the signal that there was a network assigned again and lost it's port binding. I had to `sudo service gogs restart` to get it working again.
> 
Could you be more specific about that signal i.e. where it is coming from and how you have determined that gogs has lost it's port binding?

Does the IP address stay the same when network connection is lost for some period of time and comes back? This should not matter unless gogs binds to specific IP address.
