### ISSUE TITLE
wrong git command line with git protocole

### ISSUE THREAD

**Issue by Ericounet** [gogs/gogs#5690]
First of all, read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html.

If you don't want to read, it's up to you. But don't waste your time continue reporting.

The issue will be closed without any explanation if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [中文](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please do not end your title with a question mark or period.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [ ] No: explain why
- Log gist (usually found in `log/gogs.log`):

**Comment by Ericounet** [comment]
After creating a repository, a summary of the command lines is given for the https protocole and for the git protocole: the line with the git protocole is wrong.

architecture: I have a git repository on /home/git/Repos/user-name/project.git

When I created the project, the name was: Project  with a caps P

problem:
* the git line gives me a line with the caps P but the created project is all in small caps -> project
* the line missed the Repos part.

Real example: here is the line for the https protocol:
* git remote add origin https://git.yojik.eu/eric/Chinese-Chine-nouvelle.git
Here is the line with the git protocol:
* git remote add origin git@yojik.eu:eric/Chinese-Chine-nouvelle.git

The https line works perfectly but the git did not:
the correct one is:

git remote add origin git@yojik.eu:Repos/eric/chinese-chine-nouvelle.git

thanks for your work!

**Comment by Unknwon** [comment]
Hi, the clone URL should never include path like "Repos", if you have to, then the SSH setup is messed up. See https://discuss.gogs.io/t/how-to-config-ssh-settings/34
