### ISSUE TITLE
Random crash when push the code

### ISSUE THREAD

**Issue by aegsea** [gogs/gogs#5691]
**Describe the bug**
Random crash when I push the code

**Additional context**

- Gogs version (or commit ref):  0.11.86.0130
- Git version: Go1.10.2
- Operating system: Linux iZdm8wm7ize9bbZ 4.4.0-63-generic #84~14.04.2-Ubuntu SMP Mon Feb 13 11:04:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x ] No: explain why
- Log gist (usually found in `log/gogs.log`):
	[Macaron] 2019-04-22 12:08:49: Completed POST /my_test/my_test/pulls/10/merge 302 Found in 615.817652ms
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc050c6]

	goroutine 1465967 [running]:
	github.com/gogs/gogs/models.(*Repository).getOwner(0x0, 0x11de8e0, 0xc4201ad930, 0x100000000000036, 0x0)
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:399 +0x26
	github.com/gogs/gogs/models.(*Repository).mustOwner(0x0, 0x11de8e0, 0xc4201ad930, 0x0)
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:412 +0x43
	github.com/gogs/gogs/models.(*Repository).repoPath(0x0, 0x11de8e0, 0xc4201ad930, 0x2, 0x2)
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:532 +0x43
	github.com/gogs/gogs/models.(*Repository).RepoPath(0x0, 0x44, 0xc42249fce0)
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/repo.go:536 +0x43
	github.com/gogs/gogs/models.(*PullRequest).PushToBaseRepo(0xc420213960, 0x0, 0x0)
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:639 +0x117
	github.com/gogs/gogs/models.addHeadRepoTasks(0xc42211c6a0, 0x1, 0x2)
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:721 +0x143
	github.com/gogs/gogs/models.AddTestPullRequestTask(0xc420853600, 0x29, 0xc4245b00b0, 0x7, 0xc42226c300)
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:766 +0x587
	created by github.com/gogs/gogs/models.(*PullRequest).Merge.func1
			/home/vagrant/gopath/src/github.com/gogs/gogs/models/pull.go:199 +0xc3

**Comment by Unknwon** [comment]
Hi, is the repository you are trying to push happens to be a fork and/or has webhook setup?
