### ISSUE TITLE
Can't create PR, because of Error 1062: Duplicate entry

### ISSUE THREAD

**Issue by kenjis** [gogs/gogs#5693]
**Describe the bug**
When I create a new PR, gogs shows 500 error page.

gogs.log:
```
2019/04/26 14:27:23 [ERROR] [...g/context/context.go:171 ServerError()] NewPullRequest: newIssue: Error 1062: Duplicate entry '14-311' for key 'UQE_issue_repo_index'
```

**To Reproduce**
1. Just create a PR.

**Expected behavior**
A new PR is created.

**Screenshots**
gogs's 500 error page.

**Additional context**

- Gogs version (or commit ref): 0.11.43.0330
- Git version: 2.16.2
- Operating system: CentOS release 6.10
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: It seems it is an edge case. We were able to create PR in this morning!
- Log gist (usually found in `log/gogs.log`):

**Comment by kenjis** [comment]
We've updated `num_pulls`, and now we can create PRs.

```
mysql> select num_pulls + 1 from repository where id = 14\G
*************************** 1. row ***************************
num_pulls + 1: 311
1 row in set (0.00 sec)
```

```
mysql> update repository set num_pulls =  num_pulls + 1 where id = 14\G
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```

**Comment by Unknwon** [comment]
Thanks for the update!

I recommend you upgrade Gogs to newer version, there was some bugs about issues/pulls counting.
