### ISSUE TITLE
backup error

### ISSUE THREAD

**Issue by JyBigBoss** [gogs/gogs#5694]
**Describe the bug**
when i create the full backup with command: `./gogs bakcup`
although can created the backup file,but has some errors.

**To Reproduce**
1.exec `./gogs bakcup`

**Expected behavior**
please see screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/20468538/56791330-647f4e00-6839-11e9-9055-d78ba68d382e.png)

**Additional context**

- Gogs version (or commit ref): `Gogs version 0.11.66.0916`
- Git version: `git version 1.8.3.1`
- Operating system: `CentOS Linux release 7.5.1804 (Core)`
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: explain why
- Log gist (usually found in `log/gogs.log`):
nothing

**Comment by Unknwon** [comment]
Thanks for the feedback!

Can you try apply `-v` flag so we have more context?

**Comment by JyBigBoss** [comment]
This is caused by an invalid webhook configured in the repository.
When I deleted the webhook, it is now normal.

**Comment by JyBigBoss** [comment]
But why do  trigger webhook when backup?

**Comment by Unknwon** [comment]
Thanks for the follow up!

Can you provide more information about what is a "invalid webhook configured" looks like?

**Comment by JyBigBoss** [comment]
Sorry, Now in a normal state and cannot provide previous information.
