### ISSUE TITLE
[Request] Add 3rd party email sender service, like mailgun

### ISSUE THREAD

**Issue by swayoleg** [gogs/gogs#5696]
Good day.
I have an issue regarding mailing from gogs.

Mail notification always spammed, even with DNS mx records for proper IP.
Yes, I know - there is a possibility with SPF. 
But I believe that a lot of gogs users prefer to use some spam proof mail services like mailgun, or any.

It can be any service, but from mine point of view, mailgun is easiest to integrate 
(Can be done with simple curl request)

So I see the solution, when in config we can choose if we should use mail service, and add token to it. At sending point we checks the method of sending, and in case of mailgun send the curl request. 
Hope it wouldn't be hard to integrate.

Thanks in advance.

**Comment by swayoleg** [comment]
any thoughts ?

**Comment by MohammedFadin** [comment]
I vouch for this as well. Let's wait to hear from the maintainers.

**Comment by unknwon** [comment]
Hi, thanks your feedback!

You can use Mailgun already (that's what https://try.gogs.io uses), I'm a bit lost what is missing here?
