### ISSUE TITLE
Restore Repositories runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by SaintLoong** [gogs/gogs#5699]
First of all, read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html.

If you don't want to read, it's up to you. But don't waste your time continue reporting.

The issue will be closed without any explanation if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [中文](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please do not end your title with a question mark or period.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

**Describe the bug**

**To Reproduce**
1. console run ./gogs backup，
2. Backup succeed! Archive is located at: gogs-backup-20190429075419.zip，File Size 2.79GB
3. move file to new server, new server is docker run gogs, run "docker exec -it gogs"
4. run ./gogs restore --from gogs-backup-20190429075419.zip, 
5.after A few seconds throw error:

**Expected behavior**
Restore Repositories

**Screenshots**
![图片](https://user-images.githubusercontent.com/1243233/56872259-7fc8a400-6a59-11e9-96f7-ae31872a852f.png)

**Additional context**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [* ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [* ] No: explain why
- Log gist (usually found in `log/gogs.log`):
No current related operations logs，logs last 10 line：
a346fd74c603:/app/gogs/log$ tail -f gogs.log
2019/04/28 08:10:32 [ WARN] parseRemoteUpdateOutput: unexpected update line " + f6f5c717...ed5c2575 refs/pull/86/MERGE -> refs/pull/86/MERGE  (forced update)"
2019/04/28 08:20:30 [ WARN] parseRemoteUpdateOutput: unexpected update line " + f923c2b4...c1de81b6 refs/fetches/_.Wendy/master -> refs/fetches/_.Wendy/master  (forced update)"
2019/04/28 08:20:30 [ WARN] parseRemoteUpdateOutput: unexpected update line " + cda71a47...afc3daef refs/pull/49/MERGE          -> refs/pull/49/MERGE  (forced update)"
2019/04/28 08:20:30 [ WARN] parseRemoteUpdateOutput: unexpected update line " + f923c2b4...c1de81b6 refs/pull/49/head           -> refs/pull/49/head  (forced update)"
2019/04/28 16:20:48 [ WARN] parseRemoteUpdateOutput: unexpected update line " + 21798402...bfe35a67 refs/pull/40/MERGE        -> refs/pull/40/MERGE  (forced update)"
2019/04/28 16:20:48 [ERROR] [...ogs/models/mirror.go:447 SyncMirrors()] GetFullCommitID [7]: object does not exist [id: refs/heads/refs/fetches/wnlsh/v4-dev, rel_path: ]
2019/04/28 16:20:48 [ERROR] [...ogs/models/mirror.go:447 SyncMirrors()] GetFullCommitID [7]: object does not exist [id: refs/heads/refs/fetches/wnlsh/v4-master, rel_path: ]
2019/04/28 16:30:30 [ WARN] parseRemoteUpdateOutput: unexpected update line " + e46894b3...a55a4002 refs/pull/60/MERGE -> refs/pull/60/MERGE  (forced update)"
2019/04/28 16:31:00 [ WARN] parseRemoteUpdateOutput: unexpected update line " + b913afeb6...98020d09d refs/pull/3535/merge -> refs/pull/3535/merge  (forced update)"
2019/04/28 22:10:43 [ WARN] parseRemoteUpdateOutput: unexpected update line " + 599e1603...08690539 refs/pull/27/merge -> refs/pull/27/merge  (forced update)"

**Comment by unknwon** [comment]
Please be respectful to the issue template.
