### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by needsearch** [gogs/gogs#5703]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot find "Issues". With thousands of issues, it's impossible to find what I need.

**Describe the solution you'd like**
A search box in the "issues page", like the one that already exists in " commit history".

**Describe alternatives you've considered**
The only solution is to scroll all issues one by one, until I find the one I need. But this is not good, nor practical. The only remaining alternative is to not use Gogs at all.

**Additional context**
Please add a search box for issues like the one that is in the "Commit" page.

This is a pretty useful feature by the way, could this one please be added to Gogs? It doesn't have to be any sophisticated search, even a simple search by title/content keywords would be a good addition! Thank you very much!

**Comment by fenchu** [comment]
I'm not using issues, but the same goes for repos and files within repos, I have 100+ repos and the pagesize is 15.  I would love a big generic search :-)

**Comment by unknwon** [comment]
Duplicated https://github.com/gogs/gogs/issues/4239.
