### ISSUE TITLE
Problem to restore my backup

### ISSUE THREAD

**Issue by danilorsilva** [gogs/gogs#5706]
- Gogs version (or commit ref): Gogs version 0.11.86.0130
- Git version: git version 2.20.1
- Operating system: Kubernetes on GKE using helm to install Gogs
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X ] Yes: provide example URL
  - [ ] No: explain why
- Log gist (usually found in `log/gogs.log`):

## Description
Hello, i am trying to backup and restore gogs. I can create the backup successfully usind `gogs backup` using git user.

When i try to restore backup a have this error (i am using git user to restore):

2019/05/13 19:05:09 [ INFO] Restore backup from: gogs-backup-20190513190259.zip
2019/05/13 19:05:10 [ERROR] [...ogs/models/models.go:373 ImportDatabase()] Failed to reset 'created_unix': pq: syntax error at or near "user"
2019/05/13 19:05:10 [ERROR] [...ogs/models/models.go:373 ImportDatabase()] Failed to reset 'created_unix': pq: syntax error at or near "user"
2019/05/13 19:05:29 [FATAL] Failed to import 'custom': rename /tmp/gogs-backup/custom /data/gogs: invalid cross-device link

Anyone can help me?

...

**Comment by unknwon** [comment]
Hi, I think this is duplicated to https://github.com/gogs/gogs/issues/4339#issuecomment-358339037.
