### ISSUE TITLE
Hook not working when executed from push

### ISSUE THREAD

**Issue by esteban-turnocheck** [gogs/gogs#5707]
Hi! I'll repost this comment as a new issue from here [https://github.com/gogs/gogs/issues/4338](https://github.com/gogs/gogs/issues/4338) because when I wrote that comment, didn't see it was closed, and besides I have some new data now.

I have a script very similar to https://discuss.gogs.io/t/how-to-work-a-git-hook/998, which originated that issue.

I know there are many variables involved, but for the sake of clarity I'll try to explain the problem first and fill in the data that could appear relevant when somebody think it is. Also, will cut the script to one single line which reproduces the issue.

The script has a line in which I need to run a command as another user. Not root, but the owner of a series of files that make up my development web site. I've created a post-receive hook that simply checks-out the 'develop' branch on the webroot each time I push on 'develop'. Had it working for over a year (in a CentOS 6.5 VPS), but now I'm moving to a different host (Ubuntu 18.04), and there is no way it works.

When I run the script as user `git` (`sudo -E -u git ./post-receive`) (the user under which gogs and git runs), it works perfectly wich is checked because the user `git` doesn't have permission for accesing the directories on the webroot, but the line on the `post-receive` that executes `sudo -E -u tcpanel1 cd /home/tcpanel1/public_html/desarrollo` work as expected (the user `tcpanel1` has that access allowed so the `cd` gets executed)
But when I make a `push` from the client, and the script is run by gogs (with user `git`), it gives back the error:
`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

- I've been searching all weekend and already checked with `mount` to see if there is something which has the "noexec" bit or so. Nothing.

- The user git is in the sudoers:
`git ALL=(tcpanel1:tcpanel) NOPASSWD:ALL`

- The most dazzling thing is that it works perfectly when I run it from a ssh terminal as user git

I hope somebody can help me since I'm lost since three days ago! Thank's!!!

**UPDATE**:
I gave up and installed Gitea, in the hope of have some more data to track down this problem, and it turns out that with gitea, the hook worked as expected. In fact, I copied/pasted the script from gogs on the old server to gitea on the new one, and had to do anything but a push, and it was all well. 
I could find out anything else but that, but I'm ready to help in whatever is to my reach to find a solution for this on gogs.

Thanks!

**Comment by unknwon** [comment]
Please be respectful to the issue template.

Thanks for the feedback and glad you find something working for you.
