### ISSUE TITLE
Nested Markdown elements inside a list get rendered incorrectly

### ISSUE THREAD

**Issue by neon-dev** [gogs/gogs#5710]
Both of the following issues currently apply for 0.11.29 up to the latest version:
https://github.com/gogs/gogs/issues/1415
https://github.com/gogs/gogs/issues/1416

Didn't try older versions, so I don't know exactly when this broke.

**Comment by unknwon** [comment]
Please be respectful to the issue template.

**Comment by neon-dev** [comment]
Sorry but I hate redundancy. Does copy the descriptions of both linked issues make this one better in any way?
Just wanted to point out to reopen these two old issues but wasn't sure if anyone would notice if commenting on such old closed ones.

**Comment by unknwon** [comment]
It's not about copy and paste, it's about fill in the information for the bug report.

**Comment by neon-dev** [comment]
I understand, but unfortunately I have no additional information so I can only format my original post how you expect it. It doesn't add more info but surely looks nicer (see above).

**Comment by unknwon** [comment]
Thanks for the update! But if you can't describe what is expected and what you saw instead, and/or reproduce on https://try.gogs.io, I don't know how to move forward.

And I don't spot any visual bugs found in the example repo from two issues you linked: https://try.gogs.io/manfer/MarkDownSample

**Comment by neon-dev** [comment]
You are right, it looks like issue #1415 doesn't happen anymore.
But i still see problems when nesting a block of code in a list, so #1416 still exists.
Code:
```
1. Item 1
    ```
    nested block of code
    ```
```
Expected result:
1. Item 1
    ```
    nested block of code
    ```
Actual result:
![Bug](https://image.prntscr.com/image/SAIaKCugR5uSHwJ4hdMe7Q.png)

The four space indented block mentioned in #1416 doesn't seem to work for my neither in Github nor Gogs, so I would ignore it for now.

**Comment by unknwon** [comment]
https://try.gogs.io/manfer/MarkDownSample#list-with-code-sample:
>Needs blank line to separate list item from its code content.

Gogs only supports standard markdown

**Comment by neon-dev** [comment]
Ok then there is at least a way to solve previous issues. But I would still argue that the formatting in my screenshot is not correct, because it's inline and not block code. By the way, is there a spec that defines the requirement of a blank line?
Also you can currently omit the blank lines on the following items:
```
1. Item 1

    ```
    git remote -v
    ```
2. Item 2
    ```
    git branch
    ```
3. Item 3
    ```
    git checkout -b newbranch
    ```
```
works, but this doesn't:
```
1. Item 1
    ```
    git remote -v
    ```
2. Item 2
    ```
    git branch
    ```
3. Item 3
    ```
    git checkout -b newbranch
    ```
```

**Comment by unknwon** [comment]
Link break: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#line-breaks
