### ISSUE TITLE
correct ldap authentication does login to gogs

### ISSUE THREAD

**Issue by uvwild** [gogs/gogs#5711]
I am successfully  running gogs in a docker container for our project using local authentication.
`35c841ea9eed        gogs/gogs:0.11.86           "/app/gogs/docker/st…"   2 weeks ago         Up 23 minutes            0.0.0.0:12322->22/tcp, 0.0.0.0:12380->3000/tcp     cicd_gogs-repo_1`

Now, I tried to add LDAP authentication like in the neighboring jenkins where it works fine. The LDAP connection works, but the LDAP authentication does not result in a session :(

I end up with a not very helpful  trace log (details changed):
```
2019/05/16 13:46:58 [TRACE] Fetching attributes '', 'givenName', 'sn', 'userPrincipalName', 'cn' with filter '(sAMAccountName=tester)' and base 'CN=Tester\, Uv (12345),OU=06,OU=Users,DC=domain,DC=com'
2019/05/16 13:46:58 [TRACE] Bound successfully with userDN: CN=TESTER\, Uv (123456),OU=Users,DC=domain,DC=com
2019/05/16 13:46:58 [ERROR] [...g/context/context.go:191 ServerError()] UserLogin: e-mail has been used [email: uv.tester@bogus.mail]
2019/05/16 13:46:58 [TRACE] Template: status/500
[Macaron] 2019-05-16 13:46:58: Completed POST /user/login 500 Internal Server Error in 176.045776ms
```
I usually try to investigate further but cant find anything in this log to help me.
Whats the missing error here, or what is causing the ServerError!
(I dont have a golang setup to dig further)

There are other issues ending up with http 500 but i cannot find analogy.

**Comment by uvwild** [comment]
So the answer is.........
**make sure the email from the LDAP account is not used anywere else.**
This is not very transparent since I used a username for login and never really see the ldap entry with the email. Also usually there are only very few accounts available for testing logins in a corporate LDAP.

A trace log entry stating that there is a duplicate email would have answered the issue instantly!!!
Thats missing from the log.

**Comment by iamdoubz** [comment]
Good afternoon. I have this same problem but I can ellaborate much more. I am using the LDAP (via BindDN), and have setup the ability for my end users to log in with either their usernames, email address, or company assigned employee number (`(&(objectClass=Person)(|(sAMAccountName=%s)(mail=%s)(employeenumber=%s)))`). I also have that the username attribute to use is the `sAMAccountName` to keep everything clean (logins do not differ from end user to end user).

Using this setup, I can log in using `sAMAccountName` or `email`, but when I try to log in using `employeenumber`, I get the 500 error. It appears that it does the checks, finds the correct user, then forgets to check if it is already an active/activated user.

My log file logging in with `employeenumber` and then `sAMAccountName`:
```
2020/01/08 10:46:21 [TRACE] Session ID: e58286af26323e62
2020/01/08 10:46:21 [TRACE] CSRF Token: cN9iGpuM6A1BkAa9YsDg4EThqiI6MTU3ODUwMTk3MTEzOTA5OTMwMA==
2020/01/08 10:46:21 [TRACE] LDAP: Dialing with security protocol '0' without verifying: false
2020/01/08 10:46:21 [TRACE] LDAP will use BindDN
2020/01/08 10:46:21 [TRACE] Search for LDAP user: 962478
2020/01/08 10:46:21 [TRACE] LDAP: Bound as BindDN: CN=AdminGogs,CN=Users,DC=my,DC=domain
2020/01/08 10:46:21 [TRACE] LDAP: Searching for DN using filter '(&(objectClass=Person)(|(sAMAccountName=962478)(mail=962478)(employeenumber=962478)))' and base 'CN=Users,DC=my,DC=domain'
2020/01/08 10:46:21 [TRACE] Binding with userDN: CN=First M. Lastname,CN=Users,DC=my,DC=domain
2020/01/08 10:46:21 [TRACE] Bound successfully with userDN: CN=First M. Lastname,CN=Users,DC=my,DC=domain
2020/01/08 10:46:21 [TRACE] Fetching attributes 'sAMAccountName', 'cn', '(employeenumber)', 'mail', 'loram_aus_admin' with filter '(&(objectClass=Person)(|(sAMAccountName=962478)(mail=962478)(employeenumber=962478)))' and base 'CN=First M. Lastname,CN=Users,DC=my,DC=domain'
2020/01/08 10:46:21 [TRACE] Checking admin with filter '(memberOf=CN=gogAdmins,CN=Users,DC=my,DC=domain)' and base 'CN=First M. Lastname,CN=Users,DC=my,DC=domain'
2020/01/08 10:46:21 [ERROR] [...g/context/context.go:191 ServerError()] UserLogin: e-mail has been used [email: first.m.lastname@my.domain]
2020/01/08 10:46:21 [TRACE] Template: status/500
2020/01/08 10:46:28 [TRACE] Session ID: e58286af26323e62
2020/01/08 10:46:28 [TRACE] CSRF Token: cN9iGpuM6A1BkAa9YsDg4EThqiI6MTU3ODUwMTk3MTEzOTA5OTMwMA==
2020/01/08 10:46:28 [TRACE] Template: user/auth/login
2020/01/08 10:46:39 [TRACE] Session ID: e58286af26323e62
2020/01/08 10:46:39 [TRACE] CSRF Token: cN9iGpuM6A1BkAa9YsDg4EThqiI6MTU3ODUwMTk3MTEzOTA5OTMwMA==
2020/01/08 10:46:39 [TRACE] LDAP: Dialing with security protocol '0' without verifying: false
2020/01/08 10:46:39 [TRACE] LDAP will use BindDN
2020/01/08 10:46:39 [TRACE] Search for LDAP user: fmlastname
2020/01/08 10:46:39 [TRACE] LDAP: Bound as BindDN: CN=AdminGogs,CN=Users,DC=my,DC=domain
2020/01/08 10:46:39 [TRACE] LDAP: Searching for DN using filter '(&(objectClass=Person)(|(sAMAccountName=fmlastname)(mail=fmlastname)(employeenumber=fmlastname)))' and base 'CN=Users,DC=my,DC=domain'
2020/01/08 10:46:39 [TRACE] Binding with userDN: CN=First M. Lastname,CN=Users,DC=my,DC=domain
2020/01/08 10:46:39 [TRACE] Bound successfully with userDN: CN=First M. Lastname,CN=Users,DC=my,DC=domain
2020/01/08 10:46:39 [TRACE] Fetching attributes 'sAMAccountName', 'cn', '(employeenumber)', 'mail', 'loram_aus_admin' with filter '(&(objectClass=Person)(|(sAMAccountName=fmlastname)(mail=fmlastname)(employeenumber=fmlastname)))' and base 'CN=First M. Lastname,CN=Users,DC=my,DC=domain'
2020/01/08 10:46:39 [TRACE] Checking admin with filter '(memberOf=CN=gogAdmins,CN=Users,DC=my,DC=domain)' and base 'CN=First M. Lastname,CN=Users,DC=my,DC=domain'
2020/01/08 10:46:39 [TRACE] Session ID: e58286af26323e62
2020/01/08 10:46:39 [TRACE] CSRF Token: lrJGc3ORSUpEwGinYQM_EEskZrs6MTU3ODUwMTk5OTM2MDc4NDAwMA==
2020/01/08 10:46:39 [TRACE] Session ID: e58286af26323e62
2020/01/08 10:46:39 [TRACE] CSRF Token: lrJGc3ORSUpEwGinYQM_EEskZrs6MTU3ODUwMTk5OTM2MDc4NDAwMA==
2020/01/08 10:46:39 [TRACE] Template: user/dashboard/dashboard
```

Screen shot after pressing "Sign In" using `employeenumber` as the Username input:

![GOGS-LDAP-Bind-Error](https://user-images.githubusercontent.com/4871781/71999965-f08aa780-3207-11ea-9f6a-8cf1cbf65e40.png)

### My Environment
1. Go 1.12.7
2. gogs 0.11.91
3. Installed from binary [Windows amd64 w/mws](https://dl.gogs.io/0.11.91/gogs_0.11.91_windows_amd64_mws.zip)
4. IIS reverse proxy to localhost on custom port

**Comment by unknwon** [comment]
Thanks @iamdoubz! Would you mind file a new issue with the information in your above comment?
