### ISSUE TITLE
Docker run get a error on raspberry

### ISSUE THREAD

**Issue by gujianxing** [gogs/gogs#5713]
I run the command `docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs` And get a error. I use the ubuntu server 18.04 on raspberry3.
A error like this: standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by kdomanski** [comment]
The images on Docker Hub are built only for amd64 architecture. You're going to need to build your own image for ARM.
