### ISSUE TITLE
Fail to execute custom post-receive hook: exit status 128

### ISSUE THREAD

**Issue by fivenull** [gogs/gogs#5715]
I have a problem
post-receive problem, my post-receive.log shows "[...ogs/gogs/cmd/hook.go:274 runHookPostReceive()] Fail to execute custom post-receive hook: exit status 128"

post-receive:
#!/bin/sh
export GIT_WORK_TREE=/var/home/gogs_projects
export GIT_DIR=${GIT_WORK_TREE}/.git
cd ${GIT_WORK_TREE}
git pull origin master

what should i do now

**Comment by redaness** [comment]
hi,I have face the same problem. Do u solve it?

**Comment by unknwon** [comment]
Please be respectful to the issue template.

You should check logs in `logs/hook/post-receive.log` see if anything there.
