### ISSUE TITLE
The document url is not open

### ISSUE THREAD

**Issue by efynn** [gogs/gogs#5716]
The certificate may be expired, and the document page cannot be opened:
![0cdf3499ac00f322e1fe2f577313d61](https://user-images.githubusercontent.com/50618747/58230021-c01ff700-7d65-11e9-9bb9-d4531a17757a.png)

**Comment by adojck** [comment]
Yes, certificate is expired, but you can still access the website. Press the opposite of blue button and there will be a link to accept invalid certificate.

**Comment by efynn** [comment]
Ok, thanks.
