### ISSUE TITLE
SSL fails on local gogs / ManInMiddle Vulnerability  /  Port change fails on install

### ISSUE THREAD

**Issue by diveyez** [gogs/gogs#5718]
# Issue Update #1

- gogs restart made port change take into the data/application

- gogs restart did not fix SSL issue, cannot connect due to **"Error code: SSL_ERROR_RX_RECORD_TOO_LONG"**

```
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified. Please contact the website owners to inform them of this problem.
```

**Describe the bug**
Installed, changed port, and tried to set to https only, both failed once installed.

**To Reproduce**
Installed, changed port, and tried to set to https only, both failed once installed.
**Expected behavior**

Expected both http:// to https:// change and port :3000 to :<customport>
change to stick after install, neither did.

**Additional context**

- Gogs version (or commit ref): Current Stable 
- Git version: Current Stable
- Operating system: Debian x64
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: I did not configure it, and cannot reconfigure try.gogs.io
- Log gist N/A

**Comment by jp31415926** [comment]
I have this issue as well when trying to enable HTTPS. I have a working setup using HTTP and port 8080. However, when I make the changes recommended on the FAQ to enable HTTPS and then go to the HTTPS URL, I get SSL_ERROR_RX_RECORD_TOO_LONG. If I try to access the URL using HTTP, it works as before. It appears the new config appears to ignore (without anything output in the log) the HTTPS directives.

I have change other things in the app.ini file (i.e. port, SSH, etc) and I am certain the file is getting read and used by GOGS.

The gogs.log file doesn't offer much except that it says, "http://0.0.0.0:8080" which also makes me think that it is not attempting to enable HTTPS. I can't see any other indicators in the log file.

# uname -a
Linux wd-pricejp-lnx.[domain removed] 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Original app.ini file server section configured (and working) for HTTP:
`[server]`
`PROTOOCOL        = http`
`DOMAIN           = wd-pricejp-lnx`
`HTTP_PORT        = 8080`
`DISABLE_SSH      = false`
`SSH_PORT         = 8022`
`START_SSH_SERVER = true`
`OFFLINE_MODE     = true`

New app.ini file server section configured to use HTTPS:
`[server]`
`PROTOOCOL        = https`
`CERT_FILE        = custom/https/cert.pem`
`KEY_FILE         = custom/https/key.pem`
`DOMAIN           = wd-pricejp-lnx`
`HTTP_PORT        = 8080`
`DISABLE_SSH      = false`
`SSH_PORT         = 8022`
`START_SSH_SERVER = true`
`OFFLINE_MODE     = true`

gogs.log file:
`2019/10/03 13:07:56 [TRACE] Log Mode: File (Trace)`
`2019/10/03 13:07:56 [ INFO] Gogs 0.11.91.0811`
`2019/10/03 13:07:56 [ INFO] Cache Service Enabled`
`2019/10/03 13:07:56 [ INFO] Session Service Enabled`
`2019/10/03 13:07:56 [ INFO] Mail Service Enabled`
`2019/10/03 13:07:56 [ INFO] Notify Mail Service Enabled`
`2019/10/03 13:07:56 [ INFO] Git Version: 2.17.1`
`2019/10/03 13:07:56 [ INFO] SQLite3 Supported`
`2019/10/03 13:07:56 [ INFO] Run Mode: Production`
`2019/10/03 13:07:56 [TRACE] Doing: CheckRepoStats`
`2019/10/03 13:07:56 [ INFO] SSH server started on 0.0.0.0:8022`
`2019/10/03 13:07:56 [TRACE] SSH server cipher list: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128]`
`2019/10/03 13:07:56 [ INFO] Listen: http://0.0.0.0:8080`

**Comment by afilippov1985** [comment]
@jp31415926  You make a mistake in the word `PROTOOCOL`
