### ISSUE TITLE
open /usr/local/gogs/custom/conf/app.ini: read-only file system

### ISSUE THREAD

**Issue by Kry1702** [gogs/gogs#5721]
URL http://IP:3000/install
Click on the install 
Error Out: open /usr/local/gogs/custom/conf/app.ini: read-only file system
Version Use : 0.11.86.0130
Binary build gogs The root directory does not contain”custom/conf/app.ini“ 
Manually create ”custom/conf/app.ini“ files to give writable permissions, Web config Install Still an error，Same error message：open /usr/local/gogs/custom/conf/app.ini: read-only file system。

**Comment by Kry1702** [comment]
Manual start command：“su - git -c "/usr/local/gogs/gogs web"” ，The Web page can be configured and installed successfully；
through command"systemctl start gogs.service"  start gogs services Web config Error:"open /usr/local/gogs/custom/conf/app.ini: read-only file system"  Give maximum authority in a timely manner，Is the same。

This is mainly due to the configuration of "ProtectSystem=full" in "gogs.service"
 If  set to full, mounts the /usr and /boot  and /etc  directories read-only for processes invoked by this unit.

The solution
1.Remove /usr and /boot and /etc directory
2. Set the to ProtectSystem = false

**Comment by MohammedFadin** [comment]
Does this also applies for Gogs on Docker/Kubernetes? When doing the Gogs helm installation, the localhost/install page cannot updates app.ini due to the file is read only.
