### ISSUE TITLE
gogs works abnormal when recreat docker container base on an exist gogs volume 

### ISSUE THREAD

**Issue by hulb** [gogs/gogs#5723]
**Describe the bug**
When I remove the gogs docker container but keep the volume on the host and recreate a gogs container and run it with the volume exist already, gogs works very abnormal.The cpu is too high and the log is all the same 

**To Reproduce**
1. run gogs container : `docker run -d -v /root/gogs:/data -p 8080:3000 -p 10020:22 gogs/gogs`
2. create a repository in gogs
3. stop and remove the container
4. repeat step 1 and gogs container run successfully but will not be accessable.

**Expected behavior**
gogs works fine and I can access my repository created before in the last container since I keep the /root/gogs volume

**Screenshots**
None
**Additional context**

- Gogs version (or commit ref):  0.11.88.0220
- Git version: 
- Operating system: debian docker
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: I can't redeploy the gogs on it
- Log gist (usually found in `log/gogs.log`):
```
 usermod: no changes
gogs           | Jun 14 05:32:02 syslogd started: BusyBox v1.29.3
gogs           | Jun 14 05:32:02 sshd[28]: Server listening on :: port 22.
gogs           | Jun 14 05:32:02 sshd[28]: Server listening on 0.0.0.0 port 22.
gogs           | 2019/06/14 05:32:03 [TRACE] Custom path: /data/gogs
gogs           | 2019/06/14 05:32:03 [TRACE] Log path: /app/gogs/log
gogs           | 2019/06/14 05:32:03 [TRACE] Build Time: 2019-03-26 10:59:43 UTC
gogs           | 2019/06/14 05:32:03 [TRACE] Build Git Hash: 4f9c5b60c56606e709c4da2d1587aa7096ae24da
gogs           | 2019/06/14 05:32:03 [TRACE] Log Mode: File (Info)
gogs           | 2019/06/14 05:32:03 [ INFO] Gogs 0.11.88.0220
gogs           | 2019/06/14 05:32:04 [TRACE] Custom path: /data/gogs
gogs           | 2019/06/14 05:32:04 [TRACE] Log path: /app/gogs/log
gogs           | 2019/06/14 05:32:04 [TRACE] Build Time: 2019-03-26 10:59:43 UTC
gogs           | 2019/06/14 05:32:04 [TRACE] Build Git Hash: 4f9c5b60c56606e709c4da2d1587aa7096ae24da
gogs           | 2019/06/14 05:32:04 [TRACE] Log Mode: File (Info)
gogs           | 2019/06/14 05:32:04 [ INFO] Gogs 0.11.88.0220
gogs           | 2019/06/14 05:32:05 [TRACE] Custom path: /data/gogs
gogs           | 2019/06/14 05:32:05 [TRACE] Log path: /app/gogs/log
gogs           | 2019/06/14 05:32:05 [TRACE] Build Time: 2019-03-26 10:59:43 UTC
gogs           | 2019/06/14 05:32:05 [TRACE] Build Git Hash: 4f9c5b60c56606e709c4da2d1587aa7096ae24da
gogs           | 2019/06/14 05:32:05 [TRACE] Log Mode: File (Info)
gogs           | 2019/06/14 05:32:05 [ INFO] Gogs 0.11.88.0220
```

**Comment by Rio517** [comment]
I wonder if you're seeing the same issue we did: https://github.com/gogs/gogs/pull/5724

**Comment by hulb** [comment]
Nope, it was created after I post this issue.

**Comment by Rio517** [comment]
I don't understand what your referencing. The version in your issue, 0.11.88.0220, does appear to contain the problem cited in PR #5724. Of course, it may be totally unrelated. 

See: https://github.com/gogs/gogs/blob/8b383f86de84799494a1eb48bbe9006f5fa05919/docker/s6/gogs/setup#L23

**Comment by hulb** [comment]
thx for reply.

**Comment by wangyoukun** [comment]
> **Describe the bug**
> When I remove the gogs docker container but keep the volume on the host and recreate a gogs container and run it with the volume exist already, gogs works very abnormal.The cpu is too high and the log is all the same
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. run gogs container : `docker run -d -v /root/gogs:/data -p 8080:3000 -p 10020:22 gogs/gogs`
> 2. create a repository in gogs
> 3. stop and remove the container
> 4. repeat step 1 and gogs container run successfully but will not be accessable.
> 
> **Expected behavior**
> gogs works fine and I can access my repository created before in the last container since I keep the /root/gogs volume
> 
> **Screenshots**
> None
> **Additional context**
> 
> * Gogs version (or commit ref):  0.11.88.0220
> * Git version:
> * Operating system: debian docker
> * Database (replace `[ ]` with `[x]`):
>   
>   * [ ]  PostgreSQL
>   * [ ]  MySQL
>   * [ ]  MSSQL
>   * [x]  SQLite
> * Can you reproduce the bug at https://try.gogs.io:
>   
>   * [ ]  Yes: provide example URL
>   * [x]  No: I can't redeploy the gogs on it
> * Log gist (usually found in `log/gogs.log`):
> 
> ```
>  usermod: no changes
> gogs           | Jun 14 05:32:02 syslogd started: BusyBox v1.29.3
> gogs           | Jun 14 05:32:02 sshd[28]: Server listening on :: port 22.
> gogs           | Jun 14 05:32:02 sshd[28]: Server listening on 0.0.0.0 port 22.
> gogs           | 2019/06/14 05:32:03 [TRACE] Custom path: /data/gogs
> gogs           | 2019/06/14 05:32:03 [TRACE] Log path: /app/gogs/log
> gogs           | 2019/06/14 05:32:03 [TRACE] Build Time: 2019-03-26 10:59:43 UTC
> gogs           | 2019/06/14 05:32:03 [TRACE] Build Git Hash: 4f9c5b60c56606e709c4da2d1587aa7096ae24da
> gogs           | 2019/06/14 05:32:03 [TRACE] Log Mode: File (Info)
> gogs           | 2019/06/14 05:32:03 [ INFO] Gogs 0.11.88.0220
> gogs           | 2019/06/14 05:32:04 [TRACE] Custom path: /data/gogs
> gogs           | 2019/06/14 05:32:04 [TRACE] Log path: /app/gogs/log
> gogs           | 2019/06/14 05:32:04 [TRACE] Build Time: 2019-03-26 10:59:43 UTC
> gogs           | 2019/06/14 05:32:04 [TRACE] Build Git Hash: 4f9c5b60c56606e709c4da2d1587aa7096ae24da
> gogs           | 2019/06/14 05:32:04 [TRACE] Log Mode: File (Info)
> gogs           | 2019/06/14 05:32:04 [ INFO] Gogs 0.11.88.0220
> gogs           | 2019/06/14 05:32:05 [TRACE] Custom path: /data/gogs
> gogs           | 2019/06/14 05:32:05 [TRACE] Log path: /app/gogs/log
> gogs           | 2019/06/14 05:32:05 [TRACE] Build Time: 2019-03-26 10:59:43 UTC
> gogs           | 2019/06/14 05:32:05 [TRACE] Build Git Hash: 4f9c5b60c56606e709c4da2d1587aa7096ae24da
> gogs           | 2019/06/14 05:32:05 [TRACE] Log Mode: File (Info)
> gogs           | 2019/06/14 05:32:05 [ INFO] Gogs 0.11.88.0220
> ```

Have you solved this problem?
