### ISSUE TITLE
Gogs Problem Timeout Services

### ISSUE THREAD

**Issue by JorgeAlejandroMuedanoCorrea** [gogs/gogs#5728]
Hi...

I configure a server and it's work good, but after many hours the page didn't response, if I check the terminal on the cmd at the server, it's doesn't have register, but if I send the command "Ctrl + C", the page load the information, and the service continue normaly only for a minutes. The same problem ocurs, when many users are logged. The server gogs is in Intranet.

thanks. 

**To Reproduce**
I don't have problem in my pc.

**Additional context**

- Gogs version (or commit ref): 0.11.86.0130
- Git version: 2.22.0
- Operating system: Windows Server 2016
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] Yes: provide example URL
  - [X ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ X] No: explain why
- Log gist (usually found in `log/gogs.log`):

 [ INFO] Listen: http://0.0.0.0:3000
2019/06/21 08:43:19 [ INFO] Gogs 0.11.86.0130
2019/06/21 08:43:19 [ INFO] Cache Service Enabled
2019/06/21 08:43:19 [ INFO] Session Service Enabled
2019/06/21 08:43:19 [ INFO] Git Version: 2.22.0
2019/06/21 08:43:19 [ INFO] SQLite3 Supported
2019/06/21 08:43:19 [ INFO] Run Mode: Production
2019/06/21 08:43:20 [ INFO] Listen: http://0.0.0.0:3000
2019/06/21 09:22:55 [ INFO] Gogs 0.11.86.0130
2019/06/21 09:22:55 [ INFO] Cache Service Enabled
2019/06/21 09:22:55 [ INFO] Session Service Enabled
2019/06/21 09:22:55 [ INFO] Git Version: 2.22.0
2019/06/21 09:22:55 [ INFO] SQLite3 Supported
2019/06/21 09:22:55 [ INFO] Run Mode: Production
2019/06/21 09:22:56 [ INFO] Listen: http://0.0.0.0:3000
2019/06/21 09:39:51 [ INFO] Gogs 0.11.86.0130
2019/06/21 09:39:51 [ INFO] Cache Service Enabled
2019/06/21 09:39:51 [ INFO] Session Service Enabled
2019/06/21 09:39:51 [ INFO] Git Version: 2.22.0
2019/06/21 09:39:51 [ INFO] SQLite3 Supported
2019/06/21 09:39:51 [ INFO] Run Mode: Production
2019/06/21 09:39:52 [ INFO] Listen: http://0.0.0.0:3000

**Comment by unknwon** [comment]
Hi,

>if I check the terminal on the cmd at the server, it's doesn't have register

What does it mean "it's doesn't have register"?

**Comment by JorgeAlejandroMuedanoCorrea** [comment]
Hi...

I refer at the window cmd that have the registry of the all requests done, in the server where I've configured the service the Gogs.

I add a example.

![Log](https://user-images.githubusercontent.com/45463169/61739738-ad6c7300-ad52-11e9-86d3-a48cabf4bcd0.png)

**Comment by unknwon** [comment]
Hmm, sorry I'm completely confused, what was the problem you have?
