### ISSUE TITLE
error: git-upload-pack died of signal 13

### ISSUE THREAD

**Issue by abanger** [gogs/gogs#5740]
- Gogs version (or commit ref):  gogs_0.11.86_linux_amd64
- Git version:   git version 1.8.3.1
- Operating system: centos 7
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ x] Yes: provide example URL  http://git.lab.cn
  - [ ] No: explain why
- Log gist (usually found in `log/gogs.log`):

2019/07/04 10:12:26 [ERROR] [.../routes/repo/http.go:260 serviceRPC()] HTTP.serviceRPC: fail to serve RPC 'upload-pack': exit status 128 - fatal: The remote end hung up unexpectedly
2019/07/04 10:12:35 [ERROR] [.../routes/repo/http.go:260 serviceRPC()] HTTP.serviceRPC: fail to serve RPC 'upload-pack': exit status 141 - error: git-upload-pack died of signal 13

**Comment by Unknwon** [comment]
Hi, are you able to reproduce this error constantly? If so, what are the reproduce steps? Thanks!

**Comment by abanger** [comment]
use github desktop to clone a repository .

```
2019/08/19 09:15:50 [ERROR] [.../routes/repo/http.go:260 serviceRPC()] HTTP.serviceRPC: fail to serve RPC 'upload-pack': exit status 141 - error: git-upload-pack died of signal 13
2019/08/19 09:16:39 [ERROR] [.../routes/repo/http.go:260 serviceRPC()] HTTP.serviceRPC: fail to serve RPC 'upload-pack': exit status 141 - error: git-upload-pack died of signal 13
2019/08/19 09:17:25 [ERROR] [.../routes/repo/http.go:260 serviceRPC()] HTTP.serviceRPC: fail to serve RPC 'upload-pack': exit status 141 - error: git-upload-pack died of signal 13
2019/08/19 09:17:46 [ERROR] [.../routes/repo/http.go:260 serviceRPC()] HTTP.serviceRPC: fail to serve RPC 'upload-pack': exit status 141 - error: git-upload-pack died of signal 13
2019/08/19 09:27:18 [ERROR] [.../routes/repo/http.go:260 serviceRPC()] HTTP.serviceRPC: fail to serve RPC 'upload-pack': exit status 141 - error: git-upload-pack died of signal 13
```

**Comment by abanger** [comment]
> Hi, are you able to reproduce this error constantly? If so, what are the reproduce steps? Thanks!

use github desktop to clone a repository .

**Comment by unknwon** [comment]
Thanks for the follow up! What if you use Git on the command line interface? Without using any GUI tool.
