### ISSUE TITLE
Push to https://mydomain.com/user/repo.git gives error: RPC failed HTTP 401 curl 22

### ISSUE THREAD

**Issue by Zombitch** [gogs/gogs#5746]
Hi,

Pushing to _https://mydomain.com/user/repo.git_ gives the following error :

_error: RPC failed HTTP 401 curl 22_

However, if I push to _https://**login**@mydomain.com/user/repo.git_ , it works

Additional information : I installed gogs with docker image and Gogs Version is 0.11.88.0627

Thanks &  have a good day.

**Comment by Unknwon** [comment]
Please be respectful to the issue template.
