### ISSUE TITLE
Error 500 on creating new repository on Windows 10

### ISSUE THREAD

**Issue by dimmuboy** [gogs/gogs#5757]
**Describe the bug**
On fresh new server installation I get Error 500 page after create new repo when I check Initialize Repository, otherwise repo is created but can’t push any data.
I tried to set full permissions for all users on root folders including repo dir, use MSSQL and SQLite3 as database, run as windows service with hostname in RUN_USER option and resychronizing hooks too.

**To Reproduce**
1. Go to 'New Repository' page
2. Set repository name
3. Click on checkbox 'Initialize this repository with selected files and template'
4. After 'Create Repository' I see error 500
`An error has occurred : initRepository: initRepoCommit: git push: remote: E To C:\gogs\repos\lukasm03\test.git ! [remote rejected] master -> master (pre-receive hook declined) error: failed to push some refs to 'C:\gogs\repos\lukasm03\test.git'
`

**Additional context**

- Gogs version (or commit ref): 0.11.86.0130
- Git version: 2.2.2
- Operating system: Windows 10 v1803
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: it's local problem
- Log gist (usually found in `log/gogs.log`):
```
2019/07/22 14:17:45 [ERROR] [.../routes/repo/repo.go:103 handleCreateError()] CreatePost: initRepository: initRepoCommit: git push: remote: E
To C:\gogs\repos\lukasm03\test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'C:\gogs\repos\lukasm03\test.git'
2019/07/22 14:17:45 [TRACE] Template: status/500
2019/07/22 14:26:35 [TRACE] Doing: MirrorUpdate
```

**Comment by aligoren** [comment]
I have the same issue. I don't know what can I do.

**Comment by begin1209** [comment]
I have the same issue, then I changed the SCRIPT_TYPE to sh（default is bash） in the conifig file（custom/conf/app.ini). It worked.

**Comment by begin1209** [comment]
> I have the same issue. I don't know what can I do.

You can have a try in this way!  Change the SCRIPT_TYPE to sh（default is bash） in the conifig file（custom/conf/app.ini)

**Comment by dimmuboy** [comment]
> I have the same issue, then I changed the SCRIPT_TYPE to sh（default is bash） in the conifig file（custom/conf/app.ini). It worked.

Operating system: Windows 10 v1803

**Comment by aligoren** [comment]
Yes, I also use Windows server latest version. Actually, I'm not using Windows for 8 years. So, I don't have any idea about SCRIPT_TYPE and sh in Windows.

**Comment by unknwon** [comment]
I currently have a Windows Server 2019, I'll see if I'm able to reproduce.

**Comment by unknwon** [comment]
I have a fresh install on Windows Server 2019 and is able to create new repository with `.gitginore` and `README`, etc. @dimmuboy would you mind post error logs located in `path/to/gogs/log/hooks/pre-receive.log`?

**Comment by dimmuboy** [comment]
Sorry for late answer but I have no pre-recieve.log file
