### ISSUE TITLE
希望增加类似github或者gitlab那种热力图的界面

### ISSUE THREAD

**Issue by zmapleshine** [gogs/gogs#5762]
现在即便是超级管理员，也无法得知某个具体的用户在今天或者指定日期有没有提交过代码，除非去登录该账号，这是一个严重的功能缺失。希望开发方能多多考虑，多谢！

**Comment by unknwon** [comment]
Please be respectful to the issue template.

Ref: https://github.com/gogs/gogs/issues/1640
