### ISSUE TITLE
Gogs automatic deployment (docker, etc)

### ISSUE THREAD

**Issue by fraballi** [gogs/gogs#5763]
Hi, @Team
Great effort.

Would be great having a mechanism for automatic deployment. I'm thinking on an API call skipping step: http://localhost:3000/install.

I have the dockerfile, where already got copied a custom **app.ini** file into /data/gogs/conf, when I load the /install page I can see that all my params are correclty loaded, so the feature request would be being able of submitting info from custom app.ini and not having to load the page to complete the process.

I inspected the form submission and you create some cookies every time the page is refreshed.
So if I want to use: curl ''', passing the **custom app.ini** file data and your **csrf** and **cookies**, how could be addressed and telling the application that settings where already submitted in order I can go directly to /user/login page?

Thanks in advance.

;-)

**Comment by unknwon** [comment]
Hi, the trick is to set the following value to be `true` in your custom **app.ini**:

https://github.com/gogs/gogs/blob/c154721f4a8f3e24d2f6fb61e74b4b64529255c2/conf/app.ini#L181-L182
