### ISSUE TITLE
Suddenly not able to push/pull over ssh

### ISSUE THREAD

**Issue by mbentley** [gogs/gogs#5765]
**Describe the bug**
I have gogs running in Docker and recently I started having issues being able to push or pull any content over SSH:

```
$ git pull origin master
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git remote -v
origin  ssh://git@git.mbentley.net:10022/mbentley/glados-scripts.git (fetch)
origin  ssh://git@git.mbentley.net:10022/mbentley/glados-scripts.git (push)
```

I turned on debug logging and in `log/gogs.log`, I see the following:
```
2019/08/02 02:36:04 [TRACE] SSH: Handshaking for 192.168.0.1:21982
2019/08/02 02:36:04 [TRACE] SSH: Connection from 192.168.0.1:21982 (SSH-2.0-OpenSSH_7.9)
2019/08/02 02:36:04 [ERROR] [.../runtime/asm_amd64.s:1337 goexit()] env: exit status 1
```
but I am not sure what it means.

I did create a new user and tried to push using my key and it still fails with the same message.  I also removed my keys via the web UI and re-added them but still the same issue.

**To Reproduce**
1. Try to perform a `git push` or `git pull`

**Expected behavior**
I expect to be able to push or pull.

**Screenshots**

**Additional context**

- Gogs version (or commit ref): `0.11.88.0627`
- Git version: `git version 2.20.1 (Apple Git-117)`
- Operating system: Mac OSX (client) / Gogs in Docker
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: explain why - not sure
- Log gist (usually found in `log/gogs.log`):
```
2019/08/02 02:36:04 [TRACE] SSH: Handshaking for 192.168.0.1:21982
2019/08/02 02:36:04 [TRACE] SSH: Connection from 192.168.0.1:21982 (SSH-2.0-OpenSSH_7.9)
2019/08/02 02:36:04 [ERROR] [.../runtime/asm_amd64.s:1337 goexit()] env: exit status 1
```

**Comment by mbentley** [comment]
I'm not really sure what happened; something was definitely broken.  I tried to restore from backups over the past week or so and I wasn't able to get things fixed so I just cleared all of my data and installed.  I didn't have more than like 20 repos, all of which I just repushed the data so I'm not sure what it was but I was able to just start from scratch at least and things are working fine.

**Comment by unknwon** [comment]
Hi, based on the logs you provide:

```
2019/08/02 02:36:04 [TRACE] SSH: Handshaking for 192.168.0.1:21982
2019/08/02 02:36:04 [TRACE] SSH: Connection from 192.168.0.1:21982 (SSH-2.0-OpenSSH_7.9)
2019/08/02 02:36:04 [ERROR] [.../runtime/asm_amd64.s:1337 goexit()] env: exit status 1
```

It seems like you've enabled both builtin SSH and the SSHD provided by the Gogs Docker image. 

As [docs suggested](https://github.com/gogs/gogs/tree/master/docker):

>Builtin SSH server is not recommended inside Docker Container

**Comment by prologic** [comment]
I've run into this too and use the Builtin SSH server; but I could swear I've not enabled both :) I'll check...

**Comment by prologic** [comment]
Setting `START_SSH_SERVER = false` and reconfiguring my Docker Swarm stack with:

```#!yaml
version: "3.2"

services:
  gogs:
    image: gogs/gogs:0.11.91
    ports:
      - "2222:22"
...
```

Fixed things for me :)
