### ISSUE TITLE
Add Rsync as a default package in Dockerfile

### ISSUE THREAD

**Issue by pabloalcantara** [gogs/gogs#5769]
Hi,
If it´s possible to add rsync to the default dockerfile.
Rsync is crucial for backup inside Openshit.

**Comment by unknwon** [comment]
Hi, you're welcome to send a PR to update current Dockerfile(s)!

**Comment by andreanidouglas** [comment]
@unknwon this was merged on pull #5773. Issue fixed!

**Comment by unknwon** [comment]
@andreanidouglas Thanks! Closing :)
