### ISSUE TITLE
the redirection url after install setup is localhost 

### ISSUE THREAD

**Issue by Seenivasanseeni** [gogs/gogs#5777]
When you freshly installed gogs from scratch, you are in the install ui page and you have filled in the details and clicked Install. After the successful completion of setup in the backend server, the page redirects to "localhost:3000/user/login" which will fail when gogs is installed in docker/cloud platforms.
Problem: redirection is made to "localhost:3000/user/login"
Possible solution: based on the current ip/domain name/(HTTP header field HOST), we can redirect correctly. 
If this issue is worth fixing, ping me. I can work on this.

**Comment by unknwon** [comment]
Please be respectful to the issue template.

FYI, it depends on "Application URL" you set in the installation form.
