### ISSUE TITLE
docker version push commit to server fail

### ISSUE THREAD

**Issue by muziling** [gogs/gogs#5779]
Gogs 0.11.89.0728,  docker also have default ENV setting  GOGS_CUSTOM=/data/gogs
Error seems not read mysql url from /data/gogs/conf/app.ini , and default to 127.0.0.1

> POST git-receive-pack (167707 bytes)
POST git-receive-pack (167707 bytes)
remote: 2019/08/13 13:42:39 [ WARN] Custom config '/app/gogs/custom/conf/app.ini' not found, ignore this if you're running first time        
remote: Gogs: Internal error        
remote: GetProtectBranchOfRepoByName [repo_id: 6, branch: master]: dial tcp 127.0.0.1:3306: connect: connection refused        
Pushing to http://192.168.222.8:13000/muziling/forum2.git
To http://192.168.222.8:13000/muziling/forum2.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://192.168.222.8:13000/muziling/forum2.git'

**Comment by unknwon** [comment]
>remote: 2019/08/13 13:42:39 [ WARN] Custom config '/app/gogs/custom/conf/app.ini' not found, ignore this if you're running first time

This line tells me that your Gogs docker container does not have mounted volume (that contains configuration file) in place.
