### ISSUE TITLE
新建项目，给一个账号只读权限，拉不了代码，报没有权限错误

### ISSUE THREAD

**Issue by guozhenyi** [gogs/gogs#5780]
操作方式：
1. 新建项目A
2. 仓库设置-增加写作者-给账号B增加只读权限
3. git pull 无法拉取代码
排查：
1. git ssh 配置正确，因为其他项目拉取代码正常。
2. 账号B在web端可以正常查看项目A。
3. 尝试账号B的权限为可写、管理员，依然无法拉取代码。

错误信息：
Gogs: Repository does not exist or you do not have access
fatal: Could not read from remote repository.

排查原因以后，我认定可能是gogs权限同步问题。
然后重启了gogs，perfect，问题解决了！

所以认定，gogs在web端权限和git协议权限同步方面有bug。
具体原因希望开发者兄弟们排查一下。

**Comment by unknwon** [comment]
Please be respectful to the issue template.

**Comment by guozhenyi** [comment]
好装啊，母语都不会说了？
