### ISSUE TITLE
Sending email to non-active users

### ISSUE THREAD

**Issue by Supme** [gogs/gogs#5782]
1. Go to any repository 
2. Click on 'Watch '
3. Set this account is not active and prohibited to login
4. But notifications sending to his email

**Expected behavior**

**Screenshots**

**Additional context**

- Gogs version (or commit ref):  0.11.86.0130
- Git version: 2.1.4
- Operating system: linux
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: i`m not admin
- Log gist (usually found in `log/gogs.log`):

**Comment by Supme** [comment]
And removing people from organization does not remove them from repository watchers.

**Comment by Supme** [comment]
Or/and make button "unwatch" for admin in repository watchers page.

**Comment by unknwon** [comment]
Thanks for the feedback!

I think the solution is as easy as check if user is active before add to the recipients.

**Comment by unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogs/gogs/pull/5788, please help test on `develop` branch.

**Comment by Supme** [comment]
I don't know if I want to remove users from observers when remove them from organization, or only make button "unwatch" for admin.
