### ISSUE TITLE
为什么git的环境已经配置好了还是一直显示找不到git命令

### ISSUE THREAD

**Issue by dearkz** [gogs/gogs#5784]
![image](https://user-images.githubusercontent.com/18300927/63136773-1ff50980-c006-11e9-9676-caa181b8bb64.png)
如图，set path都显示有配置了，但还是一直提示找不到git

**Comment by fawdlstty** [comment]
Is the deployment location local?If so, try restarting the gogs service

**Comment by dearkz** [comment]
thx

**Comment by unknwon** [comment]
Please be respectful to the issue template.
