### ISSUE TITLE
No SQLite support in latest Rasperry Pi archives (0.11.91)

### ISSUE THREAD

**Issue by BoboTiG** [gogs/gogs#5790]
**Describe the bug**

I upgraded from `0.11.86` to `0.11.91` and it seems the archives are missing SQLite3 support.
Archive used: `https://dl.gogs.io/0.11.91/gogs_0.11.91_raspi_armv7.zip`.

**Additional context**

- Gogs version (or commit ref): `0.11.91.0811`
- Git version: `2.1.4`
- Operating system: Raspberry Pi v2
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: local installation
- Log gist (usually found in `log/gogs.log`):

        2019/08/25 14:13:21 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: connect to database: this binary version does not build support for SQLite3

**Comment by geofreak** [comment]
I have the same problem on my raspberry pi 3.

**Comment by unknwon** [comment]
Sorry I didn't notice that. Recompiling right now.

**Comment by unknwon** [comment]
Archives in GitHub releases and https://dl.gogs.io are updated!

**Comment by HattDroid** [comment]
Hi,

Same issue with Raspberry Pi Zero here.
I guess gogs_0.11.91_linux_armv5.zip should be updated too.

Thanks.

**Comment by HattDroid** [comment]
Hi,

Same issue with Raspberry Pi Zero here.
I guess gogs_0.11.91_linux_armv5.zip and 
gogs_0.11.91_linux_armv6.zip  should be updated too.

Thanks.

**Comment by unknwon** [comment]
Hi, armv5 v6 never had support for SQLite, because I don’t have machine in that architecture.

**Comment by HattDroid** [comment]
Thanks for the quick answer.
I used to run this package gogs_0.11.86_raspi2_armv6.zip which had support for SQlite3.

In any case, I've tried running the armv7 flavor of version 0.11.91 and it's working perfectly fine on my Pi Zero, there must be some hard compatibility between v6 and v7. Sorry for the inconvenience and thanks for the work, it's all good now. 👍

**Comment by unknwon** [comment]
Raspi armv7 was mislabeled as v6, corrected since last release :D
