### ISSUE TITLE
crashing and not able to serve any request when launched though opensvc

### ISSUE THREAD

**Issue by s0xx** [gogs/gogs#5791]
Hi.

I installed gogs arm version on a raspberry pi 4, with it own system user.
It runs fine when i launch it with ./gogs web as "appgogs" user.

Then I added a service on opensvc to manage gogs through it own IP.

When i run the opensvc service, including only IP 192.168.0.233, then start gogs manually from the shell it works fine.
```
# sudo -u appgogs /app/gogs/scripts/start.sh
nohup: appending output to 'nohup.out'
# ps -ef | grep gogs
appgogs  24464     1 19 20:14 pts/2    00:00:00 /app/gogs/products/gogs/gogs web
```
I can access it through 192.168.0.233:3000. It's OK.

When i add gogs to the opensvc service, in order to handle it automatically, gogs crash when it serve the first HTTP request, without any information in logs.
I'm sure opensvc run gogs with the correct user as i can see the process before doing the 1st http request.

Here opensvc configuration
```
# svcmgr -s gogs print config
[DEFAULT]
id = 88a6a85e-603f-4828-b107-43c3e5b1942d

[ip#0]
ipname = 192.168.0.233
ipdev = wlan0
monitor = true

[app#0]
start = /app/gogs/scripts/start.sh
check = /app/gogs/scripts/check_gogs.sh

```
Then i start it

```
# svcmgr -s gogs start --local --rid app#0
picluster4b0.gogs.app#0       exec /app/gogs/scripts/start.sh as user appgogs
picluster4b0.gogs.app#0       2019/08/26 20:16:46 [TRACE] Custom path: /app/gogs/products/gogs/custom
picluster4b0.gogs.app#0       2019/08/26 20:16:46 [TRACE] Log path: /data/gogs/logs
picluster4b0.gogs.app#0       2019/08/26 20:16:46 [TRACE] Build Time: 2019-08-12 02:38:47 UTC
picluster4b0.gogs.app#0       2019/08/26 20:16:46 [TRACE] Build Git Hash: c154721f4a8f3e24d2f6fb61e74b4b64529255c2
picluster4b0.gogs.app#0       2019/08/26 20:16:46 [TRACE] Log Mode: File (Info)
picluster4b0.gogs.app#0       2019/08/26 20:16:46 [ INFO] Gogs 0.11.91.0811
picluster4b0.gogs.app#0       start done in 0:00:02.319432 ret 0


# ps -ef | grep gogs
appgogs  24959     1  2 20:16 ?        00:00:00 /app/gogs/products/gogs/gogs web

```

The process stay UP til i perform a request to 192.168.0.232:3000.
It crash without any information in the logs.

I reproduced the issue2 time without to be able to identify the root cause.

**Comment by unknwon** [comment]
>picluster4b0.gogs.app#0       2019/08/26 20:16:46 [TRACE] Log path: /data/gogs/logs

Your log is here. `/data/gogs/logs/gogs.log`.
