### ISSUE TITLE
commit detail page suggest adding a pagination or display section

### ISSUE THREAD

**Issue by zhangyiqiu** [gogs/gogs#5792]
**I have 100+ files and 32000+ rows code in this commit**

**Screenshots**
![image](https://user-images.githubusercontent.com/22910338/63830174-12dd0080-c99e-11e9-9203-74d23bb8566e.png)

**Additional context**
- Gogs version (or commit ref): 0.11.91.0811
- Git version: 
- Operating system: 
- Database (replace `[ ]` with `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes
  - [ ] No
- Log gist (usually found in `log/gogs.log`):

**Comment by unknwon** [comment]
Thanks for the feedback!

I think this is the same as https://github.com/gogs/gogs/issues/4986.
