### ISSUE TITLE
web title display not correct

### ISSUE THREAD

**Issue by dingxiaobo** [gogs/gogs#5800]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [中文](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please do not end your title with a question mark or period.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 0.11.86.0130
- Git version: 2.x
- Operating system: centos7
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [ ] No: explain why
- Log gist (usually found in `log/gogs.log`):

## Description

Web title display not correct while I using version number started commit message
-------------------------------------
![image](https://user-images.githubusercontent.com/23743074/64467408-cb4b3700-d14a-11e9-9f1b-72aa151a74cd.png)
![image](https://user-images.githubusercontent.com/23743074/64467444-28df8380-d14b-11e9-9c77-41a364dcf663.png)

...

**Comment by unknwon** [comment]
Please be respectful to the issue template.

>Can you reproduce the bug at try.gogs.io:
