### ISSUE TITLE
index page url generator error

### ISSUE THREAD

**Issue by hak1985** [gogs/gogs#5805]
i migrate https://github.com/apachecn/AiLearning to my gogs, in index page, the generat url from README.md was incorrect, like "<td><a href="docs/ml/xxx.md" rel="nofollow"></a></td>"
but this href based on https://xxxx/Awesome/AiLearning wa not an correct url,  correct href should be "https://xxxx/Awesome/AiLearning/src/master/docs/ml/xxx.md", seems missing "src/master"

**Comment by unknwon** [comment]
Please be respectful to the issue template.
