### ISSUE TITLE
Use Last-Modified HTTP header for raw files

### ISSUE THREAD

**Issue by mdhowle** [gogs/gogs#5811]
I would like to request `Last-Modified` HTTP header be added when displaying raw files.  This allows wget and other utilities to download the file only if necessary.

**Is your feature request related to a problem? Please describe.**
I would like to download (e.g. wget -N https://gogs/foo/bar/raw/master/somefile) iff the file was modified.

**Describe the solution you'd like**
Add the `Last-Modified` to HTTP headers with the latest time the file was modified in the specified branch: `git log -1 --format="%ad" -- somefile`

**Describe alternatives you've considered**
 
1.  Use releases.  This requires some scripting to determine the latest release version, download and extract, and deploy to the location.
2.  Use `git pull`. Requires installing git on machines that wouldn't otherwise need it.
3.  Download the file regardless of changes.  This would waste bandwidth if the file is large or bandwidth is limited.

**Comment by unknwon** [comment]
Thanks for the feedback! I think it will be a good addition!

**Comment by unknwon** [comment]
This is claimed to be fixed by merging #5827, please help test on `develop` branch or https://try.gogs.io.
