### ISSUE TITLE
No wiki information about Gogs + SeLinux solutions

### ISSUE THREAD

**Issue by Fohroer** [gogs/gogs#5817]
Hello!

Since I haven't found any informations about configuring Gogs to run on CentOS 7 and also using SELinux to prevent attacks I'm asking for best practices to do this in public cloud.
Can Gogs and SELinux run at the same time. If not, maybe you'd recommend me to use another distro and AppArmor? Maybe OpenSUSE or Ubuntu?

**Comment by unknwon** [comment]
Hi, just use CentOS 7, is good enough.
