### ISSUE TITLE
go get gogs fails: Invalid psuedo-version

### ISSUE THREAD

**Issue by kstenerud** [gogs/gogs#5819]
**Describe the bug**
Typing `go get -u github.com/gogs/gogs` as per the instructions at https://gogs.io/docs/installation/install_from_source fails with the following error:

```
go: github.com/go-xorm/xorm@v0.7.1-0.20180606084314-a8bd843a55a7 requires
	github.com/go-xorm/core@v0.0.0-20180322150003-0177c08cee88: invalid pseudo-version: does not match version-control timestamp (2018-03-22T14:29:44Z)
```
**To Reproduce**

1. Type `go get -u github.com/gogs/gogs`

**Expected behavior**
It gets gogs, as described in the instructions

**Additional context**

- Gogs version (or commit ref): Latest, I assume
- Git version: 2.17.1
- Operating system: Ubuntu 18.04
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: this is an installation problem
- Log gist (usually found in `log/gogs.log`):

There is no log.

**Comment by unknwon** [comment]
Hi, which Go version you are using? Can you show the output of your `go env` command?

Gogs uses vendor which should not fetch any dependency over the network and I don't know what "go" command is doing recently. 🤕

**Comment by unknwon** [comment]
Hi, I just tested on a fresh machine with `go get -u github.com/gogs/gogs` with `GO111MODULE=auto`.

Gogs has not yet enabled Go modules.
