### ISSUE TITLE
try.gogs.io emails disclosure

### ISSUE THREAD

**Issue by ybudimirov** [gogs/gogs#5822]
**Issue description:**
try.gogs.io emails disclosure

**To Reproduce**
1. Go to 'try.gogs.io'
2. Register account
3. Login
4. Click on 'Explore' -> 'Users'
or open link: https://try.gogs.io/explore/users
5. See users emails

**Expected behavior**
Don't show emails

**Comment by unknwon** [comment]
I think this is duplicated to https://github.com/gogs/gogs/issues/3358.
