### ISSUE TITLE
Error when pushing commit in GitHub Desktop to gogs

### ISSUE THREAD

**Issue by ghost** [gogs/gogs#5825]
I'm trying to commit a very minor change to gogs via Github desktop. This works fine in the command line by doing the following;
setting my file directory
git add .
git commit -m

The commit will come up on the gogs repository as expected. However, when I try and push this via github, I get the following error;

![image](https://user-images.githubusercontent.com/56733923/67109504-93fb8b80-f1c8-11e9-9271-8c6bb3d99da6.png)

in github desktop.

I have tried the suggested solutions from other threads e.g. adding my username to the remote url/removing saved passwords in credential manager etc. so any other solutions would be greatly appreciated.

I'm using Windows 10 Pro, version 1809, 64-bit operating system.
Gogs version: 0.11.91.0811

Unfortunately, I can't reproduce this bug, because of the different servers.

**Comment by unknwon** [comment]
Hi,

> This works fine in the command line by doing the following;
> setting my file directory
> git add .
> git commit -m

To me, these commands will only commit changes locally, but not push to your Gogs server?

> I have tried the suggested solutions from other threads e.g. adding my username to the remote url/removing saved passwords in credential manager etc. so any other solutions would be greatly appreciated.

Can you give concrete examples?

---

GitHub Desktop is meant (guaranteed) to work with GitHub that's why it's not called Git Desktop.

**Comment by morooney99** [comment]
The commands definitely push to gogs so that’s not a problem. Any change can be an example, it can’t even push a line of comments.

**Comment by unknwon** [comment]
I was asking examples of solutions you tried.

**Comment by morooney99** [comment]
Sorry, adding my username to the origin url, updating passwords, removing passwords from credential manager, increasing the buffer size via:
git config --system http.postBuffer 52428800
Clearing git passwords via:
$ git credential-cache exit

**Comment by unknwon** [comment]
401 means no credentials or credentials are not accepted. Try adding password to the origin URL, or take a look itnext.io/how-to-use-github-desktop-with-gitlab-cd4d2de3d104.

**Comment by morganrooney28** [comment]
How do you mean add password to the origin url?

**Comment by unknwon** [comment]
1. Have you read the article I linked?
2. How did you add your username to origin URL?

**Comment by morganrooney28** [comment]
I added the username to the origin url via;
git remote remove origin
git remote add origin <new url with my username in it>

Yes I've read it but trying to use gogs not gitlab, am I getting confused somewhere?

**Comment by unknwon** [comment]
> I added the username to the origin url via;
> git remote remove origin
> git remote add origin

Please show the exact full URL with redacted domain name. Otherwise, I couldn't help you.



> Yes I've read it but trying to use gogs not gitlab, am I getting confused somewhere?

The idea is the same, to generate a personal access token and put in the origin URL.
