### ISSUE TITLE
Dont work with reverse proxy port 80

### ISSUE THREAD

**Issue by Caaruzo** [gogs/gogs#5826]
Greetings, yesterday i setup a gogs in a VM. Its on the Top of an Debian 10 with an MariaDB and Apache2.

Gogs itself is running on port 3000. Now i added a reverse proxy on apache default config, so i could access it from intranet with hostname only.

> <VirtualHost *:80>
>         DocumentRoot /var/www/html
> 
>         ErrorLog ${APACHE_LOG_DIR}/error.log
>         CustomLog ${APACHE_LOG_DIR}/access.log combined
> 
>         ProxyPreserveHost On
>         ProxyRequests off
>         ProxyPass / http://127.0.0.1:3000
>         ProxyPassReverse / http://127.0.0.1:3000
> </VirtualHost>

i also enabled apache modules proxy & proxy_http.
When i access the server via http://hostname:3000 everything is fine.

When i try http://hostname it ends up look like this:

![grafik](https://user-images.githubusercontent.com/39491096/67143802-80573000-f26f-11e9-8324-1ad4bf987fe5.png)

Someone know what i missed, thats not noticed in documentation maybe? xD

Thx

**Comment by unknwon** [comment]
Looks like you don't need "DocumentRoot": https://gogs.io/docs/intro/faqs#how-do-i-use-apache-2-with-reverse-proxy%3F, but I never used Apache, maybe I'm wrong.

**Comment by Caaruzo** [comment]
Removing this dont change anything ofc, cause gogs isnt a apache served service^^

**Comment by unknwon** [comment]
Could you open the Chrome developer tool, network tab, then refresh and post a screenshot here?

**Comment by Caaruzo** [comment]
:o on chrome it says 

```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: DNS lookup failure for: 127.0.0.1:3000user
```
![grafik](https://user-images.githubusercontent.com/39491096/67544494-ef140d80-f6f5-11e9-8341-4e27149cb4c1.png)

**Comment by unknwon** [comment]
>127.0.0.1:3000user

Looks like you're missing a slash `/` at the end. You probably should use `http://127.0.0.1:3000/` in your proxy config.

**Comment by Caaruzo** [comment]
ha that worked. Awesome. thx.
