### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by deimosfr** [gogs/gogs#583]
Hi,

I'm using Gogs since several months now and recently saw that packages are now available. I decided to use Debian ones.

Installation works like a charm and I decided to start from scratch to avoid failing upgrades. The problem is, on a new installation I can:
- Configure gogs with the install menu
- Add my SSH key to my personal user
- Create a repository

However, when I want to clone, I got errors in my logs:

```
==> gogs.log <==
[xorm] [info]  2014/10/26 09:37:16.545323 [sql] SELECT a.* FROM `user` AS a, public_key AS b WHERE a.id = b.owner_id AND b.id=? [args] [2]

==> serv.log <==
2014/10/26 09:37:16 [serve.go:100 runServ()] [F] Fail to get user by key ID(2): Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: NO)
```

This error message looks like a MySQL error message. However the credentials in the configuration are not set with root and no password.

Any idea ?

Thanks

**Comment by kossa** [comment]
Hi,
I dont know where can I add question, so I have the same problem I cannot clone my repo via SSH, I added my pub key but nothing I got : 
```
Cloning into 'MY_REPO'...
git@107.170.219.51's password: 

Permission denied (publickey,password).
fatal: Could not read from remote repository.
.....
Please make sure you have the correct access rights
and the repository exists.
```
Where is the problem ?

**Comment by Unknwon** [comment]
Hi @kossa,

Based on the error:

> Permission denied (publickey,password).

I think your SSH server denied your access, and your clone request didn't even get to Gogs instance.
