### ISSUE TITLE
String "<>" is not usable in pull requests

### ISSUE THREAD

**Issue by AniiXx** [gogs/gogs#5841]
**Describe the bug**
When a pull request is created and "<>" is used within the pull request title an internal server error occures.

**To Reproduce**
1. Go to any repo of your choice
2. Click the pull requests link
3. Create new pull request using "<>" in title

**Expected behavior**
I expected the pull request title to be escaped and the request to be handled like any other pull request would be.

**Additional context**

- Gogs version (or commit ref): 0.11.91.0811
- Git version: 2.21.0.windows.1
- Operating system: Windows 10 Pro x64 (10.0.18362 Build 18362)
- Database (replace `[ ]` with `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: There is no repo available that would allow a pull request.
- Log gist (usually found in `log/gogs.log`):
2019/10/26 09:41:57 [ERROR] [...g/context/context.go:191 ServerError()] NewPullRequest: newIssue: Error 1062: Duplicate entry '1-71' for key 'UQE_issue_repo_index'

**Comment by unknwon** [comment]
Thanks for your feedback!

> * [x]  No: There is no repo available that would allow a pull request.

You can create a repository with two branches, and make random change to send a PR.

>   2019/10/26 09:41:57 [ERROR] [...g/context/context.go:191 ServerError()] NewPullRequest: newIssue: Error 1062: Duplicate entry '1-71' for key 'UQE_issue_repo_index'

This error a bit surprise, would like to a reproduce on demo site.
