### ISSUE TITLE
git URL迁移外部仓库passphase

### ISSUE THREAD

**Issue by iMinusMinus** [gogs/gogs#5842]
您的产品支持迁移外部仓库，且支持HTTPS和GIT。
当我想迁移github仓库，使用git URL，没有地方输入passphase，而我的RSA私钥需要密码。在没有输入密码的情况下，gogs提示“您没有获得导入本地仓库的权限。”。
可否增加一个功能，当输入的URL是git类型URL时，提供一个可选的passphase输入？

ps: HTTPS提示“迁移失败：Clone: exit status 128 - fatal: unable to access 'https://@github.com/id/repo.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443”
pps: 没有密码保护的私钥还是不太安全，所以不想清除密码。

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
