### ISSUE TITLE
docker安装失败

### ISSUE THREAD

**Issue by muziling** [gogs/gogs#5844]
docker升级镜像后，进入界面自动跳到首次运行安装程序
然后和以前一样的配置，提交后提示：
应用配置保存失败：open /app/gogs/custom/conf/app.ini: no such file or directory

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
