### ISSUE TITLE
Provide Guide for Gogs Server using pagekite

### ISSUE THREAD

**Issue by Argzero** [gogs/gogs#5847]
**Describe the bug**
To correctly connect over HTTPS through pagekite, use an SSL supported pagekite subdomain.  You should NOT set the certificate info in the GOGS app.ini; this breaks the SSL from pagekite's service. Doing this allows SSL / HTTPS for your pagekite GOGS server.

Operating system: Windows 7
Database (replace `[ ]` with `[x]`):
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] PostgreSQL
  - [x] SQLite

Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [x] No: explain why
  - Need root access to test. You are welcome to try this using a pagekite free trial and free ssl subdomain.

Let me know if you need the logs. I don't think they are necessary and would prefer to keep the contents of my logs private for security reasons.

**Comment by Argzero** [comment]
An alternative course of action is to find some way for Gogs itself to handle external SSL support in this way.

**Comment by unknwon** [comment]
Hi... what is about?

**Comment by Argzero** [comment]
https://pagekite.net/
