### ISSUE TITLE
高并发访问gogs出现500错误

### ISSUE THREAD

**Issue by emmafeng17** [gogs/gogs#5858]
[ERROR] [...tes/repo/download.go:58 SingleDownload()] ServeBlob: short write
 [ERROR] [...g/context/context.go:191 ServerError()] GetBranches: pipe2: too many open files
 [ERROR] [...g/context/context.go:191 ServerError()] GetTags '/usr1/gogs-repositories/root/gradle.git': open /dev/null: too many open files
[ERROR] [.../pkg/context/repo.go:341 func1()] GetBranchCommit: fork/exec /usr/bin/git: too many open files
[ERROR] [...tes/repo/download.go:58 SingleDownload()] ServeBlob: short write
[ERROR] [...g/context/context.go:191 ServerError()] GetTags '/usr1/gogs-repositories/root/gradle.git': pipe2: too many open files
[ERROR] [...g/context/context.go:191 ServerError()] GetTags '/usr1/gogs-repositories/root/gradle.git': fork/exec /usr/bin/git: too many open files
[ERROR] [...tes/repo/download.go:58 SingleDownload()] ServeBlob: short write
 [ERROR] [...tes/repo/download.go:58 SingleDownload()] ServeBlob: short write
[ERROR] [...g/context/context.go:191 ServerError()] GetBranches: fork/exec /usr/bin/git: too many open files
 [ERROR] [...tes/repo/download.go:58 SingleDownload()] ServeBlob: short write

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
