### ISSUE TITLE
How to hide all explore content to the ones who were not signing in?

### ISSUE THREAD

**Issue by No54** [gogs/gogs#5861]
How to hide all explore content to the ones who were not signing in?
请问如何让不登录的人看不到所有发现的内容，即所有的人员、组织、以及公开的代码？

We established a GOGS on our cloud. 
我们在云上搭了一个GOGS

But we find that if one were not signed in, explore content would also showed on the web.
但是我们发现，如果不登录，仍然可以看到发现里的内容

Is there any setting about this promotion？ 
有关于这个改进的设置吗？

Thanks！
谢谢！

**Comment by unknwon** [comment]
Hi, I think this is duplicated to https://github.com/gogs/gogs/issues/5080.
