### ISSUE TITLE
web edit files error

### ISSUE THREAD

**Issue by cyanBone** [gogs/gogs#5867]
**Describe the bug**

web edit files error

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

- Gogs version (or commit ref): 0.11.91.0811
- Git version: 1.8.3.1
- Operating system: centos7.2
- Database (replace `[ ]` with `[x]`):
  - [ x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes: provide example URL
  - [ x] No: explain why
- Log gist (usually found in `log/gogs.log`):

2019/11/18 20:24:29 [ERROR] [...outes/repo/editor.go:280 editFilePost()] Failed to update repo file: update local copy branch[master]: git clone master: mkdir data: permission denied
2019/11/18 20:25:07 [ERROR] [...outes/repo/editor.go:280 editFilePost()] Failed to update repo file: update local copy branch[master]: git clone master: mkdir data: permission denied
2019/11/18 20:26:54 [ERROR] [...outes/repo/editor.go:280 editFilePost()] Failed to update repo file: update local copy branch[master]: git clone master: mkdir data: permission denied
2019/11/18 22:55:55 [ERROR] [...outes/repo/editor.go:280 editFilePost()] Failed to update repo file: update local copy branch[master]: git clone master: mkdir data: permission denied
2019/11/18 23:05:17 [ERROR] [...outes/repo/editor.go:280 editFilePost()] Failed to update repo file: update local copy branch[master]: git clone master: mkdir data: permission denied
2019/11/18 23:05:22 [ERROR] [...outes/repo/editor.go:280 editFilePost()] Failed to update repo file: update local copy branch[master]: git clone master: mkdir data: permission denied
2019/11/18 23:20:38 [ERROR] [...outes/repo/editor.go:280 editFilePost()] Failed to update repo file: update local copy branch[master]: git clone master: mkdir data: permission denied
![QQ截图20191118235539](https://user-images.githubusercontent.com/51378072/69068028-0cbb6500-0a5f-11ea-9393-ce718d777845.png)

**Comment by cyanBone** [comment]
@unknwon Just restart gogs and the problem will be solved

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread because I think this is a process permission issue and this repository has no control over it.
