### ISSUE TITLE
Private repositories are hidden in the organization's view

### ISSUE THREAD

**Issue by dezzeus** [gogs/gogs#5869]
Within the organization's page I was expecting to find our private repositories, but they weren't there; only the public ones. I happened to find them only throught the generic "explore" menù.

The organizazion's page should list only the public repositories when the user isn'n logged in or if he/she doesn't have the permissions. Otherwise both the public and private ones should be listed.

Gogs version 0.11.96.1107

**Comment by unknwon** [comment]
Hi, can you reproduce it on the demo site as request in [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by dezzeus** [comment]
Yes, here you are:

- [Organisation's page](https://try.gogs.io/qwerty_inc) with only the `public_repo` showed despite both you and I are "owners".
- The [Explore page](https://try.gogs.io/explore/repos?q=private_repo) with the `private_repo` shown.

**Comment by unknwon** [comment]
Thanks! Will take a look this week.

**Comment by lightning-zgc** [comment]
This also happend in latest docker image ([`7058b922`](https://hub.docker.com/layers/gogs/gogs/latest/images/sha256-7058b9225aadebb4d467ed3b48625b6820beeda7d54722b80f12f3a44e666063))  
But it's ok in 0.11.91 docker image ([`5d2c19df`](https://hub.docker.com/layers/gogs/gogs/0.11.91/images/sha256-5d2c19df2eb154ea088e35081f6549851440aace1d49c8089d48ff2adeb97c71))

**Comment by unknwon** [comment]
@lightning-zgc:
> But it's ok in 0.11.91 docker image

Interesting... I will verify, not obvious to me any change related to this bug after 0.11.91 release.

**Comment by alimy** [comment]
Commit a PR #5890 to fixes this bug.
```
docker pull bitriory/gogs:latest  # try test the patch just pull this images
```
