### ISSUE TITLE
Can't browse repositories from user's profile page that was shared with me

### ISSUE THREAD

**Issue by shahariaazam** [gogs/gogs#5873]
For example,

User "X" has a repository and he is the owner. Also I am a contributor to that repository.

But when I go to his profile GIT_URL/X then in the repository tab I can't see those repositories that I should see because I have the permission also in those repository.

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
