### ISSUE TITLE
After upgrade gogs no longer read config from /etc/gogs/conf/app.ini

### ISSUE THREAD

**Issue by tschallacka** [gogs/gogs#5874]
I had an old gogs install made via https://www.digitalocean.com/community/tutorials/how-to-set-up-gogs-on-ubuntu-14-04 and have been happily using it for more than a year.

Since I want that snazzy backup command that was introduced along the line, I need to upgrade.
I used this tutorial for it: https://gogs.io/docs/upgrade/upgrade_from_binary

All fine and dandy, I get gogs running, but my main gripe now is: It doesn't read the config from /etc/gogs/conf/app.ini but demands it from /opt/gogs/custom/conf/app.ini

The server starts all fine, but I'd rather not have one config file in a place where I don't expect it. How can I get gogs to use config file in /etc?

I added in some typos to get a print out which config file was used.

> 2019/11/28 17:41:49 [FATAL] [...g/setting/setting.go:435 NewContext()] Fail to load custom conf '/opt/gogs/custom/conf/app.ini': key-value delimiter not found: asdfasdf;a[pd;fpdfsdf

is there a way to force gogs to use another config file, like php has the -c flag, or is there something else I need to change, or is this a bug?

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

./gogs -v
Gogs version 0.11.91.0811
```

**Comment by unknwon** [comment]
Hi, thanks for the feedback! But I think this should be posted to the forum: https://discuss.gogs.io. The issue template makes things crystal clear this is not the place for asking help.

---

To answer your question: 

> is there a way to force gogs to use another config file, like php has the -c flag, or is there something else I need to change, or is this a bug?

If you ever tried it... you'll know there is a `-c` flag :)

```
➜  gogs git:(master) ./gogs web -h
...

OPTIONS:
   --port value, -p value    Temporary port number to prevent conflict (default: "3000")
   --config value, -c value  Custom configuration file path (default: "custom/conf/app.ini")
```
