### ISSUE TITLE
a 404 error when i try to close a  milestone but it's closed

### ISSUE THREAD

**Issue by unimits** [gogs/gogs#5875]
**Describe the bug**
a 404 error when i try to close a  milestone but it's closed.

**Gogs version or commit**
0.11.91.0811

**Git version**

```
$ git version
git version 1.7.1
```

**Operating system**
centos 6.5

**Database**
sqllite

**To Reproduce**
1. Go to 'milestones list'
2. Click on 'close a milestone'
3. See error

**Can you reproduce the bug at https://try.gogs.io?**
yes, I reproduced the bug. below is the link:
https://try.gogs.io/nodenota/test/milestones%3Fstate=closed

**Expected behavior**
the milestone was closed and forward to a success page.

**Actual behavior**
404 error

**Screenshots**
![{5AB85E69-F965-4797-8346-539E1523D0C4}_20191130144127](https://user-images.githubusercontent.com/58244032/69897017-d516bc00-1380-11ea-8178-32b0ddca8975.jpg)

**Additional context**
there is no any error messages in gogs.log.

**Comment by unknwon** [comment]
I think this is duplicated to https://github.com/gogs/gogs/issues/5677.
