### ISSUE TITLE
Support of Sentry releases

### ISSUE THREAD

**Issue by yeleleo** [gogs/gogs#5876]
To support webhook configuration for Sentry Logs as 
https://docs.sentry.io/workflow/releases/?platform=python

or github-like API to connect gogs

**Comment by unknwon** [comment]
Hi, thanks for the feedback but I don't what's the thing you're asking for specifically (I never used Sentry), can you be more specific?

**Comment by yeleleo** [comment]
Sentry is a tool (on-demand too) which used for crash reporting. They support releases and integrations with repositories which can be used for better understanding of the reasons for any crash. So if you are able to link release to the commit you would be able to simply track all the crashes.

**Comment by unknwon** [comment]
Thanks, so what does “webhook configuration for Sentry Logs” mean exactly?
