### ISSUE TITLE
gogs会自己访问一些奇怪的地址，怎么回事

### ISSUE THREAD

**Issue by halcy0n90** [gogs/gogs#5879]
日志如下

[Macaron] 2019-11-29 12:08:44: Started HEAD http://123.125.114.144/ for 113.58.245.143
[Macaron] 2019-11-29 12:08:44: Completed HEAD http://123.125.114.144/ 302 Found in 979.8碌s
[Macaron] 2019-11-29 12:08:45: Started HEAD http://123.125.114.144/user/login for 113.58.245.143
[Macaron] 2019-11-29 12:08:45: Completed HEAD http://123.125.114.144/user/login 200 OK in 1.9999ms
[Macaron] 2019-11-29 12:08:48: Started CONNECT www.baidu.com:443 for 175.184.165.16
[Macaron] 2019-11-29 12:08:48: Completed CONNECT www.baidu.com:443 404 Not Found in 1.9624ms
[Macaron] 2019-11-29 12:08:51: Started GET http://www.rfa.org/english/ for 36.32.3.98
[Macaron] 2019-11-29 12:08:51: Completed GET http://www.rfa.org/english/ 302 Found in 0s
[Macaron] 2019-11-29 12:08:51: Started GET http://www.epochtimes.com/ for 180.95.238.138
[Macaron] 2019-11-29 12:08:51: Completed GET http://www.epochtimes.com/ 302 Found in 972.4碌s
[Macaron] 2019-11-29 12:08:51: Started CONNECT www.ipip.net:443 for 221.11.60.154
[Macaron] 2019-11-29 12:08:51: Completed CONNECT www.ipip.net:443 404 Not Found in 2.0021ms
[Macaron] 2019-11-29 12:08:53: Started GET http://www.123cha.com/ for 113.128.104.60
[Macaron] 2019-11-29 12:08:53: Completed GET http://www.123cha.com/ 302 Found in 976碌s
[Macaron] 2019-11-29 12:08:54: Started CONNECT www.voanews.com:443 for 124.235.138.250
[Macaron] 2019-11-29 12:08:54: Completed CONNECT www.voanews.com:443 404 Not Found in 997.1碌s
[Macaron] 2019-11-29 12:08:55: Started GET http://www.123cha.com/user/login for 113.128.104.60
[Macaron] 2019-11-29 12:08:55: Completed GET http://www.123cha.com/user/login 200 OK in 1.9759ms
[Macaron] 2019-11-29 12:08:57: Started GET http://www.wujieliulan.com/ for 27.224.136.210
[Macaron] 2019-11-29 12:08:57: Completed GET http://www.wujieliulan.com/ 302 Found in 673.7碌s
[Macaron] 2019-11-29 12:08:58: Started GET http://boxun.com/ for 221.198.80.211
[Macaron] 2019-11-29 12:08:58: Completed GET http://boxun.com/ 302 Found in 1.0026ms
[Macaron] 2019-11-29 12:09:01: Started CONNECT cn.bing.com:443 for 222.82.59.252
[Macaron] 2019-11-29 12:09:01: Completed CONNECT cn.bing.com:443 404 Not Found in 975.3碌s

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
