### ISSUE TITLE
GetFullCommitID error while mirroring repo

### ISSUE THREAD

**Issue by dangyajun** [gogs/gogs#5881]
直接上图:
![image](https://user-images.githubusercontent.com/5320386/70403863-1ee35e80-1a73-11ea-9106-905310ed9af9.png)

**Comment by dangyajun** [comment]
version number is : 0.11.91

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
