### ISSUE TITLE
Dashboard doesnt't update even though  push is successful

### ISSUE THREAD

**Issue by INNKCake** [gogs/gogs#5886]
Hello,

the similar problem I'm facing is described here:
https://gogs.io/docs/intro/troubleshooting.html - Push succeeds, but the dashboard timeline doesn’t update
But I'm using git over HTTPS, not SSH, so this doesn't look like my case.
I've already tried to re-sync all hooks, but that did not helped. 

Macaron logs show something interesting when I push:
```
[Macaron] 2019-12-20 10:28:56: Started GET /pathto/repository.git/info/refs?service=git-receive-pack for 127.0.0.1
[Macaron] 2019-12-20 10:28:56: Completed GET /pathto/repository.git/info/refs?service=git-receive-pack 200 OK in 7.364803ms
[Macaron] 2019-12-20 10:28:57: Started POST /pathto/repository.git/git-receive-pack for 127.0.0.1
[Macaron] 2019-12-20 10:28:57: Completed POST /pathto/repository.git/git-receive-pack 401 Unauthorized in 3.888391ms
[Macaron] 2019-12-20 10:28:58: Started POST /pathto/repository.git/git-receive-pack for 127.0.0.1
[Macaron] 2019-12-20 10:28:58: Completed POST /pathto/repository.git/git-receive-pack 200 OK in 74.685221ms
```
For some reason POST returns 401 Unauthorized first time.

I've checked all permissions for git user, they seems fine.

**Gogs version**
0.11.91.0811
**Git version**
2.7.4
**Operating system**
 Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1050-gcp x86_64)
The system is running on Google Cloud Platform, with nginx reverse proxy set up.
**Database**
Sqlite3

**Comment by INNKCake** [comment]
I forgot to mention that database and repositories were migrated from another instance via _gogs backup_ and _gogs restore_.

**Comment by unknwon** [comment]
Hi, have you checked `path_to_gogs/log/hooks` to see if any errors there?

**Comment by INNKCake** [comment]
> 
> 
> Hi, have you checked `path_to_gogs/log/hooks` to see if any errors there?

Hello, there's no such log there.

**Comment by unknwon** [comment]
> Hello, there's no such log there.

What commands you used to conclude this?

---

If you go to any sub-directory (e.g. "<owner>/<repo>.git/hooks") of your repository root path:

https://github.com/gogs/gogs/blob/76b87b1bbd9dcbb1adf0192b1168905565fea774/conf/app.ini#L74-L76

What files do you see? (i.e. `ls -al`)

**Comment by INNKCake** [comment]
Sorry for delayed response.
> What commands you used to conclude this?
```
innkcake@ubuntu-taiga:/home/git/gogs/log$ ls -al
total 28
drwxr-xr-x 2 git git    4096 Dec 20 13:15 .
drwxr-xr-x 9 git ubuntu 4096 Dec 13 13:56 ..
-rw-r----- 1 git git    6885 Dec 20 12:23 gogs.log
-rw-r----- 1 git git    1010 Dec 13 14:04 gogs.log.2019-12-12
-rw-r----- 1 git git    2298 Dec 13 17:10 gogs.log.2019-12-13
-rw-r----- 1 git git     349 Dec 16 11:04 gogs.log.2019-12-16
-rw-r----- 1 git git       0 Dec 20 10:20 xorm.log
```
> If you go to any sub-directory (e.g. "/.git/hooks") of your repository root path:
> 
> https://github.com/gogs/gogs/blob/76b87b1bbd9dcbb1adf0192b1168905565fea774/conf/app.ini#L74-L76
> 
> What files do you see? (i.e. `ls -al`)
```
innkcake@ubuntu-taiga:/home/git/gogs-repositories/user/repo.git/hooks$ ls -al
total 68
drwxrwxr-x 2 git git 4096 Dec 13 13:56 .
drwxrwxr-x 6 git git 4096 Dec 13 13:56 ..
-rw-rw-rw- 1 git git  478 Dec  4 14:02 applypatch-msg.sample
-rw-rw-rw- 1 git git  896 Dec  4 14:02 commit-msg.sample
-rw-rw-rw- 1 git git 3327 Dec  4 14:02 fsmonitor-watchman.sample
-rw-rw-rw- 1 git git  106 Dec 16 10:45 post-receive
-rw-rw-rw- 1 git git  189 Dec  4 14:02 post-update.sample
-rw-rw-rw- 1 git git  424 Dec  4 14:02 pre-applypatch.sample
-rw-rw-rw- 1 git git 1638 Dec  4 14:02 pre-commit.sample
-rw-rw-rw- 1 git git 1492 Dec  4 14:02 prepare-commit-msg.sample
-rw-rw-rw- 1 git git 1348 Dec  4 14:02 pre-push.sample
-rw-rw-rw- 1 git git 4898 Dec  4 14:02 pre-rebase.sample
-rw-rw-rw- 1 git git  105 Dec 16 10:45 pre-receive
-rw-rw-rw- 1 git git  544 Dec  4 14:02 pre-receive.sample
-rw-rw-rw- 1 git git  109 Dec 16 10:45 update
-rw-rw-rw- 1 git git 3610 Dec  4 14:02 update.sample
```

**Comment by INNKCake** [comment]
I solved the issue by cloning existing repositories to local machine, re-creating them on server and pushing them back to server.
