### ISSUE TITLE
Official support share ssh port between docker and host

### ISSUE THREAD

**Issue by GongT** [gogs/gogs#5891]
**Describe the feature**
Share SSH port between docker and host, without using any trick, support this `feature` by default.

**Describe the solution you'd like**
Create a new "slave" mode:
1. do not start SSH
1. tell user to create a user (maybe `git`) with `useradd USERNAME`
1. tell user to append an argument to `docker run`: "-v/home/USERNAME:/master"
1. start a unsafe server (very like `telnet`), allow client to run `git-*` commands
1. write a client to connect this server *from host machine*
1. generate `authorized_keys` to invoke this client (instead of `/app/gogs/gogs`)

**Describe alternatives you've considered**
```bash
useradd git --groups docker --home-dir /data/gogs-data/git --uid 1000 --non-unique
echo '#!/bin/bash
CONTAINER_NAME="gogs"
exec docker exec -i -u git "-eUSER=$USER" "-eSSH_ORIGINAL_COMMAND=$SSH_ORIGINAL_COMMAND" "$CONTAINER_NAME" "/app/gogs/gogs" "$@"
' > /app/gogs/gogs
chmod a+x /app/gogs/gogs
```

In this tick:
* host uid is not changable
* must place a file at `/app/gogs/gogs`, not other place
* host user must have access to docker

**Comment by unknwon** [comment]
Thanks for the feedback!

I have few questions:
1. What problems will be solved by having this feature?
2. It seems to me like a deploy issue/feature, why should Gogs (as an application) take care of it?

**Comment by GongT** [comment]
Will resolve: **docker** deploy **must** create `/app/gogs/gogs` and `user git` on the **host** machine to share SSH port.

It caused by gogs itself not fully configuable.

**Comment by unknwon** [comment]
> **docker** deploy **must** create `/app/gogs/gogs`

You don't need to if you use Docker Volume: https://github.com/gogs/gogs/tree/master/docker#using-docker-19-volume-command



> `user git` on the **host** machine

Creating a separate user is already intentional to not run Gogs from `root`.

**Comment by GongT** [comment]
/app/gogs/gogs is not related with Docker Volume.

But the separate user can only use uid `1000` which already normally

**Comment by unknwon** [comment]
> /app/gogs/gogs is not related with Docker Volume.

What do you mean by "docker deploy must create /app/gogs/gogs"?

---

I think we need to go back to the original question, why is it important/needed to share SSH port between docker and host?
