### ISSUE TITLE
What is <gogs web>/debug web path and how can I turn it off

### ISSUE THREAD

**Issue by dexterxx-pl** [gogs/gogs#5906]
I've ran `nmap -n -p80,443 --script http-enum my.gogs.website.com`, gave me result:
```
Starting Nmap 7.40 ( https://nmap.org ) at 2020-01-18 23:30 CET
Nmap scan report for my.gogs.website.com (x.x.x.x)
Host is up (0.011s latency).
PORT    STATE SERVICE
80/tcp  open  http
443/tcp open  https
| http-enum:
|_  /debug/: Potentially interesting folder

Nmap done: 1 IP address (1 host up) scanned in 12.56 seconds
```

So I've checked `/debug` URL and found at least sensitive data:
* Command line `https://gogs.host.com/debug/pprof/cmdline` with my absolute path to Gogs installation on my server
* Other runtime and memory information's, that I'm sure they're are not necessary to be public and might be used in someking hack

**Affected version:** 0.11.91.0811
**Cmd line** `/home/user/somewhere/gogs.host.com/gogs/gogs web`

**Comment by achilleas-k** [comment]
This has been brought up before and there's an open PR to restrict access.  See issue #5578 for a discussion and a link to the PR.

For now you can just block access to it through the reverse proxy configuration, if you're using one.  In Apache this would look like:
```
<Location /debug>
    Deny from  all
</Location>
```

**Comment by unknwon** [comment]
Thanks @achilleas-k!

Closing as duplicated.
