### ISSUE TITLE
Phonemic transcription is not standard English

### ISSUE THREAD

**Issue by dustinnewman98** [gogs/gogs#5916]
**Describe the bug**
The README transcribes "Gogs" as /gɔgs/, which while not incorrect per se, is a very strange transcription. English prefers its obstruents (like /g/) to match in voicing to adjacent consonants. For example, "dogs" would be /dɑgz/ whereas "cats" would be /kæts/. Note that /d/ is voiced whereas /t/ is voiceless and /z/ (following /d/) is voiced, whereas /s/ (following /s/) is voiceless. 

The vowel quality is also questionable, using open o (/ɔ/) rather than script a (/ɑ/ as in "dogs"). While this is not incorrect, it would reflect more of a British pronunciation than American. However, even a British pronunciation would be more likely to use the turned script a (/ɒ/) instead of open o. 

Considering this, I believe a more faithful transcription to American English speakers would be /gɑgz/ and to British English speakers, /gɒgz/.

**Gogs version or commit**
The transcription in question was commited at db4bf20df33f008fa16fb1c813cc7ee14673d038.

**To Reproduce**
1. Go to [the README](https://github.com/gogs/gogs/blob/master/README.md)
2. Scroll down to ["Vision"](https://github.com/gogs/gogs/blob/master/README.md#vision)
3. See transcription in question

**Expected behavior**
/gɑgz/

**Actual behavior**
/gɔgs/

**Screenshots**
<img width="897" alt="Screen Shot 2020-02-06 at 11 03 01 PM" src="https://user-images.githubusercontent.com/7496435/74008075-d80bcb00-4934-11ea-8c52-2a99eaa00fe3.png">

**Comment by unknwon** [comment]
Wow, thank you!

**Comment by unknwon** [comment]
README updated via fd14ad6.
