### ISSUE TITLE
Gogs install error with username non "git"

### ISSUE THREAD

**Issue by BorysVrublevskyi** [gogs/gogs#5918]
1. Installer returns error when system user is not "git" (exp "gogs"), even when it exists and have correct permissions.
2. Installation is successful when specified user is "git" even if it does not exists.

**Comment by unknwon** [comment]
Hi, this is intentional to make sure you do not run as root by accident.

**Comment by BorysVrublevskyi** [comment]
Understand. But for now gogs checking if "$user = git", but must "$user != root"

**Comment by unknwon** [comment]
"git" is the default, you can change it to whatever you want, and you can still run as "root" if you wish.

**Comment by BorysVrublevskyi** [comment]
I mean, during installing I wasn't able to set any other user but "git". **Installer** returns error every time I tried to set existing system user "gogs" with correct rights on folder with repositories.

**Comment by unknwon** [comment]
Why can't?

![image](https://user-images.githubusercontent.com/2946214/74287832-de031100-4d65-11ea-8dc2-207b909d8062.png)

**Comment by BorysVrublevskyi** [comment]
Yes, this is the error. Specified user has rights to repository root path, but installer doesn't allow to continue installation. So I set user to default "git", which doesn't exists in my system, and installation successfully finished. How can this be?

**Comment by unknwon** [comment]
Whatever value put in this input box must match the `$USER` environment variable, by default, it is the system user runs the Gogs. But environment variable can be changed to anything you like.

**Comment by BorysVrublevskyi** [comment]
Thanks! Now I understand. Gogs service must be run from user that must be provided during installation.
