### ISSUE TITLE
Missing ng/base/footer template

### ISSUE THREAD

**Issue by nandak522** [gogs/gogs#592]
- **Bug Description**: http://localhost:3000/ is redirecting to http://localhost:3000/install and failing with this error: `html/template:install:149: no such template "ng/base/footer"`
- **Gogs Version**: `0.5.6.1027 Beta`
- **Git Version**: `2.1.0`
- **System Type**: `Ubuntu 64 Bit 14.04`
- **Error Log**: 
  
  $ ./gogs web
  2014/10/31 11:28:45 [T] Custom path: /jnandakishore/workspace/gogs_binary/custom
  2014/10/31 11:28:45 [T] Log path: /jnandakishore/workspace/gogs_binary/log
  2014/10/31 11:28:45 [I] Clicbank Git Service 0.5.6.1027 Beta
  2014/10/31 11:28:45 [I] Log Mode: Console(Trace)
  2014/10/31 11:28:45 [I] Redis Enabled
  2014/10/31 11:28:45 [I] Memcache Enabled
  2014/10/31 11:28:45 [I] Cache Service Enabled
  2014/10/31 11:28:45 [I] Session Service Enabled
  2014/10/31 11:28:45 [I] SQLite3 Enabled
  2014/10/31 11:28:45 [I] Run Mode: Development
  2014/10/31 11:28:45 [I] Listen: http://0.0.0.0:3000
  [Macaron] Started GET / for 127.0.0.1
  [Macaron] Completed / 302 Found in 3.066963ms
  [Macaron] Started GET /install for 127.0.0.1
  [Macaron] Completed /install 500 Internal Server Error in 15.420582ms
- **Other information**:
  Using the latest amd64 binary from http://gobuild.io/github.com/gogits/gogs

**Comment by wedgeV** [comment]
getting this when running through your docker image:
```html/template:user/dashboard/dashboard:131:11: no such template "ng/base/footer"```
used to work fine with 0.8.2

**Comment by Unknwon** [comment]
@wedgeV delete `templates` directory on your volumed path.
