### ISSUE TITLE
 debug memory leakage

### ISSUE THREAD

**Issue by linsfg** [gogs/gogs#5924]
https://try.gogs.io/debug
https://try.gogs.io/debug/profile/

<img width="383" alt="aa" src="https://user-images.githubusercontent.com/650478/74749540-42adf680-52a5-11ea-8c8a-3305f3db93ec.png">

<img width="1007" alt="bb" src="https://user-images.githubusercontent.com/650478/74749807-af28f580-52a5-11ea-8fdf-9bb8f13f9620.png">

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
