### ISSUE TITLE
docker run gogs with raspberry 4b

### ISSUE THREAD

**Issue by dongshimou** [gogs/gogs#5925]
**Describe the bug**
run the cmd `sudo docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs`
i get this error: `standard_init_linux.go:211: exec user process caused "exec format error"`

**Gogs version or commit**
last

**Git version**

```
$ git version

```

**Operating system**
raspberry

**Database**
mysql 5.7

**To Reproduce**
1. `docker pull gogs/gogs`
2. `sudo mkdir -p /var/gogs`
3. `sudo docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs`
4. get the error: `standard_init_linux.go:211: exec user process caused "exec format error`

**Comment by unknwon** [comment]
Hi, have you tried this Docker image? https://hub.docker.com/repository/docker/gogs/gogs-rpi

**Comment by dongshimou** [comment]
@unknwon thanks! it's work fine.
maybe should update the raspberry version README.

**Comment by unknwon** [comment]
Good idea, will do.

**Comment by unknwon** [comment]
Updated in https://github.com/gogs/gogs/commit/5b14cc6f0b7b661beb2640a94bd15660cdb48587.
