### ISSUE TITLE
API for listing Git repository tree

### ISSUE THREAD

**Issue by bharatnc** [gogs/gogs#5934]
**Describe the feature**

I'm running into a use case where I would like to fetch all the files in a given repo for a given `ref` (say master)  and then fetch their raw content. 

This endpoint: `/api/v1/repos/:user/:repo-name/raw/:refs/:filename`  is very much useful if I actually know which file I need to fetch raw.

It would be useful to have api endpoint which can fetch a list of all files for a given ref for a given repo for a given user. 

**Describe the solution you'd like**

When given:  `/repos/:user/:repo_name/tree` fetch the list of all the files in that repo. Additionally params for recursive functionality can also work with `?recursive=1 `.  For more context, Gitlab provides a repository tree API: https://docs.gitlab.com/ee/api/repositories.html.

**Additional context**

I perused the gogs source code for API and haven't found any tree endpoint exposed: https://github.com/gogs/gogs/blob/master/internal/route/api/v1/repo/repo.go. 

 I haven't actually looked at the core backend to understand if all that's needed is to expose the backend logic via proper api path. 

Would like to help implement it if we don't already have this feature  and is do-able.

PS: Pardon if I might be double reporting an existing/similar issue, but I tried my best to isearch through existing issues to ensure that this hasn't been asked before and the closet I can find are issues like: #1061 and #1253.

Thank you!

**Comment by unknwon** [comment]
Thanks for the feedback!

For the API design, I would like to align with GitHub API v3, i.e. https://developer.github.com/v3/git/trees/. It is definitely doable with existing codebase (though we don't need to truncate results in the initial implementation). 

Roughly, you would:
1. Get the root tree via: https://github.com/gogs/git-module/blob/f29bce1e3a666c02175d080892be185405dd3af4/repo_tree.go#L20
2. List entries in the root tree: https://github.com/gogs/git-module/blob/f29bce1e3a666c02175d080892be185405dd3af4/tree.go#L137
3. For each tree entry in the root tree, do https://github.com/gogs/git-module/blob/f29bce1e3a666c02175d080892be185405dd3af4/tree.go#L108

NOTE: The methods I liked are on `git-module@v0.8.3`, NOT `git-module@v1.0.0-beta` (this is a refactored one, and haven't migrated Gogs to adopt it yet, it has huge amount of work and testing ahead).

**Comment by bharatnc** [comment]
@unknwon thanks for the pointers, I'm going to attempt to take a look.

**Comment by jianboy** [comment]
How to get all the files with "git tree" API? or **get a sub-tree?**

Github has a parameter:
```
?recursive=1
```
