### ISSUE TITLE
Docker Healthcheck support

### ISSUE THREAD

**Issue by ElleshaHackett** [gogs/gogs#5935]
**Describe the feature**
Being able to see a "health status" of the Gogs Docker container.

**Describe the solution you'd like**
I would like support for the Docker Healthcheck (that is also shown in Portainer.io and probably other Docker management software).

**Describe alternatives you've considered**
Alternative is setting up something similarly without the use of the already existing tools within Docker.

**Additional context**
The `Dockerfile` could contain something like this:

`HEALTHCHECK --interval=60s --timeout=10s --retries=3 CMD (curl -sS http://localhost:10080 && curl -sS http://localhost:10022) || exit 1`. 

For debugging and testing purposses you can use:

`docker inspect --format "{{json .State.Health}}" containername`

![image](https://user-images.githubusercontent.com/5116641/75119630-ea9c3900-5684-11ea-8aa7-3aa2ae737a54.png)

**Comment by unknwon** [comment]
Looks like an easy change! PR is welcome :)

**Comment by ElleshaHackett** [comment]
Except that I made a mistake. A HTTP check with curl on port :10022 obviously won't work since it isn't HTTP but SSH protocol. I will look into it later when I have more time.

`HEALTHCHECK --interval=60s --timeout=10s --retries=3 CMD curl -sS http://localhost:10080 || exit 1` will surely work when only considering the HTTP check on the UI.

**Comment by unknwon** [comment]
Quick question: is this port supposed to be the one inside the Docker container or the host port binds to the Docker container?

**Comment by ElleshaHackett** [comment]
It is about the inside of the container meaning that in my example also `curl` needs to be available.

So the used port at host is irrelevant as the inner container port is static.

**Comment by cubanp3te** [comment]
Have checked, both latest images (amd64 and arm) already have curl available, looking into potential health-checks based on the suggestions of @ElleshaHackett

**Comment by cubanp3te** [comment]
Apologies for the delay, tested and confirmed for Dockerfile.rpi amd Dockerfile.aarch64 (RaspberryPi 4 and Pinebook Pro)

**Comment by cubanp3te** [comment]
Pull request #6522 submitted to address this issue.
