### ISSUE TITLE
EXTERNAL_URL has the server listen port prepended when using unix protocol

### ISSUE THREAD

**Issue by EyeOfMidas** [gogs/gogs#5936]
**Describe the bug**
When using the `unix` protocol, the EXTERNAL_URL setting will always include the port even when it's not relevant

**Gogs version or commit**
afc2500aee471faaf17d4d588d4cb6bbc8d6a0c4

**Git version**

```
$ git version
git version 2.20.1
```

**Operating system**
Debian 10

**Database**
default-mysql-server (MariaDB)

**To Reproduce**
1. Edit the /etc/gogs/conf/app.ini file and change a few values:
2. EXTERNAL_URL = http://%(DOMAIN)s
3. PROTOCOL = unix
4. HTTP_ADDR = /run/gogs/gogs.pid
5. save the file and restart the gogs-web service `sudo service gogs-web restart`
6. It might be necessary to set up the webserver to listen to the socket instead:
7. In nginx this is: 
8. `location / {
                proxy_pass http://unix:/run/gogs/gogs.pid;
        }`
9. log in to the gogs instance with an account that has admin access

**Can you reproduce the bug at https://try.gogs.io?**
Cannot access the config or Administration panel on try.gogs.io

**Expected behavior**
The EXTERNAL_URL should be an exact match and should not be calculated unless during initial install
For example:
http://mydomain.tld/

**Actual behavior**
If I do not specify a port in the EXTERNAL_URL, it will stick the port immediately after the protocol, before the domain name.
For example:
http://6000mydomain.tld/
![Screenshot from 2020-02-24 00-34-08](https://user-images.githubusercontent.com/3173530/75130675-a5d0cc00-569d-11ea-8ea6-8cd52363fb52.png)

**Comment by unknwon** [comment]
Thanks for your high quality bug report ❤️

I'm looking into this now.

**Comment by EyeOfMidas** [comment]
Thanks for looking into it! If you need any help reproducing or testing, let me know

**Comment by unknwon** [comment]
Hi, I'm just about to post that I'm not able to reproduce locally. How did you install your Gogs?

**Comment by unknwon** [comment]
NVM, I reproduced with `./gogs web -port xxx`

**Comment by unknwon** [comment]
Patch has been pushed to `master`, you could re-pull it now. If you're using packager.io, it might take hours to have this update available 😞

**Comment by EyeOfMidas** [comment]
You're incredible! I am using packager; I'll keep an eye on the build there and let you know when I see it.

**Comment by unknwon** [comment]
I just received an email says the build failed with absolutely no reason why. The build process of packager.io feels really flaky to me.

https://packager.io/gh/gogs/gogs/builds/97

**Comment by EyeOfMidas** [comment]
I see this error in the packager logs:

```tar: ./conf/locale/locale_bg-BG.ini: Wrote only 8192 of 10240 bytes
tar: ./conf/locale/locale_es-ES.ini: Cannot write: No space left on device
tar: ./docs: Cannot mkdir: No space left on device
tar: ./docs: Cannot mkdir: No space left on device
tar: ./docs/local_development.md: Cannot open: No such file or directory```

Maybe it's time for a support ticket?

**Comment by EyeOfMidas** [comment]
I just heard back from Cyril at packager.io. The disk space issue is fixed; can you trigger another gogs build and see if it works?

**Comment by unknwon** [comment]
Thanks, triggered a new one here: https://packager.io/gh/gogs/gogs/builds/100

**Comment by EyeOfMidas** [comment]
Confirmed fixed! Thanks for all your work!
