### ISSUE TITLE
Docker backup cronjob (location, interval, retention)

### ISSUE THREAD

**Issue by ElleshaHackett** [gogs/gogs#5939]
**Describe the feature**
Backup options on the Docker container.

**Describe the solution you'd like**
As described here https://discuss.gogs.io/t/how-to-backup-restore-and-migrate/991 it is possible to make and restore backups of Gogs. I'd like to see a few options on the Docker container for that such as `backupInterval`, `backupRetention`, `backupFolder`.

In that case you can just run Docker with `-e backupInterval=1h -e backupRetention=1w -v /media/externalDrive/gogsBackups:/backups`. The docker container could use simple cronjobs to achieve this.

**Describe alternatives you've considered**
Manually using a terminal to gain access to the Docker container and run and move the backups manually.

**Additional context**
A shared docker volume can be used to determine the folder backups will be written to. A linux cronjob could be used the run the backups periodically.

**Comment by unknwon** [comment]
Thanks for the feedback!

Is there a way to optionally start cronjob in Dockerfile?

**Comment by ElleshaHackett** [comment]
Looking at the codebase for a few minutes I think the best place to do this, is to check in `gogs/docker/finalize.sh` if the described docker environment variables as described above are used and depending on that setup the cronjob. Maybe I will workout a suggestion but I'm very short on time.

But I am not sure if that script only runs on image build or on container startup. In case it is only used for build, you could do the same and run both the current entrypoint and another bash script to achieve this.

**Comment by unknwon** [comment]
I think it is only ran at build time:
https://github.com/gogs/gogs/blob/85f94676baaf9af40ced0f20468d1adb8856ade3/docker/finalize.sh#L2

**Comment by xZero707** [comment]
I can help with that. Starting on it ASAP.

**Comment by unknwon** [comment]
@xZero707 thank you!

**Comment by ElleshaHackett** [comment]
Nice :)

**Comment by xZero707** [comment]
_Just small update:_ 
I was kept very busy recently, so this is slightly delayed, however, I expect to deliver this quite soon. 
Currently working on retention policy and rotation.

**Comment by unknwon** [comment]
Thanks for the update @xZero707!



> Minute basis BACKUP_INTERVAL will be removed as is just a side-effect and seems redundant.
> Now, backup can run on hourly basis, so I suppose BACKUP_RETENTION that is limited to days only, could be a severe drawback?

Yeah, I don't think minute basis is practical and as useful. And retention based on days makes most sense to me.

**Comment by ElleshaHackett** [comment]
Looks good. I would suggest to suggest more dynamic input. For example is "h", I would like to make a back-up every 2-4 hours when I have many developers actively changing stuff. Just for the sake of not loosing the work. I would allow any hour input. Maybe to simplify allow integer input only on both values, for example in hours.

**Comment by xZero707** [comment]
@ElleshaHackett You misunderstood me.

I said:
> Now, backup can run on hourly basis

And not:
> Now, backup can - only -  run on hourly basis

 Backup interval can be run on hourly, daily or weekly basis. With Xh, Xd, Xw respectively. 

Backup retention value is in days, fixed.

**Comment by xZero707** [comment]
**Update**:

Everything is done. Now testing. Welcome test if you want (build from my repo needed).
 
**Outcome**:
* **BACKUP_INTERVAL** supports interval in hours (h), days (d), months (M). 
**eg.** 3h **_or_** 7d **_or_** 3M
* **BACKUP_RETENTION** now supports expressions in minutes (m) and days (d). 
**eg.** 360m **_or_** 2d

**Comment by xZero707** [comment]
Testing is so far so good :tada:

**Comment by brianpierson2020** [comment]
Looking good @xZero707, nice work! :) Hope it will soon be stable and released.

**Comment by xZero707** [comment]
@ElleshaHackett @brianpierson2020 FYI - This was released few days ago :tada: 

@unknwon This issue can be closed now, I suppose?

**Comment by unknwon** [comment]
Thanks @xZero707, closing!

**Comment by notDavid** [comment]
For reference, for all the docker noobs like me:

1. Start the docker image with something like this to mount the backup folder to the host:
```
docker run --name=gogs -p 10022:22 -p 10880:3000 -v /var/gogs:/data \
-v /var/gogs-backup:/backup -e RUN_CROND=true -e BACKUP_INTERVAL=7d \
gogs/gogs
```
2. Your backups will now automatically be placed in `/var/gogs-backup` on the host.

For additional options see the repo’s [readme](https://github.com/gogs/gogs/tree/main/docker#container-options)
