### ISSUE TITLE
Support API  `GET /repos/:owner/:repo/contents/:path`

### ISSUE THREAD

**Issue by bharatnc** [gogs/gogs#5949]
**Describe the feature**

The gogs content api `GET /repos/:username/:reponame/raw/:ref/:path` returns the raw file contents: https://github.com/gogs/docs-api/blob/master/Repositories/Contents.md.

For my use case, I need  a `Github` style api: https://developer.github.com/v3/repos/contents/#get-contents.

This would be extremely useful because as far as I have explored the gogs api, there isn't a direct way to get all the information about a file / directory by just providing the path to it: 

**Describe the solution you'd like**

Example: `GET /repos/:owner/:repo/readme`. Will return the following response:

```bash
{
  "type": "file",
  "encoding": "base64",
  "size": 5362,
  "name": "README.md",
  "path": "README.md",
  "content": "encoded content ...",
  "sha": "3d21ec53a331a6f037a91c368710b99387d012c1",
  "url": "https://api.github.com/repos/octokit/octokit.rb/contents/README.md",
  "git_url": "https://api.github.com/repos/octokit/octokit.rb/git/blobs/3d21ec53a331a6f037a91c368710b99387d012c1",
  "html_url": "https://github.com/octokit/octokit.rb/blob/master/README.md",
  "download_url": "https://raw.githubusercontent.com/octokit/octokit.rb/master/README.md",
  "_links": {
    "git": "https://api.github.com/repos/octokit/octokit.rb/git/blobs/3d21ec53a331a6f037a91c368710b99387d012c1",
    "self": "https://api.github.com/repos/octokit/octokit.rb/contents/README.md",
    "html": "https://github.com/octokit/octokit.rb/blob/master/README.md"
  }
}
```
(Reference: https://developer.github.com/v3/repos/contents/#get-contents)

There are two ways that we can about to implement this:
1. Modify the existing `/repos/:username/:reponame/raw/:ref/:path` so that it returns a json response along with the content in base64 encoded format.

2. Add a new api endpoint `GET /repos/:owner/:repo/readme` that returns the information about the file along with the contents of the file. Optionally, we can just omit the contents of the file and just return all the other information.

**Describe alternatives you've considered**

I have quite exhaustively used various methods to go about this. Given a repo like:

```
gogs-demo(root)___
                 |
                 dir1  (file1, file3)
                 |
                 README
```

I currently get the commit at the base of the tree using `GET repos/:user/:project/:refs` api endpoint. Then I use the tree to get the tree for the `:sha` to get the remaining tree using `GET /repos/:user/:project/git/trees`. 

But you can see that you can only traverse in one direction Top Down with no ability to know what is the :sha of the parent. In my use case this is important.

**Additional context**

Pardon if this feature is already existent and is hiding somewhere in the docs :P - but I'm pretty sure that I have double checked the docs.

I will be interested in implementing this if the proposal sounds good. I am strongly inclined to # 2 in the solution section above.

**Comment by unknwon** [comment]
> 1. Modify the existing `/repos/:username/:reponame/raw/:ref/:path` so that it returns a json response along with the content in base64 encoded format.
> 2. Add a new api endpoint `GET /repos/:owner/:repo/readme` that returns the information about the file along with the contents of the file. Optionally, we can just omit the contents of the file and just return all the other information.
>...
> I will be interested in implementing this if the proposal sounds good. I am strongly inclined to # 2 in the solution section above.

Yep, I agree, we should do # 2.

**Comment by bharatnc** [comment]
@unknwon thank you for the input. I will update with a PR when I get this working locally.

**Comment by bharatnc** [comment]
@unknwon following the git api v3 spec, I have the following response:
```bash
[
  {
    "type": "tree",
    "size": 26178,
    "name": "test.pdf",
    "path": "tmp",
    "sha": "a247ab36bd13a4564dec02a005f73f8a529608fa",
    "url": "http://localhost:3000/api/v1/repos/root/testrepo2/trees/tmp",
    "git_url": "http://localhost:3000/api/v1/repos/root/testrepo2/trees/a247ab36bd13a4564dec02a005f73f8a529608fa",
    "html_url": "http://localhost:3000/api/v1/repos/root/testrepo2/tree/a247ab36bd13a4564dec02a005f73f8a529608fa",
    "download_url": "http://localhost:3000/api/v1/root/testrepo2/raw/tmp",
    "_links": {
      "git": "http://localhost:3000/api/v1/repos/root/testrepo2/trees/a247ab36bd13a4564dec02a005f73f8a529608fa",
      "self": "http://localhost:3000/api/v1/repos/root/testrepo2/trees/tmp",
      "html": "http://localhost:3000/api/v1/repos/root/testrepo2/tree/a247ab36bd13a4564dec02a005f73f8a529608fa"
    }
  }
]

```
Do you think everything under `_links` and also `url` `git_url`, `html_url`, `download_url` makes sense to you? Some of these are actually broken, it somehow feels to me if we should omit these and probably just have a `url` that points to the actual content  / project. Wanted to clarify this with you.

**Comment by unknwon** [comment]
I think match whatever GitHub API v3 does is the best, and we could still response the API URL in those "url" field, and file issues for them and fix later.
