### ISSUE TITLE
"panic: runtime error: invalid memory address or nil pointer dereference" when pushing with token

### ISSUE THREAD

**Issue by sebw** [gogs/gogs#5956]
I'm running gogs in Docker and update automatically against the latest branch.

Yesterday, I could push changes with my tokens. My container has been upgraded last night.

Today, I'm getting an error when I try to push.

```
$ git push origin master
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 366 bytes | 366.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: panic: runtime error: invalid memory address or nil pointer dereference
remote: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10b149f]
remote: 
remote: goroutine 1 [running]:
remote: gogs.io/gogs/internal/cmd.setup(0xc0002a82c0, 0x141c9db, 0x15, 0x1)
remote: 	gogs.io/gogs@/internal/cmd/serv.go:71 +0x14f
remote: gogs.io/gogs/internal/cmd.runHookPreReceive(0xc0002a82c0, 0x0, 0xc00029a2d0)
remote: 	gogs.io/gogs@/internal/cmd/hook.go:70 +0x82
remote: github.com/urfave/cli.HandleAction(0x124e700, 0x1ce2ce0, 0xc0002a82c0, 0xc0002a82c0, 0x0)
remote: 	github.com/urfave/cli@v1.22.1/app.go:523 +0xbe
remote: github.com/urfave/cli.Command.Run(0x140806d, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x142ce6d, 0x1d, 0x0, ...)
remote: 	github.com/urfave/cli@v1.22.1/command.go:174 +0x51c
remote: github.com/urfave/cli.(*App).RunAsSubcommand(0xc0002981c0, 0xc0002a8000, 0x0, 0x0)
remote: 	github.com/urfave/cli@v1.22.1/app.go:404 +0x869
remote: github.com/urfave/cli.Command.startApp(0x13fa0c7, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1443689, 0x2c, 0x0, ...)
remote: 	github.com/urfave/cli@v1.22.1/command.go:329 +0x845
remote: github.com/urfave/cli.Command.Run(0x13fa0c7, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1443689, 0x2c, 0x0, ...)
remote: 	github.com/urfave/cli@v1.22.1/command.go:102 +0x9ca
remote: github.com/urfave/cli.(*App).Run(0xc000298000, 0xc000092040, 0x4, 0x4, 0x0, 0x0)
remote: 	github.com/urfave/cli@v1.22.1/app.go:276 +0x718
remote: main.main()
remote: 	gogs.io/gogs@/gogs.go:39 +0x27a
```

Since I'm now running 0.12 and have faced two regressions in a few days, I checked the image tags and 0.12 is not available, I would like to pin my container to the stable 0.12 I had yesterday. Would reverting 0.11 cause problems?

Thanks!

**Comment by unknwon** [comment]
Hi, sorry about the regression, 0.12 has not released yet. And you can put back to 0.11 without problems.

The patch has been pushed: https://github.com/gogs/gogs/commit/7382c23a17cad73c137e9bca66be0cd1b04b75fd

**Comment by sebw** [comment]
I pulled the image 10 minutes ago and tested but I'm still facing the issue.

I pinned back to develop from 4 months ago, I assume this is considered more "stable"?

Thanks for the quick response!

**Comment by unknwon** [comment]
0.11.91 hasn’t been report any fatal issue so far, it’s definitely more stable than the current master as lots of refactoring going on. 😅

Docker Hub is always building things slow, so maybe give it 20 more minuets.

**Comment by unknwon** [comment]
I did a fresh `docker run gogs/gogs ...` and could confirm it is fixed.

**Comment by sebw** [comment]
I confirm as well! Thanks for the quick patch :D

**Comment by fgm** [comment]
The packager.io version for Debian still has 0.12.0+dev with that bug, FWIW.

**Comment by unknwon** [comment]
It is stuck on a build that never finishes ...

![image](https://user-images.githubusercontent.com/2946214/75665210-c48f1e00-5cae-11ea-87ac-41202422dcfe.png)

I'll shot the site admin an email for help.

**Comment by fgm** [comment]
Doesn't seem to improve much, I'm afraid.

![Capture d'écran 2020-03-02 13 39 05](https://user-images.githubusercontent.com/143311/75677236-41a89c00-5c8b-11ea-839a-094cd6b12fff.png)

**Comment by unknwon** [comment]
"Open source projects are supported in the best effort", I guess that's how that it. LOL. sometimes pretty fast.

**Comment by fgm** [comment]
More generally, I've long been wondering what the recommended practice for deploying Gogs was. The docs describe the process from binaries, sources, or packages, and packages seem by far the easiest way to remain updated, but I've often had the impression these builds were somehow "remote" from the project, and other deployments were recommended. Also, you mention docker in this issue, which is not part of the documented installs. Is there any best practice you would recommend ?

**Comment by unknwon** [comment]
@fgm Install by binaries is always the preferred, but if you want some kind of `apk update`, Docker is the best suit. Docs are here: https://github.com/gogs/gogs/tree/master/docker

Good point about not mentioning Docker in the website, that was overlooked. 🤔

**Comment by unknwon** [comment]
OK, we finally have a successful one: https://packager.io/gh/gogs/gogs/builds/124

**Comment by fgm** [comment]
And I can confirm it fixes the issue: I was able to push again on my server. Thanks a lot.
