### ISSUE TITLE
Undefined or incorrect behaviour when both "Allow public access to issues when repository is private" and "Use external issue tracker" are enabled

### ISSUE THREAD

**Issue by achilleas-k** [gogs/gogs#5961]
**Describe the bug**
Enabling "Allow public access to issues when repository is private" then "Use external issue tracker" makes repositories show up in public listings but the repository page is inaccessible for other users (404).

**Gogs version or commit**
931da04dc2c7bdc078ded191b4d44d1e1f0d161b

**Git version**

```
$ git version
git version 2.22.2
```

**Operating system**
Alpine Linux (Docker)

**Database**
sqlite3

**To Reproduce**
1. Create a new repository and set it private
2. Go to repository settings
3. Click on "Allow public access to issues when repository is private"
4. Click on "Use external issue tracker"
5. Click on "Update Settings"
6. Sign out (or if public browsing is not allowed, sign in with a different account) and navigate to "Explore"
7. Click on the listed private repository

**Can you reproduce the bug at https://try.gogs.io?**
Yes.
Go to https://try.gogs.io/explore/repos?q=testpriv and click on the result.

**Expected behavior**
One of two things:
- If the "Allow public access ..." option does not apply to external issue trackers (which the visual grouping of the options implies it should not), the repository shouldn't appear in the public listing.
- If the "Allow public access ..." option does apply, the option hierarchy should be changed and the repository should behave in the same way as when "Use builtin lightweight issue tracker" is selected (repository is accessible, but the code is not).

**Actual behavior**
404 page.

**Screenshots**
See image below for configuration
![image](https://user-images.githubusercontent.com/2369197/75690444-28134e80-5ca3-11ea-8f9d-8b62d78a3a29.png)

**Comment by unknwon** [comment]
Thanks for your high quality bug report ❤️


> * If the "Allow public access ..." option does not apply to external issue trackers (which the visual grouping of the options implies it should not), the repository shouldn't appear in the public listing.

I think this option is expected, could be an easy flip to `false` for **Allow public access to issues when repository is private** when **Use external issue tracker** is selected on form submission.

**Comment by alpencrossi** [comment]
I think the same applies to the wiki settings when **Use external wiki** is selected and also if the wiki or the issues are disabled.

Could be fixed in the **where clause** while fetching the repos.
https://github.com/gogs/gogs/blob/6a096811ffb658f575525921fd49bd7f4f0d45a5/internal/db/repo.go#L1784-L1787
Pro: User settings don't have to be changed. Con: Additional checks have to be evaluated each time the repos are fetched.

So, from perfomance view it might be better to flip to `false` just as @unknwon already stated:
> I think this option is expected, could be an easy flip to `false` for **Allow public access to issues when repository is private** when **Use external issue tracker** is selected on form submission.

Either way, I'd like do a PR if no one else did.

**Comment by unknwon** [comment]
@alpencrossi Thanks! I think flip to false on write is more desirable, given this issue is also not critical/blocker.
