### ISSUE TITLE
How to change “Git Clone Operation Timeout” default value?

### ISSUE THREAD

**Issue by fearlessxjdx** [gogs/gogs#5969]
This is my steps:
1. create `/data/gogs/custom/conf/app.ini` file in docker container.  
2. edit `/data/gogs/custom/conf/app.ini` like is:
```plain
[git.timeout]
CLONE                                   = 3000
```
3. execute `docker restart gogs`.  

restart success(no error),but the default value didn't change....

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
