### ISSUE TITLE
Using Gogs as a front end for other Git Server

### ISSUE THREAD

**Issue by psyciknz** [gogs/gogs#5971]
Can gogs be the front end of an external Git server?

I've successfully in linux and windows run Gogs servers where the git repos are local.   But I'm looking at a situation where I might want gogs running on a windows server (with the web ui and database), but the actual location of the Git repositories are on a linux server somewhere else.  

Could this be done?  Preferably without resorting to samba/nfs shares.

**Comment by unknwon** [comment]
Hi, if Git data is not available locally, the performance is often like hell. Regardlessly, I don't think it's possible.
