### ISSUE TITLE
Clearer doc comments for mirror config options

### ISSUE THREAD

**Issue by Sauermann** [gogs/gogs#5977]
**Describe the bug**

The gogs/conf/app.ini file contains two options that appear to contradict each other.

https://github.com/gogs/gogs/blob/e87f1107ca74c267ec0ef07054085b7a7871eb77/conf/app.ini#L400-L402

https://github.com/gogs/gogs/blob/e87f1107ca74c267ec0ef07054085b7a7871eb77/conf/app.ini#L445-L447

The first option indicates that all mirrors get updated every 10 minutes and the second option indicates that all mirrors get updated every 8 hours.

**Gogs version or commit**

e87f1107ca74c267ec0ef07054085b7a7871eb77

**Expected behavior**

I would expect that configuration options do not contradict each other.

**Comment by unknwon** [comment]
The config option name may not be the best. But there are not contradict to each other.

`[cron.update_mirrors] SCHEDULE` is for how often the mirror syncer runs to check if anything needs to update based on schedule, `[mirror] DEFAULT_INTERVAL` is used to set how long until next sync for this single repo (after a successful mirror sync).

**Comment by TheCasualObserver** [comment]
Thank you for the reply, perhaps including these short explanations into the variables comments would be beneficial.

**Comment by Sauermann** [comment]
Thank you for the reply. Perhaps adding these explanations to the variables comments would be beneficial.

**Comment by unknwon** [comment]
haha, PR welcome :)

**Comment by alpencrossi** [comment]
I'd like to open a PR with something like:

`[cron.update_mirrors] SCHEDULE`
SCHEDULE defines how often the mirror syncer checks if any mirror needs to be synchronized (based on the mirror update interval)

`[mirror] DEFAULT_INTERVAL`
Defines (in hours) the default interval until the next synchronization for a mirror (after a successful mirror sync). Can be overridden individually for each mirror in the mirror settings.


This should clear it up.

**Comment by Sauermann** [comment]
Thank you for resolving this issue!
