### ISSUE TITLE
Support API: `GET /repos/:owner/:repo/git/blobs/:file_sha`

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#5979]
Ref: https://developer.github.com/v3/git/blobs/#get-a-blob

**Comment by iamprathamesh** [comment]
Hi @unknwon ,
could you please elaborate the issue?

**Comment by unknwon** [comment]
@iamprathamesh What questions do you have in particular?

**Comment by jonatan5524** [comment]
@unknwon Can you elaborate on what was missing in the PR I submitted?
Was it because the response JSON was not the same as the GitHub response?

**Comment by unknwon** [comment]
> @unknwon Can you elaborate on what was missing in the PR I submitted? Was it because the response JSON was not the same as the GitHub response?

I only see a route change (reuse), and does not implement what's being asked for this issue.

**Comment by jonatan5524** [comment]
I thought using the existing method that already existed that response with part of the data required is sufficient, I guess not, I will work on fixing it.

**Comment by jonatan5524** [comment]
I think maybe needed to add for this issue to the git-modules a method to cat-file an object, currently, there is [CatFileCommit](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileCommit) and [CatFileType](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileType) both of them not giving me the content of the blob.

**Comment by unknwon** [comment]
> I think maybe needed to add for this issue to the git-modules a method to cat-file an object, currently, there is [CatFileCommit](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileCommit) and [CatFileType](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileType) both of them not giving me the content of the blob.

`Commit` embeds a `Tree`, which [should be able to give you the blob](https://pkg.go.dev/github.com/gogs/git-module#Tree.Blob).

**Comment by jonatan5524** [comment]
> > I think maybe needed to add for this issue to the git-modules a method to cat-file an object, currently, there is [CatFileCommit](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileCommit) and [CatFileType](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileType) both of them not giving me the content of the blob.
> 
> `Commit` embeds a `Tree`, which [should be able to give you the blob](https://pkg.go.dev/github.com/gogs/git-module#Tree.Blob).

It is an option, but it only gives me the blob in the current branch (work tree) and unnecessary iteration over the tree when this method is implemented in git using cat-file, so this can resolve to get the content in one command.

**Comment by unknwon** [comment]
> > > I think maybe needed to add for this issue to the git-modules a method to cat-file an object, currently, there is [CatFileCommit](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileCommit) and [CatFileType](https://pkg.go.dev/github.com/gogs/git-module#Repository.CatFileType) both of them not giving me the content of the blob.
> > 
> > 
> > `Commit` embeds a `Tree`, which [should be able to give you the blob](https://pkg.go.dev/github.com/gogs/git-module#Tree.Blob).
> 
> It is an option, but it only gives me the blob in the current branch (work tree) and unnecessary iteration over the tree when this method is implemented in git using cat-file, so this can resolve to get the content in one command.

Yeah, you're right! We only have ["cat-file" for commit and file type](https://sourcegraph.com/github.com/gogs/git-module/-/blob/repo_commit.go?L83), would be useful to add one for file content as well.

**Comment by unknwon** [comment]
> I can work on it and make a PR to git-modules before I continue on this issue, is this ok?
> Do you want to open an issue in git-modules and assign in to me?

@jonatan5524 You can send a PR to git-module and just reference this issue.
