### ISSUE TITLE
Import from local file system or from network file system

### ISSUE THREAD

**Issue by replay111** [gogs/gogs#5984]
Hi,
is there any way to import local repositories (bare repos) to just started brand new instance of gogs (on docker in my case)?
I was hoping that this tool allows to import already cloned repositories like gitlab - by invoking some command like:

```
gitlab-rake gitlab:import:repos['/var/opt/gitlab/git-data/repositories']
```

or by invoking some API url?

**Comment by unknwon** [comment]
If you're an admin or have granted permissions to clone by local path, just put the path in the **Clone Address** field in **New migration** form.

**Comment by replay111** [comment]
Does it mean that gogs will clone and create new copy of that repo?

**Comment by unknwon** [comment]
Yes, that is correct.

**Comment by replay111** [comment]
ok so this does not the correct solution for me. I was rather expecting to read pointed directory on file system and import information about the repositories located there. I do not want to clone anything as I already did that.

Anyway thanks for response!
