### ISSUE TITLE
aarch64 release?

### ISSUE THREAD

**Issue by lujiaxing** [gogs/gogs#5990]
I need gogs v0.11.91 for ARMv8-A.
It seems there's no release for ARMv8 (AARCH64)

I'm trying to compile gogs v0.11.91 but I am living in mainland China and could not be complete "go mod init" because of "THE GREAT FIREWALL", and naturally impossible to accomplish following operations...

can anybody upload a release for aarch64 ?

thx

**Comment by unknwon** [comment]
Use goproxy.cn

**Comment by lujiaxing** [comment]
> Use goproxy.cn

i know to use `go env GOPROXY="https://goproxy.cn,direct"` and `go env -w GO111MODULE=on`
but `go mod init` doesn't recognize GOPROXY. It's a known bug [#33767](https://github.com/golang/go/issues/33767) in GO 1.13.

But finally i got a remote server to finish this job, my problem resolved.

anyway, thanks.
