### ISSUE TITLE
External URL incorrect when using gogs behind web proxy after recent upgrade.

### ISSUE THREAD

**Issue by btafoya** [gogs/gogs#5992]
**Describe the bug**
The external URl shows as

`http://git.premadev.com:6000/`

While

`ROOT_URL = https://git.premadev.com/`

**Gogs version or commit**
Application version
    0.12.0+dev

apt repo version: 0.11.91-1584338268.c69a3865.xenial amd64

**Go version**
    go1.13.8

**Git version**
    2.7.4

**Operating system**
Ubuntu 16.04

**Database**
Server version: 5.7.29-0ubuntu0.16.04.1 (Ubuntu)

**To Reproduce**
Exists on all repositories, new and existsing for http: http://git.premadev.com:6000/repodir/repo.git

**Expected behavior**
Should be: https://git.premadev.com/repodir/repo.git

**Actual behavior**
http://git.premadev.com:6000/repodir/repo.git

**Additional context**
This issue began after a recent update via the apt repo,
`https://dl.packager.io/srv/deb/gogs/gogs/master/ubuntu 16.04 main`

I have researched and found other issue recent related issues, one in particular to the LOCAL_ROOT_URL is set to a unix file reference. It does not appear to address the use of LOCAL_ROOT_URL  = %(PROTOCOL)s://%(HTTP_ADDR)s:%(HTTP_PORT)s/.

EXTERNAL_URL has the server listen port prepended when using unix protocol #5936

**Comment by btafoya** [comment]
I have downgraded to version 0.11.91-1582129253.422a2064.xenial as a temporary fix. Is there a more recent version that is 0.11.19 code, rather than 0.12+dev?

**Comment by unknwon** [comment]
Thanks for your high quality bug report ❤️

You should start using `[server] EXTERNAL_URL` and remove the `ROOT_URL` (ref: https://github.com/gogs/gogs/blob/master/CHANGELOG.md), but until 0.13.0, it falls back to `ROOT_URL` if you have configured. I have double checked and couldn't reproduce your scenario, sadly I don't know know how exactly packager.io packages set up Gogs's config files. 

In short, setting `[server] EXTERNAL_URL` and remove the `ROOT_URL` should resolve the problem.

**Comment by FieldofClay** [comment]
I just experienced this after upgrading my Docker instance to 0.12.0+dev. I also serve mine out from the subdir /gogs/ and it was incorrectly redirecting up to /, so nothing worked remotely. 

Changing ROOT_URL to EXTERNAL_URL fixed it.

**Comment by dalu** [comment]
I just changed the "deprecated" options in app.ini, and this lead to gogs wanting a new install.
The changelog says that ROOT_URL will be removed in 13.0 but it's removed in 12.0 already.

There has to be an automatic configuration update or all gogs installations will fail once 13.0 comes.

**Comment by unknwon** [comment]
>I just changed the "deprecated" options in app.ini, and this lead to gogs wanting a new install.

"new install" sounds like a completely different problem that your Gogs is being pointed to a wrong/non-exist app.ini.

**Comment by dalu** [comment]
no the app.ini was where it always was just the "deprecated" stuff isn't deprecated. But this ROOT_URL is alreayd deprecated despite you writing that it's going to be removed in 13.0

So when you change all the "deprecated" configuration variables gogs wants to start a new install. comprende?

It's not a "completely different problem" it's a result of the variables being replaced with what the document says they should be

**Comment by unknwon** [comment]
https://try.gogs.io is still using the old `app.ini` created in 2015. I think this ticket is very specific to packager.io deployment, which I currently have no clue how it actually works.

**Comment by btafoya** [comment]
This is not a docker deployment but installed via the apt repository. I have the version held back at the last functional build for the time being and will re-evaluate at a future date. :)
