### ISSUE TITLE
Server IP change. How to update the url for existing and new repos to reflect the new IP?

### ISSUE THREAD

**Issue by whisperdancer** [gogs/gogs#5993]
I setup a gogs server on a raspberry pi initially with 192.168.1.209. I subsequently changed the IP to 192.168.1.31. I can get to the web dashboard, but noticed all my existing repos continue to show the .209 in the url and all newly created repos show the .209 also. I looked around, but don't see where I an tell gogs to update the urls to reflect the new IP. 
Is there a setting in the UI or another way to do it. I have ssh access to the server.

Thank you kindly!

**Comment by unknwon** [comment]
https://github.com/gogs/gogs/blob/c69a38652da09cb10bfe31714b6b39fec3f8ede8/conf/app.ini#L14-L15
