### ISSUE TITLE
backup: support exclude mirror repositories

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6000]
e.g. `./gogs backup --exclude-mirror-repos`.

**Comment by fishbullet** [comment]
Want to try this one @unknwon

**Comment by unknwon** [comment]
Thanks @fishbullet !

Here are the rough steps:
1. Make a new function to list all non-mirror repositories from the database in `internal/db/repo.go`.
2. Add a new flag to `backup` command in `internal/cmd/backup.go`, and loop over repositories then add them to ZIP archive. Similar to what we do here: https://sourcegraph.com/github.com/gogs/gogs@bugfix/set-engine-panic/-/blob/internal/cmd/backup.go?utm_product_name=GoLand&utm_product_version=GoLand#L123:5-132:10, you may want to spend some time on how to use `github.com/unknwon/cae/zip` package.

LMK if you have any questions and I'm also available on Discord with no SLA guarantee.

**Comment by fishbullet** [comment]
@unknwon   Sorry, both links are dead :( 
https://sourcegraph.com/github.com/gogs/gogs@bugfix/set-engine-panic/-/blob/internal/cmd/backup.go?utm_product_name=GoLand&utm_product_version=GoLand#L123:5-132:10 

github.com/unknwon/cae/zip

**Comment by unknwon** [comment]
Oops, branch deleted, fixed in my comment. And the second one is not a GitHub link, it's a import path. https://github.com/unknwon/cae
