### ISSUE TITLE
500 when get commits info of submodule

### ISSUE THREAD

**Issue by evdenis** [gogs/gogs#6007]
**Describe the bug**

Gogs fails to display repo in web interface and raises 500 error. This happens when gogs fails to fetch commits info from git submodules in bare repo. Gogs worked correctly two of three versions back on debian 10.

**Gogs version or commit**

Gogs: Go Git Service 0.12.0+dev

**Git version**

git version 2.20.1

**Operating system**

Debian GNU/Linux 10 (buster)

**Additional context**

```
2020/03/23 11:24:57 [ERROR] [...gogs/internal/route/repo/view.go:278 Home()] get commits info: get submodule "toolchain": revision does not exist
2020/03/23 11:24:57 [TRACE] Template: status/500
```

**Comment by unknwon** [comment]
Can you reproduce the bug at try.gogs.io?

**Comment by evdenis** [comment]
Yes. Look at the repo: https://try.gogs.io/dimorphus/test

**Comment by unknwon** [comment]
Thanks 👍

**Comment by unknwon** [comment]
Interestingly... I couldn't reproduce locally. Which makes me wonder if it's a problem with old Git. The demo server is using git 1.8.3.1, which Git binary version do you have on your server?

**Comment by evdenis** [comment]
Debian 10. git version 2.20.1

**Comment by unknwon** [comment]
OK, problem found!

**Comment by ELForcer** [comment]
The problem is not solved. The error is still included.

500: An error has occurred : get submodule "tcpdf": revision does not exist

Application Version: 0.12.3

**Comment by assist726** [comment]
Have the same issue here, but only on specific branches of the repo. I assume certain styles of commit histories break the system ?

**Comment by taellinglin** [comment]
I just added an existing git folder that had a submodule. I want to try to clone the submodule as well, but I get this 500 server error:
![image](https://user-images.githubusercontent.com/82527149/138160440-88888fd2-855b-47c3-b7ea-b71704acdb51.png)
