### ISSUE TITLE
Error: "Permissions 0755 for '/data/ssh/ssh_host_rsa_key' are too open."

### ISSUE THREAD

**Issue by numbworks** [gogs/gogs#6010]
Hello guys!

In the first place, **thank you** for the amazing work so far! 
GOGS is blazing fast and my issue tracker of choice since quite a lot of time!

**Goal**
I'm a digital nomad and I use three different Windows laptops to do my development work, and I would like to share my GOGS data among them (issues, repositories, etc). 

Until now my GOGS container has been running on my QNAP NAS server but I'm often unable to connect to it due of lack of connectivity, therefore I would like to have a more portable solution that doesn't depend on the internet connection and that I can sync among my three different machines when I'm online. An optimal location would be my local Dropbox folder, since I keep there all the documentation I write and all the "local" code files as well. 

The idea I have is to run GOGS as a Docker Container on each laptop and map its /data folder to a *local* folder located in C:\Dropbox. For my needs, having a SQLite database as back-end is more than enough, and the laptops are not used at the same time.

**Environment**
I'm running **Docker Desktop for Windows v.2.2.0.4 (43472)** on a **Windows 10 Pro Version 1903 Build 18362** machine:

```
PS C:\> (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId                                                              1903

C:\>ver
Microsoft Windows [Version 10.0.18362.720]
```

**Steps**
I performed the following steps:

```
PS C:\> docker pull gogs/gogs:0.11.91
PS C:\> mkdir C:\Dropbox\Containers\gogs\data
PS C:\> docker run --name=gogs -p 10022:22 -p 10080:3000 -v c/Dropbox/Containers/gogs/data:/data gogs/gogs:0.11.91
```
The last command successfully creates the "git", "log" and "ssh" sub-folders in "data", but then docker keeps printing this message on the console:

```
Mar 24 21:20:36 syslogd started: BusyBox v1.30.1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/data/ssh/ssh_host_rsa_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Unable to load host key "/data/ssh/ssh_host_rsa_key": bad permissions
Unable to load host key: /data/ssh/ssh_host_rsa_key
```

and it's not possible to proceed.

**Steps**
This error should depend by the fact that Linux permissions are not properly mapped by Docker Desktop to the Windows ones, because of the limits of the SMB protocol under the hood, therefore this is not specifically a GOGS bug. 

But I would like to ask if there is a flag or a workaround that I can use to ask GOGS to bypass this kind of error. Or if you have another proposal for having GOGS storing its data into a **portable volume**.

Thank you for your help!

**Comment by unknwon** [comment]
Hi, AFAIK there is no solution to permissions problem on a portable device with Docker. (I encounter the same thing with running GitLab inside Docker container.)



> But I would like to ask if there is a flag or a workaround that I can use to ask GOGS to bypass this kind of error. Or if you have another proposal for having GOGS storing its data into a **portable volume**.

The ultimate solution I have in mind is to directly run Gogs binary, and not use the SSH feature at all.
