### ISSUE TITLE
Support API: `GET /repos/:user/:repo/releases`

### ISSUE THREAD

**Issue by fgm** [gogs/gogs#6012]
The API is currently missing the releases endpoint at `/repos/:user/:repo/releases`, at least in its basic form exposing the list of releases.

See https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

**Additional context**

This prevents use of Goreleaser with Gogs, although it is available in Gitea, causing Gitea to be supported there but not Gogs.

**Comment by unknwon** [comment]
@fishbullet This one feels more intuitive and straightforward, WDYT?

**Comment by fishbullet** [comment]
@unknwon I'm on it, any advice how to done it right?

**Comment by unknwon** [comment]
- Routes for repo-related APIs lives in https://github.com/gogs/gogs/tree/master/internal/route/repo.
- DB methods for releases lives in https://github.com/gogs/gogs/blob/master/internal/db/release.go.
