### ISSUE TITLE
template: repo/diff/box:82:21: executing "repo/diff/box" at <call $.IsImageFile $file.Name>: error calling call: revision does not exist

### ISSUE THREAD

**Issue by onedou** [gogs/gogs#6029]
template: repo/diff/box:82:21: executing "repo/diff/box" at <call $.IsImageFile $file.Name>: error calling call: revision does not exist

**Comment by zTrix** [comment]
Just got same issue here. To provide more information, the situation occurred when creating pull request, when selected some branch and click that, the page jumped and showed something like this:

<img width="622" alt="2020-03-29_11-57" src="https://user-images.githubusercontent.com/471934/77839964-8bb26e00-71b4-11ea-88da-6f0bd8294255.png">

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
