### ISSUE TITLE
Failed to display commit with template error

### ISSUE THREAD

**Issue by zTrix** [gogs/gogs#6034]
When creating pull request by click "New Pull Request" button, gogs shows a web page for selecting base branch and compare branch. However after selecting the compare branch, the web page always jump to some error page like showed below.

<img width="622" alt="2020-03-29_11-57" src="https://user-images.githubusercontent.com/471934/77850913-415adc80-7208-11ea-94a4-565b99c5396e.png">

**Git version**

I'm using the latest version pulled from `docker pull gogs/gogs:latest` , Image Id `4d9b2aaae928`.

git commit https://github.com/gogs/gogs/commit/470274204e6714c8062a49fa9e96450a67452133

```
$ ./gogs --version
Gogs version 0.12.0+dev
```

**Operating system**

```
$ docker exec -it git_gogs_1 cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.4
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Database**
```
$ file gogs.db 
gogs.db: SQLite 3.x database, last written using SQLite version 3030001
```

**To Reproduce**
1. Go to pull request page of any project.
2. Click on `New Pull Request`
3. Select some branch other than `master` for compare branch
4. See error like screenshot shown above.

**Can you reproduce the bug at https://try.gogs.io?**

No, the error page did not show and I've no idea why.

**Expected behavior**

Continue to show diff page of the pull request.

**Actual behavior**

A plain web page shown saying that: `template: repo/diff/box:82:21: executing "repo/diff/box" at <call $.IsImageFile $file.Name>: error calling call: revision does not exist`

**Screenshots**

<img width="622" alt="2020-03-29_11-57" src="https://user-images.githubusercontent.com/471934/77850913-415adc80-7208-11ea-94a4-565b99c5396e.png">

**Additional context**

No error found in log/gogs.log.

**Comment by zTrix** [comment]
Just tried `docker pull gogs/gogs:0.11.91` and everything goes ok.

**Comment by unknwon** [comment]
Thanks for the feedback!

Are you doing cross-repo PR or within the same repository?

**Comment by zTrix** [comment]
> Thanks for the feedback!
> 
> Are you doing cross-repo PR or within the same repository?

Same repo.

**Comment by xZero707** [comment]
Having the same issue with my instance of Gogs. 
In my case it also occurs when I click on some specific commits. 


Following is for branch compare:
`template: repo/diff/box:82:21: executing "repo/diff/box" at <call $.IsImageFile $file.Name>: error calling call: revision does not exist`


When I click on some commit (the same error):
eg. https://git.example.com/Someone/SomeRepo/commit/964f4a07d55b3a76e49c03c27bf1d46d95c0802b

**Comment by onedou** [comment]
My situation is:
First
![image](https://user-images.githubusercontent.com/3422640/77867496-143f1600-726a-11ea-8992-820552216a54.png)
Then
![image](https://user-images.githubusercontent.com/3422640/77867522-2e78f400-726a-11ea-8f45-7960eec16be0.png)

**Comment by unknwon** [comment]
@onedou only this specific commit has this problem, or all commits? Would you mind post the patch of the commit here?

**Comment by onedou** [comment]
only this specific commit @unknwon

**Comment by unknwon** [comment]
OK, would you mind post the patch of the commit here?

**Comment by onedou** [comment]
http://git.bel.org.cn/big/school-chat/commit/bcb722edd2f8fbdaf2b9c8449a7f8c6c0ef352a1 @unknwon

**Comment by zTrix** [comment]
Another commit resulting the same error: http://git.bel.org.cn/big/school-chat/commit/d3ec1322f3d1b2daf5d827e4a668f50c55c51f7c

**Comment by unknwon** [comment]
Awesome! Thanks @onedou and @zTrix, will look into this tonight.

**Comment by zTrix** [comment]
After some debugging, I think this is a upstream bug of  https://github.com/gogs/git-module

The issue happens when there are `rename` operation in git repo.

**Comment by xZero707** [comment]
@zTrix Then it makes sense. I've done a lot of refactoring recently, including renaming. That explains semi-random occurrence. 
Btw amazing work. Never seen anyone looking into issue this fast! 
So, should we create a new issue on gogs/git-module ?

**Comment by zTrix** [comment]
Agreed.

I think the following steps should be a minimal setup for reproducing the issue:

1. create a new git branch from some existing repo
2. git rename some file and commit
3. visit http://127.0.0.1:3000/<repo>/<project>/compare/master...<repo>:some_branch

**Comment by unknwon** [comment]
> So, should we create a new issue on gogs/git-module ?

No need, that's just a subproject of Gogs.

**Comment by zTrix** [comment]
Actually for old working version (maybe git-module@0.8.3), when some git rename happens, `IsImageFile` would not handle the logic either. However, the old version `IsImageFile` just ignores the err and returns `false`, that's why this issue only occurs now.

https://github.com/gogs/git-module/blob/f29bce1e3a666c02175d080892be185405dd3af4/commit.go#L79

**Comment by unknwon** [comment]
> Actually for old working version (maybe git-module@0.8.3), when some git rename operation happens, `IsImageFile` would not handle logic correctly either. However, the old version `IsImageFile` just ignores the err and returns `false`, that's why this issue only occurs now.
> 
> [gogs/git-module:commit.go@`f29bce1`#L79](https://github.com/gogs/git-module/blob/f29bce1e3a666c02175d080892be185405dd3af4/commit.go#L79)

Good find!

**Comment by unknwon** [comment]
Tracked down the root issues (actually two bugs), with some improvements about handling file rename. PR coming soon.

**Comment by unknwon** [comment]
It now works! https://try.gogs.io/unknwon/template-error/commit/d3ec1322f3d1b2daf5d827e4a668f50c55c51f7c

**Comment by zTrix** [comment]
Great! Thanks!

**Comment by xZero707** [comment]
Wow. You're amazing! Thanks a lot!
