### ISSUE TITLE
[TRACE] SSH: Handshaking for <IP>:<PORT>

### ISSUE THREAD

**Issue by BigGitWorld** [gogs/gogs#6050]
Hello everyone.
I installed the Gogs in my VPS successfully and it is working fine.
But I don't know what is the below messages in the logging when run the Gogs by ``./gogs web``.
Where the ``<ip-X>`` and ``<port-X>`` are unknown for me!
These messages are repeated periodically.
```
[TRACE] SSH: Handshaking for <ip-1>:<port-1>
[ERROR] [.../runtime/asm_amd64.s:1337 goexit()] SSH: Error on handshaking: ssh: unmarshal error for field Language of type disconnectMsg
...
[TRACE] SSH: Handshaking for <ip-2>:<port-2>
[ERROR] [.../runtime/asm_amd64.s:1337 goexit()] SSH: Error on handshaking: ssh: unmarshal error for field Language of type disconnectMsg
```
What is this?Is this a **Security vulnerability** in the Gogs?

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
