### ISSUE TITLE
PGSQL auth fails

### ISSUE THREAD

**Issue by pycycle** [gogs/gogs#6057]
**Describe the bug**
When configuring the PostgreSQL database I see the following error:
```
[...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: sync: pq: unknown authentication response: 10
```
As fare as I can tell the error only shows up if I use SCRAM-SHA-256 authentication for the database. After some googling I assume that the currently used pg library does not support this authentication.
Could you possibly verify if this is the problem and if so, are there plans to update the pg library?

**Gogs version or commit**
Gogs Version: 0.11.91.0811

For the installation I used the provided binary (https://gogs.io/docs/installation/install_from_binary)

**Git version**
git version 2.20.1

**Operating system**
Raspbian Buster

**Database**
Postgresql 11.7

**To Reproduce**
I used following configuration for the database connection:
* [database]
* DB_TYPE  = postgres
* HOST     = [dns-name of database]
* NAME     = gogs
* USER     = [db-username]
* PASSWD = [db-user password]
* SSL_MODE = require

**Can you reproduce the bug at https://try.gogs.io?**
No

**Expected behavior**
The connection to the database is established.

**Actual behavior**
The connection fails and consequently Gogs cannot be started.

**Comment by unknwon** [comment]
Hi, thanks for the feedback!

The latest `master` uses `lib/pq` v1.3.0 which should have SCRAM support:  https://github.com/gogs/gogs/blob/bae1d6ccd81cd427382a2456e7c3646bdac9cf46/go.mod#L35
