### ISSUE TITLE
Broken LDAP Auth

### ISSUE THREAD

**Issue by Jacox98** [gogs/gogs#6074]
**Describe the bug**
Hello,
I noticed a problem with the configuration and use of the LDAP server.
When trying to edit or add a method the server responds with the following error
An error has occurred: sql: Scan error on column index 5, name "cfg": unsupported Scan, storing driver.Value type [] uint8 into type * core.Conversion

The fact is highly blocking because it makes the platform unusable, nobody can authenticate themselves in LDAP

**Gogs version or commit**
gogs/gogs:latest

**Operating system**
Docker

**Database**
mariadb:latest

**To Reproduce**
Simple login in LDAP
or
Administration panel
authentication
Try to modify one of the servers
Crash

**Expected behavior**
Login

**Actual behavior**
Unable to login or edit auth method

**Screenshots**
![image](https://user-images.githubusercontent.com/35966887/78577058-cc059200-782d-11ea-948a-879e466554de.png)

**Comment by unknwon** [comment]
Thanks for the feedback! I've reproduced on my dev machine, working on fix now.

**Comment by unknwon** [comment]
Patch has been merged to `master`, please wait for ~20mins for Docker Hub to finish building the new image.

**Comment by Jacox98** [comment]
> Patch has been merged to `master`, please wait for ~20mins for Docker Hub to finish building the new image.

Hi thanks for the quick fix, but I seem that the image is always broken even by downloading it again from the docker hub

**Comment by unknwon** [comment]
Hmm... which image version have you pulled to your local machine?

**Comment by unknwon** [comment]
OK, looks like Docker Hub has been failing to build image since yesterday, let me see what's going on.

**Comment by unknwon** [comment]
Docker Hub seems taking forever to build an image :(

**Comment by Jacox98** [comment]
> Docker Hub seems taking forever to build an image :(

Ouroboros has updated the container now everything works thanks a lot.
Good day
