### ISSUE TITLE
RPM from Packager.io installes wrong Build 

### ISSUE THREAD

**Issue by SurtursRevenge** [gogs/gogs#6093]
Hello,

i am trying to install gogs stable on centos 7 via repository from packager.io (https://packager.io/gh/gogs/gogs/builds/221/install/centos-7)

The package is tagged as version  0.11.91 but 1.12+dev version gets installed with this package.
What am i doing wrong ? This happens on update with yum and also on fresh install.

**Comment by unknwon** [comment]
It's the the current version per se, packager.io uses the latest tag for some reason.
