### ISSUE TITLE
Webhook doesn't auto-trigger when using gogs docker image

### ISSUE THREAD

**Issue by showgp** [gogs/gogs#6096]
**Describe the bug**

Webhook is not triggered automatically when use the latest version of gogs docker image.

**Gogs version, commit or Docker image SHA**

The output of `docker image inspect gogs/gogs` command:

```json
[
    {
        "Id": "sha256:61f6ff15f097be9753dc82a8fa6c8bfb9f760e469b458443f7a7def7d787c7a0",
        //...
    }
]
```

**Operating system**

Centos 7.0

**Database**

MySQL 

**To Reproduce**

1. create & run the gogs container (latest version):
    ```
    docker run -d --name=gogs --restart always -p 10022:22 -p 10080:3000 -v gogs-data:/data gogs/gogs
    ```
1. create & run the mysql container (latest version):
    ```
    docker run --name gogs-mysql -v gogs_mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=xxxxxxxxxxxx -d mysql
    ```

1. connect to mysql container and create a database named "gogs":
    ```sql
   CREATE DATABASE gogs;
    ```
1. go to "http://my.domain:10080" and install gogs.
1. start a backend server that can handle the POST request send from gogs's webhook.

1. configure a repo's webhook:
![image](https://user-images.githubusercontent.com/17868582/79124273-88cb9600-7dce-11ea-839e-dc38b12c07e3.png)

1. click the "Test Delivery" button, the request was successfully send:
![image](https://user-images.githubusercontent.com/17868582/79124418-da742080-7dce-11ea-84b3-52f9b48b398f.png)

1. git commit -> the webhook generate a new record, but not send:
![image](https://user-images.githubusercontent.com/17868582/79124715-7f8ef900-7dcf-11ea-8542-3291f36a64cd.png)

**Expected behavior**

Webhook should automatically trigger the POST request.

**Actual behavior**

The POST request doesn't send automatically.

> BTW I'm not sure if this is a bug or just a configuration issue.

**Comment by unknwon** [comment]
Thanks for your high quality bug report ❤️

---

1. Have you turned on "Require sign-in view" during installation?
2. Could you provide logs in the `/data/gogs/log/hooks/post-receive.log` (path inside your Docker container)?

**Comment by lz1974** [comment]
> 感谢您的高质量错误报告 ❤️
> 
> 1. 在安装过程中是否打开了“需要登录视图”？
> 2. 您能否在`/data/gogs/log/hooks/post-receive.log`（Docker容器内的路径）中提供日志？

我也遇到这个问题，post-receive.log我查看了下大小是0KB

**Comment by lz1974** [comment]
> Thanks for your high quality bug report ❤️
> 
> 1. Have you turned on "Require sign-in view" during installation?
> 2. Could you provide logs in the `/data/gogs/log/hooks/post-receive.log` (path inside your Docker container)?

I also encountered this problem. I checked the size of post-receive.log as 0kb

**Comment by lz1974** [comment]
> **描述错误**
> 
> 使用最新版本的gogs docker映像时，不会自动触发Webhook。
> 
> **Gogs版本，提交或Docker映像SHA**
> 
> `docker image inspect gogs/gogs`命令输出：
> 
> ```json
> [
>     {
>         “ id ”： “ sha256：61f6ff15f097be9753dc82a8fa6c8bfb9f760e469b458443f7a7def7d787c7a0 ”，
>          // ...
>     }
> ]
> ```
> 
> **操作系统**
> 
> Centos 7.0
> 
> **数据库**
> 
> 的MySQL
> 
> **重现**
> 步骤来重现行为：
> 
> 1. 创建并运行gogs容器（最新版本）：
>    ```
>    docker run -d --name=gogs --restart always -p 10022:22 -p 10080:3000 -v gogs-data:/data gogs/gogs
>    ```
> 2. 创建并运行mysql容器（最新版本）：
>    ```
>    docker run --name gogs-mysql -v gogs_mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=xxxxxxxxxxxx -d mysql
>    ```
> 3. 连接到mysql容器并创建一个名为“ gogs”的数据库：
>    ```sql
>    创建 数据库 插件 ;
>    ```
> 4. 转到“ [http：//my.domain：10080](http://my.domain:10080) ”并安装Gogs。
> 5. 启动一个后端服务器，该服务器可以处理来自gogs的webhook的POST请求。
> 6. 配置仓库的webhook：
>    ![图片](https://user-images.githubusercontent.com/17868582/79124273-88cb9600-7dce-11ea-839e-dc38b12c07e3.png)
> 7. 单击“测试交付”按钮，请求已成功发送：
>    ![图片](https://user-images.githubusercontent.com/17868582/79124418-da742080-7dce-11ea-84b3-52f9b48b398f.png)
> 8. git commit-> webhook生成新记录，但不发送：
>    ![图片](https://user-images.githubusercontent.com/17868582/79124715-7f8ef900-7dcf-11ea-8542-3291f36a64cd.png)
> 
> **预期行为**
> 
> Webhook应该会自动触发POST请求。
> 
> **实际行为**
> 
> POST请求不会自动发送。
> 
> > 顺便说一句，我不确定这是错误还是只是配置问题。

我也遇到这个问题，想请教下后续你是怎么解决的?

**Comment by unknwon** [comment]
@lz1974 Upgrade to latest `master`.
