### ISSUE TITLE
Fall back to default time format when misconfigured

### ISSUE THREAD

**Issue by brandonpoc** [gogs/gogs#6098]
**Describe the bug**
In Ubuntu 16.04.6 LTS, with the latest gogs release (gogs 0.11.91-1586665127.d19287d5.xenial), the service fails to start because a dependency, the gogs web server, fails with the following errors:

2020/04/13 23:36:20 [FATAL] [...i3d/opt/gogs/internal/cmd/web.go:161 runWeb()] Failed to initialize application: init configuration: unrecognized '[time] FORMAT':

FIX: Commenting out the [time] key/heading in the /etc/gogs/conf/app.ini file along with its FORMAT= sub-key seems to fix this. I do not know if this is Ubuntu specific or what; but this takes care of it.

**Gogs version and commit**
0.11.91-1586665127.d19287d5.xenial (Ubuntu 16.04 LTS)

**Git version**

$ git version
git version 2.7.4

**Operating system**
Ubuntu 16.04.6 LTS 'xenial'

**Database**
mysql

**To Reproduce**
1. the 'service' and 'systemctl' commands do not provide much information; however, running '/usr/bin/gogs  run web' reveals the issue.

**Expected behavior**
gogs web server would start.

**Actual behavior**
error as above.

**Fix**
Commenting out the [time] key/heading in /etc/gogs/conf/app.ini file along with its FORMAT= sub-key seems to fix this. I do not know if this is Ubuntu specific or what; but this takes care of it.

**Comment by unknwon** [comment]
Thanks for your high quality bug report ❤️

---

I think this is packager.io specific problem, but the workaround is easy, just fall back to use `time.RFC3339`:
https://github.com/gogs/gogs/blob/659acd48b1a131476fd98a54604fa6416b1cef9d/internal/conf/conf.go#L296-L297

PR is welcome :)

**Comment by kousikmitra** [comment]
If no one has worked on this I would like to raise a PR!

**Comment by unknwon** [comment]
@kousikmitra That would be great, thank you!
