### ISSUE TITLE
`sshd` starts regardless of whether `START_SSH_SERVER` is set or not when running in docker

### ISSUE THREAD

**Issue by ly4096x** [gogs/gogs#6104]
**Describe the bug**

When running in docker, `sshd` starts regardless of whether `START_SSH_SERVER` is set or not.

**Gogs version and commit**

083ecb7244486d530ddc8587b6b4776d21616353

**Git version**

2.22.2

**Operating system**

CentOS 8 with Docker

**Database**

SQLite

**To Reproduce**

1. Set `START_SSH_SERVER = false` in `app.ini`
2. Start the container
3. From host `htop` I can find `sshd` is running

**Can you reproduce the bug at https://try.gogs.io?**

Not able to run `htop` so it's no.

**Expected behavior**
`sshd` not running when `START_SSH_SERVER = false`

**Actual behavior**

`sshd` is running when `START_SSH_SERVER = false`

**Screenshots**

```
 1010 root       20   0 1756M 53644 22732 S  0.0  0.1 10:28.99 ├─ containerd
 2008 root       20   0  106M  8276  3956 S  0.0  0.0  0:10.87 │  ├─ containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.ru
 2033 root       20   0  1060   388   348 S  0.0  0.0  0:00.30 │  │  └─ s6-svscan /app/gogs/docker/s6/
 2293 root       20   0  1064   512   476 S  0.0  0.0  0:00.00 │  │     ├─ s6-supervise syslogd
 2294 root       20   0  1556     4     0 S  0.0  0.0  0:00.00 │  │     │  └─ syslogd -nS -O-
 2292 root       20   0  1064   440   404 S  0.0  0.0  0:00.00 │  │     ├─ s6-supervise openssh
 2295 root       20   0  4340  2928  2536 S  0.0  0.0  0:00.00 │  │     │  └─ sshd -D -f /app/gogs/docker/sshd_config
 2291 root       20   0  1064   424   388 S  0.0  0.0  0:00.00 │  │     ├─ s6-supervise gogs
 2296 git        20   0  143M 94444 28780 S  0.0  0.1  1:30.30 │  │     │  └─ gogs web
 2290 root       20   0  1064   444   404 S  0.0  0.0  0:00.00 │  │     └─ s6-supervise crond
```

**Additional context**

```
gogs_1  | 2020-04-09T08:19:30.389601073Z usermod: no changes
gogs_1  | 2020-04-09T08:19:30.429586004Z Apr  9 04:19:30 syslogd started: BusyBox v1.30.1
gogs_1  | 2020-04-09T08:19:30.482918351Z Apr  9 08:19:30 sshd[29]: Server listening on :: port 22.
gogs_1  | 2020-04-09T08:19:30.482931194Z Apr  9 08:19:30 sshd[29]: Server listening on 0.0.0.0 port 22.
gogs_1  | 2020-04-09T08:19:30.573942783Z 2020/04/09 04:19:30 [TRACE] Log mode: File (Info)
```

**Comment by unknwon** [comment]
Thanks for your high quality bug report ❤️

---

OpenSSH is a separate application from Gogs, so Gogs's configuration does not and should not have effect on it. And in fact `START_SSH_SERVER = false` is made for builtin SSH server.

If you don't want to expose SSH access to your Gogs instance, you can simply not expose the SSH port when you start the Docker container.
