### ISSUE TITLE
[DOCKER] Looping after configuration: Log mode: File (Info)

### ISSUE THREAD

**Issue by glamax13** [gogs/gogs#6108]
Building on my development computer when well.
But i am currently trying to deploy a gogs container with docker on my production server and it stays stuck on with the message:
2020/04/15 15:31:51 [TRACE] Log mode: File (Info)

Environment:
> Gogs version: e131a45.
> Prod: ubuntu server 18.04 LTS
> Dev: ubuntu 19.04
> Latest postgresql ( PG_VERSION=12.2-2.pgdg100+1" ) database running in the same network than gogs.

Following this command:
> docker run -d\
> 	--name gogs\
> 	--network net_gogs\
> 	-v gogs_data:/data\
> 	-p 29102:22\
> 	-p 29103:3000\
> 	gogs/gogs

and after having correctly configured the database connection (wrong settings fails correctly), then:
I am supposed to be welcome with a login page.
But the server doesn't respond and i'm stuck with a 502 bad gateway (proxy with nginx).

> $ docker logs -f 61e273d74188b882b4b2ad166fea971d8c0e68f964287675cfec2219f882ae3d
> usermod: no changes
> Apr 15 15:24:15 syslogd started: BusyBox v1.31.1
> 2020/04/15 15:24:15 [ WARN] Custom config "/data/gogs/conf/app.ini" not found. Ignore this warning if you're running for the first time
> 2020/04/15 15:24:15 [TRACE] Log mode: Console (Trace)
> 2020/04/15 15:24:15 [ INFO] Gogs 0.12.0+dev
> 2020/04/15 15:24:15 [TRACE] Work directory: /app/gogs
> 2020/04/15 15:24:15 [TRACE] Custom path: /data/gogs
> 2020/04/15 15:24:15 [TRACE] Custom config: /data/gogs/conf/app.ini
> 2020/04/15 15:24:15 [TRACE] Log path: /app/gogs/log
> 2020/04/15 15:24:15 [TRACE] Build time: 2020-04-15 02:39:22 UTC
> 2020/04/15 15:24:15 [TRACE] Build commit: e131a4564680a3257a2d4795af7669e4260b33b9
> 2020/04/15 15:24:15 [ INFO] Run mode: Development
> 2020/04/15 15:24:16 [ INFO] Listen on http://0.0.0.0:3000
> Apr 15 15:24:16 sshd[50]: Server listening on :: port 22.
> Apr 15 15:24:16 sshd[50]: Server listening on 0.0.0.0 port 22.
> 2020/04/15 15:25:21 [TRACE] Session ID: 046384e5a0bf49ce
> 2020/04/15 15:25:21 [TRACE] CSRF Token: VtQi2qt4ybe8hKsjnxAki_kMAKU6MTU4Njk2NDMyMTczNDEyNjU1Ng
> 2020/04/15 15:25:21 [TRACE] Template: install
> 2020/04/15 15:26:10 [TRACE] Session ID: 046384e5a0bf49ce
> 2020/04/15 15:26:10 [TRACE] CSRF Token: 6doQSCGLofWT9mltKLHdHf6SYm06MTU4Njk2NDM3MDc0NzkwNjk5MA
> 2020/04/15 15:26:11 [TRACE] Log mode: File (Info)
> 2020/04/15 15:26:11 [TRACE] Log mode: File (Info)
> 2020/04/15 15:26:12 [TRACE] Log mode: File (Info)
> etc...

**Comment by glamax13** [comment]
I don't know what it was but i just append to deleted my production docker environment, refresh the postgres image, used simple testing logins and it just append to... work?! I might reopen it if it fails again.

**Comment by unknwon** [comment]
FYI, log goes into `/app/gogs/log/gogs.log`.
