### ISSUE TITLE
Require_Signin_view does not work

### ISSUE THREAD

**Issue by HelloWorldlsla** [gogs/gogs#6109]
I installed gogs with `docker pull gogs/gogs`.
Then I run it.
Then I opened my browser (which is always in anonymous) in `localhost:8080/install`
I enabled the `Require_Signin_view` option, configured the Database to sqlite3 and clicked on Finish.
I created a new git repository (in public mode) and a new account (called toto).

I logged out and closed the browser. Then i opened it again and I opened `localhost:8080/`.
I clicked in the `Expore` button and I was able to see all the repositories and all users in the server.

(I verified with admin,  `Require_Signin_view` was enabled).

I executed `docker stop gogs`. Then `docker start gogs`. Nothing changed (I was still able to see repos and users without logged in).

I executed `docker exec -it gogs bash` and I run `reboot`. Then I started it again with `docker start gogs`.
Now the  `Require_Signin_view` works perfectly.

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

---

FYI, this option requires restarting Gogs 😞
