### ISSUE TITLE
Repository browsing still very slow

### ISSUE THREAD

**Issue by jukisu23** [gogs/gogs#6114]
When I open any repository it takes a very long time.
For a full repo with a lot of files it's around ~8min and for a completely empty repo it still takes ~25sec.
Anything unrelated to repositories responds very fast (eg settings, profile,...)

```
DISABLE_GRAVATAR = true
ENABLE_FEDERATED_AVATAR = false
```
2020 Gogs Version: 0.11.91.0811

**Operating system**
Windows Server 2012 on local Network

**Database**
10.4.11-MariaDB

**To Reproduce**
1. Go to anything related to a repository (not just the main page, also issues, wiki, files,...)

**Expected behavior**
Fast response times

**Actual behavior**
Takes ages to load
Empty Repo:  `Page: 22345ms Template: 9ms`
Full Repo: `Page: 558342ms Template: 100ms`

**Comment by unknwon** [comment]
Thanks for the feedback!

I think this is duplicated to https://github.com/gogs/gogs/issues/1518.
