### ISSUE TITLE
Proposal: Remove `db.User.LoginType` field

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6117]
The [only use case of this field](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/gogs/gogs%24%40master+.LoginType+&patternType=literal) is to help determine if a user is a local account, i.e. 

https://github.com/gogs/gogs/blob/fa497b16332c24bc4d9e788c64bda94e3c1499a7/internal/db/user.go#L143-L146

The same thing can be achieved by the following:

```go
func (u *User) IsLocal() bool {
	return u.LoginSource <= 0
}
```

Thus, propose to remove this field.

**Comment by kousikmitra** [comment]
@unknwon would like to work on this!

**Comment by unknwon** [comment]
Thanks @kousikmitra!
