### ISSUE TITLE
Error when starting does not appear in systemd output

### ISSUE THREAD

**Issue by DrJHD** [gogs/gogs#6121]
To replicate:
Create a new Debian server.
Enable ssh on the server generally.
Install gogs according to the instructions with internal ssh disabled.
Install the gogs.system file per the documentation.
Reboot to confirm that gogs starts automatically.
Edit app.ini to enable the internal ssh server.
Restart gogs using systemctl.
Immediate use of systemctl status gogs will show it starting, but after a few seconds it will stop and the error message will state that the start request was repeated too quickly.
Start gogs using the command line, copying the instruction from the gogs.system file.
This will show the important error. The internal ssh server cannot run on the same port as the server's.

This error message is the most important one for fixing the installation and should appear in the systemd output. The current systemd output is misleading.

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
