### ISSUE TITLE
config ''C:/gogs/custom/conf/app.ini'' not found

### ISSUE THREAD

**Issue by lisihe** [gogs/gogs#6125]
在`authorized_keys`文件中生成的指令
```
command="C:/gogs/gogs.exe serv key-1 --config='C:/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa xxx
```
中`'C:/gogs/custom/conf/app.ini'`多一对引号。
如果有这个引号，ssh执行时会报
```Custom config ''C:/gogs/custom/conf/app.ini'' not found, ignore this if you're running first time```
错误，这样ssh提交就一直失败。
如果手动修改`authorized_keys`文件，将多余的一对引号出掉就不会报错。
gogs将`'C:/gogs/custom/conf/app.ini'`整个字符串当做文件名查找了。
请问有解决方案吗？

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
