### ISSUE TITLE
Windows版本Pull Request自动合并时提示需要冲突，本地合并无冲突

### ISSUE THREAD

**Issue by BokalaQuan** [gogs/gogs#6127]
如题，OS版本为WIN10家庭版，DB为PostgreSQL10，Gogs版本为0.11.91.0811

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
