### ISSUE TITLE
[Features] Hosted Repo :)

### ISSUE THREAD

**Issue by aice09** [gogs/gogs#6129]
**Describe the feature**

Is their way to host repository in gogs, the same way the the Github do it but also execute other language like .py .php that Heroku do it?
1. Hosted a website like github pages
 e.g. repo1.localhost:3000
2. Enables to run other language to hosted website like Heroku that run .php, .py, .go etc
3. Enable database connection of hosted repo
4. Enable custom domain

**Describe the solution you'd like**

I would like to host a repository in my gogs like github pages and enable **not only markdown** to run into it **but other programming language** that is most likely do by Heruko. And I would like to connect my repo to different database not only a web hosted database like mongo atlas, firebase, or dynamo but also connect ti my self histed databases. Then add custom domain to connect to my actual paid domain name or create a local domain,to not only display like repo1.localhost:3000 but also like firstrepo.local or firstrepo.com

This is just a suggestion.  :)

**Comment by unknwon** [comment]
Thanks for the suggestion! However, I think this is far beyond what Gogs is intended. You should instead use whatever tool good at doing hosted repo and connect to Gogs.
