### ISSUE TITLE
Gogs post receive hook for mirroring on windows

### ISSUE THREAD

**Issue by psyciknz** [gogs/gogs#6133]
Gogs 0.11.91.0811 on Windows
I'm trying to set up a gogs mirror to a Git Linux Server.

I have a custom post-receive hook defined in the repository for:
```
#!/usr/bin/env bash
echo "receive"
git push --mirror server:/GIT/Reports
```

When I, as me, run git push --mirror server:/GIT/Reports it works fine.
When I, do a commit to trigger the post-receive hook, I see an error for 
```
remote: receive
remote: Host key verification failed.
remote: fatal: Could not read from remote repository.
remote:
remote: Please make sure you have the correct access rights
remote: and the repository exists.
remote: Gogs: Internal error
```

Now I'm assuming this is because gogs is running under Local System for windows.   So I had a play with setting a .ssh/config file and using my private key for the destination machine.

But what is getting me stuck is that I only receive the error message:
```
2020/04/23 12:07:11 [FATAL] [...ogs/gogs/cmd/hook.go:274 runHookPostReceive()] Fail to execute custom post-receive hook: exit status 128
```
In the post-receive log.
Where I was expecting to see my Echo statement as well, making me think it's not runnign at all.  I want to get the echo wokring so I can then start figuring out what my user is, to give to the remote git server.

**Comment by unknwon** [comment]
Hi, have you tried with just echo?

```sh
#!/usr/bin/env bash
echo "receive"
```

What do you get? (please paste output or log)

**Comment by psyciknz** [comment]
I found that it wasn't posting receive into the log that I expected...but did see it on session where I was puhing the commit.   Once I saw that happing I started adding a bunch of commands to the post-receive hook, including explicit ssh commands and debugging.

What finally ended up working for me was to ssh to the server (before the git push command) with 
```
ssh -vvv -o StrictHostKeyChecking=no
```
This looked like it connected, and then after removing that line from the script, the push is working.

You can actually see in my first post, that it says 
```
remote: receive
```

Which I didn't realise was the scripting outputting "receive" for me.

But I have it working now, it was an ssh issue.

**Comment by unknwon** [comment]
Ah! I see, this was the actual error:
```
remote: Host key verification failed.
```
