### ISSUE TITLE
packager.io builds for raspberry pi / raspbian

### ISSUE THREAD

**Issue by anderbubble** [gogs/gogs#6137]
**Describe the feature**

I want to install Gogs on a Raspberry Pi using Salt. There are a few formulae that install from the github builds, but since there are packager.io packages I'd like to try to build a formula around them. However, I don't see a build for the Raspberry Pi / Raspbian. (Presumably the Debian build would work as long as it was built for arm vs x86_64.)

**Describe the solution you'd like**

I think there should be a packager.io package compatible with the Raspberry Pi.

**Describe alternatives you've considered**

- Manual installation using the available raspberry pi builds on github

**Additional context**

I am absolutely willing to help with this; but I haven't used packager.io before. If this seems feasible to the maintainers (e.g., if packager.io is known to support Raspberry Pi, and, e.g., this is just a matter of research an a PR to this project) I'll do that research, but any pointers or feedback before I get started are welcome.

**Comment by unknwon** [comment]
Thanks for the feedback!

This is the file configures the target system to build on packager.io: https://github.com/gogs/gogs/blob/master/.pkgr.yml. However, I do not know if they ever support ARM, which has to be researched.

**Comment by anderbubble** [comment]
I went poking around on the packager.io site and can't find any references to either arm or raspberry. It appears it can only do x86_64 builds; so I guess this is a non-starter.
