### ISSUE TITLE
Pull Request Error -500 Server Error

### ISSUE THREAD

**Issue by psyciknz** [gogs/gogs#6138]
Getting the following error when trying to run a pull request on a repository:
```
2020/04/29 12:23:23 [ERROR] [...g/context/context.go:191 ServerError()] GetPatch: execution is timeout [duration: 1m0s] - Syntax Error: Couldn't read xref table
Syntax Warning: PDF file is damaged - attempting to reconstruct xref table...
```
Is that trying to do something with some PDFs in the repository, or is it something else?
How can I resolve?

Version is 2020 Gogs Version: 0.11.91.0811 
Can i exclude, or remove any PDFs file in the repo is that is the problem?

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
