### ISSUE TITLE
Backup and restore are broken in latest release

### ISSUE THREAD

**Issue by xZero707** [gogs/gogs#6139]
**Describe the bug**

In latest version (build hash dbe373af6f2132bb4fba4e108180cab23c7e4d80) `./gogs backup` now fails with an error:
```
 Failed to dump database: dump table 'LFSObject': pq: column "id" does not exist
```

This happens with either new or upgraded gogs install. 

I haven't tested with other database than Postgres. 
I haven't tested binary directly but only docker release. 

**Gogs version and commit**

Gogs version: 0.12.0+dev

Commit: dbe373af6f2132bb4fba4e108180cab23c7e4d80

**Git version**

```
$ git version

```

2.24.3

**Operating system**

Alpine Linux

**Database**

Postgres 12.2

**To Reproduce**
It's simple; Just run `./gogs backup`

**Can you reproduce the bug at https://try.gogs.io?**

I don't have access to command line on try.gogs.io. 

**Expected behavior**

Backup archive should have been created. 

**Actual behavior**

Fails with error:
` Failed to dump database: dump table 'LFSObject': pq: column "id" does not exist`

**Screenshots**

![Opera Snapshot_2020-04-29_104044_portainer](https://user-images.githubusercontent.com/3281104/80576706-f1895400-8a05-11ea-907d-e25697faa8b1.png)

**Additional context**

No errors. 
```
2020/04/29 08:27:02 [ INFO] Gogs 0.12.0+dev
2020/04/29 08:27:02 [ INFO] Git config user.name set to Gogs
2020/04/29 08:27:03 [ INFO] Git config user.email set to gogs@fake.local
2020/04/29 08:27:03 [ INFO] Run mode: Production
2020/04/29 08:27:03 [ INFO] First-time run install finished!
```

**Comment by xZero707** [comment]
I found this while testing #5939. The error occurred after merging upstream to my fork. 
Before merging, backups was working smoothly. 

Then I spun up the official image and confirmed it happens there as well. 
I've also tested with new/fresh install.

**Comment by unknwon** [comment]
Thanks for the report! I'm aware of this bug and working on it (just very slow as my availability isn't much recently).

**Comment by xZero707** [comment]
Great work @unknwon. Let me know if I can help.

**Comment by unknwon** [comment]
Everything should work as before in the latest `master`. If not, please let me know!
