### ISSUE TITLE
Register check and disable registeration

### ISSUE THREAD

**Issue by wuchang** [gogs/gogs#614]
什么时候有注册审核和禁止注册功能？

**Comment by mehrad-rafigh** [comment]
I am trying to find the config file to disable registration. Could you please point me to the right direction?

**Comment by Unknwon** [comment]
Hi @mehrad-rafigh , it's in section(http://gogs.io/docs/advanced/configuration_cheat_sheet.html#service) and `DISABLE_REGISTRATION`. :star:

**Comment by PVineeth** [comment]
@Unknwon In Ubuntu after changing DISABLE_REGISTRATION = false in custom/conf/app.ini, registration is still open. What to do next? How to restart gogs?

**Comment by Unknwon** [comment]
@PVineeth You just did the opposite.

**Comment by PVineeth** [comment]
@Unknwon I set DISABLE_REGISTRATION = true and SHOW_REGISTRATION_BUTTON = false. It is still showing up. 

I restarted gogs using `sudo service gogs restart`, still it showed up.

In logs I get, 

> Fail to start server: listen tcp 0.0.0.0:3000: bind: address already in use

I had to reboot my system and now it is not showing up.

**Comment by Unknwon** [comment]
>Fail to start server: listen tcp 0.0.0.0:3000: bind: address already in use

This means you started Gogs in another way.

**Comment by PVineeth** [comment]
@Unknwon This is how I started it: ./gogs web &
