### ISSUE TITLE
Restore wrongly reports 'Current Gogs version is lower than backup version'

### ISSUE THREAD

**Issue by MasterTalon** [gogs/gogs#6146]
**Describe the bug**
Attempting to restore a backup from version 0.11.68.1023, to a brand new install of version 0.12.0+dev, I received the fatal error message, "Current Gogs version is lower than backup version...".

**Gogs version and commit**
Version: 0.12.0+dev
Commit: 82ffca3fc9988345016c8033f7f65c5b028dfe10

**Git version**
git version: 2.26.2

**Operating system**
FreeBSD 11.2-RELEASE-pl5

**Database**
MySQL 5.7.30

**To Reproduce**
1. Create a backup from a Gogs installation of version 0.11.68.1023
2. Attempt to restore the backup on Gogs installation of version 0.12.0+dev
    a. The command-line used was './gogs restore --config ~/gogs/custom/conf/app.ini -t /tmp/gogs -from ~/gogs-backup-20200503015423.zip'
3. Observe the failure 'Current Gogs version is lower than backup version: 0.12.0+dev < 0.11.68.1023'

**Can you reproduce the bug at https://try.gogs.io?**
N/A Don't have a data-set to work with there.

**Expected behavior**
A user should be able to restore a backup from version 0.11.68.1023 to 0.12.0+dev

**Actual behavior**
A fatal error is encountered.

**Screenshots**
N/A

**Additional context**
If you go into `gogs/internal/cmd/restore.go`, you'll find the comparison on [~line 73](https://github.com/gogs/gogs/blob/82ffca3fc9988345016c8033f7f65c5b028dfe10/internal/cmd/restore.go#L73) and it looks well enough.  However, clearly 0.12.x is not lower (or less) than 0.11.x.  Likely something with the `version.Compare` doesn't like the `+dev` in the version number.

If you swap the `<` in the compare to `>`, and run the restore, it completes fine.  So, the data works; it's just the comparison that doesn't.

**Comment by unknwon** [comment]
Thanks for the report! Will look into this.
