### ISSUE TITLE
关于 GET /repos/:username/:reponame/contents/:path

### ISSUE THREAD

**Issue by coldlin** [gogs/gogs#6148]
因为开发系统需要使用到该接口来获取仓库文件列表, 但是目前Release版本并不支持该接口, 请问什么时候能够出最新版本改善该特性

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
