### ISSUE TITLE
Permanently deleting file from Git not removing from Gogs /data/tmp/local-repo

### ISSUE THREAD

**Issue by peter-snr** [gogs/gogs#6151]
**Describe the bug**

A file that was inadvertantly introduced to the repository has been deleted from Git history and branches using instructions from this Url: [removing-sensitive-data-from-a-repository](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#using-filter-branch) executing commands from items 1 - 6.

However although the file (a large tgz) is no longer present in the checked out repo and the repository has shrunk when checking on the server I can see the file in this directory:

/data/tmp/local-repo/73/<file_is_here>

Is it safe to delete directory '73'?
Should it not also have been removed?

**Gogs version and commit**
Sorry I do not have access to /admin but this is the version number:

Version: 0.11.86.0130

**Git version**

git version 1.8.3.1

**Operating system**
CentOS Linux release 7.5.1804

**Database**
sqlite3 
```
$ sqlite3 --version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668
```
**To Reproduce**
1. Introduce a tgz file to the repository, checking in, committing and push to remote.
2. Carry out steps 1..6 from here to clear from repository.
   [Removing Sensitive Data from a repository](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history)
3. Once all steps are completed (including the push), check on the Gogs server at /data/tmp/local-repo/73/<file_still_here>
4. The file is still on the server in a numbered repository

**Can you reproduce the bug at https://try.gogs.io?**
No, I did not try to introduce a large binary file, did not seem like a good idea as it was a mistake in the first place

**Expected behavior**
As per the GitHub link, the deleted file to be removed from the repository

**Actual behavior**
When checking on the server the file can be found in: /data/tmp/local-repo/73/<file_still_here>

**Screenshots**
N/A

**Additional context**
No Error Logs

Thanks for taking the time to look.

**Comment by unknwon** [comment]
Hi, `/data/tmp/` only gets cleaned up on a restart of Gogs. Generally, you can delete this directory freely, but it's safer to just restart Gogs :)

**Comment by peter-snr** [comment]
Thank you for the swift response!
