### ISSUE TITLE
全量备份很大概率性报错，文件或者目录找不到

### ISSUE THREAD

**Issue by neier-** [gogs/gogs#6154]
Gogs 版本：0.12.0+dev
Go 版本: go1.14.2
数据库：8.0
问题描述：备份未停机，备份的时候经常出错找不到文件或者目录，报错 Failed to save backup archive/no such file or directory。命令是：/app/gogs/gogs backup --tempdir /data/tmp_backups --target /data/backups
![err](https://discuss.gogs.io/uploads/default/original/2X/e/e8125adf95d39f677039378c8d93791e67793cdc.png)

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by unknwon** [comment]
https://github.com/gogs/gogs/issues/6155
