### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by johnTux** [gogs/gogs#6165]
**Describe the bug**

LDAP Result Code 49 "Invalid Credentials"

**Gogs version and commit**

0.11.91.0811

**Git version**

```
$ git version
1.8.3.1
```

**Operating system**

CentOS Linux release 7.8.2003

**Database**

MariaDB-server-10.4.13

**Screenshots**

https://imgur.com/a/SGrjMO1

hi,
command ldapsearch returend next info (deleted some filed values)
```
ldapsearch -H ldap://localhost/ -x -b "ou=SAMBA,dc=company" -LLL '(uid=USER)'
```
dn: cn=Name Surname,ou=users,ou=SAMBA,dc=company
cn: Name Surname
givenName::
gidNumber:
sn::
objectClass: inetOrgPerson
objectClass: sambaSamAccount
objectClass: posixAccount
objectClass: top
sambaSID:
sambaAcctFlags:
uidNumber:
homeDirectory:
userPassword::
sambaLMPassword:
sambaNTPassword:
uid: USER

After setting simple ldap auth I get error:
```
2020/05/15 11:24:21 [TRACE] Session ID: cf09b7493a16439e
2020/05/15 11:24:21 [TRACE] CSRF Token: v9A-rshMCvoODRRP4gHF4C_4aZM6MTU4OTUxODQxODIzOTEyMjI3Mg==
2020/05/15 11:24:21 [TRACE] LDAP: Dialing with security protocol '0' without verifying: false
2020/05/15 11:24:21 [TRACE] LDAP will bind directly via UserDN template: ou=SAMBA,dc=company
2020/05/15 11:24:21 [TRACE] Binding with userDN: ou=SAMBA,dc=company
2020/05/15 11:24:21 [TRACE] LDAP authentication failed for 'ou=SAMBA,dc=company': LDAP Result Code 49 "Invalid Credentials": 
2020/05/15 11:24:21 [TRACE] Template: user/auth/login
```
help, please!

**Comment by unknwon** [comment]
Hi, what LDAP service you're using? Have you looked at this page? https://support.jumpcloud.com/support/s/article/ldap-connection-attempt-results-in-invalid-credentials-49---cannot-bind1

Basically saying credentials are indeed invalid.

**Comment by johnTux** [comment]
i'm using openldap-servers-2.4.44

**Comment by unknwon** [comment]
Thanks for the info, I'm not very familiar with LDAP, how do you 100% verify the credentials are valid?

**Comment by johnTux** [comment]
I use similar services for example redmine with ldap auth. And works fine.

**Comment by johnTux** [comment]
configured ldap (via BindDN) auth, in field Bind DN wrote that is in /etc/openldap/slapd.conf line rootdn
