### ISSUE TITLE
Docker docs point to non-existing URL

### ISSUE THREAD

**Issue by iamhosseindhv** [gogs/gogs#6167]
**Describe the bug**
On docker page there's a link to `app.ini`'s documentation which resolves to a 404 page. more details below.

**To Reproduce**
1. Go to [docker README.MD](https://github.com/gogs/gogs/tree/master/docker#settings)
2. Click on the link stating: "Full documentation of application settings can be found [here](https://gogs.io/docs/advanced/configuration_cheat_sheet.html)."
3. See a 404 error

**Expected behavior**
The link should resolve to configuration [cheat sheet](https://github.com/gogs/docs/blob/master/en-US/advanced/configuration_cheat_sheet.md), or a page on [gogs.io](https://gogs.io/).

**Actual behavior**
A new page gets open on [gogs.io](https://gogs.io/) with 404 error.

**Screenshots**

<img width="1680" alt="Screenshot 2020-05-19 at 15 12 35" src="https://user-images.githubusercontent.com/26996372/82337042-3429c500-99e3-11ea-8654-33d6316c6bc4.png">

**Comment by unknwon** [comment]
Good catch! Fixed.
