### ISSUE TITLE
组织权限不起作用

### ISSUE THREAD

**Issue by JaneYork** [gogs/gogs#6168]
系统：
云服务器centos6.9 64位
git2.26.2
mysql8.0.20社区版
gogs0.11.91（git下载的二进制release版）
部署步骤：
https://blog.csdn.net/qq_31708763/article/details/104814669
亲测，单人均可操作。在团队协作，创建新组织

新建团队，赋予写入权限，可以clone但是无法推送仓库。只能是赋予owner团队才可以推送。这显然是 不对的。
@unknwon @clee 

图片截图：
https://img-blog.csdnimg.cn/20200520163831919.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzMxNzA4NzYz,size_16,color_FFFFFF,t_70

https://img-blog.csdnimg.cn/20200520164051526.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzMxNzA4NzYz,size_16,color_FFFFFF,t_70

💊bug

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by JaneYork** [comment]
> Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Thank you for your prompt reply. But I know you know Chinese.

**Comment by clee** [comment]
> Thank you for your prompt reply. But I know you know Chinese.

I certainly don't. I have no idea why I was tagged :)

**Comment by JaneYork** [comment]
> > Thank you for your prompt reply. But I know you know Chinese.
> 
> I certainly don't. I have no idea why I was tagged :)

Oh, I'm terribly sorry.
Maybe your name is high on the list
Hi guys, cheer up!
