### ISSUE TITLE
Gogs is sending blank web hook requests 

### ISSUE THREAD

**Issue by snowdon-dev** [gogs/gogs#6175]
**Describe the bug**
I've seen multiple others report this issue, however I can't find a solution in my case. The logs aren't helpful to myself and you'll see the only thing recorded in log file are not from this occurrence 

**Gogs version and commit**
I can't find a checksum but
```
© 2020 Gogs Version: 0.11.91.0811 Page
```

**Git version**

```
pi@pi0:~$ docker exec -it gogs bash
bash-5.0# git --version
git version 2.22.0


```

**Operating system**
bash-5.0# cat /proc/version
Linux version 4.19.97-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1294 SMP Thu Jan 30 13:15:58 GMT 2020
**Database**
SQLlite

**To Reproduce**
0. Standard setup I've the test delivery confirms its correct
1. Push to remote repository
2. Webhook is triggered, but a blank request is sent

**Can you reproduce the bug at https://try.gogs.io?**
It won't let me login, after register I get incorrect password. I'm using the keychain so

**Expected behavior**
I expect the same request as when using test deliveries

**Actual behavior**
I get a blank request with N\A visible

**Screenshots**
![Screenshot 2020-05-25 at 12 46 35](https://user-images.githubusercontent.com/56249415/82810588-c0763500-9e86-11ea-95ae-c178bf21e2ed.png)

The display error is not relevant because its not from this particular test.  It may be relevant
![image](https://user-images.githubusercontent.com/56249415/82810675-f3202d80-9e86-11ea-9a5c-447f5cbd853a.png)

I'm sorry I'm a little stumped

**Additional context**
```
bash-5.0# cat /data/gogs/log/gogs.log 
2020/05/24 00:24:03 [ INFO] Gogs 0.11.91.0811
2020/05/24 00:24:03 [ INFO] Cache Service Enabled
2020/05/24 00:24:03 [ INFO] Session Service Enabled
2020/05/24 00:24:03 [ INFO] Git Version: 2.22.0
2020/05/24 00:24:03 [ INFO] Git config user.name set to Gogs
2020/05/24 00:24:03 [ INFO] Git config user.email set to gogs@fake.local
2020/05/24 00:24:03 [ INFO] SQLite3 Supported
2020/05/24 00:24:03 [ INFO] Run Mode: Production
2020/05/24 00:24:03 [ INFO] First-time run install finished!
2020/05/24 00:24:03 [ INFO] New random avatar created: 1
2020/05/24 02:57:35 [ INFO] New random avatar created: 2
```

I'm requesting another container that is not linked through docker networks I'm just using the hosts IP address. But as seen bellow that is not causing any issues.

```
bash-5.0# ping 192.168.8.151
PING 192.168.8.151 (192.168.8.151): 56 data bytes
64 bytes from 192.168.8.151: seq=0 ttl=64 time=0.395 ms
64 bytes from 192.168.8.151: seq=1 ttl=64 time=0.359 ms
```

**Comment by unknwon** [comment]
Hi!

According to the error in your screenshot, it seems Gogs itself can't send requests to http://0.0.0.10080. Can you fix that?


> I'm requesting another container that is not linked through docker networks I'm just using the hosts IP address.

What does it mean "requesting another container"?

**Comment by snowdon-dev** [comment]
Sorry that was not the best explanation. There is no links between the containers. So the it just makes a request to the service via its hosts IP address.

That error is from previous test I think. I'm giving Gogs a proper IP address.

**Comment by unknwon** [comment]
Sorry I'm 100% lost what is going on here.

1. Could you describe how you deploy your Gogs instance. Is it `docker run ...`? 
2. What URL you use to access your Gogs instance?
3. The log output you provided seems incomplete, you should have a line contains "Listen on ...", can you provider a more complete one?
