### ISSUE TITLE
Raspbian Build Broke after commit 648d9e253c192 Sat Feb 22

### ISSUE THREAD

**Issue by kfreidank** [gogs/gogs#6184]
**Describe the bug**

Source build breaks with the error.
"can't load package: package gogs.io/gogs: build constraints exclude all Go files in /home/git/gogs"

**Gogs version and commit**

commit
648d9e253c1924b832248f26fee42b2fb64dc3bc

**Git version**

```
git version 2.20.1

```

**Operating system**

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Database**

psql (PostgreSQL) 11.7 (Raspbian 11.7-0+deb10u1)

**To Reproduce**
1. $ cd /home/git/gogs
2. $ git checkout -f 648d9e253c192
3. $ go build -o gogs

**Can you reproduce the bug at https://try.gogs.io?**

no, this is a build error, not a run time error
**Expected behavior**

A prompt with no errors and a successful build.
**Actual behavior**

The last 2 lines of the build process result in:
go: finding golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
**Screenshots**

**Additional context**

Build documentation should show the need to execute "$ export GOPROXY=https://goproxy.io" prior to the build.

**Comment by kfreidank** [comment]
The "Actual Behavior" line is missing the error line:  can't load package: package gogs.io/gogs: build constraints exclude all Go files in /home/git/gogs

**Comment by unknwon** [comment]
Hi, Gogs requires Go 1.14 (`master`) and Go 1.12 for https://github.com/gogs/gogs/commit/648d9e253c1924b832248f26fee42b2fb64dc3bc.
