### ISSUE TITLE
Edit Team, response 500, error "a pointer to a pointer is not allowed"

### ISSUE THREAD

**Issue by zhantss** [gogs/gogs#6185]
**Describe the bug**

gogs response 500 error when I edit team
log file show error "a pointer to a pointer is not allowed"

**Gogs version and commit**

Gogs version   0.12.0+dev
Git version   2.24.3
Go version   go1.14.2
Build commit   d28101ee66ff0be8e8944ea3cc519558ac10e760 

**Operating system**
Debian 9

**Database**
PostgreSQL

**To Reproduce**
1. Go to 'org/{org_name}/teams/{team_name}/edit'
2. Click on 'update'
3. See error

**Comment by frosteyes** [comment]
I have the same issue.

Application version 0.12.0+dev
Git version 2.24.3
Go version go1.14.4
Build time 2020-06-13 05:58:46 UTC
Build commit 2fe4d075995995fd0309ec8964aa06c9c90433f8 

Trying to change a team inside an organization returns the 500 - a pointer to a pointer is not allowed
