### ISSUE TITLE
Files and directories with same content shown with the same name in web interface

### ISSUE THREAD

**Issue by c0redump-gh** [gogs/gogs#6186]
Hello,
I installed current gogs master (158dd33) and I'm facing an issue: if I create two files or directories with identical content they are shown with the same name in the gogs web interface as you can see in the screenshot below.

![gogs](https://user-images.githubusercontent.com/24260696/83467639-d4b7c480-a47a-11ea-9034-5fd52b40a86c.JPG)

This behaviour seems similar to an old issue opened at the end of 2015 (issue #2254). I don't know if it's a regression or if there is something wrong in my setup.

Someone can help me.

Thanks in advance.

**Comment by unknwon** [comment]
Hi, can you push your demo repo to https://try.gogs.io/ so can I clone to my dev machine?

**Comment by c0redump-gh** [comment]
Hello unknwon,
I pushed my demo repo here: https://try.gogs.io/c0redump/issue6186

I can see the same issue I'm facing on my local gogs installation.

Thanks in advance.

**Comment by unknwon** [comment]
@c0redump-gh thanks! I'll take a look ASAP.

**Comment by tahirzia** [comment]
I am having same issue with all my repositories. Which ever repo i pushed multiple times have multiple files of same files. and Even directories are multiple.
