### ISSUE TITLE
MFA login support 

### ISSUE THREAD

**Issue by SurtursRevenge** [gogs/gogs#6190]
**Describe the feature**
It would be great to have native Multi Factor Authentication Support for Login with Username and Password via Web and HTTPS. General speaking having MFA Support wherever you dont log in with a key. For me MFA Support is a major thing and i think it is mandatory. 
I realy love gogs, but not having MFA makes me consider to move to another solution. 

**Describe the solution you'd like**
In the first place the integration of [OpenOTP](https://www.rcdevs.com/products/openotp-webplugins/) would be great. A lot of other good software already implemented this plugin. I think this is more of an enterprise feature, but would be realy awsome and would make gogs more 
attractive even for enterprise. 
As a second step i would like to see the support of TOTP like google authenticator or something like this. 

**Describe alternatives you've considered**
At the moment it seems like there is absolutly no mfa support in gogs.
So atm the only option is to implement mfa in a reverse proxy which causes other complication. 
A native support would be the best solution.

**Comment by unknwon** [comment]
Hi, Gogs has 2FA support, isn't that MFA?

**Comment by gerald-dotcom** [comment]
@unknwon  FUCK YOU!

**Comment by SurtursRevenge** [comment]
Its kind of.

"The difference between MFA and 2FA is simple. Two-factor authentication always utilizes two of these factors to verify the user’s identity. Multi-factor authentication could involve two of the factors or it could involve all three. “Multi-factor” just means any number of factors greater than one"

But thanks for the hint. While browsing the settings i found the google auth integration. Thats great, but i was not able do find this in the docs. 

Still it would be great to support 3rd party mfa solutions like openotp via plugin or it could be generalized to any mfa solution by integration radius support, so you can utilize a single mfa solution for all of your systems

**Comment by bibo38** [comment]
The main problem is that getting users to use 2FA is already hard. Requiring more than two factors isn't practical is most cases (few users, low security improvement compared to 2FA).

> While browsing the settings i found the google auth integration. Thats great, but i was not able do find this in the docs.

The Gogs documentation is not huge. I would say feel free to add documentation ([docs](https://github.com/gogs/gogs/tree/master/docs)-folder).

> Still it would be great to support 3rd party mfa solutions like openotp via plugin

Sure, but there needs to be someone to be interested in adding it. Either it is just a normal person coding in it's free time or a person, which is payed by somebody (e.g. a company) to implement the feature. And given that the unpayed person probably doesn't need enterprise features like OpenOTP, there is no benefit of investing time to implement it.

> or it could be generalized to any mfa solution by integration radius support, so you can utilize a single mfa solution for all of your systems

Feel free to describe (and implement) the architecture,  the possible configurations, ...


>  In the first place the integration of OpenOTP would be great. A lot of other good software already implemented this plugin. I think this is more of an enterprise feature, but would be realy awsome and would make gogs more
attractive even for enterprise.

Please give me an example of other Git-Services that implement OpenOTP. If you only reference the linked plugins, which the developer of the company producing OpenOTP have implemented, then I don't see any benefit of Gogs having an OpenOTP integration. The only one, who benefits from this is the company behind OpenOTP itself, as this might increase their OpenOTP sales.

**Comment by unknwon** [comment]
@SurtursRevenge @bibo38: Thank you both!

While integrating OpenOTP is a very tool technical thing to implement, I think current 2FA is good enough and you may follow https://github.com/gogs/gogs/issues/4384 about FIDO U2F support.
