### ISSUE TITLE
Remove OpenShift link from README as is for version of OpenShift that no longer exists.

### ISSUE THREAD

**Issue by GrahamDumpleton** [gogs/gogs#6192]
**Describe the bug**

``README`` contains a link for OpenShift under cloud providers to:

* https://github.com/tkisme/gogs-openshift

That repository describes use of OpenShift 2 (from before Kubernetes version). OpenShift 2 no longer exists as a service, so the link should be removed.

**Comment by unknwon** [comment]
Thanks! Fixed in https://github.com/gogs/gogs/pull/6194.
