### ISSUE TITLE
Run user isn't the current user

### ISSUE THREAD

**Issue by gerald-dotcom** [gogs/gogs#6193]
I was able to deploy Gogs in Heroku; however, it asks for username at install page, and I tried following usernames (Of course, I excluded the :: parts),

git
gogs
admin
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/bin/sh
bin:x:2:2:bin:/bin:/bin/sh
sys:x:3:3:sys:/dev:/bin/sh
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/bin/sh
man:x:6:12:man:/var/cache/man:/bin/sh
lp:x:7:7:lp:/var/spool/lpd:/bin/sh
mail:x:8:8:mail:/var/mail:/bin/sh
news:x:9:9:news:/var/spool/news:/bin/sh
uucp:x:10:10:uucp:/var/spool/uucp:/bin/sh
proxy:x:13:13:proxy:/bin:/bin/sh
www-data:x:33:33:www-data:/var/www:/bin/sh
backup:x:34:34:backup:/var/backups:/bin/sh
list:x:38:38:Mailing List Manager:/var/list:/bin/sh
irc:x:39:39:ircd:/var/run/ircd:/bin/sh
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/bin/sh
nobody:x:65534:65534:nobody:/nonexistent:/bin/sh
u49769:x:49769:49769:,,,:/app:/bin/bash
dyno:x:49769:49769:,,,:/app:/bin/bash

But the issue still there. and I went on ran whoami multiple times in Heroku Bash console and it looks like the username get randomized so then I  tried to use the ENV vars found on Gogs source but it didn't worked either. 

Is there are anyone who can help me?

I think addressing this issue would be beneficial because Heroku is a free service and anyone can run Googs which may help poor developers out there.

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by gerald-dotcom** [comment]
FUCK YOU!
