### ISSUE TITLE
Directory removal

### ISSUE THREAD

**Issue by lukamukaguka** [gogs/gogs#6197]
https://github.com/gogs/gogs/blob/9fd4f5562d7a59abbef5e78d44fb85a0041e0733/internal/db/repo.go#L1002

If dir exists it will be removed next step with RemoveAllWithNotice. And after will be all good. Hm...  Is it ok?

**Comment by unknwon** [comment]
Hi, it could contain previous Git repo and naively remove the directory could lose your data.
