### ISSUE TITLE
Backup: User configured to run Gogs is "git", but the current user is ""

### ISSUE THREAD

**Issue by kniec** [gogs/gogs#6219]
**Describe the bug**

**Gogs version and commit**

```
/app/gogs/gogs -v
Gogs version 0.12.0+dev
```

**Operating system**

```
/app/gogs $ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.6
```

**Database**

sqlite3

**To Reproduce**

When running `/app/gogs/gogs backup --verbose` I get the following error, even though the user I am running is `git`.

```
/app/gogs $ /app/gogs/gogs backup --verbose
2020/07/02 07:53:32 [FATAL] [gogs.io/gogs/gogs.go:40 main()] Failed to start application: init configuration: user configured to run Gogs is "git", but the current user is ""
/app/gogs $ whoami
git
/app/gogs $ id
uid=1000(git) gid=1000(git) groups=1000(git)
/app/gogs $
```

**Can you reproduce the bug at https://try.gogs.io?**

**Expected behavior**

The backup should be done

**Actual behavior**

Seems like `gogs` is not able to read the user to check against the configured user.

**Screenshots**

**Additional context**

**Comment by nasserpp22** [comment]
G

**Comment by bibo38** [comment]
Gogs currently uses environment variables to determine the current user:

https://github.com/gogs/gogs/blob/90904b3f420d41cf56c62b6d96234b199399f3e4/internal/osutil/osutil.go#L36-L44

As docker doesn't set those environment variables, it is manually added in the Gogs `start.sh` for Docker:

https://github.com/gogs/gogs/blob/90904b3f420d41cf56c62b6d96234b199399f3e4/docker/start.sh#L45

I agree that this is not really the correct thing to do and will create a PR to fix this problem.
