### ISSUE TITLE
Please Support Arm64 Release 请支持ARM64

### ISSUE THREAD

**Issue by syf2005** [gogs/gogs#6227]
RPI 4B with Raspberry OS 64 bit Beta or Ubuntu 20.04 LTS has already switch to aarch64 instruction set of ARMv8. There is no releases can be installed.
It is very difficult to compile and install something with Go language in China.
I have compiled one with RPI 4B. Hope it can help.

[Download URL](https://pan.syf.ink/#/s/qKH7)  Passwd: 5wkqh7

**Comment by bibo38** [comment]
Just as a quick hint: Go can be nicely cross-compiled, which allows for compiling on x86 hardware for the Raspberry PI: `GOOS=linux GOARCH=arm64 GOARM=7 go build` creates a nice aarch64 executable. Things like SQLite need a C cross compiler for arm.

This can be used for example to compile Gogs via GitHub Actions.
