### ISSUE TITLE
Unable to clone via SSH using `gogs/gogs-rpi`

### ISSUE THREAD

**Issue by Meeuwisse** [gogs/gogs#6277]
**Describe the bug**
First time trying out gogs docker image on raspberry; ssh refuses to work.

Followed the instructions;
`docker run -d --name gogs --publish 8022:22 --publish 3000:3000 --volume /media/seagate/gogs/:/data gogs/gogs-rpi`

Said to not enable SSH server (enabling it later, restarting docker container, or rewriting authorized_keys didn't help);
```
[server]
DOMAIN           = 192.168.1.6
HTTP_PORT        = 3000
EXTERNAL_URL     = http://192.168.1.6:3000/
DISABLE_SSH      = false
SSH_PORT         = 8022
START_SSH_SERVER = false
OFFLINE_MODE     = false
```

**Gogs version and commit**
Application version 0.12.0
Git version 2.24.3
Go version go1.14.7
Build time 2020-08-22 01:34:15 UTC
Build commit 39bdd5c2cdc85413e0d60bb0820f6042a997df0f 

**Operating system**
Linux raspberrypi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux

**Database**
sqlite3

**To Reproduce**
Install latest gogs-rpi docker image, create admin account.

Windows git create ssh key with passphrase, add to account. Create new repository.

Couldn't reproduce at try.gogs, never got email to activate account. And not raspberry image.

User settings SSH Keys shows key with correct SHA256.

On raspberry, or external laptop;
```
pi@raspberrypi:~ $ git clone ssh://git@192.168.1.6:8022/michael/asdf.git
Cloning into 'asdf'...
git@192.168.1.6: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````

Made sure passphrase is accepted with ssh-agent;
```` 
pi@raspberrypi:~ $ eval "$(ssh-agent)"
Agent pid 10852
pi@raspberrypi:~ $ ssh-add
Enter passphrase for /home/pi/.ssh/id_rsa:
Identity added: /home/pi/.ssh/id_rsa (/home/pi/.ssh/id_rsa)
````
So I'm sure my key is fine.

Issue #5798 suggested permissions and test log;
```
pi@raspberrypi:~/.ssh $ chmod 644 id_rsa.pub
pi@raspberrypi:~/.ssh $ chmod 600 id_rsa


pi@raspberrypi:~ $ chmod 0700 /media/seagate/gogs/git/.ssh
pi@raspberrypi:~ $ chmod 0600 /media/seagate/gogs/git/.ssh/*
pi@raspberrypi:~ $ ls -al /media/seagate/gogs/git/
total 20
drwxr-xr-x 4 pi systemd-timesync 4096 Aug 23 15:44 .
drwxr-xr-x 5 pi systemd-timesync 4096 Aug 23 14:54 ..
-rw-r--r-- 1 pi systemd-timesync   71 Aug 23 15:44 .gitconfig
drwxr-xr-x 3 pi systemd-timesync 4096 Aug 23 15:10 gogs-repositories
drwx------ 2 pi systemd-timesync 4096 Aug 23 15:40 .ssh
pi@raspberrypi:~ $ ls -al /media/seagate/gogs/git/.ssh/
total 16
drwx------ 2 pi systemd-timesync 4096 Aug 23 15:40 .
drwxr-xr-x 4 pi systemd-timesync 4096 Aug 23 15:44 ..
-rw------- 1 pi systemd-timesync  538 Aug 23 15:40 authorized_keys
-rw------- 1 pi systemd-timesync   23 Aug 23 14:54 environment
```

Test log shows it's attempting the key with the same SHA256 as listed under user/settings/ssh

The user/group seems completely wrong in the above, but if I restart the container like this;
`docker run -d --name gogs --publish 8022:22 --publish 3000:3000 --volume /media/seagate/gogs/:/data --user "$(id -u):$(id -g)" gogs/gogs-rpi
`
I get connection refused on both the web interface and ssh. Same if I try 1000:1000. Permissions look in order then, but there's no connection possible anymore.

I can't chown the files, as they're rewritten on every restart (and it doesn't help if I do it after). There's the instructions [here](http://www.ateijelo.com/blog/2016/07/09/share-port-22-between-docker-gogs-ssh-and-local-system) linked from the introductions, but those need uid/gid 1000:1000, and pi is already that, so that causes a conflict. Plus it sounds like a 'step 2 if you want it nicer', not 'this is absolutely required'.

Since I'm new to gogs I'm completely lost what step I might've missed at this point.

**Comment by unknwon** [comment]
I set up Gogs Docker on my Raspberry Pi and found the following log, which seems to be the root cause:

```
Aug 24 11:36:56 sshd[182]: User git not allowed because account is locked
```

**Comment by unknwon** [comment]
@Meeuwisse Thanks for a high quality bug report BTW! ❤️

**Comment by unknwon** [comment]
OK, found the root cause: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11808

Which effectively made "unlock" the user `git` failed:

```
+ usermod -p '*' git
Error relocating /usr/sbin/usermod: __lstat_time64: symbol not found
Error relocating /usr/sbin/usermod: __localtime64: symbol not found
Error relocating /usr/sbin/usermod: __fstat_time64: symbol not found
Error relocating /usr/sbin/usermod: __stat_time64: symbol not found
Error relocating /usr/sbin/usermod: __utime64: symbol not found
Error relocating /usr/sbin/usermod: __futimes_time64: symbol not found
Error relocating /usr/sbin/usermod: __gmtime64: symbol not found
Error relocating /usr/sbin/usermod: __time64: symbol not found
Error relocating /usr/sbin/usermod: __mktime64: symbol not found
Error relocating /usr/sbin/usermod: __lutimes_time64: symbol not found
Error relocating /usr/sbin/usermod: __utimes_time64: symbol not found
```

**Comment by unknwon** [comment]
All of following tags of `gogs/gogs-rpi` are updated: `latest`, `0.12` and `0.12.0`. You can re-pull the Docker image now!

**Comment by Meeuwisse** [comment]
Works! Thanks for the quick turnaround 👍
