### ISSUE TITLE
custom/conf/app.ini  and conf/app.ini  without incidence 

### ISSUE THREAD

**Issue by pascal-ace** [gogs/gogs#6279]
**Describe the bug**
when I change the settings in the configuration files, it doesn't change anything on the site (even with the clear cache) 

**Gogs version and commit**
Application version 0.13.0+dev
Git version 2.20.1
Go version go1.15

**Operating system**
Debian 10 64bit

**Database**
PostgreSQL

**To Reproduce**
1. Install Go
2. go get -u github.com/gogs/gogs
3. go build (inside the folder)
4. go to :3000/install in Chrome
5. Create 1st account 
6. change config file
7. exit gogs and ./gogs web & (started like this for test and configuration)
6. Nothing change 

**Expected behavior**
block account creation 

**Actual behavior**
account creation always possible

**Additional context**
conf/app.ini
`
; Whether to disallow anonymous users visiting the site.

REQUIRE_SIGNIN_VIEW = true

; Whether to disable self-registration. When disabled, accounts would have to be created by admins.

DISABLE_REGISTRATION = true

; Whether to enable captcha validation for registration

ENABLE_REGISTRATION_CAPTCHA = true
`

custom/conf/app.ini
`
REGISTER_EMAIL_CONFIRM = false

ENABLE_NOTIFY_MAIL     = false

DISABLE_REGISTRATION   = true

ENABLE_CAPTCHA         = false

REQUIRE_SIGNIN_VIEW    = true
`

More info :
gogs was started by user git with _./gogs web &_
I access gogs via a nginx reverse proxy. 

if you want more info, don't hesitate to contact me.

**Comment by ChengLuffy** [comment]
I have the same question.

Install gogs by docker, edit `/data/gogs/conf/app.ini`

![image](https://user-images.githubusercontent.com/15682381/91248105-71da7e80-e786-11ea-9188-f28139e4932e.png)

But users can still register

**Comment by ChengLuffy** [comment]
> I have the same question.
> 
> Install gogs by docker, edit `/data/gogs/conf/app.ini`
> 
> ![image](https://user-images.githubusercontent.com/15682381/91248105-71da7e80-e786-11ea-9188-f28139e4932e.png)
> 
> But users can still register

fixed by install tag:0.12.0

**Comment by pascal-ace** [comment]
I'll try in a few hours, I'll keep you informed.

**Comment by unknwon** [comment]
Hi, please refer to this comment: https://github.com/gogs/gogs/issues/6276#issuecomment-678787224

Some config options have been renamed since April. Pinning to 0.12.0 will continue to work as that is the last version of supporting those deprecated config options.

**Comment by pascal-ace** [comment]
I have installed version 0.12 since the releases ([https://github.com/gogs/gogs/releases](url))
It would have been preferable to change the installation doc to prevent this change. 


> @pascal-ace If you're running 0.13.0+dev, notice the config option name has moved to [auth] not [service]. See #6276 (comment).
Then it will work after a restart.

from #4765
