### ISSUE TITLE
无法获取tag列表

### ISSUE THREAD

**Issue by xishengcai** [gogs/gogs#6281]
**Describe the bug**

在你们的api里面没有发现tag， 我这里就认为获取标签列表是用labels

curl -H "Authorization: token xxxxxxx" https://try.gogs.io/api/v1/repos/cai-org/cc/labels
这个返回的是空数组

**Gogs version and commit**

**Git version**

线上环境 https://try.gogs.io/api/v1/

**Operating system**

**Database**

**To Reproduce**

**Can you reproduce the bug at https://try.gogs.io?**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

**Comment by unknwon** [comment]
Gogs currently does not have a API to list Git tags, seems duplicated to https://github.com/gogs/go-gogs-client/issues/109.

**Comment by forgethub** [comment]
我自己增加了一个接口来获取tag 列表， 修改 repo_branch.go 文件中  names, err := gitRepo.Branches()  为 names, err := gitRepo.Tags() 就可以获取Tag 的列表了


> Gogs currently does not have a API to list Git tags, seems duplicated to [gogs/go-gogs-client#109](https://github.com/gogs/go-gogs-client/issues/109).
