### ISSUE TITLE
Add a migration for deprecated configuration options

### ISSUE THREAD

**Issue by istandthon7** [gogs/gogs#6282]
**Describe the feature**

I was upgrade to 0.12 from 0.11.9
I cant show web page because of db login error.
I Found in release notes.
Configuration option [database] PASSWD is deprecated and will end support in 0.13.0, please start using [database] PASSWORD.
I think that it is possible replace configuration keys and sections.
If it is saved version info, not difficult.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by unknwon** [comment]
Thanks for the suggestion!

I'm going to add a migration in 0.13.0+dev for this. Sorry about any inconvenience caused!

**Comment by unknwon** [comment]
On a second thought, I think it is not possible because determine the migration version requires reading from database, which has to load the configuration first. 😞

**Comment by istandthon7** [comment]
No. Option(e.g. PASSWD or PASSWORD) is sign of version.
