### ISSUE TITLE
Docker: Backup Rotator

### ISSUE THREAD

**Issue by kinglike1337** [gogs/gogs#6287]
After pulling the latest docker image the backup rotator scripts creates an error:
find: unrecognized: -mtime +360

I think the quotes added by the the commit 92c5f94fe7fae17620ecb8895e287e9e66fb135c introduced this error:
https://github.com/gogs/gogs/blob/6e1c74a0f25032f43a40c71b78616d7960b3d832/docker/runtime/backup-rotator.sh#L24

The argument "FIND_EXPRESSION" is not correctly passed to the find commando.
Removing the quotes seems to fix this error.

**Comment by unknwon** [comment]
Thank you! Fix is coming.
