### ISSUE TITLE
Some listed files are not viewable from the UI giving "File Not Found" when clicked

### ISSUE THREAD

**Issue by DelightedD0D** [gogs/gogs#6290]
Tried the forums but getting "New registrations are not allowed from your IP address (maximum limit reached). Contact a staff member."

When looking at the repo in the UI, all files are shown. However, when I click on the files to view them, about 50% show the file while the other 50% show "File not found" in the browser.

Application version 0.12.0
Git version 2.17.1
Go version go1.15
Build time 2020-08-22 11:29:07 UTC
Build commit 39bdd5c2cdc85413e0d60bb0820f6042a997df0f 

**Operating system**
Ubuntu 18.04 (LTS) x64

**Database**
MySql 5.7.31-0ubuntu0.18.04.1 

**To Reproduce**
1. Go to repo
2. Click on file
3. 50% or so will result in "File not found"

**Expected behavior**
File should be shown in browser

**Actual behavior**
"File not found" is shown in browser

**Screenshots**

![image](https://user-images.githubusercontent.com/8271955/91582443-72554f80-e915-11ea-9062-6f9c8379c092.png)

![image](https://user-images.githubusercontent.com/8271955/91582469-7a14f400-e915-11ea-8c29-94f0b165cfb4.png)

**Additional context**
No errors found in log files

**Comment by unknwon** [comment]
Hi, can you push the repository in trouble or create a reproduce on https://try.gogs.io/?

**Comment by DelightedD0D** [comment]
@unknwon I cant upload the actual repo as its' a clients. I created another repo but indeed I'm unable to reproduce the issue there https://try.gogs.io/wesleysmith/larvel-app-test/src/master/config/app.php

**Comment by unknwon** [comment]
How is your reverse proxy set up? Because it ends with a `.php`, I suspect your hosting provider or reverse proxy thought it was a real PHP script instead of redirecting request to Gogs.

The second screenshot does not look like a 404 from Gogs.

**Comment by DelightedD0D** [comment]
@unknwon you nailed it, we had this in our nginix config for the subdomain, removing it fixed the issue. Thank you!


```
    location ~ \.php$ {
        include /etc/nginx/templates/fastcgi_php.tmpl;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
```
