### ISSUE TITLE
Recognize `main` as default branch if `master` is not available

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6296]
~~New repository should start using `main` as the default branch, fall back to `master` when `main` is not available when the default branch is not set.~~

When detecting the default branch, try `main` if `master` is not available.

**Comment by odiffey** [comment]
May I ask why you think this is neccesary?

**Comment by unknwon** [comment]
@odiffey Is it not required, it is nice to have.

**Comment by odiffey** [comment]
Could the default just remain as master as it has always been please?

**Comment by unknwon** [comment]
@odiffey Thanks for the opinion! I've updated the issue title and description. PTAL :)

**Comment by unknwon** [comment]
git version 2.29.0.windows.1 would create new repository with default branch `main`.

_https://discuss.gogs.io/t/gogs0-12-3/3367_

**Comment by fgm** [comment]
There is actually a current bug:

* create repo in gogs
* create local repo
* add remote to local repo
* git push origin main -u
* in Gogs, go to repo properties: the default branch in the selector is "master" although it does not exist, and cannot be validated. "main" is available and has to be selected.

**Comment by pokrakam** [comment]
It's been a good few months since this issue and major git hosts and many repos have switched to `main`, so could we default to that now? 
Also, the behaviour described by @fgm is still happening - perhaps this could be a separate issue? If a repo is pushed and no branch currently exists, `HEAD` should be changed to that repo. If I perform the same steps on GitHub, the default repo changes.

**Comment by microcai** [comment]
it's a bug of git. not gogs. @unknwon  you should submit bug reports to git

**Comment by OdinVex** [comment]
I'd prefer to be able to offer default new branch names to “main” and have that recognized correctly.

**Comment by unknwon** [comment]
> This is a bug as 'master' is hard coded into GOGS, (go_get.go line 27).
> Rather than picking up the system, gobal or user config GOGS uses this branch name.

@the-moog In this particular case, you can set default branch in the repository **Settings > Branches > Default Branch**. If you would like Gogs to consult from `.config` or `.gitconfig`, please make a separate feature request.
