### ISSUE TITLE
Yesterdays commit 23ff182 broke existing docker container setups

### ISSUE THREAD

**Issue by meyca** [gogs/gogs#6299]
**Describe the bug**
Yesterdays commit changed the password configuration for postgresql databases

https://github.com/gogs/gogs/commit/23ff182d1f8df2978785772bc58cf0ebfd2aeb0c#r41892581

After (automatically) upgrading to commit 23ff182 the software flooded the log with 

    2020/08/30 00:00:00 [ INFO] Gogs 0.13.0+dev
    2020/08/30 00:00:00 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: pq: password authentication failed for user "gogs"

**Gogs version and commit**

**Git version**
n/a, because the Gogs web frontend was not available

**Operating system**
default docker image with 
    FROM alpine:3.11

**Database**
default postgresql image 
    image: postgres:12-alpine

**To Reproduce**
Update an existing docker gogs environment and things break.

**Can you reproduce the bug at https://try.gogs.io?**
No, because that setup does not include a database?

**Expected behavior**
Update of the gogs software container should not break the existing config.

**Actual behavior**
The update of the gogs software container did break the existing config.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by meyca** [comment]
Probably a won't fix, but this might help others having the same issue. 

As commented on the source:

After changing [data-volume]/gogs/conf/app.ini from PASSWD = ... to PASSWORD = ... my environment is up again.

**Comment by unknwon** [comment]
Yeah... sorry for trouble, see https://github.com/gogs/gogs/issues/6276#issuecomment-678787224.

Recommend start using pinned minor version e.g. `gogs/gogs:0.12`.
