### ISSUE TITLE
panic: template: base/head:63: function "MD5" not defined

### ISSUE THREAD

**Issue by quincyyhuang** [gogs/gogs#6302]
**Describe the bug**

I was upgrading from 0.11 to the latest 0.12 and I followed the documentation on that. When I try to run `gogs web`, it panicked with the text in title.

**Gogs version and commit**

0.12.1

**Git version**
2.20.1

**Operating system**
Debian 10 x64

**Database**
mysql  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**To Reproduce**
This latest binary just does not run on my machine.

**Expected behavior**
Runs with no error.

**Actual behavior**
```
2020/09/03 14:52:50 [TRACE] Log mode: File (Info)
panic: template: base/head:63: function "MD5" not defined

goroutine 1 [running]:
html/template.Must(...)
        html/template/template.go:372
gopkg.in/macaron%2ev1.compile(0xc000461500, 0x14, 0xc00034e1e0, 0x1, 0x1, 0x0, 0x0, 0xc0001e7d40, 0x2, 0x2, ...)
        gopkg.in/macaron.v1@v1.3.9/render.go:291 +0x4c8
gopkg.in/macaron%2ev1.(*TemplateSet).Set(0xc00062e6c0, 0x15584e9, 0x7, 0xc0006c8000, 0x0)
        gopkg.in/macaron.v1@v1.3.9/render.go:317 +0x99
gopkg.in/macaron%2ev1.renderHandler(0xc000461500, 0x14, 0xc00034e1e0, 0x1, 0x1, 0x0, 0x0, 0xc0001e7d40, 0x2, 0x2, ...)
        gopkg.in/macaron.v1@v1.3.9/render.go:384 +0x127
gopkg.in/macaron%2ev1.Renderer(0xc000a712d0, 0x1, 0x1, 0x1b, 0x1f9fc80)
        gopkg.in/macaron.v1@v1.3.9/render.go:421 +0x133
gogs.io/gogs/internal/cmd.newMacaron(0x0)
        gogs.io/gogs/internal/cmd/web.go:120 +0x8b9
gogs.io/gogs/internal/cmd.runWeb(0xc0001066e0, 0x0, 0xc00006e4a0)
        gogs.io/gogs/internal/cmd/web.go:164 +0x105
github.com/urfave/cli.HandleAction(0x139ab80, 0x1e45260, 0xc0001066e0, 0xc0001066e0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:526 +0xfd
github.com/urfave/cli.Command.Run(0x1552afc, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x156bf6a, 0x10, 0x0, ...)
        github.com/urfave/cli@v1.22.4/command.go:174 +0x58e
github.com/urfave/cli.(*App).Run(0xc000239c00, 0xc00000e060, 0x2, 0x2, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:279 +0x7e8
main.main()
        gogs.io/gogs/gogs.go:39 +0x2e9
```

**Comment by quincyyhuang** [comment]
Ok i found what is wrong. I had some templates file in custom folder to customize the home page and those files seem to be causing problems.

Now is there a way to customize the icon, favicon and the home page?

**Comment by unknwon** [comment]
Ah, sorry about the service interruption! Should have added this to the CHANGELOG, it was removed in this commit: https://github.com/gogs/gogs/commit/6437d0180b97a26319b50c2e22927dac7c94fcdd#diff-675f585d9cd6a202ba88a50dc67e52ff



> Now is there a way to customize the icon, favicon and the home page?

Editing template files in customer folder is the correct way according to https://gogs.io/docs/features/custom_template.
