### ISSUE TITLE
500 login page

### ISSUE THREAD

**Issue by nerkdesign** [gogs/gogs#6317]
**Describe the bug**
When I go to the interface, when i click on Sign In, I have a 500 error page
**Gogs version and commit**
Gogs : version 19 docker 

**Git version**
git : 2.24.3

**Operating system**
docker 

**Database**
mariadb mysql version 10.3.23

**To Reproduce**

1. Go to gog interface
2. Click on Sign in
3. See error 500

I have this on logs : 
2020/09/09 09:24:38 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'id' in 'field list'

Can you help me to debug this ?

Thanks

**Comment by karl0ss** [comment]
Mine has been doing this for the last week..

If I reinstall using MySQL, I get the same issue, but seems to work fine with SQLlite DB..

**Comment by unknwon** [comment]
Hi, what is "Gogs : version 19 docker"? You can use `./gogs --version` to get the current version.

**Comment by nerkdesign** [comment]
Ok sorry, i took the version in the database.
For the command you send I have this :

bash-5.0# ./gogs -version
Gogs version 0.13.0+dev

I took it from hub.docker the image is gogs/gogs 

@karl0ss thanks ! I took the 12.1 image and it's working again, thanks for your advice

**Comment by nerkdesign** [comment]
I close this issue, this must be linked the de dev version.
