### ISSUE TITLE
Remove Port 3000 form External URL

### ISSUE THREAD

**Issue by arshsahzad** [gogs/gogs#6321]
**Bug Describe**
I updated Gogs app to version 0.12.1 through Cloudron update button, now when I'm fetching, pulling, pushing repository to my private git server (https://git.softretic.com), it is binding with port no 3000 with every repos (http://git.softretic.com:3000/arshsahzad/FamilyDB.git) but when I'm removing port :3000 from URL, everything is working fine 

Before Update

![Before](https://user-images.githubusercontent.com/40422856/92637117-110a8480-f2f6-11ea-9449-ec7cab185d90.JPG)

After Update 
![After](https://user-images.githubusercontent.com/40422856/92637341-562eb680-f2f6-11ea-9195-f700b18ece76.JPG)

**Gogs Version and Commit**
Application version
0.12.1
Git version
2.17.1
Go version
go1.15
Build time
2020-08-27 07:07:30 UTC
Build commit
43fc8260850090b55d4ee2586a819b3b6c016279 

**Operating System**
Ubuntu 18.04 - Using Cloudron As Management

**Database**
MySQL - Ver 8.42 Distrib 5.7.29, for Linux on x86_64

**Comment by unknwon** [comment]
Hi, Gogs just reads the value of this config option:

https://github.com/gogs/gogs/blob/594a2dc41f6e70f0cc535b125316d05e12666fda/conf/app.ini#L13-L15

And you can change it easily, check your `custom/conf/app.ini` file :)

**Comment by unknwon** [comment]
Also worth noting: https://github.com/gogs/gogs/blob/main/CHANGELOG.md#changed-1

**Comment by arshsahzad** [comment]
Thanks, removing this :%(HTTP_PORT)s/ from 
[server] 
EXTERNAL_URL = %(PROTOCOL)s://%(DOMAIN)s**:%(HTTP_PORT)s/**

Solved the problem of port attaching to it

**Comment by arshsahzad** [comment]
Thanks, removing this :%(HTTP_PORT)s/ from

`[server]
EXTERNAL_URL = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s/`

Solved the problem of port attaching to it
