### ISSUE TITLE
Unable to clone repo over SSH

### ISSUE THREAD

**Issue by arshsahzad** [gogs/gogs#6322]
**SSH Problem**
I set-up my Gogs app in Cloudron and have to choose any port (:1024) for SSH but when I'm cloning, pushing to my private Gogs server [SoftRetic](https://git.softretic.com/), I'm getting an error

**Error**
'git clone ssh://git@git.softretic.com:1024/arshsahzad/OnePage.git
Cloning into 'OnePage'...
ssh: connect to host git.softretic.com port 1024: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.'

**App Config**

[Gogs Config](https://git.softretic.com/arshsahzad/GitServer/src/666edc58970c0f9872c2a3afc8ac243eca6a7bfb/app.ini)

**Gogs SSH Config Screenshot**
![SSH](https://user-images.githubusercontent.com/40422856/92688270-b3f4ea00-f35a-11ea-9489-4a4707128cd7.JPG)

**Build Information**
'Application version
0.12.1
Git version
2.17.1
Go version
go1.15
Build time
2020-08-27 07:07:30 UTC
Build commit
43fc8260850090b55d4ee2586a819b3b6c016279'

**Comment by unknwon** [comment]
Hi, from your screenshot, it does not look like you're starting builtin SSH server, which effectively makes port 1024 useless (i.e. no one is listening to it).

I'm not familiar with Cloudron environment, but generally, if you have SSH server already set up, you should just set to use port 22 for SSH.

**Comment by arshsahzad** [comment]
& how did, I can start a builtin SSH server in my ubuntu server?

**Comment by unknwon** [comment]
Set this option to true:

https://github.com/gogs/gogs/blob/7bc3ee49aa317e48331cf6e39e1911ac89b2e325/conf/app.ini#L76-L77

**Comment by arshsahzad** [comment]
I tried  `START_SSH_SERVER = true` but the docker image is not restarting, so I have contacted the Cloudron, regarding this issue.

[Cloudron Git default app.ini](https://git.cloudron.io/cloudron/gogs-app/-/blob/master/app.ini.template#L22)

**Comment by arshsahzad** [comment]
SSH problem has been solved by Cloudron, now login shell and push/pull are working fine over SSH. 

1. This was due to, there was no`1024` port was assign in the Inbound rule of my AWS EC2 instance, My listen port is `1024`, you have to assign your own listen port in your cloud firewall in the server
2. If DNS provider is Cloudflare, you have to disable all proxy on Cloudflare for same server IP address, If not, It won't ssh and git

[SSH Solution on Cloudron Forum](https://forum.cloudron.io/topic/3260/unable-to-pull-push-repo-over-ssh?_=1601416749984)

**Comment by arshsahzad** [comment]
SSH problem has been solved by Cloudron, now login shell and push/pull are working fine over SSH. 

1. This was due to, there was no`1024` port was assign in the Inbound rule of my AWS EC2 instance, My listen port is `1024`, you have to assign your own listen port in your cloud firewall in the server
2. If your DNS provider is Cloudflare, you have to disable proxy on Cloudflare for same server IP address where Gogs address is assigned, If not, It won't ssh and git

[SSH Solution on Cloudron Forum](https://forum.cloudron.io/topic/3260/unable-to-pull-push-repo-over-ssh?_=1601416749984)

**Comment by oliver-lou** [comment]
我也有类似的问题，我在本地搭建了一个gogs服务，其他的地方都正常。当我这样clone仓库的时候，会报如下图的错误
![image](https://user-images.githubusercontent.com/73122994/106378768-35b8e300-63e2-11eb-8c50-2a6d1870bbb1.png)
用http协议clone和push的时候是没有问题的，但是我发现如果我用完整的绝对路径`git clone git@192.168.3.11:/home/git/gogs-repositories/oliver_lou/test.git`是可以clone下来的，并且还可以正常push，但是路径改为`home/git/gogs-repositories/oliver_lou/test.git`(就是把/去掉)又会报错
![image](https://user-images.githubusercontent.com/73122994/106378953-82e98480-63e3-11eb-94a9-ad51ac5fb385.png)
我觉得是`oliver_lou/test.git`这个路径别名没有生效，有没有同学遇到类似的问题，该如何解决？麻烦教我一下，不胜感激！

**Comment by arshsahzad** [comment]
> 我也有类似的问题，我在本地搭建了一个gogs服务，其他的地方都正常。当我这样clone仓库的时候，会报如下图的错误
> ![image](https://user-images.githubusercontent.com/73122994/106378768-35b8e300-63e2-11eb-8c50-2a6d1870bbb1.png)
> 用http协议clone和push的时候是没有问题的，但是我发现如果我用完整的绝对路径`git clone git@192.168.3.11:/home/git/gogs-repositories/oliver_lou/test.git`是可以clone下来的，并且还可以正常push，但是路径改为`home/git/gogs-repositories/oliver_lou/test.git`(就是把/去掉)又会报错
> ![image](https://user-images.githubusercontent.com/73122994/106378953-82e98480-63e3-11eb-94a9-ad51ac5fb385.png)
> 我觉得是`oliver_lou/test.git`这个路径别名没有生效，有没有同学遇到类似的问题，该如何解决？麻烦教我一下，不胜感激！

Can you translate this into English, so after that, if possible I can help?

**Comment by arshsahzad** [comment]
[<img width="575" alt="SSH Port" src="https://user-images.githubusercontent.com/40422856/106388734-e5ec1300-6405-11eb-9784-cb2a13d2c7c8.png">](url)

> Check your SSH Configuration in Admin Panel, if you have exposed any port `My Exposed Port is :1024` into your local server like `192.168.3.11:1024`
> If yes, then check whether the port `1024` is listing or not

<img width="302" alt="Screenshot 2021-01-31 210030" src="https://user-images.githubusercontent.com/40422856/106389059-66f7da00-6407-11eb-85a0-85430caf244b.png">

> Install telnet and run this command in your local linux server

1. sudo apt install telnet
2. telnet 192.168.3.11 22
3. telnet 192.168.3.11 exposed port

**Comment by LSL1618** [comment]
@oliver-lou ，我感觉gogs自动生成的ssh地址有问题，正常来讲应该是这样的格式：`ssh://git@ip:port/username/repository_name.git`，而gogs自动生成的却是这样的格式：`ssh://git@ip:username/repository_name.git`，前缀`ssh://`可以忽略，差异在于port的有无和username的位置。

**Comment by unknwon** [comment]
@LSL1618 You can ignore the port in the URL if it's 22.
