### ISSUE TITLE
Failure to start after attempting to connect to sqlite3 with tcp

### ISSUE THREAD

**Issue by quimnut** [gogs/gogs#6331]
Using the gogs/gogs docker I am unable to start the application using sqlite3

Gogs 0.13.0+dev

/app/gogs # tail -n2 $GOGS_CUSTOM/log/gogs.log
2020/09/12 08:39:00 [ INFO] Gogs 0.13.0+dev
2020/09/12 08:39:00 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: failed to connect to `host=127.0.0.1 user=gogs database=gogs`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)

/app/gogs # grep -i -A 8 database $GOGS_CUSTOM/conf/app.ini
[database]
DB_TYPE  = sqlite3
; HOST     = 127.0.0.1:3306
; NAME     = gogs
; USER     = root
; PASSWD   = 
; SSL_MODE = disable
PATH     = /data/gogs/data/gogs.db

/app/gogs # ls -la /data/gogs/data/gogs.db
-rw-r--r--    1 git      git         413696 Apr  9 23:40 /data/gogs/data/gogs.db

# docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
gogs/gogs                    latest              9899ce5bdf47        2 days ago          95.9MB

**Comment by lucascalion** [comment]
+1
I updated to version 0.12 and I am also having the exact same problem!

**Comment by kotnik** [comment]
The same here.

Upgraded from `0.12.0+dev` (build time `2020-06-29 04:29:19 UTC`) and gogs can't start anymore. Using exact config as above.

Switching to `gogs/gogs:0.12.1` Docker image brought the service back.

**Comment by unknwon** [comment]
Hi, some config options are changed/removed since 0.13, you can pin to 0.12.

https://github.com/gogs/gogs/blob/main/CHANGELOG.md#removed
