### ISSUE TITLE
Error 1054: Unknown column 'id' in 'field list'

### ISSUE THREAD

**Issue by teknofile** [gogs/gogs#6334]
After a recent upgrade of the gogs docker container, I can no longer log into the web ui. I upgrade the command essentially by doing a docker rm <container name> and then pull a new one down and point it to a volume on disk that is persistent. 

When starting up the container and logging into the container, this is ijn the <volume dir>/gogs/log/gogs.log file:

```2020/09/16 03:42:01 [ INFO] Gogs 0.13.0+dev
2020/09/16 03:42:01 [ INFO] Run mode: Production
2020/09/16 03:42:01 [ INFO] Listen on http://0.0.0.0:3000
2020/09/16 03:42:10 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'id' in 'field list'
2020/09/16 03:42:11 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'id' in 'field list'
2020/09/16 03:42:12 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'id' in 'field list'
2020/09/16 03:44:45 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'id' in 'field list'
2020/09/16 12:25:39 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'id' in 'field list'
```

The database is an external MariaDB. 

In gorm.log I see the following:
```2020/09/16 03:36:04 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.00549] [rows:0] 
2020/09/16 03:36:06 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.005437] [rows:0] 
2020/09/16 03:36:06 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.005081] [rows:0] 
2020/09/16 03:36:07 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.005407] [rows:0] 
2020/09/16 03:39:08 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.643134] [rows:0] SELECT `id`,`type`,`name`,`is_actived`,`is_default`,`cfg`,`created_unix`,`updated_unix` FROM `row` WHERE is_actived = true ORDER BY id ASC
2020/09/16 03:39:11 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.005492] [rows:0] 
2020/09/16 03:42:10 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.534197] [rows:0] SELECT `id`,`type`,`name`,`is_actived`,`is_default`,`cfg`,`created_unix`,`updated_unix` FROM `row` WHERE is_actived = true ORDER BY id ASC
2020/09/16 03:42:11 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.005771] [rows:0] 
2020/09/16 03:42:12 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.005493] [rows:0] 
2020/09/16 03:44:45 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.005601] [rows:0] 
2020/09/16 12:25:39 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.006256] [rows:0] 
2020/09/16 18:14:24 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'id' in 'field list'
[0.008645] [rows:0] 
```

I'm not sure what the commit number is, as I can't access /admin. But per the logfile it's gogs version 0.13.0+dev.

Git version: 2.25.1

The OS is the alpine based docker container being publieshed and pushed to: `gogs/gogs`

Database is Mariadb: `Server version: 10.4.14-MariaDB-1:10.4.14+maria~bionic-log mariadb.org binary distribution`

**Can you reproduce the bug at https://try.gogs.io?**
No, this happened after a container upgrade. 

**Expected behavior**
To be able to log in without a DB issue after the new container was pulled.

**Actual behavior**
A 500 server error is given when trying to login.

**Screenshots**
N/A

**Additional context**
Logs pasted above.

**Comment by shenpeiheng** [comment]
docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs

login


2020/09/17 08:22:01 [ INFO] Gogs 0.13.0+dev
2020/09/17 08:22:01 [ INFO] Git config user.email set to gogs@fake.local
2020/09/17 08:22:01 [ INFO] Git config user.name set to Gogs
2020/09/17 08:22:01 [ INFO] Run mode: Production
2020/09/17 08:22:01 [ INFO] First-time run install finished!
2020/09/17 08:22:16 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'type' in 'field list'
2020/09/17 08:22:19 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'type' in 'field list'


[0.373571] [rows:0] SELECT `id`,`type`,`name`,`is_actived`,`is_default`,`cfg`,`created_unix`,`updated_unix` FROM `row` WHERE is_actived = true ORDER BY id ASC
2020/09/17 08:22:19 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'type' in 'field list'

**Comment by jiangchao1987** [comment]
Me too.

gorm.log
2020/09/18 03:00:28 gogs.io/gogs/internal/db/login_sources.go:276 Error 1054: Unknown column 'type' in 'field list'
[0.00665] [rows:0]

gogs.log
2020/09/18 03:00:28 [ERROR] [...gogs/internal/route/user/auth.go:106 Login()] list activated login sources: Error 1054: Unknown column 'type' in 'field list'

**Comment by unknwon** [comment]
Thanks @teknofile @shenpeiheng @jiangchao1987!

It turns out to be a MySQL-specific problem, fix coming in https://github.com/gogs/gogs/pull/6338.
