### ISSUE TITLE
Add stable tag on Docker Hub

### ISSUE THREAD

**Issue by Vogete** [gogs/gogs#6335]
**Describe the feature**
It would be nice to have a `stable` tag for the [Gogs](https://hub.docker.com/r/gogs/gogs/tags) image on Docker Hub that points to the latest stable release. This would ensure that we don't have to continuously specify the version in order to get the latest stable version.

**Describe the solution you'd like**
Please create a `stable` tag on Docker Hub that points to the latest stable tag. At the time of writing 0.12.1 is the latest stable release, but the `latest` tag will build the 0.13 dev version.
I would like to set the docker-compose file to something like this:

```yaml  
[...]
services:
    gogs:
        image: gogs/gogs:stable
[...]
```

**Additional context**
I am using docker-compose to run Gogs to run for our company, and whenever I run the `latest` tag from Docker, it downloads the next release's development version. In order to run a stable release, I have to specify the version in the docker-compose file (eg.: `image: gogs/gogs:0.12`) which gets boring after a while. At first I used the `latest` tag, but since it's a development release, it always behaved unexpectedly and presented bugs that were not in the stable release. It would save a bit of time, and lot of annoyance to just have a `stable` channel that automatically points to the latest stable release, and I don't have to manually edit the compose file every time.

**Comment by unknwon** [comment]
Thanks for the idea!

However, I doubt its usefulness in practice. 

For example, once 0.13 is release, `stable` then will be point to `0.13` and not `0.12`, which again, could contain breaking changes.
