### ISSUE TITLE
can you release a version for arm64? please

### ISSUE THREAD

**Issue by codeoflin** [gogs/gogs#6343]
I tried to compile it by self,but golang for me it's too difficult to use. I can't compile it success, can you help me? please

**Comment by unknwon** [comment]
Will do on next release :)

Is it arm64/armv8 what you're looking for?

**Comment by unknwon** [comment]
BTW, I think you can run armv7 binaries on armv8, that's why we don't compile binaries for armv8 right now.

**Comment by codeoflin** [comment]
> 
> 
> BTW, I think you can run armv7 binaries on armv8, that's why we don't compile binaries for armv8 right now.

I have tried it, not work

**Comment by unknwon** [comment]
Can you post the steps you download and execute the binary along with the exact error message?

**Comment by codeoflin** [comment]
![image](https://user-images.githubusercontent.com/45932283/94395993-8221b700-0193-11eb-9850-37fcc03b83df.png)
that's what I see when I try to run armv7 gogs in my aarch64 system

**Comment by unknwon** [comment]
@codeoflin Thanks! I'll test to double check when cutting the next release. If armv7 is not working on v8, then I'll compile binaries for v8 separately.

**Comment by unknwon** [comment]
Binaries for armv8 is provided since https://github.com/gogs/gogs/releases/tag/v0.12.3

**Comment by codeoflin** [comment]
Thank you!
