### ISSUE TITLE
mssql database file could not be found

### ISSUE THREAD

**Issue by wjl1627** [gogs/gogs#6345]
**Describe the bug**

The server crashed and the gogs mssql database file could not be found. How to restore the warehouse in the new windows environment?
[database]
DB_TYPE  = mssql
HOST     = 127.0.0.1, 1433
NAME     = gogs_demo
USER     = xxx
PASSWD   = xxx
SSL_MODE = disable
PATH     = data/gogs.db    --this path does not exist

**Gogs version and commit**
gogs_0.11.91_windows_amd64

**Git version**

```
$ git version
git version 2.17.1.windows.2
```

**Operating system**

windows 10 2004

**Database**

MSSQL 2016

**Additional context**

no error logs

**Directory Structure**
gogs
  --custom
  --data
     --avatars
     --sessions
  --gogs-repositories
  --....

**Comment by unknwon** [comment]
Hi, I do not understand what does it mean that "mssql database file could not be found"? Can you elaborate more (I've never used MSSQL so have no idea what's going on)?

**Comment by wjl1627** [comment]
app.ini:

> [database]
DB_TYPE  = mssql
HOST     = 127.0.0.1, 1433
NAME     = gogs
USER     = xxxx
PASSWD   = xxx
SSL_MODE = disable
PATH     = data/gogs.db
------------------------------

After gogs ran, the database tables were built into the master in mssql instead of creating a gogs.db file by yourself. It was really unexpected. Why?
![image](https://user-images.githubusercontent.com/19898550/100200259-4e67d100-2f39-11eb-8d0a-3b5a94f17549.png)

**Comment by unknwon** [comment]
@wjl1627 `gogs.db` is only for SQLite3, what you saw is 100% expected.

**Comment by wjl1627** [comment]
Well, thank you for your reply.
