### ISSUE TITLE
can't use token git clone 

### ISSUE THREAD

**Issue by xishengcai** [gogs/gogs#6346]
option:
 git clone https://xishengcai:e6f05c90be5ca4052b5e8d144f8bc4cdebxxxx@try.gogs.io/xishengcai/cloud.git

result:
Cloning into 'cloud'...
fatal: Authentication failed for 'https://try.gogs.io/xishengcai/cloud.git/'

**Comment by unknwon** [comment]
Try `git clone e6f05c90be5ca4052b5e8d144f8bc4cdebxxxx@try.gogs.io/xishengcai/cloud.git`
