### ISSUE TITLE
Pages are randomly hanging for 60 seconds behind NGINX

### ISSUE THREAD

**Issue by ziSo12** [gogs/gogs#6347]
**Describe the bug**
As the title says, since I updated my Gogs, I'm experiencing very long response times, when trying to navigate Gogs web interface.
The same is occuring when trying to push via https. It works but only after an initial response time of about 20-40 seconds. **[Edit: actually 60 seconds]** 

This all is happening since I moved my gogs repositories to a docker container, which also updated my Gogs version from 0.11.xx to 0.13.dev. I'm serving Gogs through Nginx proxy, which was also the case before the update.

I have searched for similar issues, but the answers provided didn't solve the problem. 
I have set "disableGravatar" to true but without effect.
Therefor I think my problem is caused by something else.

Additional Information:
Gogs running in http mode and is behind Nginx proxy, which redirects to https://git.example.com

**Gogs version and commit**

Application version
    0.13.0+dev
Git version
    2.24.3
Go version
    go1.14.7
Build time
    2020-09-21 12:30:19 UTC
Build commit
    6ed98ca8f674d0e40d0c356df9a26fb3e2ff2cec 

**Operating system**
Ubuntu 18.04 LTS in docker environment.

**Database**
    sqlite3

**To Reproduce**
1. open browser
2. navigate to https://git.example.com
3. wait up to 40 seconds
4. page is loaded
5. consecutive requests are often much faster but not guaranteed

**Can you reproduce the bug at https://try.gogs.io?**
No

**Expected behavior**
Gogs should load pages quick as I was used to before the update.

**Actual behavior**
20-50 seconds **[Edit: actually 60 seconds]** 
 delay when trying to load or simply refresh a page via nginx ssl proxy, and when trying to push via https.
Sometimes it is really quick after an initial delay.

**Additional context**
no errors present in gogs.log

**Comment by unknwon** [comment]
FYI, 0.13 removed/renamed some config options as listed here: https://github.com/gogs/gogs/blob/main/CHANGELOG.md#removed

That could be a cause, you can pin to `gogs/gogs:0.12` as a way of not changing the config right now.

Besides, try to turn on the offline mode:

https://github.com/gogs/gogs/blob/211a1394b86dafc90d73d5d622ca85686c2fb5f6/conf/app.ini#L43-L44

If that still doesn't help, please attach a screenshot of **Chrome DevTools > Network** see which requests are being slow.

<img width="302" alt="Screen Shot 2020-09-26 at 10 10 33 PM" src="https://user-images.githubusercontent.com/2946214/94342664-1a5d5600-0045-11eb-9289-13cd0111f622.png">

**Comment by ziSo12** [comment]
I have already migrated to the latest config options. Don't think this is the issue.
I have tried setting both, OFFLINE_MODE = false and OFFLINE_MODE = true, without noticing a difference in response time. Please see attached screenshots.
To correct my previous post, the response time seems to be always 1 min. Looks like it has a 60s timeout set somewhere before showing the page.
I tried several times. Most of the time, DevTools is showing the delay at the page/document I'm trying to load (screens 1-4). However, I've also seen the 1min delay on github.css (screen 5). I've also seen the same delay on octicons.min.css and gogs.min.css one time (no screen available).

After the first long delay. When I continue browsing, it often loads much faster (screens 6-7).

For reference, I have also attached my app.ini.

[app.ini.txt](https://github.com/gogs/gogs/files/5299551/app.ini.txt)

![ksnip_20200929-155923](https://user-images.githubusercontent.com/10611138/94569523-195b3d00-026e-11eb-98d2-aa0791928539.png)
![ksnip_20200929-155929](https://user-images.githubusercontent.com/10611138/94569527-1b250080-026e-11eb-88c0-4edfe48137cc.png)
![ksnip_20200929-155930](https://user-images.githubusercontent.com/10611138/94569534-1c562d80-026e-11eb-95f3-9d28fd713e97.png)
![ksnip_20200929-155931](https://user-images.githubusercontent.com/10611138/94569538-1e1ff100-026e-11eb-861a-19b1616e1968.png)
![ksnip_20200929-155935](https://user-images.githubusercontent.com/10611138/94569543-1f511e00-026e-11eb-8a80-f8f6266a8035.png)
![ksnip_20200929-160228](https://user-images.githubusercontent.com/10611138/94569547-20824b00-026e-11eb-941e-80c54a8255d9.png)
![ksnip_20200929-160720](https://user-images.githubusercontent.com/10611138/94569554-21b37800-026e-11eb-9376-ab2415db416c.png)

**Comment by unknwon** [comment]
@ziSo12 Thanks for the config file and screenshots!

> To correct my previous post, the response time seems to be always 1 min. Looks like it has a 60s timeout set somewhere before showing the page.

I suspect the same. Would you mind also post the config of your reverse proxy?

The time to load HTML page seems reasonable, but all timeout occurs with static resources. I'm suspecting reverse proxy is trying to load them from somewhere else then timed out.

**Comment by ziSo12** [comment]
Here's my reverse proxy config. I have used the same before the update and it has worked fine:
```
server {
    listen       443 ssl;
    server_name  git.example.com;
    access_log   /var/log/nginx/git.example.access.log;
    error_log   /var/log/nginx/git.example.error.log;

    location /.well-known/ {
        root /var/www/letsencrypt/git.example.com/;
    }

   location / {
       proxy_set_header X-Real-IP $remote_addr; 
       proxy_pass http://localhost:10080;
   } 
}


server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name git.example.com;
    return 302 https://$server_name$request_uri;
}

```
The weird thing is, both my /var/log/nginx/git.example.access.log and /var/log/nginx/git.example.error.log are always empty.

**Comment by unknwon** [comment]
Thanks! Have you tried to visit your site in incognito mode (no browser extension enabled)?

**Comment by ziSo12** [comment]
The above screenshots were made off of a clean Chrome install, without any browser extensions installed. Just tried in incognito mode, but without any difference. Same on Firefox. Also tested from multiple devices. I think the issue is server side.

**Comment by mckaygerhard** [comment]
nginx stupid problem.. i cannot reproduce in lighttpd.. but i have not tryed yet 0.13.0+dev only 2 lasted stable

**Comment by Qarshi** [comment]
try following. i have been using nginx with no issue. change "domain" with yours own.

server {
    listen 80;
    server_name git.domain.com;
    include snippets/letsencrypt.conf;
#comment below line for certbot
    return 301 https://$host$request_uri;
#     location / {
#        rewrite     ^ https://git.domain.com$request_uri? permanent;
#       proxy_pass http://127.0.0.1:3000;
#   }
}


server {
    listen 443 ssl http2;
    server_name git.domain.com;

#    proxy_ssl_server_name on;
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;
    client_max_body_size 50m;

    # Proxy headers
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    ssl_certificate /etc/letsencrypt/live/git.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/git.domain.com/privkey.pem; # managed by Certbot
    ssl_trusted_certificate /etc/letsencrypt/live/git.domain.com/chain.pem;
    include snippets/ssl.conf;
    include snippets/letsencrypt.conf;
  # . . . other code
    # log files
#    access_log /var/log/nginx/git.domain.com.access.log;
#    error_log /var/log/nginx/git.domain.com.error.log;

    # Handle / requests
    location / {
       proxy_redirect off;
       proxy_pass http://localhost:3000;
    }
}

**Comment by ziSo12** [comment]
@Qarshi thanks for posting your nginx config! sorry for the delay.. I just tested it. It works like a charm now! @unknwon it seems the issue was my nginx config. so not on gogs side. issue can be closed

**Comment by unknwon** [comment]
😅 While the problem solved (thanks to @Qarshi!) I still don't understand why NGINX behave like this...
