### ISSUE TITLE
Generate New Token button doesn't take any actions

### ISSUE THREAD

**Issue by aeltawela** [gogs/gogs#6356]
**Describe the bug**

Generate new token button doesn't take any actions, I tried to check the network requests and doesn't even send any HTTP request.

**Gogs version and commit**

```
Application version
0.12.1
Git version
2.26.2
Go version
go1.15.2
```

**Git version**

```
2.26.2

```

**Operating system**
Alpine in docker container

**Database**
sqlite

**To Reproduce**
1) Install a fresh gogs
2) Create admin user
3) Enable 2 factor of authentication
3) Try to generate an application token

**Screenshots**

![gogs](https://user-images.githubusercontent.com/18292990/94343397-326ab080-0018-11eb-8983-8f0e71bc2b45.gif)

**Additional context**

No errors in gogs.log, in fact the page doesn't send any HTTP request

**Comment by unknwon** [comment]
Please fill in details :)

**Comment by aeltawela** [comment]
@unknwon it is being filled, I just accidentally pressed enter and you were too fast

**Comment by unknwon** [comment]
Haha, let me see if I can reproduce on 0.12.2 (I can't reproduce on try.gogs.io).

**Comment by unknwon** [comment]
<img width="760" alt="Screen Shot 2020-09-26 at 10 41 51 PM" src="https://user-images.githubusercontent.com/2946214/94343254-79bd6500-0049-11eb-9b5e-f75ec7efa9b9.png">

I've enabled 2FA, then able to create a new token.

**Comment by aeltawela** [comment]
@unknwon I added a screenshot, it might be related to my configurations. I can share the app.ini if it helps.

**Comment by unknwon** [comment]
@aeltawela Thanks! 

- What browser you're using? Can you use the same browser and reproduce this behavior on https://try.gogs.io?
- Can you check the **Console** tab see if there is any error?

**Comment by aeltawela** [comment]
@unknwon it is chrome on macos. I just tried https://try.gogs.io and it is reproducible. There is no error in the console tab. FYI, the recorded gif shows the console tab as well.

Macos: 10.15.6
Chrome: Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by unknwon** [comment]
I'm using Chrome on macOS too. Have you tried to open Chrome on private mode in case extensions get in the way here?

**Comment by aeltawela** [comment]
@unknwon I did some try and error and I found it is this extension https://chrome.google.com/webstore/detail/epubreader/jhhclmfgfllimlhabjkgkeebkbiadflb?hl=en

Thanks a lot for your support, I will close the ticket.
