### ISSUE TITLE
DISABLE_REGISTRATION flag is ignored starting from docker tag 0.12.1

### ISSUE THREAD

**Issue by WitnessMee** [gogs/gogs#6382]
**Describe the bug**
When I setup the `DISABLE_REGISTRATION` flag to `true` in my original container it worked as expected. I no longer saw the registration option on the login page.
A couple of months later watchtower updated my container to the latest version

**Gogs version and commit**
Versions 0.12.1, 0.12.2, 0.12.3
It works fine on docker with tag 0.12

**Git version**
2.24.3

**Operating system**
Debian Buster

**Database**
sqllite3

**To Reproduce**
1. Create a docker container with `gogs/gogs:latest`
2. Set `DISABLE_REGISTRATION` to true in app.ini
3. Go to the admin console and check disable registration. It will be unchecked.
4. Works fine with the same config file if you use `gogs/gogs:0.12`

**Can you reproduce the bug at https://try.gogs.io?**
No that setting can't be changed

**Expected behavior**
Disable registration is checked in admin console and it is no longer possible to register in login page

**Actual behavior**
It is still possible to register

**Comment by unknwon** [comment]
Change settings requires a restart of Gogs unfortunately 😞 

BTW, `gogs/gogs:0.12` is the exact the same image as `gogs/gogs:0.12.3` :)

**Comment by unknwon** [comment]
I'll see if I can reproduce, might be overlooked during last configuration overhaul.

**Comment by unknwon** [comment]
I see your reproduce step was using `gogs/gogs:latest` not any of mentioned 0.12.1, 0.12.2, nor 0.12.3. 

That is expected, see https://github.com/gogs/gogs/blob/main/CHANGELOG.md#changed-1 and https://github.com/gogs/gogs/blob/main/CHANGELOG.md#removed, the `[service]` config section has been renamed to `[auth]`.

**Comment by WitnessMee** [comment]
Thanks for looking into it!

I had the issue with `latest` and not with `0.12` so I assumed (wrongly) that all version in between where impacted (0.12.1, 0.12.2 and 0.12.3). I have updated the ticket to reflect your remarks.
So it's clear now what happened. Everything from my app.ini (created with a 0.12 version) in the `[service]` config section was ignored, a rename to `[auth]` can fix it.
