### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Callj7899** [gogs/gogs#6384]
I'm trying to see the coding as a guide for helping my project, the google preview seems it would benefit me. Everytime I try to open the link, it shows the error 404 file not found, yet I can view parts of the code? I was hoping I could get this restored somehow?

Thank you

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
