### ISSUE TITLE
windows wsl  sudo -c can not work in 0.12.x version

### ISSUE THREAD

**Issue by jimying** [gogs/gogs#6385]
environment:   win10 wsl with ubuntu 18.04

problem:   0.11.91 work fine,  0.12.x not work

when win10 os startup , control wsl to start gogs service, method as follow:
(USER is  user name,  my gogs directory is in /home/USER/gogs)
step1:   win+r, shell:startup,   open win10 startup directory

step2:  new start_gogs.vbs,  add content:

```
Set ws = WScript.CreateObject("WScript.Shell")
ws.run "C:\Windows\System32\bash.exe -c 'sudo /etc/rc.local'",0
```

step3:  wsl  console,  edit /etc/rc.local, add content
`sudo -c  USER  /etc/gogs.wsl`

Notcie:  /etc/rc.local to excutable,  chmod +x /etc/rc.local

step4: wsl console, create /etc/gogs.wsl,  add content
```
#!/bin/bash
 cd /home/USER/gogs
 ./gogs web
```
Notcie: /etc/gogs.wsl to excutable, chmod +x /etc/gogs.wsl

**Comment by unknwon** [comment]
Thanks for sharing :)
