### ISSUE TITLE
problem start gogs in crontab

### ISSUE THREAD

**Issue by ghost** [gogs/gogs#64]
Could run /opt/gogs/start.sh as user git successfully in terminal.  But failed as cron job.

edit crontab as user git:

```
# m h  dom mon dow   command
@reboot /opt/gogs/start.sh
```

After reboot, gogs cannot be started:

From git@intense.localdomain  Sun Apr  6 18:56:25 2014
Return-Path: git@intense.localdomain
X-Original-To: git
Delivered-To: git@intense.localdomain
From: root@intense.localdomain (Cron Daemon)
To: git@intense.localdomain
Subject: Cron git@intense /opt/gogs/start.sh
Content-Type: text/plain; charset=ANSI_X3.4-1968
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/git>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=git>
Date: Sun,  6 Apr 2014 18:56:17 +1200 (NZST)
Status: RO

Server is running...
Expect user(git) but current user is:

**Comment by msongz** [comment]
I recently facing the similar problem.
i run gogs in `root` user
but the crontab log is :` [FATAL] [...g/setting/setting.go:571 NewContext()] Expect user 'root' but current user is:`

my crontab script is:
`*/2 * * * * sh /home/pi/chk-gogs.sh > /tmp/renew.log`

my chk-gogs.sh is:

```
#!/bin/bash
pidof gogs > /dev/null
if [ $? -ne 0 ] ; then
   /home/pi/gogs/gogs web &
fi
```
