### ISSUE TITLE
Git commands using SSH fail when NSSM service was up for more than 24h on Windows

### ISSUE THREAD

**Issue by bmerlet-aka** [gogs/gogs#6407]
**Describe the bug**
Git commands using SSH fail every day since migrating from Gogs **0.11.86.0130** to **0.12.2** on Windows.
The windows service needs to be restarted to make it work again

The error only occurs with ssh, git commands over http work correctly

**Gogs version and commit**
Gogs Version: 0.12.2 
Build Commit: 253b2bef4c26925d2fd0555aa8911cd21fb68b8c

Using Gogs as a Windows service with nssm.

**Git version**
Git Version : 2.24.1

**Operating system**
Windows Server 2016. 

**Database**
sqlite3

**To Reproduce**

1. Use Gogs service with nssm
2. Push some data using ssh
3. Let the service run for about 24h
4. Try to fetch/pull from remote over ssh

**Can you reproduce the bug at https://try.gogs.io?**
no

**Expected behavior**
The ssh server should be running correctly and be available whenever the Gogs service is running

**Actual behavior**
SSH server becomes unavailable for git pull/push every morning. The exact time when the SSH server becomes unavailable is not known but the problem is seen when our first collaborator starts to work (around 7 AM)

A restart of the nssm service is required in order to make it work again correctly.

**Additional context**
gogs.log:
06:54:07 [ERROR] [gogs.io/gogs/internal/ssh/ssh.go:114 func1()] SSH: Wait: exit status 1

git error:
```
git pull --rebase --progress "origin"
Gogs: Internal error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Done
```

This problem seems somehow different from #6316 because git push/pull over http works fine, but the origin of the error might be related.

**Comment by unknwon** [comment]
Thanks for the feedback!

Have you tried 0.12.3 which includes the patch for #6316 in case it's the same root cause?
