### ISSUE TITLE
Maximum password length limit

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6412]
It is possible to create a password with 1000000 words which could lead the server-side Denial of Service attack.

The fix (most likely) would be truncating the `opts.Password` to 256 if the length is larger:

https://github.com/gogs/gogs/blob/6f735cc2dade8c24c66f2c131f26334784de6139/internal/db/users.go#L234

Credit to _Faizan Ahmed <ethicalhacker218@gmail.com>_

**Comment by cl-alessandro-molari** [comment]
Is there any progress on this issue?

**Comment by unknwon** [comment]
@charles-woshicai Please go ahead if you would like take it :)

**Comment by charles-woshicai** [comment]
Please help to review this [PR](https://github.com/gogs/gogs/pull/6469) @unknwon

**Comment by charles-woshicai** [comment]
> Please help to review this [PR](https://github.com/gogs/gogs/pull/6469) @unknwon

Any update?

**Comment by rajat315315** [comment]
I think in the lastest master, it warns user of excedding 25 character limit.

**Comment by wuhan005** [comment]
Seems that the form validation has checked the password's length.
Users can't create a password that is longer than 255 characters.

https://github.com/gogs/gogs/blob/main/internal/form/user.go#L69

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/12731778/172039270-10792421-61f8-4834-af21-7c162fe61a18.png">

Closed.
