### ISSUE TITLE
Upgrade gogs and it 'forgets' that it was configured to use mysql and reverts to postgres (the default?).

### ISSUE THREAD

**Issue by kyrian666** [gogs/gogs#6422]
**Describe the bug**

Upgrade: ... gogs:amd64 (0.11.91-1585846162.2bd9d0b9.stretch, 0.11.91-1598527633.016d9d8c.stretch)

Gogs then forgets it was configured to use mysql, and reverts to postgres on localhost, which I believe is the default? I am not sure if this is a gogs bug or a Debian packaging bug, but I suspect probably the former, hence reporting it here.

It has happened I think twice before when I did a gogs upgrade with apt-get but this is the first time I got around to reporting it as a bug. If it helps track down the issue I can look further into the logs on my system to find out which intervening versions it started with.

**Gogs version and commit**

gogs:amd64 (0.11.91-1585846162.2bd9d0b9.stretch, 0.11.91-1598527633.016d9d8c.stretch)

**Git version**

Don't know. Maybe it's embedded in the Debian package version?

**Operating system**

Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

**Database**

MySQL.

**To Reproduce**

Upgrade the gogs package in Debian as above with apt-get.

**Expected behavior**

Upgrade does not 'forget' the configuration to use mysql.

**Actual behavior**

Gogs does not start and I get a front-end proxy error.

DB settings are somehow reverted to postgres (port 5432) not mysql, in spite of no other configuration changes...

2020/11/19 00:39:56 [ INFO] Gogs 0.13.0+dev
2020/11/19 00:39:56 [FATAL] [...t/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: dial tcp [::1]:5432: connect: connection refused
2020/11/19 00:39:56 [ INFO] Gogs 0.13.0+dev
2020/11/19 00:39:56 [FATAL] [...t/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: dial tcp [::1]:5432: connect: connection refused
2020/11/19 00:39:56 [ INFO] Gogs 0.13.0+dev
2020/11/19 00:39:56 [FATAL] [...t/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: dial tcp [::1]:5432: connect: connection refused

**Comment by unknwon** [comment]
Hi, [many config options were renamed](https://github.com/gogs/gogs/blob/main/CHANGELOG.md#changed-1) and [removed starting 0.13](https://github.com/gogs/gogs/blob/main/CHANGELOG.md#removed), database type is one of them.

**Comment by kyrian666** [comment]
Thanks, I've corrected some of them and it no longer reverts to trying to use postgres, but now it chokes on another bit of the startup. I'll try and make sure I've got all of the changes applied to my config and then come back if there are still problems.

**Comment by unknwon** [comment]
Another option is to stick with 0.12 releases, but I think the installation approach might not support pinned versions.

**Comment by kyrian666** [comment]
Gone through all the config option changes as above, and the original error has gone away. But now am faced with this showstopper issue:

2020/12/12 00:35:34 [FATAL] [...t/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: auto migrate "LFSObject": Error 1071: Specified key was too long; max key length is 767 bytes

Gogs still won't start. I've looked at the source code that the error references, but found it impossible to follow past the db library that is used.

So I've just had to downgrade again.

If I knew which transition it were trying to apply to fix this I could do it manually, but there is no detail in that message about which database, table, key, etc is causing the problem.

**Comment by unknwon** [comment]
The problem is with the "lfs_object.oid" column: https://github.com/gogs/gogs/blob/main/docs/dev/database_schema.md#table-lfs_object 

Can you check if the column type is the same as shown in the page I linked? `VARCHAR(191)`

**Comment by kyrian666** [comment]
The table was entirely absent, creating it and putting back all of the other tweaks as above seems to have got me back in business, thank you :) I guess something is amiss in the packaging process somewhere that does not apply the database transition or something?

**Comment by unknwon** [comment]
BTW, that is the MySQL version you have?

**Comment by kyrian666** [comment]
Well, Debian no longer packages mysql by default, so the version of MariaDB is 10.1.47-0+deb9u1.

K.
