### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [gogs/gogs#6446]
**Describe the bug**
The markup version of the readme that is displayed for the main page in this repo contains the following link:

“Scaleway”
Status code [404:NotFound] - Link: https://www.scaleway.com/imagehub/gogs/

**Gogs version and commit**
N/A

**Git version**
N/A

**Operating system**
N/A

**Database**
N/A

**To Reproduce**
1. Click on the link

**Can you reproduce the bug at https://try.gogs.io?**
N/A

**Expected behavior**
Link should work

**Actual behavior**
Status code [404:NotFound] 

**Screenshots**
N/A

**Additional context**

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fgogs%2fgogs
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=gogs

--

This bad link was found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by unknwon** [comment]
Thanks for the report! The dead link has been removed.
