### ISSUE TITLE
gogs有计划支持达梦,人大金仓等国产数据库吗?

### ISSUE THREAD

**Issue by springrain** [gogs/gogs#6453]
gogs有计划支持达梦,人大金仓等国产数据库吗?

**Comment by ttimasdf** [comment]
This is an open source project. If you'd like to add a new feature, you're very welcome to send a PR. Or at least **add more explanations about your proposal**, the pros and cons of the database systems you mentioned. Better performance? Lower maintenance cost? or whatever?

Just remember, the project owner is Chinese doesn't mean this is a Chinese-only projects, Gogs has gained 36.4k stars worldwide and deployed across the globe. "国产" in your aspect means the opposite for the others.

And after all, why on earth should an open source project support these **proprietary, undocumented, platform limited, not widely-used** database systems? You tell me.
