### ISSUE TITLE
gogs的迁移外部仓库任务可以做一个任务列表界面吗？拉代码速度太慢看不到进度

### ISSUE THREAD

**Issue by Superkeyv** [gogs/gogs#6455]
能不能增加一个迁移外部仓库的页面，把拉取代码任务放到这个界面中监视状态。
平常的迁移仓库状态卡在界面上，不知道什么时候完成，很少能够成功迁移的

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

I think this is duplicated to https://github.com/gogs/gogs/issues/829.
