### ISSUE TITLE
No more raspi support?

### ISSUE THREAD

**Issue by BoboTiG** [gogs/gogs#6457]
**Describe the bug**

It seems there is no downloads for raspi since v0.12.0. Is it on purpose?

**Gogs version and commit**

0.12.0 and newer.

**Operating system**

Raspberri Pi 2.

**Database**

SQLite.

**Comment by elouin** [comment]
The Raspi2 is arm_v7 if iam not mistaken. So the linux_armv7 packages should work.

**Comment by BoboTiG** [comment]
You are right @elouin, thank you 👍
