### ISSUE TITLE
0.11.66.0916  upgrade 0.12.3  Error 1071: Specified key was too long; max keylength is 767 bytes

### ISSUE THREAD

**Issue by TelDragon** [gogs/gogs#6476]
error info

```
[FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: auto migrate "LFSObject": Error 1071: Specified key was too long; max keylength is 767 bytes

```
According to the upgrade to modify the corresponding parameters, I have already operated, and after that, the same error message is still reported.

https://github.com/gogs/gogs/blob/main/CHANGELOG.md#removed

my app.ini
```
BRAND_NAME = GOGS平台
RUN_USER = git
RUN_MODE = prod

[database]
TYPE     = mysql
HOST     = 127.0.0.1:3306
NAME     = gogs
USER     = gogs
PASSWORD = gogs
SSL_MODE = disable
PATH     = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories

[server]
DOMAIN           = gogs.xxx.com.cn
HTTP_PORT        = 3000
EXTERNAL_URL     = http://gogs.xxx.com.cn:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = false
OFFLINE_MODE     = false

[email]
ENABLED = false

[auth]
REQUIRE_EMAIL_CONFIRMATION = false
ENABLE_EMAIL_NOTIFICATION = false
DISABLE_REGISTRATION   = true
SHOW_REGISTRATION_BUTTON = false
ENABLE_REGISTRATION_CAPTCHA = true
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[session]
PROVIDER = file

[log]
MODE      = console, file
LEVEL     = Info
ROOT_PATH = /home/git/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = cvdIJ2Z3gQZQqc8
```

Is the error found on the Internet the database index limit?
I use MySQL 5.6

**Comment by TelDragon** [comment]
2021/01/27 17:44:59 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: auto migrate "LFSObject": Error 1709: Index column size too large. The maximum column size is 767 bytes.

**Comment by TelDragon** [comment]
Upgrading from 0.11.91 to 0.12.0 is still an error

**Comment by cedrictemple** [comment]
Same error here, migrating from 0.11.29 to 0.12.3 with MariaDB 10.1.26 as db engine.

**Comment by RobertKosten** [comment]
Same error here, migrating from `0.11.91.0811` to `0.12.3` with MySQL `5.5.62-0ubuntu0.14.04.1` (Yes, I know it's old, but it's not connected to the intarwebs :) )

**Comment by derak-kilgo** [comment]
I'm sure you all have worked around this by now but just in-case.

Your error is a combination issue with a "row_format" for the table doesn't support large index keys and a character set other than utf8mb4.

The migration from gogs 0.11 to 0.12 is creating a new table; lfs_object.

The innodb storage engine in mysql supports many different row formats; some of which don't support large index keys. See https://dev.mysql.com/doc/refman/8.0/en/innodb-row-format.html for a nice table and explanation.

To check this setting in your mysql instance, connect to your database and run the following query:
show variables like '%innodb_default_row_format%';

When new tables are created; they'll use that row format by default.
The options are 'redundant', 'compact', 'dynamic' and 'compressed'. 
Only 'dynamic' and 'compressed' support large index keys.

Really, this should be a connection level setting that gogs applies for before running a migration.
If gogs would run "SET innodb_default_row_format=DYNAMIC;" before running the migrations or include ROW_FORMAT=DYNAMIC in the create table statement; this error could be avoided.

Another issue is gogs db migrations don't specify the charset or collation, instead depending on the default value for the server.
Again you can check that with: "show variable like '%character_set%';
It's likely not utf8mb4

Why does that matter?
The mysql docs say:
> Fixed-length fields greater than or equal to 768 bytes are encoded as variable-length fields. For example, a CHAR(255) column can exceed 768 bytes if the maximum byte length of the character set is greater than 3, as it is with utf8mb4.

and those are things that gogs could optionally set when creating tables.

My guess is that won't happen. 
The min version on the gogs requirements page is mysql 5.7 which has defaults that would avoid both of these issues.

**Comment by RobertKosten** [comment]
My "workaround" was rolling back to the last version I had working :stuck_out_tongue_closed_eyes: 

Thx for the info (`utf8mb4` I already had, got bitten by that one before :roll_eyes:). I've been meaning to switch to postgresql anyway, so now's as good a time as any, I supoose :+1:

**Comment by enefry** [comment]
upgraded fail too !
2021/06/29 10:39:08 [xorm] [warn]  2021/06/29 10:39:08.543498 Table team_repo Column repo_id db default is NULL, struct default is 
2021/06/29 10:39:08 [xorm] [warn]  2021/06/29 10:39:08.546882 Table notice Column type db default is NULL, struct default is 
2021/06/29 10:39:08 [xorm] [warn]  2021/06/29 10:39:08.547697 Table notice Column description db default is 'NULL', struct default is 
2021/06/29 10:39:08 [xorm] [warn]  2021/06/29 10:39:08.548432 Table notice Column created_unix db default is NULL, struct default is 
2021/06/29 10:39:08 [xorm] [warn]  2021/06/29 10:39:08.551775 Table email_address Column is_activated db default is NULL, struct default is

**Comment by einverne** [comment]
Same here, upgrade from Gogs 0.11.97.1209 to 0.12.3
.

I'm using MariaDB.

```
2021/09/20 01:34:46 [ INFO] Gogs 0.12.3
2021/09/20 01:34:46 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: auto migrate "LFSObject": Error 1071: Specified key was too long; max key length is 767 bytes

```

**Comment by TelDragon** [comment]
@derak-kilgo 

Thank you very much. My problem has been solved.

非常感谢，我的问题已经得到了解决。
