### ISSUE TITLE
gogs测试分支push   master分支绑定的jenkins项目也会跟着构建

### ISSUE THREAD

**Issue by metka495** [gogs/gogs#6477]
Gogs Webhook
BranchFilter  refs/heads/master
Generic Webhook Trigger 两个分支分配了不同的token

一个gogs仓库里加了两个gogs 不同的token触发不同的jenkins项目

但是每次push test分支的时候 master分支也会构建

**Comment by liwenchao1984** [comment]
参考这个页面，https://blog.csdn.net/TianKongDeTangGuo/article/details/108681836

使用generic-webhook-trigger ，加上分支判断，可以解决此问题。

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
