### ISSUE TITLE
Smart links to other issues and PRs are not generated anymore (>= 0.12)

### ISSUE THREAD

**Issue by WuShell** [gogs/gogs#6506]
**Describe the bug**

Generation of (smart) links to issues and PRs don't work in versions higher than 0.12.

**Gogs version and commit**

Tried with 0.12.3 (several instances, different servers) and 0.13.0-dev

**It happens also in https://try.gogs.io** (see attached screenshots)

**Git version**

```
$ git version
git version 2.30.1

```

**Operating system**

FreeBSD, Debian

**Database**

PostgreSQL 11, MySQL 5.5

**To Reproduce**

1. open an issue, in the description write the number of another issue, like #2
2. click on preview, in the rendered preview, #2 is a link to issue number 2
3. click save, in the rendered page with the new issue, **#2 is not a link to issue number 2**

**Can you reproduce the bug at https://try.gogs.io?**

Yes

https://try.gogs.io/14mroot/testing-issue/issues/2

**Expected behavior**

Write #{issue} and a link to the issue to be rendered

**Actual behavior**

Wrote #{issue} and a link to the issue is not rendered

**Screenshots**

Attached are three screenshots with the described behaviour in try.gogs.io
![gogs-report-1](https://user-images.githubusercontent.com/875005/108832687-29ccd500-75cc-11eb-8bbd-cf1738e9c635.png)
![gogs-report-2](https://user-images.githubusercontent.com/875005/108832690-2a656b80-75cc-11eb-8fbd-bf96e94c8323.png)
![gogs-report-3](https://user-images.githubusercontent.com/875005/108832693-2a656b80-75cc-11eb-8a1b-fe4666cff26f.png)

**Additional context**

**Comment by oscarmlage** [comment]
Same here too. `0.13.0-dev` on Docker + `MySQL`. Preview is working but then when publishing the comment I don't get the link to the issue.

**Comment by jjakob** [comment]
I'm having the same issue on 0.12.3.

**Comment by oscarmlage** [comment]
Experiencing same issue even in current [try.gogs.io](https://try.gogs.io):

- https://try.gogs.io/oscarmlage/testing-repo/issues/1

If I put `#2` as reference to the issue n. 2 it's not working, it only works if I write ` [#2](/issues/2)`.

**Comment by unknwon** [comment]
Thanks for reporting! I'm going to take a look as it seems should be easy to fix, and https://github.com/gogs/gogs/commit/e6b4c467e83a959f00e9244ef359ea3c8359ca5c might be suspicious.

**Comment by oscarmlage** [comment]
Thank you so much @unknwon!

**Comment by unknwon** [comment]
The 0.12.4 has been released that includes the patch of the reported issue.
