### ISSUE TITLE
外部wiki连接中对地址中的?字符的处理有问题，保存成%F，在点击打开时无法打开链接

### ISSUE THREAD

**Issue by wangweinjcn** [gogs/gogs#6516]
例如：我设置的外部wiki地址：http://tst.com:9000/wiki/pages/viewpage.action?pageId=2097175
保存到数据库，再打开时变成了：http://tst.com:9000/wiki/pages/viewpage.action%3FpageId=2097175

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
