### ISSUE TITLE
The authentication source selected is not associated with the user.

### ISSUE THREAD

**Issue by dvgoyeneche** [gogs/gogs#6531]
when using ldap (via bindDN) I get this error on the logon page:
The authentication source selected is not associated with the user.

In the logs I cant see any error

**Comment by esgungor** [comment]
If you use the same account name in Local Authentication, it could be caused conflict.
Trying different LDAP account probably fixes the situation. However, I'm not sure why would this happens.

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
