### ISSUE TITLE
Question: How do I move servers?

### ISSUE THREAD

**Issue by ghost** [gogs/gogs#654]
How do I move servers with Gogs? I have repos installed in Gogs that are actively being used. How should I go about moving servers?

Migrate all to Bitbucket or so and then migrate them back in order to be sure no data loss occurs?

Or is there a different way?

Also, sorry about posting this in Gogs issues but I couldn't find any support forum or other :)

**Comment by II-Matto** [comment]
Hi, @Unknwon , I am using gogs on Windows 10 and trying to move my gogs repositories from one laptop to another. I have copied the `data` and `repo` directory, after which all my repositories can be found in my new gogs. But when I tried to `push`, git reported errors.
```
remote: hooks/update: line 2: <old_gogs_location>/gogs.exe: No such file or directory
remote: error: hook declined to update refs/heads/master
To http://localhost:3000/<user_name>/<repo_name>.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'http://localhost:3000/<user_name>/<repo_name>.git'
```
I then tried `gogs.exe fix location <old_gogs_location>`, but it reported `No help topic for 'fix'`. And I didn't find any file like `*fix*` in my gogs directory. BTW, I used a portable version of gogs with zip file.

So, how can I correctly move gogs from one computer to another on Windows? Many thanks.

**Comment by II-Matto** [comment]
Hi, @Unknwon , my `push` problem is solved by manually modifying the corresponding `hooks/update` file (change the `<old_gogs_location>` to the new one). I was wondering if there are anything else that I should do for my migration.

**Comment by Unknwon** [comment]
@II-Matto you can update path in the hook in the admin panel actually...

**Comment by II-Matto** [comment]
Hi, @Unknwon ,thanks for your reply. I tried `http://localhost:3000/admin` and found there is an operation `Rewrite all update hook of repositories (needed when custom config path is changed)`. Is this the one I need to run?

**Comment by Unknwon** [comment]
Yes, and another one, see https://gogs.io/docs/intro/troubleshooting#incorrect-binary-path-for-update-hook.

**Comment by II-Matto** [comment]
@Unknwon Great thanks for your prompt reply! Happy New Year : )
