### ISSUE TITLE
docker 部署gogs 使用drone 打包不可以webhook自动化打包，只能手动推送

### ISSUE THREAD

**Issue by demon471** [gogs/gogs#6546]
### 如图webhook推送失败，发送内容为N/A，如果手动发送就会成功。
**docker 部署参数如下：**
gogs
`docker run -p 10022:22 -p 10080:3000 --name=gogs --net docker-mynet --ip 172.172.0.80 --restart=always -e TZ="Asia/Shanghai" -v /soft/docker/gogs:/data  -d gogs/gogs`

drone
`docker run \
  -v /soft/docker/drone:/data  --net docker-mynet --ip 172.172.0.79 \
  -e DRONE_AGENTS_ENABLED=true \
  -e DRONE_GOGS_SERVER=http://runtume.top:10080 \
  -e DRONE_RPC_SECRET=dronerpc666 \
  -e DRONE_SERVER_HOST=runtume.top:3080 \
  -e DRONE_SERVER_PROTO=http \
  -e DRONE_USER_CREATE=username:demon471,admin:true \
  -e TZ="Asia/Shanghai" \
  -p 3080:80 \
  --restart=always \
  --detach=true \
  --name=drone \
  drone/drone`

![image](https://user-images.githubusercontent.com/12760215/116508380-d2145800-a8f3-11eb-8182-ab6651852560.png)

**Comment by baiyijun** [comment]
我这里也一样,gogs的版本
![image](https://user-images.githubusercontent.com/11145358/116548949-7e236680-a927-11eb-8f45-2b000a1a68b8.png)

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
