### ISSUE TITLE
Too slow docker boot on NFS mounts

### ISSUE THREAD

**Issue by druppy** [gogs/gogs#6554]
**Describe the bug**

I have been using the docket image as part of a new HELM v3 upgrade I made (I have no idea where to publish this as of now), and it works really good, except for a small detail.

When starting my docker image, it took a really long time to startup, and in fact the k8s cluster I used ended up terminating the container as the live check only works when the service are running.

I took a deep look inside the container, and found that there where a `chown -R $USER:$USER /data` command running. This would normally not be a problem for small and physical mounts, but my setup was a really large (20k+ files) NFS mount. 

I have therefor made a pull request #6553 , that change the `start.sh` to test if `/data` have the ownership we expect, and then only run the `chown` command when needed. There could be an argument about what happens if one of the files down the `/data` tree have changed ownership, and yes ... that would be a problem. But I assume that the `chown` command are here to ease migration, and not to keep file ownership in sync.

I really hope this could get pulled, to allow for better NFS integration.

**Gogs version and commit**
master 

**Git version**
2.30.2

**Operating system**
Debian Linux 

**Database**
PostgrSQL

**To Reproduce**

1. setup docker image using a large NFS mount as `/data`
2. start the container
3. observe really long boot (depending on the location on your NFS server.

**Can you reproduce the bug at https://try.gogs.io?**
Nope, this is boot relevant

**Expected behavior**
Fast boot

**Actual behavior**
Really long startup time

**Comment by julienfabre** [comment]
I'm having the same issue and would love to see this merged !

**Comment by unknwon** [comment]
Hey @julienfabre, I just merged #6553, and it takes about an hour to finish automated Docker build for `gogs/gogs:latest`.

**Comment by julienfabre** [comment]
Thank you @unknwon , I'm not seeing the fix in the latest release from today though (https://github.com/gogs/gogs/releases/tag/v0.12.5), do you plan to release it separately?

**Comment by unknwon** [comment]
@julienfabre I haven't QA it myself just in case it break anything, so did not include in today's patch release. If I get the chance to do the sanity check, it could be included in the next patch release (which is currently no planned).

**Comment by unknwon** [comment]
QA seems good, will be included in 0.12.5.

**Comment by unknwon** [comment]
The 0.12.6 has been released that includes the patch of the reported issue.
