### ISSUE TITLE
Submodules from github in gogs

### ISSUE THREAD

**Issue by wipedlifepotato** [gogs/gogs#6581]
2021/06/21 08:26:10 [ERROR] [...gogs/internal/route/repo/view.go:57 renderDirectory()] get commits info: get submodule "luasql": revision does not exist
Just create submodule to github and push the commit...

**Comment by zhpengfei** [comment]
i got the same error，have you fixed it?

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this as it is not using one of the [issue forms](https://github.com/gogs/gogs/issues/new/choose).
