### ISSUE TITLE
Error on loading homepage when built from source

### ISSUE THREAD

**Issue by flaxeneel2** [gogs/gogs#6582]
**Describe the bug**
Basically the dashboard page does not load if it is told to load from disk, instead it throws out an error, no 

**Gogs version and commit**
The latest (built from source)

**Git version**

```
$ git version
git version 2.25.1
```

**Operating system**

**Database**

**To Reproduce**
1. Download source
2. Build
3. Install
4. Enable load from disk
5. load page as incognito 

**Can you reproduce the bug at https://try.gogs.io?**
no

**Expected behavior**
load the page normally

**Actual behavior**
gives the following error:
`html/template:home: "<" in attribute name: "</p>\n\t\t\t</div>\n\t\t\t<div class=\"ei"`

**Screenshots**
![image](https://user-images.githubusercontent.com/60919292/122769847-fbc77b00-d2b5-11eb-853c-aa3503f9b854.png)

**Additional context**
No error logs even after setting to verbose

**Comment by flaxeneel2** [comment]
Welp, for now there is a quick workaround, in home.tmpl (in templates), just remove all code for all the other languages and keep the part which was there in the `{{else}}` block, remember to remove the `{{end}}` at the end too. It does remove langs other than english but it works

**Comment by pndx** [comment]
same error. delete all else block and end block not work.

**Comment by pndx** [comment]
I found out it work fine if i am logged in. it show `html/template:home: "<" in attribute name: "</p>\n\t\t\t</div>\n\t\t\t<div class=\"ei"
`if i logged out.

**Comment by unknwon** [comment]
Thanks for reporting! Should have been fixed in `main` branch.
