### ISSUE TITLE
数据库设置不正确：Error 1071: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by erwzqsdsdsf** [gogs/gogs#6586]
![微信截图_20210707195815](https://user-images.githubusercontent.com/3872983/124755242-b36ab700-df5d-11eb-938b-0cc668dc7033.png)

程序版本是   Gogs 0.12.3

**Comment by ihlfo** [comment]
同样遇到此问题
![image](https://user-images.githubusercontent.com/5234001/127286807-14ef6fc6-a937-4397-a8bf-c0d45981b653.png)

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
