### ISSUE TITLE
最新版不支持Sqlite了吗？

### ISSUE THREAD

**Issue by skyformat99** [gogs/gogs#6588]
最新版不支持Sqlite了吗？ Sqlite好用啊，轻便

主页上都不提了：
所有的版本都支持 MySQL、PostgreSQL 和 TiDB（使用 MySQL 协议）作为数据库，并且均使用构建标签（build tags）cert 进行构建。需要注意的是，不同的版本的支持状态有所不同，请根据实际的 Gogs 提示进行操作。

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
