### ISSUE TITLE
remote: hooks/update: line 2: /path/to/dir: No such file or directory

### ISSUE THREAD

**Issue by facat** [gogs/gogs#659]
I recompiled gogs and used the old config and database. gogs is now in another directory. When I submitted new code to the remote repository, this errors occurred. It seems that this error occurred because its directory was changed but database remained the same. Where can I reset the new path?

**Comment by benyaminl** [comment]
@unknwon Hello, I wanna ask, I tried to run `./gogs fix`, it return no option, but seems `./gogs admin resync-hooks` fix the issue, does this mentioned on docs? I don't see it anywhere. Thank you

**Comment by unknwon** [comment]
@benyaminl There is no `./gogs fix` 😂 But sounds like a good idea!

**Comment by benyaminl** [comment]
@unknwon but does that command really the way to fix it? Because I face same error as the OP, and after run it, I can push the code to repo. Just need clarification. Thanks

**Comment by unknwon** [comment]
> @unknwon but does that command really the way to fix it? Because I face same error as the OP, and after run it, I can push the code to repo. Just need clarification. Thanks

It is expected approach to fix/do whenever you moved your Gogs binary (e.g. migrate to a new server).
