### ISSUE TITLE
0.12.3 go get 有问题

### ISSUE THREAD

**Issue by evildecay** [gogs/gogs#6590]
go get的时候 返回的xml中go-import的meta tag不对，换成0.11.9就没问题。有人提出一样的问题如下：
[0.12.3版私有仓库go-get=1无法获得go-import信息](https://discuss.gogs.io/t/0-12-3-go-get-1-go-import/3444)

**Comment by kvii2202** [comment]
我也是差不多的问题。
gogs v0.12.3 版本开启 `REQUIRE_SIGNIN_VIEW=true` 之后，
在 go get 私有仓库时，go-get=1 这个请求会被重定向到 /user/login。
除了回退 gogs 版本之外，有什么其他的方法越过这个重定向吗？

I have got the same issue.
I use  `REQUIRE_SIGNIN_VIEW=true` with gogs v0.12.3.
Request `go-get=1` will be redirected to `/user/login` when I use `go get`.
And I try to downgrade gogs but I can't build it.
I don't think "can not use `go get` without login"  is true,
but have any way to resolve it?

**Comment by kvii2202** [comment]
@evildecay 喜大普奔！这个问题在 5 天前被 pr #6598  解决了！
要是方便用最新开发版的话可以直接用了。
但是 v0.12 版的配置文件有一些字段变了，注意不要踩坑了。

Oh !!! This issue has solved 5 days ago.
You can use it if you want to use the unstable version of gogs.
But there are some changes of config file between  v0.11 and v0.12, carefully about it.

**Comment by zhu168** [comment]
这个bug得有1年多了

**Comment by zhu168** [comment]
我去年就因为升级后碰到这个bug老老实实的滚回0.11了，不过现在代码状态编译后运行好像有问题

**Comment by zhu168** [comment]
实测问题已经解决了，只是需要自行编译
目前情况是macos下运行会报错，linux的正常

**Comment by unknwon** [comment]
Should have been fixed in the `main` branch.
