### ISSUE TITLE
自定义模板文件错误

### ISSUE THREAD

**Issue by inkss** [gogs/gogs#6591]
**Describe the bug**

在使用自定义模板过程中，修改 [home.tmpl](https://github.com/gogs/gogs/blob/ba8be9489e6d959fa9005fc7d38bf62562580d23/templates/home.tmpl) 时，存在一处语法错误，它会导致页面渲染失败：

```txt
html/template:home: "<" in attribute name: "</p>\r\n\t\t\t</div>\r\n\t\t\t<div class=\""
```

我检查了下这个文件，在第 282 行，`a` 标签没有结尾，这似乎是一个遗漏。

```html
Usa Gogs con <a target="_blank" $ 
```

https://github.com/gogs/gogs/blob/ba8be9489e6d959fa9005fc7d38bf62562580d23/templates/home.tmpl#L282

以上。

**Comment by unknwon** [comment]
Thanks for reporting! Should have been fixed in `main` branch.
