### ISSUE TITLE
The console enters the code warehouse and reports an internal error of the server

### ISSUE THREAD

**Issue by AsherHuu** [gogs/gogs#6592]
[ERROR] [...gogs/internal/route/repo/view.go:57 renderDirectory()] get commits info: get submodule "ffi": revision does not exist

![image](https://user-images.githubusercontent.com/32830348/126923223-eec6e631-f2ac-452c-a9b1-c73cd88e9aec.png)

![image](https://user-images.githubusercontent.com/32830348/126923229-0be863b3-038f-42a4-be2f-398ce4e16f7f.png)

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
