### ISSUE TITLE
本地部署好卡

### ISSUE THREAD

**Issue by yjgfn** [gogs/gogs#6624]
本地部署好卡，是我部署问题么？
windows 直接localhost部署的，特别是点击仓库查看代码，反应要半天（平均10秒左右）才响应

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
