### ISSUE TITLE
Running as service on CentOS 7

### ISSUE THREAD

**Issue by SerenityDevelopment** [gogs/gogs#6625]
**Describe the bug**
Setting up Gogs to run as a service on CentOS 7 is not working properly. When I start Gogs it does not load on my site but if I manually start it then it loads on my site just fine. So the service is not starting Gogs as it should.

**Gogs version and commit**
0.12.3

**Git version**
1.8.3.1

**Operating system**
CentOS 7

**Database**
MySQL 8.0.26

**To Reproduce**
1. Follow steps under "For Deployment" here: https://gogs.io/docs/installation/configuration_and_run.html
2. Type systemctl start gogs or systemctl start gogs-web
3. Type systemctl status gogs
4. You will see it is active and running
5. Load website address where Gogs is running (I'm using Nginx so I had to do some stuff with proxy and fastcgi to get it to load under a subdomain).

**Can you reproduce the bug at https://try.gogs.io?**
No as that is just Gogs running like normal.

**Expected behavior**
Gogs to start and be running as intended.

**Actual behavior**
Systemctl shows Gogs as active and running but it is actually not running.

**Screenshots**

**Additional context**
I'm also not able to register at https://discuss.gogs.io otherwise I would just have this discussion there.

**Comment by unknwon** [comment]
Hey @SerenityDevelopment!

Are you able to provide some logs (usually in `log/gogs.log`)? Can't really help you much without logs.
