### ISSUE TITLE
Gogs doesn't load anymore

### ISSUE THREAD

**Issue by gianmarcogg03** [gogs/gogs#6626]
**Describe the bug**

After installing iRedMail the server didn't want to work anymore. The log just says `[TRACE] Log mode: File (Info)`, but if I try to go to the Gogs interface on my browser it just times out or gives me a 503 error.

**Gogs version and commit**

0.12.3

**Git version**

```
$ git version
git version 2.20.1
```

**Operating system**

Debian 10

**Database**

sqlite3

**To Reproduce**
1. Install iRedMail by following the instructions on their website
2. Once the installation is done, reboot the machine
3. Start the Gogs server

**Can you reproduce the bug at https://try.gogs.io?**

No, I would need access to the command line.

**Expected behavior**

The server should work as usual.

**Actual behavior**

The server seems to start but it doesn't load.

**Screenshots**

![Senzanome](https://user-images.githubusercontent.com/28053717/137310600-8ec457f5-2de4-4767-bfd2-978b4fe95cae.png)

**Additional context**

`2021/10/14 13:33:50 [ INFO] Gianmarco's Git Server 0.12.3
2021/10/14 13:33:50 [ INFO] Run mode: Production
2021/10/14 13:33:50 [ INFO] Listen on http://0.0.0.0:3000`

**Comment by unknwon** [comment]
Sorry to hear that... but honestly... how is it related to Gogs 😇, I think your browser is not even sending the request to Gogs, which has been hijacked by other services.

What do you get if you try `curl http://0.0.0.0:3000` on your server?

**Comment by kafuuchino-desu** [comment]
I have reproduced the same bug, it's cause by the log mode config, with default config(MODE=file), gogs refuses to load and any http request returns empty. But when I set MODE=console, it loads and I can access gogs web

**Comment by kafuuchino-desu** [comment]
> I have reproduced the same bug, it's cause by the log mode config, with default config(MODE=file), gogs refuses to load and any http request returns empty. But when I set MODE=console, it loads and I can access gogs web

could you please take a look into this? @unknwon sorry for the ping if it bothers you

**Comment by unknwon** [comment]
@kafuuchino-desu That's a good find!

Could you answer the same question I asked in https://github.com/gogs/gogs/issues/6626#issuecomment-966400298?
