### ISSUE TITLE
Clone with HTTP link doesn't work. Returns 500. 

### ISSUE THREAD

**Issue by ddl-denis-parnovskiy** [gogs/gogs#6634]
```
% git clone http://localhost:10880/test/testrepo.git                                   
Cloning into 'testrepo'...
fatal: unable to access 'http://localhost:10880/test/testrepo.git/': The requested URL returned error: 500
```

** Gogs version **
Using gogs container 
docker pull gogs/gogs:latest 
DIGEST 1c4223301026

**Git version**
```
git --version
git version 2.30.0
```

**Operating system**
MacOs Catalina

**Database**
SQLite in data/gogs.db

**To Reproduce**
* Create new gogs container 
* docker run -d --name=gogs -p 10022:22 -p 10880:3000 -v /tmp/gogs/data:/data gogs/gogs
* Copy the clone link from repository. E.g. http://localhost:3000/test/testrepo.git
* Replace port 300 with docker exposed port 

% git clone http://localhost:10880/test/testrepo.git                                   
Cloning into 'testrepo'...
fatal: unable to access 'http://localhost:10880/test/testrepo.git/': The requested URL returned error: 500

**Can you reproduce the bug at https://try.gogs.io?**
Yes.

git clone https://try.gogs.io/denispar/testrepo.git
Cloning into 'testrepo'...
fatal: unable to access 'https://try.gogs.io/denispar/testrepo.git/': Received HTTP code 500 from proxy after CONNECT

% git clone https://denispar:censored@try.gogs.io/denispar/testrepo.git
Cloning into 'testrepo'...
fatal: unable to access 'https://try.gogs.io/denispar/testrepo.git/': Received HTTP code 500 from proxy after CONNECT

**Expected behavior**
git over http works

**Actual behavior**
git over http fails and returns 500

**Comment by unknwon** [comment]
Hey, can you specify the actual Gogs version? `gogs/gogs:latest` is not a version.

**Comment by ddl-denis-parnovskiy** [comment]
Checked: works with latest container and works with  https://try.gogs.io
