### ISSUE TITLE
OpenSSH 8.8p1 does not have ssh-rsa anymore, but built-in SSH server does not support anything except ssh-rsa

### ISSUE THREAD

**Issue by dmstek** [gogs/gogs#6638]
**Describe the bug**
After update to 8.8 git clone via built-in SSH server does not work. Error in log:

```[gogs.io/gogs/internal/ssh/ssh.go:151 func1()] SSH: Error on handshaking: ssh: no common algorithm for host key; client offered: [rsa-sha2-512-cert-v01@openssh.com rsa-sha2-256-cert-v01@openssh.com rsa-sha2-512 rsa-sha2-256 ssh-ed25519-cert-v01@openssh.com ecdsa-sha2-nistp256-cert-v01@openssh.com ecdsa-sha2-nistp384-cert-v01@openssh.com ecdsa-sha2-nistp521-cert-v01@openssh.com sk-ssh-ed25519-cert-v01@openssh.com sk-ecdsa-sha2-nistp256-cert-v01@openssh.com ssh-ed25519 ecdsa-sha2-nistp256 ecdsa-sha2-nistp384 ecdsa-sha2-nistp521 sk-ssh-ed25519@openssh.com sk-ecdsa-sha2-nistp256@openssh.com], server offered: [ssh-rsa]```

**Gogs version and commit**
0.12.3
https://github.com/gogs/gogs/commit/f0e3cd90f8d7695960eeef2e4e54b2e717302f6c

**Git version**
git version 2.33.0

**Operating system**
Centos 7 server, Arch Linux client

**Database**
sqlite3

**To Reproduce**
Just do "git clone" on system with OpenSSH 8.8 and you will get error "no matching host key type found. Their offer: ssh-rsa" and that error in GOGS log.

**Can you reproduce the bug at https://try.gogs.io?**
I cannot, as try.gogs.io seems does not work properly.
```Cloning into test...
ssh: connect to host try.gogs.io port 22: Network is unreachable
fatal: Could not read from remote repository.
```

**Expected behavior**
git clone should work (and everything else)

**Actual behavior**
git clone fails with error

**Comment by featdd** [comment]
Hi @dmstek,

I encountered the same issue, you can at least workaround this when adding this to your ssh configuration:

```
Host git.domain.tld
  HostKeyAlgorithms +ssh-rsa
  PubkeyAcceptedKeyTypes +ssh-rsa
```

It allows "ssh-rsa" again for console, but maybe your Git GUI client (like [fork](https://fork.dev/) for me) still has issues with this.

Greetings
Daniel

**Comment by abrander** [comment]
I believe updating `golang.org/x/crypto` should resolve this issue.

https://github.com/golang/crypto/commit/b4de73f9ece

**Comment by unknwon** [comment]
Thanks for the reporting and @abrander for the hint!

While this is a bug for the internal SSH server, I do see you're running on Centos 7 which has an SSH server. What's the reason you're using the internal SSH server?

The internal SSH server is never meant to be a replacement of the OpenSSH server pre-installed and was more of a workaround to no easy way to have SSH server installed on Windows systems).

**Comment by featdd** [comment]
@unknwon Hi,

I'm using the docker image, is it possible to change the ssh server there too?

**Comment by unknwon** [comment]
Internal SSH server is disabled by default, so you must have turned it on. Just flip the switch to turn it off.

**Comment by unknwon** [comment]
Note to the implementer:

- Relevant code block: https://github.com/gogs/gogs/blob/main/internal/ssh/ssh.go#L181-L191
- Add config options to decide which key type to generate, default will become `ed25519` (`gogs.ed25519`) instead of `rsa` (`gogs.rsa`).

**Comment by unknwon** [comment]
The patch to support list of user-defined algorithms has landed in https://github.com/gogs/gogs/pull/7345, which will be check-picked to 0.12 when 0.12.11 is released.
