### ISSUE TITLE
Markdown rendering for numbered lists with multiple digits do not work as expected

### ISSUE THREAD

**Issue by ajstadlin** [gogs/gogs#6644]
**Describe the bug**

Markdown rendering for numbered lists with multiple digits do not work as expected when viewed in *gogs* compared to viewing the same content in *github* and *vscode*.

**Gogs version and commit**

I discovered this with 2 *gogs* versions:  0.11.49.0521 and 0.13.0+dev

I tested and confirmed this is still an issue in [try.gogs.io/Tektite/MarkDownTests](https://try.gogs.io/Tektite/MarkDownTests)

```text
Application version 0.13.0+dev
Git version 2.25.1
Go version go1.15.2
```

**Operating system**

My gogs servers are running Ubuntu Server 20 LTS

Web viewing using Windows 10 Enterprise IoT 21H1 and Raspberry Pi Raspberry Pi OS (Buster)

Windows browsers tested: Microsoft Edge, Chrome, Firefox

Raspberry Pi browser tested: Chromium

**Database**

sqlite3

**To Reproduce**

79. If you do not see this line starting with "79." then you *See error*

**Can you reproduce the bug at https://try.gogs.io?**

The error is clearly displayed in my README.md test and screenshots [try.gogs.io/Tektite/MarkDownTests](https://try.gogs.io/Tektite/MarkDownTests)

**Expected behavior**

I expected the numbering behavior and rendering to be consistent with other markdown rendering platforms like *github* and *vscode*.

**Actual behavior**

Starting lines with out of sequence numbering is problematic, especially when the numbers have multiple digits.

1. For example, how can I Start the next line with "333." ?

333.  I want this line to start with "333." please

My markdown for the above is:

```markdown
1. For example, how can I Start the next line with "333." ?

333.  I want this line to start with "333." please
```

**Screenshots**

- Unexpected results with **gogs** 0.11.49.0521 and same in 0.13.0+dev
![Numbering_gogs](https://user-images.githubusercontent.com/14024430/141141608-23bcc2b7-b120-4c55-9860-129658c13afc.png)

- Unexpected results with **try.gogs.io** shown in a Raspberry Pi 4, Chromium browser
![Numbering_trygogs_rpi4chromium](https://user-images.githubusercontent.com/14024430/141141611-0507fe56-028c-4a77-9843-fa5196316bf6.png)

- Expected results with **github**
![Numbering_github](https://user-images.githubusercontent.com/14024430/141141617-70c1d643-f2b2-41e5-a819-056fe49367cb.png)

- Expected results with **vscode**
![Numbering_vscode](https://user-images.githubusercontent.com/14024430/141141615-1e124832-aa0d-4c67-906f-00574bf94599.png)

**Comment by ajstadlin** [comment]
Taking a second look, I notice the final rendering in my screenshots are all consistent between GOGS, GITHUB, and VSCODE. All fail to show the actual out of sequence numbers by forcing any line beginning with a number in the format `##.` to be part of a *sequence*. So, how do I do numbering like: "10." "20." "30." ?

I am closing this issue because it is not really a GOGS specific issue.

**Comment by unknwon** [comment]
<img src="https://media2.giphy.com/media/3ohhwyZkVgdhxIO58I/giphy.gif"/>

Is this even supported by Markdown? ... I really don't know...
