### ISSUE TITLE
为啥api里面没有获取所有仓库列表的接口

### ISSUE THREAD

**Issue by forgethub** [gogs/gogs#6649]
为啥api里面没有获取所有仓库列表的的接口，做devops 平台的时候，需要获取展示所有的仓库列表，我自己修改代码加了一个接口，请问可以merger 合并到官方的代码里面来吗

**Comment by unknwon** [comment]
Pull requests are welcome!

Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
