### ISSUE TITLE
a fatal exception when  migrate

### ISSUE THREAD

**Issue by oyjs78** [gogs/gogs#6653]
**Describe the bug**

**Gogs version and commit**

**Git version**

```
$ git version
2.25
```

**Operating system**

ubuntu20.04 or ubuntu18.04
**Database**

mysql5.7 or mysql8.0
**To Reproduce**
1. Go to 'user repo'
2. Click on 'migrate external private repo'
3. Input the url of repo ,  keep authentication user and password is null, modify the repo name
4. Scroll down to 'migrate' and click
5. See error
sometimes return error like cannot access ... ，is normal；sometimes no any response, on the time can find the server required input user name ，after input username， and enter ，appear gogs service auto exit，no access the gogs service again ... , is abnormal。

**Can you reproduce the bug at https://try.gogs.io?**

**Expected behavior**

Prompt user name or password error

**Actual behavior**

the service will be invalid，must kill the process and restart the service

**Screenshots**

**Additional context**

when error ，no log output

**Comment by oyjs78** [comment]
the service print info when  auto exiting ：
[1]+  Stopped                 ./gogs web

**Comment by unknwon** [comment]
Hey @oyjs78!

Are you able to provide some logs (usually in `log/gogs.log`)? Can't really help you much without logs.
