### ISSUE TITLE
How to solve the exit problem in the system prompt:failed to perform health check on repository xxx:exit status 2

### ISSUE THREAD

**Issue by jiaruihuang** [gogs/gogs#6654]
Application version 0.13.0+dev
Git version 2.24.4
Go version go1.14.7
Compile time 2021-05-19 07:16:50 UTC
Build commit ba8be9489e6d959fa9005fc7d38bf62562580d23

The above environments are deployed using docker

system prompt
Failed to perform health check on repository '/data/git/gogs-repositories/xxxxxxxx.git': exit status 2
How can I troubleshoot or solve the above problems
thanks

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
