### ISSUE TITLE
Organization Display Name

### ISSUE THREAD

**Issue by OdinVex** [gogs/gogs#6661]
I haven't seen an entry for a feature request to offer aliases/display names for Organizations. Instead of seeing "MyCompanyTeamLLC" I'd like to see "My Company Team" or such. Quite low priority.

**Comment by unknwon** [comment]
It is supported named **Organization Full Name**. Also please use issue template.

**Comment by OdinVex** [comment]
> It is supported named **Organization Full Name**. Also please use issue template.

Sorry about the Issue Template thing, exhausted and must've missed it. I didn't see an option for Organization Full Name until I started grepping source and found out the only way to find this is to use the cog-wheel/gear icon, barely noticed it.
