### ISSUE TITLE
[FATAL] [...g/setting/setting.go:591 NewContext()]

### ISSUE THREAD

**Issue by cuibaiyi** [gogs/gogs#6662]
centos 7.9
gogs version 0.11.91
git version 1.8.3.1

hello, 部署完gogs后，使用普通用户启动的服务，RUN_USER = app，在另外一台主机通过ssh访问gogs的主机（已经配置好私钥了，正常情况下是免密登录的），报错：2021/12/16 16:24:27 [FATAL] [...g/setting/setting.go:591 NewContext()] Expect user 'app' but current user is: root。

**Comment by cuibaiyi** [comment]
gogs version 0.11.91
git version 1.8.3.1

**Comment by unknwon** [comment]
Thank you for the feedback! However, I'm closing this thread according to the [issue template](https://github.com/gogs/gogs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by unknwon** [comment]
I think the error is pretty obvious... you're configured to run as "app" but in fact you're running as the "root".
