### ISSUE TITLE
Post-receive hook created on Windows stops working after migrated to CentOS

### ISSUE THREAD

**Issue by zsedcbm** [gogs/gogs#6691]
### Gogs version

 0.12.3

### Git version

- Server: 1.8.3.1
- Client: 2.23.0 windows.1

### Operating system

CentOS 7

### Database

MySQL 5.7

### Describe the bug

I first deployed gogs on the windows server, and later migrated to the CentOS server.

Project A was created on the windows server, and project B was created on the centOS server.

After the migration, I executed "re-synchronize pre-receive, update, post-receive hooks of all warehouses"

But it was found that the pre-receive/post-receive was not executed after the project A was submitted. After project B is submitted, the pre-receive/post-receive is executed successfully.

```
2021/12/24 17:18:43 [TRACE] Template: repo/home
2021/12/24 17:19:13 [TRACE] [Git] Authenticated user: wukon
2021/12/24 17:19:13 [TRACE] TriggerTask: wukon/test@test1 by "wukon"
2021/12/24 17:19:13 [TRACE] DeliverHooks [repo_id: 49]
2021/12/24 17:19:13 [TRACE] AddTestPullRequestTask [head_repo_id: 49, head_branch: test1]: finding pull requests
2021/12/24 17:19:13 [TRACE] AddTestPullRequestTask [base_repo_id: 49, base_branch: test1]: finding pull requests
2021/12/24 17:20:14 [TRACE] [Git] Authenticated user: wukon
2021/12/24 17:20:16 [TRACE] [Git] Authenticated user: wukon
```

In logs, project B submit has TriggerTask,DeliverHooks . But project A submit has nothing.

### To reproduce

first deployed gogs on the windows server, create projectA

migrated to the CentOS server. create projectB

### Expected behavior

project A hooks will be worked;

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey @zsedcbm!

Could you:

1. Post the content of post-receive hook you found for project A? Namely `<path to project A>/hooks/post-receive`.
2. Post the content of same hooks but for project B.
3. Post logs from `<path to Gogs binary>/log/hooks/post-receive.log`.

**Comment by zsedcbm** [comment]
@unknwon 

Just added a sentence of echo, one project has output, one has no output, it seems that it is not executed at all

```
#!/bin/sh
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo $oldrev $newrev $refname $branch >> /app/sgjd.md
    if [ "test_proj" = "$branch" ]; then
        # Do something
        cd /mnt/gitWorkSpace/sgjd
        git pull
        mvn package
    fi
done
```

Whether it is successful or unsuccessful, post-receive.log is always blank

I modified [log]level = Debug in app.ini, but there is still no log output

**Comment by unknwon** [comment]
@zsedcbm Thanks for the follow up, but I asked for three things, could you also post the other two? And which one you posted is the one in my requested bullet list?

**Comment by zsedcbm** [comment]
两个项目的 post-receive 内容一样，都只是在默认的脚本中加了一行echo

项目B 在post之后，gogs.log 日志里面有 TriggerTask，项目A在post之后，日志中没有 TriggerTask

不管是项目A（post-receive 没有执行）还是项目B（post-receive 执行成功），post-receive.log 这个日志文件一直是空白的，没有内容输出。

一开始gogs 部署在windows服务器，创建了项目A，后来迁移到centos

因为项目A的post-receive一直没有执行，所以建了测试项目B，写了post-receive。测试后，项目B能正常执行。

一开始自己发现了 /usr/local/gogs/repositories/group/projectA.git/hooks的 post-receive 文件路径是windows路径，发现错误后，参照projectB项目手动修改了，并重启了gogs，结果还是不行。

后来通过管理面板“重新同步所有仓库的pre-receive,update,post-receive钩子”，执行了之后，结果还是不行。

**Comment by unknwon** [comment]
@zsedcbm,

1. Are you sure that you're using 0.12.3? The `post-receive` hook you posted in https://github.com/gogs/gogs/issues/6691#issuecomment-1001149523 does not look like what you should have in 0.12, which is expected to have the following:
	```
	#!/usr/bin/env bash
	".../gogs" hook --config='.../custom/conf/app.ini' post-receive
	```
2. What evidences make you believe that the post-receive hook is working for your project B?
3. What are the permission bits of both `post-receive` hooks for project A and B? Usually you can get the permission bits by executing `ls -l <path to file>`.
4. What happens if you delete the existing post-receive hook for project A and do "re-synchronize pre-receive, update, post-receive hooks of all warehouses"?

**Comment by zsedcbm** [comment]
I found the problem. 
The file permissions of the migration from windows are
```
-rw-r--r-- 1 root root 108 December 30 13:58 post-receive
```
If you do not delete the old file, just do "re-synchronize pre-receive, update, post-receive hooks of all warehouses", the file permissions have not changed, delete the file and then regenerate, the new file permissions are
```
-rwxr-xr-x 1 root root 108 December 30 13:58 post-receive
```
Then the script executed successfully
