### ISSUE TITLE
error when making a pull request

### ISSUE THREAD

**Issue by HamelBarrer** [gogs/gogs#6702]
### Gogs version

0.12.3

### Git version

- Server: window
- Client: git version 2.32.0.windows.1

### Operating system

Windows 10

### Database

SQLite 3

### Describe the bug

The moment of wanting to generate a new pull request, gogs responded with a 404

### To reproduce

It is making a new pull request without any problem, but when I was generating it I pressed the back button of google chrome, when I wanted to go back again to generate the pull request, I started getting a 404 error.

### Expected behavior

create the pull request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey @HamelBarrer, I think "the back button of google chrome" may sends a GET request which does not always work on all URLs. I may be able to share more technical insights if you could share a GIF of some sort for reproduce.
