### ISSUE TITLE
Network jitter or manual refresh pages when migrating repos will cause migration failed

### ISSUE THREAD

**Issue by geek981108** [gogs/gogs#6715]
### Describe the feature

Network jitter or manual refresh pages when migrating repos will cause migration failed especially migrating heavy repos such as kubernetes. So async migration with migration notices sounds like a good idea to handle it.

### Describe the solution you'd like

Asynchronous migration with migration notices sounds like a good idea to handle it.

### Describe alternatives you've considered

It can be an optinal setting for user to use .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thanks for the feedback!

> Asynchronous migration with migration notices sounds like a good idea to handle it.

Could you expand more? For example, will/should/how the "asynchronous migration" will survive Gogs restarts? How are errors surfaced to users if the migration failed/succeed? How will users inspect the current migrations?

**Comment by geek981108** [comment]
> will/should/how the "asynchronous migration" will survive Gogs restarts? 
First of all, if the migration does survive during Gigs restart would be wonderful. But the solution I can just think of is push the migration task to "minor sync queue" using cron job even Gogs restarts it can be added and done automatically. In this situation I'm not sure is there a way to storage the repo's mirror address.
> How are errors surfaced to users if the migration failed/succeed?
In PR #6710, I use system notice to monitor migration progress. It can be a bad idea since there is no user notification module because only administrators can inspect it.
> How will users inspect the current migrations?
Perfect question! I'm not sure is there any way to monitor `git clone` progress. 

Best wishes!

**Comment by unknwon** [comment]
> > will/should/how the "asynchronous migration" will survive Gogs restarts?
> 
> First of all, if the migration does survive during Gogs restart would be wonderful. But the solution I can just think of is push the migration task to "minor sync queue" using cron job, so even Gogs restarts it can be added and done automatically. In this situation I'm not sure is there a way to storage the repo's mirror address.

We need to nail down a lot more details than this.

At the very least, IMO we need a separate table serve the purpose as the mirror task queue, and an additional column `state` to the `repos` table to indicate the current state, for mirror repositories, the value of `state` could be something simple like "cloning", "cloned". On top of that, UI needs to show users what's the current state of the mirroring, if something went wrong, then display what was the error. On restarts, Gogs needs to pick up unfinished mirror tasks from the mirror task queue table.

In terms of notifications, I'd against using system notice as by its name, that's for system problems meant to be only seen by admins. For regular users, I think UI is the best place to show the error, or if succeed, displaying the repository content is good enough for saying "everything went well".

To support all this, we need to design and code background workers.

**Comment by geek981108** [comment]
Thanks for reply. That's truly a complex work to do. Will it be a break change to users who is using Gogs?
BTW, it's very annoy when migrating repos occurs network jitter.

**Comment by unknwon** [comment]
> Thanks for reply. That's truly a complex work to do.

Yes, it's complex to do it right, that's part of the reason why this hasn't been done yet 😂 

> Will it be a break change to users who is using Gogs?

How is it going to be a break change? I don't think so.

> BTW, it's very annoy when migrating repos occurs network jitter.

That's true indeed.

**Comment by geek981108** [comment]
Got it, I'll try! Thanks for providing such an amazing project

**Comment by geek981108** [comment]
Thanks for advise, I’ll check!
Thanks again.

**Comment by unknwon** [comment]
This is essentially asking the same thing as https://github.com/gogs/gogs/issues/829, thus closing this one.

**Comment by unknwon** [comment]
In case you're still interested in hearing about proposal itself, here is my blog post: https://unknwon.io/posts/220210-write-a-proposal-for-open-source-contributions/

**Comment by geek981108** [comment]
So much thanks for the article!
I found myself a real buster in article writing. The article helps me for how to do meaningful contribution in the open sourse world.
I will understand the text carefully and put it into practice.
Thanks again！
2022年2月10日 +0800 20:07 Joe Chen ***@***.***>，写道：
