### ISSUE TITLE
和并请求页面自动显示所有我创建的仓库对应的和并请求

### ISSUE THREAD

**Issue by mbossX** [gogs/gogs#6720]
### Describe the feature

目前版本 合并请求页面需要选择账户、组织等来筛选，当我创建多个组织时，比如有 A、B、C三个组织，加上我自己账户，共四个，都需要一个个选中筛选，不是很方便。
在部分公司里头，git作为源代码管理工具，很多时候多个项目会集中在某个管理人员的账号里面做最后的备份合并，我这边就是这种情况。现在的版本每次筛选合并不方便。

### Describe the solution you'd like

增加一个选项，可以显示当前账号下面所有由此账号创建的仓库对应的和并请求，不管是我自己账号下的还是我其他某个组织里面创建的，只要是我这个登录账号创建的，都显示出来，方便快速合并。

### Describe alternatives you've considered

无

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, please update the issue description using English so others can understand :)
