### ISSUE TITLE
邮件无法发送

### ISSUE THREAD

**Issue by AsherHuu** [gogs/gogs#6738]
### Gogs version

 0.13.0+dev

### Git version

- Server: 
- Client: 
2.32.0

### Operating system

centos 7.6

### Database

sqlite3

### Describe the bug

邮件功能其用不了，用的docker容器运行的
![image](https://user-images.githubusercontent.com/32830348/150138342-e2385e07-f7e5-45cb-bcc1-1d9e2385bd54.png)

BRAND_NAME = Gogs
RUN_USER   = git
RUN_MODE   = prod

[database]
TYPE     = sqlite3
HOST     = 127.0.0.1:5432
NAME     = gogs
SCHEMA   = public
USER     = gogs
PASSWORD = 
SSL_MODE = disable
PATH     = data/gogs.db

[repository]
ROOT = /data/git/gogs-repositories

[server]
DOMAIN           = localhost
HTTP_PORT        = 3000
EXTERNAL_URL     = http://localhost:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = false
OFFLINE_MODE     = false

[mailer]
ENABLED = true
HOST    = smtp.exmail.qq.com:465
FROM    = 1111@qq.com
USER    = 111111@qq.com
PASSWD  = 123456

[auth]
REQUIRE_EMAIL_CONFIRMATION  = true
DISABLE_REGISTRATION        = true
ENABLE_REGISTRATION_CAPTCHA = false
REQUIRE_SIGNIN_VIEW         = false

[user]
ENABLE_EMAIL_NOTIFICATION = true

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /app/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = wEq2UVV3OSrgxqu

### To reproduce

install 页面时候配置邮件发送信息

### Expected behavior

正常发送邮件

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Please use English :) I'll re-open once it's done.
