### ISSUE TITLE
0.12.4: Unable to start on lower GLIBC version with precompiled binary

### ISSUE THREAD

**Issue by shu7734** [gogs/gogs#6752]
### Gogs version

0.12.4

### Git version

- Server:CenOS 7.9 
- Client: 

### Operating system

CenOS 7.9

### Database

SQLite 3

### Describe the bug

在服务器上运行时
- ./gogs --help
./gogs: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./gogs)

操作系统默认的Glibc版本是2.17，
操作系统的libc不能随意替换，会导致所有命令无法执行，且无法开机。
所以希望已编译的版本能在低版本的操作系统下编译，才能不需要升级Libc
谢谢！

### To reproduce

无法运行

### Expected behavior

在低版本服务器上编译并发布下载会比较好

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yunemr** [comment]
哈哈，我也是，升级要改的太多。退回旧版。

**Comment by daty2141** [comment]
我也是，之前有过升级glibc导致系统无法启动的经历，现在不敢升glibc了，希望有基于glibc 2.17的gogs

**Comment by unknwon** [comment]
Thanks for the feedback! I'll look into compiling binaries using Ubuntu 16.04.

**Comment by unknwon** [comment]
It turns out even Ubuntu 16.04 has `ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23`.

Looks like CentOS 7 is the way to go, which has `ldd (GNU libc) 2.17`.

**Comment by daty2141** [comment]
i have build it on RedHat 7 which has **ldd (GNU libc) 2.17** and it works fine.thank you

**Comment by unknwon** [comment]
I've uploaded new release archives for Linux amd64 with GLIBC 2.17. Please check out!
