### ISSUE TITLE
Migration API Endpoint gives 404

### ISSUE THREAD

**Issue by JasonRivers** [gogs/gogs#6766]
### Gogs version

0.12.3

### Git version

- Server: 2.32.0
- Client: 

### Operating system

Ubuntu 20.04 / Docker

### Database

MariaDB-10.3.13

### Describe the bug

Sending data to the endpoint /repos/migrate as POST as per the api repository documentation[https://github.com/gogs/docs-api/tree/master/Repositories#migrate]( https://github.com/gogs/docs-api/tree/master/Repositories#migrate)  responds with a 404 not found.

### To reproduce

Send post to gogs:/api/v1/repos/migrate

### Expected behavior

Creating a migration repository and response as per the documentation [https://github.com/gogs/docs-api/tree/master/Repositories#migrate](https://github.com/gogs/docs-api/tree/master/Repositories#migrate)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, can you:

1. Post the exact payload you used?
2. Is any other API endpoints working in your installation?
