### ISSUE TITLE
何时能上线tag保护功能，等了2年了！

### ISSUE THREAD

**Issue by imxiangli** [gogs/gogs#6767]
### Describe the feature

标签保护

### Describe the solution you'd like

标签保护功能对于正规的研发团队很有用，现在没有这个功能，非常不便。

### Describe alternatives you've considered

标签保护

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, please update the issue description using English so others can understand :) You may use [DeepL](https://www.deepl.com/en/translator) to get help with translations.

I'll re-open once it's been done, thank you!
