### ISSUE TITLE
timeout registering users - gogs docker

### ISSUE THREAD

**Issue by ehehdada** [gogs/gogs#6772]
### Gogs version

0.13.0+dev (docker lastest)

### Git version

- Server: 2.32.0
- Client: 2.24.1

### Operating system

docker gogs/gogs latest

### Database

MariaDB 10.6.5 (also docker mariadb latest)

### Describe the bug

gogs is running in a docker container behind a proxy, email has been disabled

I get http/504 from the gateway, timeout on
1. user registration
2. new issue with user assigned
3. commenting an issue referencing a user

I saw this in the logs
bash-5.1# cat /app/gogs/log/gogs.log
2022/02/16 07:14:03 [ INFO] Gogs 0.13.0+dev
2022/02/16 07:14:03 [ INFO] Run mode: Production
2022/02/16 07:14:04 [ INFO] Listen on http://0.0.0.0:3000
2022/02/16 07:20:49 [ INFO] Gogs 0.13.0+dev
2022/02/16 07:20:49 [ INFO] Run mode: Production
2022/02/16 07:20:49 [ INFO] Listen on http://0.0.0.0:3000
2022/02/16 07:32:36 [ INFO] Gogs 0.13.0+dev
2022/02/16 07:32:37 [ INFO] Run mode: Production
2022/02/16 07:32:37 [ INFO] Listen on http://0.0.0.0:3000
2022/02/16 09:27:36 [ERROR] [...ogs/internal/route/repo/issue.go:586 viewIssue()] mark read by: Error 1205: Lock wait timeout exceeded; try restarting transaction
2022/02/16 09:29:52 [ERROR] [...ogs/internal/route/repo/issue.go:586 viewIssue()] mark read by: Error 1205: Lock wait timeout exceeded; try restarting transaction
2022/02/16 09:31:06 [ERROR] [...ogs/internal/route/repo/issue.go:586 viewIssue()] mark read by: Error 1205: Lock wait timeout exceeded; try restarting transaction
2022/02/16 09:32:19 [ERROR] [...io/gogs/internal/context/auth.go:154 authenticatedUserID()] Failed to get user by ID: dial tcp 172.18.0.3:3306: connect: connection refused
2022/02/16 09:32:19 [ERROR] [...io/gogs/internal/context/auth.go:154 authenticatedUserID()] Failed to get user by ID: dial tcp 172.18.0.3:3306: connect: connection refused
2022/02/16 09:32:19 [ERROR] [...gogs/internal/route/user/auth.go:83 Login()] auto login: get user by name: dial tcp 172.18.0.3:3306: connect: connection refused
2022/02/16 11:19:40 [ INFO] Gogs 0.13.0+dev
2022/02/16 11:19:40 [ INFO] Run mode: Production
2022/02/16 11:19:41 [ INFO] Listen on http://0.0.0.0:3000

### To reproduce

the docker containers were created with these commands

sudo docker network create -d bridge scm_nw
sudo docker run -d --restart=always --name=scm.lucentinian.com --network=scm_nw \
  -p 3000:3000 -p 3022:22  -v /var/overmind_data/gogs:/data:rw gogs/gogs
sudo docker run \
  --name mariadb_scm.lucentinian.com \
  -d --restart=always \
  --network=scm_nw \
  --env MARIADB_USER=gogs --env MARIADB_PASSWORD=gogs \
  --env MARIADB_ROOT_PASSWORD=xxx \
  -v /var/overmind_data/mariadb:/var/lib/mysql \
  mariadb \
  --character-set-server=utf8  --collation-server=utf8_general_ci

then, after configuration, attempt to register a user using the webpage of this gogs instance, or create an issue assigning a user, or comment an issue referencing a user

### Expected behavior

1. the page that indicates the user has been registered
2. the created issue
3. the issue with the new comment

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ehehdada** [comment]
I've removed the installation with sudo docker rm -f scm.lucentinian.com and installed the gogs/gogs:0.12.4 version and runs not only as expected but also faster, and I have configured the email server and I can even get emails now

**Comment by unknwon** [comment]
```
2022/02/16 09:27:36 [ERROR] [...ogs/internal/route/repo/issue.go:586 viewIssue()] mark read by: Error 1205: Lock wait timeout exceeded; try restarting transaction
2022/02/16 09:29:52 [ERROR] [...ogs/internal/route/repo/issue.go:586 viewIssue()] mark read by: Error 1205: Lock wait timeout exceeded; try restarting transaction
2022/02/16 09:31:06 [ERROR] [...ogs/internal/route/repo/issue.go:586 viewIssue()] mark read by: Error 1205: Lock wait timeout exceeded; try restarting transaction
2022/02/16 09:32:19 [ERROR] [...io/gogs/internal/context/auth.go:154 authenticatedUserID()] Failed to get user by ID: dial tcp 172.18.0.3:3306: connect: connection refused
2022/02/16 09:32:19 [ERROR] [...io/gogs/internal/context/auth.go:154 authenticatedUserID()] Failed to get user by ID: dial tcp 172.18.0.3:3306: connect: connection refused
2022/02/16 09:32:19 [ERROR] [...gogs/internal/route/user/auth.go:83 Login()] auto login: get user by name: dial tcp 172.18.0.3:3306: connect: connection refused
```

These logs are telling me the DB is in a very ill state, no wonder why any application would hang.

I'm closing the issue since you've solve in other ways. Let me know if you wanna further discussion on this issue.
