### ISSUE TITLE
/repos/search?q="repos_name" 查询仓库的时BUG

### ISSUE THREAD

**Issue by forgethub** [gogs/gogs#6773]
### Gogs version

0.12.3

### Git version

- Server: 
- Client: 

### Operating system

centos7

### Database

mysql5.7

### Describe the bug

/repos/search?q="repos_name" 搜索仓库的接口，当仓库是fork其他项目生成的时，
![有问题的代码](https://user-images.githubusercontent.com/28828118/154647892-9ad153c8-7b71-4222-8b90-601159a7ed1f.png)
直接报错退出了，没有执行后续的代码

### To reproduce

等我解决后提交个PR

### Expected behavior

空

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, please update the issue description using English so others can understand :) You may use [DeepL](https://www.deepl.com/en/translator) to get help with translations.

I'll re-open once it's been done, thank you!
