### ISSUE TITLE
Improper PAM authorization handling

### ISSUE THREAD

**Issue by ysf** [gogs/gogs#6810]
### Gogs version

<= 0.13

### Git version

N/A

### Operating system

Archlinux

### Database

n/a

### Describe the bug

The security policy states not disclosing anything. So here is the report on huntr.dev it is only viewable to people with write access to this repository, an me: https://huntr.dev/bounties/ea82cfc9-b55c-41fe-ae58-0d0e0bd7ab62/

### To reproduce

See report

### Expected behavior

See report

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Approved on huntr.dev, thank you!

**Comment by unknwon** [comment]
@ysf You already included a potential fix in the report, do you wanna do a PR or do you prefer me to investigate? (former is faster).

**Comment by ysf** [comment]
The idea was that you can look of the patch suits you. If so, I'll push it to a branch. Regular it's not possible to pick up the other bounty.

I'll create a PR asap.

**Comment by ysf** [comment]
There it is. Sry for my github inconvenience.

**Comment by unknwon** [comment]
The 0.12.5 has been released that includes the patch of the reported issue.
