### ISSUE TITLE
A TPL BUG

### ISSUE THREAD

**Issue by bqf9979** [gogs/gogs#6824]
### Gogs version

gogs:master

### Git version

- Server: 
- Client: lastest

### Operating system

ubuntu

### Database

mysql8.0

### Describe the bug

template: repo/settings/options:43:65: executing "repo/settings/options" at <.Repository.IsUnlisted>: can't evaluate field IsUnlisted in type interface {}

### To reproduce

template: repo/settings/options:43:65: executing "repo/settings/options" at <.Repository.IsUnlisted>: can't evaluate field IsUnlisted in type interface {}

### Expected behavior

template: repo/settings/options:43:65: executing "repo/settings/options" at <.Repository.IsUnlisted>: can't evaluate field IsUnlisted in type interface {}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, there is no `master` in this repository :)
