### ISSUE TITLE
Remote command execution in file uploading

### ISSUE THREAD

**Issue by wuhan005** [gogs/gogs#6833]
### Gogs version

<=0.12.5

### Git version

N/A

### Operating system

macOS 12.1

### Database

N/A

### Describe the bug

A remote command execution vulnerability exists in Gogs that could allow a malicious user to execute any command on the remote server and gain the privileged user account.

Here is the report on huntr.dev https://huntr.dev/bounties/b4928cfe-4110-462f-a180-6d5673797902

### To reproduce

See report on huntr.dev

### Expected behavior

See report on huntr.dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey @JamieSlome, @wuhan005 made this report prior to I invited him to be part of the organization. Now he has been recognized as a maintainer on the huntr.dev and I couldn't hit the "Confirm Fix" button and get

<img width="574" alt="image" src="https://user-images.githubusercontent.com/2946214/159113305-4a10bd55-83ce-4d63-977b-9d46952a856c.png">

Could you help us here? Thanks!

**Comment by JamieSlome** [comment]
@unknwon - got an alarm on my side too 👍 

I have removed @wuhan005 as a maintainer from your repository on our platform, so you should be able to go ahead and re-confirm the fix. Please allow 15 minutes for our cache to update before you do this.

@unknwon - I assume that @wuhan005 is no longer a "maintainer"/"contribution" to the organization? If so, we will need to create a ticket here to address this unique situation.

**Comment by unknwon** [comment]
@JamieSlome Thanks for a fast response! Appreciated ❤️ 



> @unknwon - I assume that @wuhan005 is no longer a "maintainer"/"contributor" to the organization? If they are, we will need to create a ticket here to address this unique situation.

@wuhan005 is temporarily leaving the organization, and will be added back once both the huntr.dev report and GitHub Advisory are published.

**Comment by JamieSlome** [comment]
@unknwon - thanks for the info 😄
