### ISSUE TITLE
Use Go embed to replace go-bindata and drop Go 1.15 support

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#6846]
- [x] Delete Go 1.15 from CI and add Go 1.18
- [x] Update `go:build` and `+build` tags
- [x] Update Go version requirement in [local development guide](https://github.com/gogs/gogs/blob/main/docs/dev/local_development.md#step-1-install-dependencies) and [official website](https://gogs.io/docs/installation/install_from_source)
- [x] Convert usage of go-bindata to Go embed

**Comment by alimy** [comment]
~ How about #6851 PR, Welcome optimize this PR or re-commit another better PR for support go:embed ~

**Comment by unknwon** [comment]
> ~ How about #6851 PR, Welcome optimize this PR or re-commit another better PR for support go:embed ~

@alimy Thanks! Will take a look :)
