### ISSUE TITLE
Can't evaluate field IsUnlisted in type *db.Repository

### ISSUE THREAD

**Issue by jianboy** [gogs/gogs#6868]
### Gogs version

0.12.6

### Git version

- Server: 
- Client: 
git version 2.22.0

### Operating system

Centos

### Database

sqlite3

### Describe the bug

template: explore/repo_list:13:16: executing "explore/repo_list" at <.IsUnlisted>: can't evaluate field IsUnlisted in type *db.Repository

### To reproduce

update gogs from v0.12.3 to 0.12.6.

IsUnlisted the field lost.

### Expected behavior

template: explore/repo_list:13:16: executing "explore/repo_list" at <.IsUnlisted>: can't evaluate field IsUnlisted in type *db.Repository

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, [`IsUnlisted` is not in the `release/0.12` branch at all](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/gogs/gogs%24%40release/0.12+IsUnlisted&patternType=literal).

1. Where or how did you get your Gogs binary?
2. Where and how to reproduce this error?

**Comment by jianboy** [comment]
> Hey, [`IsUnlisted` is not in the `release/0.12` branch at all](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/gogs/gogs%24%40release/0.12+IsUnlisted&patternType=literal).
> 
> 1. Where or how did you get your Gogs binary?
> 2. Where and how to reproduce this error?

I have checkout master branch source . Thanks,
