### ISSUE TITLE
There is no need to request an external api to set the avatar imgage

### ISSUE THREAD

**Issue by cluyun** [gogs/gogs#6871]
### Gogs version

Application version 0.12.3 Git version 2.23.0 Go version go1.15 Build time 2020-10-07 03:03:48 UTC

### Git version

Application version
0.12.3
Git version
2.23.0
Go version
go1.15
Build time
2020-10-07 03:03:48 UTC

Build commit:f0e3cd90f8d7695960eeef2e4e54b2e717302f6c 

### Operating system

redhat 7

### Database

MySQL8

### Describe the bug

 Out of time ：https://secure.gravatar.com/avatar/xxxxx

### To reproduce

Server has no network，Do not set custom avatar image

### Expected behavior

Fast running speed

### Additional context

There is no need to request an external api !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
You can turn on offline mode:

https://github.com/gogs/gogs/blob/3c49a6173d9cdf339f4a27d427a4cfc3dd51a24f/conf/app.ini#L43-L44
