### ISSUE TITLE
method GetBySHA need both uid and SHA.

### ISSUE THREAD

**Issue by kvii** [gogs/gogs#6889]
### Gogs version

0.13.0+dev

### Git version

- Server: 2.25.1
- Client: 2.25.1

### Operating system

Ubuntu 20.04.4 LTS

### Database

MySQL 8.0.26

### Describe the bug

[AccessTokensStore.GetBySHA](https://github.com/gogs/gogs/blob/main/internal/db/access_tokens.go#L138) has only one parameter called sha.
But the AccessToken need both uid and sha to locate the unique row.
If someone have a valid token. Then he can use this token to access all user's private repo.

### To reproduce

1. Create an Access Token "token1" for user1 at your.gogs.com/user/settings/applications.
2. Use token1 and user2 to access user2's private content.

### Expected behavior

change the method signature from 
``` go
GetBySHA(sha string) (*AccessToken, error)
```
to
``` go
GetBySHA(uid uint, sha string) (*AccessToken, error)
```

### Additional context

I don't know why gogs use username as token at [here](https://github.com/gogs/gogs/blob/main/internal/route/repo/http.go#L134)

I have a ~/.netrc file as below.
```
machine your.gogs.com login USERNAME password API_KEY
```

So when I download a go dependency from private repo.
Git will add the base64 encrypted `USERNAME:API_KEY` to Authorization header.
And then failed.
‘Cause gogs try to use USERNAME as token, not API_KEY.
I'm not sure if this is a bug. But there must be something wrong with function GetBySHA.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
> [AccessTokensStore.GetBySHA](https://github.com/gogs/gogs/blob/main/internal/db/access_tokens.go?rgh-link-date=2022-04-03T09%3A19%3A56Z#L138) has only one parameter called sha.
> But the AccessToken need both uid and sha to locate the unique row.
> If someone have a valid token. Then he can use this token to access all user's private repo.

Access token itself is the equivalent powerful credentials as the combination of username+password. So there is no additional security benefit of checking the uid again IMO. In other words, it is by design.



> So when I download a go dependency from private repo.
> Git will add the base64 encrypted `USERNAME:API_KEY` to Authorization header.
> And then failed.
> ‘Cause gogs try to use USERNAME as token, not API_KEY.
> I'm not sure if this is a bug. But there must be something wrong with function GetBySHA.

This was a bad design decision in very old days 😅 but I think it is unrelated to the topic we're discussing in this issue.
