### ISSUE TITLE
" " is not a valid URL

### ISSUE THREAD

**Issue by Demonlinx** [gogs/gogs#6907]
### Gogs version

0.12.6

### Git version

- Server: 2.25.1
- Client: 2.25.1

### Operating system

Ubuntu 20.04.1 LTS

### Database

SQLite 3

### Describe the bug

I have a main gogs running that is hosting a number of repositories. I am working on setting up a second gogs that is going to mirror a number of repo's to our second location. However I get an error: " is not a valid URL."

I can do a git clone of that specific repository on a given client machine.

### To reproduce

![image](https://user-images.githubusercontent.com/14986844/163055582-d37bfff4-05be-46f3-b511-916371aa5115.png)

Clone address: https://gogs.domain.com/org/repo.git

put in the appropriate user credentials, click mirror migration type and click migrate repository. 

### Expected behavior

I would expect the repo to be migrated and mirrored onto the new gogs installation.

### Additional context

[12/Apr/2022:14:14:55 -0700] "POST /repo/migrate HTTP/1.1" 200 3668 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"

This is what I see in the apache log files. There are nothing in gogs logs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinsgithub** [comment]
Same situation as @Demonlinx with the only difference I use Gogs docker image.
Going backwards I confirm that the last working release on this feature is gogs/gogs:0.12.4.

**Comment by unknwon** [comment]
Hey, thanks for the feedback!

Does the URL happen to be resolved to a local/private network address? It is disallowed due to security concerns (SSRF) since 0.12.5, see also https://github.com/gogs/gogs/issues/6841.

To allow specific local network address, you can use the config option `[security] LOCAL_NETWORK_ALLOWLIST`:

```ini
[security]
LOCAL_NETWORK_ALLOWLIST = <specific network address, separated by commas>
```

**Comment by vinsgithub** [comment]
Hi @unknwon , actually I'm behind a http proxy that allows me to connect to my internet facing https git service.
Should I need to set 
LOCAL_NETWORK_ALLOWLIST = <mypublic_git>
or
LOCAL_NETWORK_ALLOWLIST = <myproxy:myproxyport>
because I'm behind a proxy? (I haven't tried it yet with latest gogs version)

**Comment by unknwon** [comment]
> Hi @unknwon , actually I'm behind a http proxy that allows me to connect to my internet facing https git service. Should I need to set `LOCAL_NETWORK_ALLOWLIST = <mypublic_git>` or `LOCAL_NETWORK_ALLOWLIST = <myproxy:myproxyport>` because I'm behind a proxy? (I haven't tried it yet with latest gogs version)

@vinsgithub I think it should be your proxy (`<myproxy>`, no port).

**Comment by vinsgithub** [comment]
@unknwon I confirm that gogs/gogs:0.12.6 setting LOCAL_NETWORK_ALLOWLIST = <IPPROXY>
(I'm sure it has been loaded because it is showed under /admin/config panel) 
I get same result: "not a valid URL".
Rolling back to gogs/gogs:0.12.4 same URL works.

**Comment by unknwon** [comment]
> @unknwon I confirm that gogs/gogs:0.12.6 setting LOCAL_NETWORK_ALLOWLIST = < IPPROXY > (I'm sure it has been loaded because it is showed under /admin/config panel) I get same result: "not a valid URL". Rolling back to gogs/gogs:0.12.4 same URL works.

@vinsgithub Thanks for the followup! I'll try to improve the error message to help diagnosis and find out which network address should be used for `LOCAL_NETWORK_ALLOWLIST`.

**Comment by unknwon** [comment]
> > @unknwon To allow specific local network address, you can use the config option [security] LOCAL_NETWORK_ALLOWLIST:
> > [security] LOCAL_NETWORK_ALLOWLIST = <specific network address, separated by commas>
> 
> Is this necessary on both machines or just the "client" gogs?

Just the "client" Gogs.
