### ISSUE TITLE
update local_development install go-task

### ISSUE THREAD

**Issue by jonatan5524** [gogs/gogs#6909]
### What needs to be improved? Please describe

In the local_development instructions it is told to install go-task with go get:
https://github.com/gogs/gogs/blob/e5350b9627736a8a859f202d3035657d76de55b7/docs/dev/local_development.md?plain=1#L77
this doesn't work.
This method works for me:
```go
 go install github.com/go-task/task/v3/cmd/task@latest
```

It's also preferred to install binary modules in go using go install.

### Why do you think it is important?

For easy setup of the local development for new contributors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonatan5524** [comment]
I am new to this repo, I would like to work on it if it is possible.

**Comment by unknwon** [comment]
Thanks for the feedback! I've created a PR to adopt your solution in https://github.com/gogs/gogs/pull/6972.
