### ISSUE TITLE
b739dca8b0ad   gogs/gogs       "/app/gogs/docker/st…"   5 minutes ago   Up 3 minutes (unhealthy) 

### ISSUE THREAD

**Issue by CXW0504** [gogs/gogs#6923]
### Gogs version

docker 

### Git version

- Server: 
- Client: 
docker

### Operating system

ubuntu docker

### Database

silte3

### Describe the bug

docker restart container 就访问不了

### To reproduce

docker restart 

### Expected behavior

正常启动

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Please enrich your issue description for us being helpful.
