### ISSUE TITLE
user_id in gogs.action should be indexed

### ISSUE THREAD

**Issue by qzivli** [gogs/gogs#6932]
https://github.com/gogs/gogs/blob/e51e01683408e10b3dcd2ace65e259ca7f0fd61b/internal/db/action.go#L73

I got lots of slow queries like:

```sql
SELECT `id`, `user_id`, `op_type`, `act_user_id`, `act_user_name`, `repo_id`, `repo_user_name`, `repo_name`, `ref_name`, `is_private`, `content`, `created_unix` FROM `action` WHERE (user_id = 15) ORDER BY `id` DESC LIMIT 20;
```

while the rows of action table is more than 4000000

**Comment by unknwon** [comment]
Hey, the index is added since https://github.com/gogs/gogs/commit/083c3ee659c6c5542687f3bafae68cbc24dbc90f#diff-1fecab9c19a192d887e230f4da0560b9be337aac984b459110cc4319d3b07e3a, please pull the latest to try out!
