### ISSUE TITLE
authentication via identity providers

### ISSUE THREAD

**Issue by zfrhv** [gogs/gogs#6944]
### Describe the feature

sorry if i make any mistakes, im not a professional at authentication.

Instead of configuring kerberos, or any other complicated authentication methods, add option to authenticate with additional identity provider such as keycloak or dex.

### Describe the solution you'd like

the external identity provider will manage the users, and gogs will just have the option to login with those IDPs.

this is very useful especially if the organization already has some user management tool, and then installs gogs.

### Describe alternatives you've considered

gogs will supposed many authentication methods by itself, but its a lot of work and efforts when you can simply use other application that manages the users for you.

### Additional context

sorry if any similar issue was already opened before, i didnt found similar request. (or maybe i dont understand the subject enough)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, which authentication protocol you're referring to?

- The issue for OAuth 2: https://github.com/gogs/gogs/issues/4602
- The issue for SAML: https://github.com/gogs/gogs/issues/1221
- The issue for CAS: https://github.com/gogs/gogs/issues/2060

**Comment by zfrhv** [comment]
yep, its OAuth2 and OpenID Connect(OIDC)


im closing because case for oauth 2 is already open
