### ISSUE TITLE
The web page format is chaotic, and Google browser developer mode shows semantic-2.4.2 min.css failed

### ISSUE THREAD

**Issue by cuibaiyi** [gogs/gogs#6958]
### Gogs version

"0.12.6"

### Git version

- Server: 1.8.3.1
- Client: 1.8.3.1

### Operating system

"CentOS 7"

### Database

aliyun-RDS-5.7

### Describe the bug

Google browser developer mode display semantic-2.4.2.min.css status failed net::ERR_INCOMPLET_CHUNKED_...,But I think the public directory generated by the gogs program is semantic-2.3.1 min.css

### To reproduce

Google browser page access will be garbled

### Expected behavior

Google browser page access is normal

### Additional context

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/26649998/169450490-cab6caac-baca-4990-b9bf-e8dd00adeb31.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/26649998/169450512-50a0bf72-c4e8-4a37-81fe-5750582096ce.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey! I think you have outdated "templates" directory because the `templates/base/head.tmpl` file on the `release/0.12` branch also points to "semantic-2.4.2`:

https://github.com/gogs/gogs/blob/release/0.12/templates/base/head.tmpl#L62
