### ISSUE TITLE
No files shown in repository after uploading an existing repository

### ISSUE THREAD

**Issue by hamishmb** [gogs/gogs#6971]
### Gogs version

0.12.3

### Git version

- Server: 2.25.1
- Client: 2.25.1

(Both are running the same OS: Linux Mint 20.3)

### Operating system

Linux Mint 20.3

### Database

SQLite 3

### Describe the bug

Seems to be the same as this bug: https://github.com/gogs/gogs/issues/3697

Step 1: create git repository with gogs web interface
Step 2: add git repository as remote to local repository with SSH
Step 3: push changes to remote origin

Result: After upload is finished (~100MB) no Browse is shown, only the description of how to clone the repository.

### To reproduce

I don't know how to reproduce this - on the second try after deleting and recreating the repo with the same name, it worked fine.

### Expected behavior

Expectation: After finished upload, the Browse option should be possible and the files visible within the web interface

### Additional context

I know this is an older version of GOGS, but I couldn't find any other issues about this, so to the best of my knowledge this doesn't seem to have been fixed.

I'm unsure if there's anything sensitive in the gogs.log file. The repositories on this machine are private, so I am reluctant to upload without more information about what's in the log.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey!

> Step 1: create git repository with gogs web interface

Just to confirm, did you create an empty repository?

> Step 2: add git repository as remote to local repository with SSH

What is the remote URL looks like? And did you use the one copied from the web UI?

It is common with incorrect SSH URL would make push did not call Gogs's callback which updates the repository state.

**Comment by hamishmb** [comment]
Hi there.

Yes, I created an empty repository (didn't initialise with README or LICENSE files during creation).

The URL in the web UI is a http://localhost:3000/hamishmb/<reponame> format, but as I pushed from a different machine I had to use http://192.168.10.212:3000/hamishmb/<reponame>. I can provide the exact names if you want.

I used the history feature of my terminal to run exactly the same commands the second time, so I know that there were no differences between runs (I checked that no other repos had appeared after it behaved oddly the first time I tried pushing the files).

Cheers,
Hamish

**Comment by unknwon** [comment]
>Step 2: add git repository as remote to local repository with SSH

"http://192.168.10.212:3000/hamishmb/" is an HTTP URL not SSH, I'm a bit confused on what the "step 2" means now 🤔 

---

Workaround is just to create the repository with something.

**Comment by hamishmb** [comment]
My bad, I use http for this server, not ssh.

**Comment by unknwon** [comment]
No worries!

Could you try running the following action in the `/admin`

<img width="867" alt="CleanShot 2022-06-04 at 16 15 11@2x" src="https://user-images.githubusercontent.com/2946214/171990996-aeb768d9-7de9-496e-b7f9-0032623755da.png">

Then do a new push?

**Comment by hamishmb** [comment]
Would that be useful, now the repo is working? It only did this once, and it then worked on the second try after deleting and recreating the repo.

**Comment by unknwon** [comment]
> It only did this once, and it then worked on the second try after deleting and recreating the repo.

Could you speak with more context? what is "this", "it", and second try of "what"?

**Comment by hamishmb** [comment]
Okay, fair enough.

I only saw the bug in the bug description a single time - it didn't happen after deleting the repo and trying to push the same files to it again. Knowing this, would it still be useful for me to try that action?

I'm happy to create new repos and push the same files over and over try to try reproduce the problem, and then try the action, if that might help?

**Comment by unknwon** [comment]
> I only saw the bug in the bug description a single time - it didn't happen after deleting the repo and trying to push the same files to it again. Knowing this, would it still be useful for me to try that action?

Hmm, I don't understand this... how could you continue to push files after deleting the repo you're trying to push to?

**Comment by hamishmb** [comment]
I deleted it and then recreated it.

**Comment by unknwon** [comment]
> I deleted it and then recreated it.

Ah gotcha! Yeah, in that case, it sounds like it was just something went wrong unexpected for a single time. The recreation of the repository is effectively the "re-sync hooks" action for that single repository, no need to do that anymore.

**Comment by hamishmb** [comment]
I'm not sure this should be closed - I didn't create it to fox my problem, as I'd already done that. I wanted to figure out why it happened so it can be fixed, as I couldn't find any other issues about it that seemed to result in a fix.

**Comment by unknwon** [comment]
Judging by the symptom, it is a known configuration issue for push/pull through SSH, this is the first time seeing on HTTP push/pull. If this issue happens again and is fixed by performing the action suggested in https://github.com/gogs/gogs/issues/6971#issuecomment-1146565666, I think this issue is also configuration-related or ephemeral to the deployed environment.

If the suggested action does not fix it the next time you encountered this issue, we can revisit this issue and discuss further.

**Comment by hamishmb** [comment]
Okay, but what is the configuration issue? At some point I probably will be using SSH, so it would be good to know.

**Comment by unknwon** [comment]
Most often one is https://github.com/gogs/gogs/issues/1703#issuecomment-221878307

**Comment by hamishmb** [comment]
I've decided to decommission my GOGS instance - I won't be able to provide any further information on this bug.

Thanks for all the great work on GOGS. It's full featured enough for many uses, and lightweight enough to run on a Raspberry Pi 1, and it has served me well.
