### ISSUE TITLE
Gogs is slow

### ISSUE THREAD

**Issue by mooleshacat** [gogs/gogs#6974]
### Gogs version

unavailable

### Git version

git version 2.30.2

 Gogs won't even start

### Operating system

Debian 10

### Database

unknown

### Describe the bug

Gogs is slow. I run gogs web and it shows:
```2022/05/26 18:24:22 [TRACE] Log mode: File (Info)``` but it is stuck there and never moves

I tried to chown the directory to gogs user but that doesnt fix it either. Disabled Gravatar and it still does not work.

I cannot load the web interface, it won't even start listening on the port... It can't even get that far.

### To reproduce

run gogs

### Expected behavior

gogs should run

### Additional context

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mooleshacat** [comment]
So I ran it and checked the website and it worked ... I remember seeing multiple lines in the log before so seeing only one confused me but it appears the log output is gone... It was kind of nice to see it working by watching the log, but it's gone.

Considering the main issue of gogs being slow is fixed I am closing ticket

**Comment by unknwon** [comment]
I thought is would be obvious logs are going into file and only info-level based on "Log mode: File (Info)"? 😄
