### ISSUE TITLE
Incorrect SSH server command with OpenSSH on Windows

### ISSUE THREAD

**Issue by fjxhkj** [gogs/gogs#6977]
### Gogs version

0.12.7

### Git version

- Server: win X64 2.36.1
- Client: win X64 2.36.1

### Operating system

Windows Server 2012 R2 , Windows 10

### Database

Sqlite3

### Describe the bug

Is there a mistake in the logic of connecting to the database?

Why is the database type sqlite3 still used to connect to it using IP?

### To reproduce

Gogs's app.ini :

```ini
BRAND_NAME = Gogs
RUN_USER   = Administrator
RUN_MODE   = prod

[database]
TYPE     = sqlite3
HOST     = 127.0.0.1:5432
NAME     = gogs
USER     = gogs
PASSWORD =
SSL_MODE = disable
PATH     = x:/gogs/data/gogs.db

[repository]
ROOT = x:/gogs/data/gogs-repositories

[server]
DOMAIN           = vm.com
HTTP_PORT        = 3000
EXTERNAL_URL     = http://vm.com:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = false
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = true
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = x:/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = w8Hf5ZbPqEz1BwK
```

run:

`git clone Administrator@vm.com:user/test.git`

then:

```
Cloning into 'test'...
Gogs: Internal error
Failed to set database engine: open database: dial tcp 127.0.0.1:5432: connectex: No connection could be made because the target machine actively refused it.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Expected behavior

See `reproduce`

### Additional context

- Only happends when using ssh, https is fine.

- Please tell me where is the app.ini's full document?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, based on the error log 

```
open database: dial tcp 127.0.0.1:5432:
```

It is clear to me that Gogs is trying to connect to PostgreSQL (default). 

Have you ever changed the path to your `app.ini` (looks like so)? It is possible that the SSH proxy command is still pointing to the old config file path (which probably no longer exists thus uses default for everything).

You can go to `/admin` and try:

<img width="883" alt="CleanShot 2022-06-03 at 20 27 46@2x" src="https://user-images.githubusercontent.com/2946214/171853710-9c74b1b1-6b19-417c-88d3-2cfe58a0b448.png">

**Comment by fjxhkj** [comment]
@unknwon 
I don't think it's what you think, but ...
Finally I found the problem is.
When I runs the Operations : Rewrite '.ssh/authorized_keys ...' , my authorized_keys file's content is:
```
command="x:\gogs\gogs.exe serv key-1 --config='x:\gogs\custom\conf\app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 xxxxxx....xxx
```
**But** Windows has no single quotes syntax rules, but `--config=\"path with space\"`, so I changed the authorized_keys file's content to:
```
command="x:\gogs\gogs.exe serv key-1 --config=\"x:\gogs\custom\conf\app.ini\"",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 xxxxxx....xxx
```
And then it succeeds worked!
I still think this is a bug, although not the database issue I mentioned above, but the operation scripts should be slightly modified for the Windows platform. Thank you.

**Comment by unknwon** [comment]
> **But Windows has no single quotes syntax rules**, rather `--config=\"path with space\"`, so I changed the authorized_keys file's content to:
> 
> 
> ```
> command="x:\gogs\gogs.exe serv key-1 --config=\"x:\gogs\custom\conf\app.ini\"",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 xxxxxx....xxx
> ```
> 
> 
>     
>   
> 
> And then it succeeds worked!

@fjxhkj  Wow, nice find! What SSH server software you're using? Gogs has the assumption you'd be using bash, and git-bash is recommended.

**Comment by fjxhkj** [comment]
I'm using [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) with cmd.exe (or powershell).
However, even when I use git-Bash the above problems also occur. I'm trying to do it in both cmd and git-bash:
```
x:\gogs\gogs.exe serv key-1 --config='x:\gogs\custom\conf\app.ini',no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 xxxxxx....xxx
```
and got:
```
[ WARN] Custom config "x:\\gogs\\gogs\\'d:\\_runtimes\\gogs\\gogs\\custom\\conf\\app.ini',no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty" not found. Ignore this warning if you're running for the first time
Gogs: Internal error
Failed to set database engine: open database: dial tcp 127.0.0.1:5432: connectex: No connection could be made because the target machine actively refused it.
```
So I think that is operating the script is a problem with the statement.
