### ISSUE TITLE
Unable to start Gogs Docker container with `latest` tag using SQLite 

### ISSUE THREAD

**Issue by liukonen** [gogs/gogs#7019]
### Gogs version

0.13.0+dev

### Git version

- Server: 2.34.1
- Client: 2.36.0.windows.1

### Operating system

Ubuntu 22.04 / Docker Latest image

### Database

sqlite

### Describe the bug

12.8 appears to have released fine, however, there was a release to the latest image that appears to have DB issues.
When I revert to the tag 0.12, it appears to work correctly. 
Exception in log appears to be
Failed to initialize ORM engine: migrate: do migrate: auto migrate: sql: converting argument $1 type: unsupported type clause.Expr, a struct
Using Base DB (I believe it was an instance of SQL Lite) 
Based on the release schedule, I am assuming that 12.8 was released some 7 days ago. The edition of Gogs I see having the problem was deployed to docker 12 hours ago, but doesn't appear to tie directly with any release specific to github.

### To reproduce

On docker start, could not navigate to gogs page, and in logs, found the error repeated above. (portainer log just says something like "write to file"... while logs in my data directory point to the SQL issue noted above)

### Expected behavior

be able to connect to gogs site (page just errors out)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey! Are you trying to run a fresh Gogs installation and encountered this error? Or upgrading from some older version?

**Comment by Zwixx** [comment]
Same problem here. I use watchtower to update the gogs container. Since this night he don't come up correctly and I get the same error.

**Comment by unknwon** [comment]
Looks like a bug in GORM: https://github.com/go-gorm/gorm/issues/4960

**Comment by Zwixx** [comment]
in my gogs.log there are many of:
2022/06/07 00:00:05 [ INFO] Gogs 0.13.0+dev
2022/06/07 00:00:05 [ INFO] Migration: migrate access tokens to store SHA56
2022/06/07 00:00:05 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: migrate: do migrate: auto migrate: sql: converting argument $1 type: unsupported type clause.Expr, a struct

**Comment by unknwon** [comment]
Fix is coming in https://github.com/gogs/gogs/pull/7025.

**Comment by SR-G** [comment]
So ... any news about this ?
Because the (currently) latest image seems to be pushed 6 hours ago (from now), so should include the patch ...
Is it this one ?
https://hub.docker.com/layers/gogs/gogs/gogs/latest/images/sha256-8cfacba36d1ff591114a4b728595119a8d2967dbb517558b67a682fcbb576f98?context=explore

With this one, i still have the exact same issue :

```
2022/06/07 22:21:53 [ INFO] Gogs 0.13.0+dev
2022/06/07 22:21:53 [ INFO] Migration: migrate access tokens to store SHA56
2022/06/07 22:21:53 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: migrate: do migrate: auto migrate: sql: converting argument $1 type: unsupported type clause.Expr, a struct
```

(numerous times inside logs)
(and i hope my database won't be corrupted...)

**Comment by unknwon** [comment]
@SR-G yes, you're running the one included the "fix" ... maybe because I was testing against a brand new SQLite3 file, which often uses the latest version since I don't have an database file from an old version 🤔 

>(and i hope my database won't be corrupted...)

Rest assured, if SQLite is ACID, your data is safe.

**Comment by unknwon** [comment]
@SR-G just to confirm, what exact command you ran to start a new container from the new image after pulling the latest Docker image of gogs/gogs?

**Comment by SR-G** [comment]
Yes, i'm using the same "run" command since years, with very few things inside it : 

```
docker run -p 19041:3000 -p 19042:22 -d -v /home/datas/docker-datas/gogs:/data --name gogs gogs/gogs
```

I took the latest image published today, but still the same problem : 

```
docker pull gogs/gogs:latest
latest: Pulling from gogs/gogs
Digest: sha256:c271fe8d5ace5db11d1cd78ad646d0931ef53ced352a1bcf06df7fda53262484
Status: Image is up to date for gogs/gogs:latest
docker.io/gogs/gogs:latest
(...)
2022/06/08 07:59:54 [ INFO] Gogs 0.13.0+dev
2022/06/08 07:59:54 [ INFO] Migration: migrate access tokens to store SHA56
2022/06/08 07:59:54 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: migrate: do migrate: auto migrate: sql: converting argument $1 type: unsupported type clause.Expr, a struct
```

My DB is the default one : 

```
[database]
TYPE     = sqlite3
HOST     = 127.0.0.1:3306
NAME     = gogs
USER     = root
SSL_MODE = disable
PATH     = /data/gogs/data/gogs.db
```

**Comment by unknwon** [comment]
@SR-G Thanks for the followup! I'm able to reliably reproduce this now. Seeking new fixes!

**Comment by unknwon** [comment]
Let's give it another 45 minutes <img src="https://media3.giphy.com/media/l4JyRqcDU93S334KQ/giphy.gif"/>

**Comment by liukonen** [comment]
Sorry for the late reply... thank you so much, the Latest tag appears to be working on my system again

**Comment by Zwixx** [comment]
Yes, works for me too. Thank you.
