### ISSUE TITLE
Failed to initialize ORM engine: migrate: auto migrate "version" table: near "integer": syntax error

### ISSUE THREAD

**Issue by chonglou** [gogs/gogs#7056]
### Gogs version

docker.io/gogs/gogs:latest(9152dcffa4b71) 0.13.0+dev

### Git version

- Server: Unknown (in docker)
- Client: 2.36.1

### Operating system

Ubuntu 20.04

### Database

Sqlite 3

### Describe the bug

After I upgrade the docker image:
![image](https://user-images.githubusercontent.com/6397317/173480303-e7754ac2-6379-4bce-8927-0fb06cca4422.png)

And start then with:
![image](https://user-images.githubusercontent.com/6397317/173480402-94e4fcad-1804-4a05-9d04-12990de67a20.png)

It show:
![image](https://user-images.githubusercontent.com/6397317/173480469-390045de-66e4-49c3-a1e7-78667b6a095c.png)

### To reproduce

```bash
docker pull gogs/gogs
docker run -d --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
```

### Expected behavior

It should start successfuly as usual.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chonglou** [comment]
Finally, I switched to ```gogs/gogs:0.12``` and it worked.

**Comment by unknwon** [comment]
Thanks for the feedback!

The patch has been merged, please allow up to 45 minutes for the latest Docker image to be built.
