### ISSUE TITLE
Trojan detected in version 0.12.9

### ISSUE THREAD

**Issue by mlgd** [gogs/gogs#7058]
### Gogs version

0.12.9

### Git version

N/A

### Operating system

Windows Server 2016

### Database

SQLite

### Describe the bug

Windows Defender detect trojan Program:Win32/Cayunamer.A!ml

### To reproduce

Deploy Gogs 0.12.9 on Windows Server 2016

### Expected behavior

No trojan

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
If you don't trust the compiled binary version from us, just [compile from source](https://gogs.io/docs/installation/install_from_source) :)
