### ISSUE TITLE
French translations are not up to date on the 2 last releases

### ISSUE THREAD

**Issue by vinceAmstoutz** [gogs/gogs#7068]
### Gogs version

0.12.9

### Git version

- Server:  2.34.1
- Client: 2.34.1

### Operating system

Ubuntu Server 22.04

### Database

PostgreSQL 14

### Describe the bug

The latest validated French translations (validated in Crowdin and in the project) do not appear in the latest release versions. 

### To reproduce

Just compare french traduction from Crowdin or the projet and with last releases (the last 2).

### Expected behavior

Up to date with last translations in my gogs project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Hey, we do not port back translations to release branches because it is very difficult to manage changed items between different versions. If you want to use the latest translations, please consider using `0.13.0+dev` :)

**Comment by vinceAmstoutz** [comment]
Ok thanks, so the translations will be on the `13.* +` versions right?

**Comment by unknwon** [comment]
> Ok thanks, so the translations will be on the `13.* +` versions right?

0.13.* + 😁

**Comment by vinceAmstoutz** [comment]
And when approximately please ?

**Comment by unknwon** [comment]
> And when approximately please ?

There is currently no ETA for 0.13 release(s).
