### ISSUE TITLE
After pushing the code, the repository gets a 500 error. It is normal before pushing

### ISSUE THREAD

**Issue by nanxia990105** [gogs/gogs#7072]
### Gogs version

Gogs version 0.12.6

### Git version

- Server:  git version 2.33.0.windows.2
- Client:  git version 2.34.1.windows.1

### Operating system

- Server:  windows 11
- Client:  windows 10

### Database

mysql  Ver 8.0.26 for Win64 on x86_64 (MySQL Community Server - GPL)

### Describe the bug

After pushing the code, the repository gets a 500 error. It is normal before pushing

<img width="923" alt="image" src="https://user-images.githubusercontent.com/64909808/175234484-6dd6df7d-1780-4f95-bdf6-dc4a0afd31f4.png">

### To reproduce

I'm not so sure, it's just that the repositories that can be used get a 500 error after pushing the code

### Expected behavior

It should be pushed normally

### Additional context

<img width="960" alt="image" src="https://user-images.githubusercontent.com/64909808/175234886-dbedd6f1-58cb-4031-99c6-c71089ea0d67.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thanks for the feedback!

I think this is duplicate to https://github.com/gogs/gogs/issues/6436, let me know if you think otherwise.
