### ISSUE TITLE
Web Hooks

### ISSUE THREAD

**Issue by downyws** [gogs/gogs#7073]
### Gogs version

0.12.9

### Git version

- Server: 
- Client: 1.8.3.1

### Operating system

Centos7

### Database

MySQL5.7

### Describe the bug

WEB HOOKS 触发后没有发起请求

### To reproduce

仓库设置 > 管理web钩子 > WEB钩子 > 测试推送

### Expected behavior

![GOGS](https://user-images.githubusercontent.com/11483531/175326014-d44ccebc-2d03-4df3-864c-aa0fcfd3ea78.png)

### Additional context

2022/06/23 22:17:32 [ERROR] [...s.io/gogs/internal/db/webhook.go:490 AfterSet()] Unmarshal [4]: readObjectStart: expect { or n, but found P, error found in #1 byte of ...|Payload URL|..., bigger context ...|Payload URL resolved to a local network address tha|...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Merging this issue to https://github.com/gogs/gogs/issues/7074.
