### ISSUE TITLE
Still trouble with local webhooks

### ISSUE THREAD

**Issue by grasshide** [gogs/gogs#7074]
### Gogs version

0.13.0+dev

### Git version

- Server: 2.32.2
- Client: intellij

### Operating system

debian

### Database

postgres:9.5

### Describe the bug

Since some change, gogs would not let me put any local URL in the webhook URL field. That was fixed with this Issue: https://github.com/gogs/gogs/issues/7051 when I added:
LOCAL_NETWORK_ALLOWLIST = 192.168.1.200

I thought that would be it, but non of my webhooks are actually firing.
So I set the log to trace instead of info and I'm getting this:
[ERROR] [...s.io/gogs/internal/db/webhook.go:490 AfterSet()] Unmarshal [452]: readObjectStart: expect { or n, but found P, error found in #1 byte of ...|Payload URL|..., bigger context ...|Payload URL resolved to a local network address tha|...

Not sure what this means, but I think there is still some local restriction in place.

### To reproduce

My settings are the very basic for the webhook:
URL: http://192.168.1.200:8555/some-token
Content Type: application/json
Just push the event
active

### Expected behavior

I expect the webhook to be triggered. But noting ever arrives on the target side.

### Additional context

 gogs: image: gogs/gogs:latest container_name: gogs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thanks for the feedback! PR is coming in https://github.com/gogs/gogs/pull/7075

**Comment by grasshide** [comment]
Thanks!

**Comment by unknwon** [comment]
The 0.12.10 has been released that includes the patch of the reported issue.
