### ISSUE TITLE
Permission denied (publickey) when upgrade client's version

### ISSUE THREAD

**Issue by wideweide** [gogs/gogs#7108]
### Gogs version

     0.12.7

### Git version

- Server: 
git version 2.37.0.windows.1
- Client: 
git version 2.37.1.windows.1

### Operating system

windows 10

### Database

SQLite 3

### Describe the bug

upgrade client git version from 2.28( or 2.31 ) to 2.37.1,could not clone or pull any more:

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### To reproduce

ssh port not 22，so 
[~/.ssh/config]
```
host xy.com
hostname xy.com
port 8022
```

upgrade client git version from 2.28( or 2.31 ) to 2.37.1 then reproduce
install old git version then work fine

### Expected behavior

new git version work fine

### Additional context

log info: 
 [ERROR] [gogs.io/gogs/internal/ssh/ssh.go:151 func1()] SSH: Error on handshaking: [ssh: no auth passed yet]

I'm not sure this is the gogs'e problem,or git new version's ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by awsms** [comment]
I'm having this as well.

**Comment by broken-ufa** [comment]
I have same issue
### openssh-client 1:8.9p1-3

on client I get error: 
`"Permission denied (publickey)"`

in gogs-log:
`2022/10/28 15:29:15 [ERROR] [gogs.io/gogs/internal/ssh/ssh.go:151 func1()] SSH: Error on handshaking: [ssh: no auth passed yet]
`

**Comment by broken-ufa** [comment]
Okay. I'm investigated it.
acording to https://confluence.atlassian.com/bitbucketserverkb/ssh-rsa-key-rejected-with-message-no-mutual-signature-algorithm-1026057701.html

rsa keys is deprecated and better to generate new keys in ed25519
or add `PubkeyAcceptedKeyTypes +ssh-rsa` to user's `.ssh/config`

**Comment by lerry** [comment]
> Okay. I'm investigated it. acording to https://confluence.atlassian.com/bitbucketserverkb/ssh-rsa-key-rejected-with-message-no-mutual-signature-algorithm-1026057701.html
> 
> rsa keys is deprecated and better to generate new keys in ed25519 algorithm or add `PubkeyAcceptedKeyTypes +ssh-rsa` to user's `.ssh/config`

thanks, it helps a lot !
