### ISSUE TITLE
Err 500 on try.gogs.io like in closed #5905

### ISSUE THREAD

**Issue by pflegende** [gogs/gogs#7110]
### Gogs version

-

### Git version

- Server: 
- Client: 

### Operating system

-

### Database

-

### Describe the bug

Err 500 on try.gogs.io

like in closed issue

https://github.com/gogs/gogs/issues/5905#issue-550396076

---

tried 5 times with a delay of 15 min
![Err500on_try gogs io](https://user-images.githubusercontent.com/52720420/180583753-a25ba1d4-b909-486b-8fa8-5d3f5ce9e814.png)

always same result

### To reproduce

try to register on
try.gogs.io

### Expected behavior

 use the https://try.gogs.io system

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thank you for the prompt! Cleaned up some disk space 🙏
