### ISSUE TITLE
build error on arm64

### ISSUE THREAD

**Issue by linjinbao666** [gogs/gogs#7126]
### Gogs version

latest

### Git version

- Server: 2.30.2
- Client: 2.30.2

### Operating system

Debian 11

### Database

SQLite 3

### Describe the bug

I am trying to build gogs on my self machine, which had an environment of debian 11 and arm64, I use then command `go build -o gogs`  what was written in the document, but it brokes with output follow:
```code
root@debian:~/gogs# go build -o gogs 
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
root@debian:~/gogs# 
```
 it seems to be an error of go-sqlite3, in one issue of other [repo](https://github.com/mattn/go-sqlite3/issues/822), I found the way to solve this `CGO_CFLAGS="-g -O2 -Wno-return-local-addr" go build `

my machine info:
```code
root@debian:~/gogs# uname -a 
Linux debian 5.10.0-16-arm64 #1 SMP Debian 5.10.127-1 (2022-06-30) aarch64 GNU/Linux
root@debian:~/gogs# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@debian:~/gogs# 
```

### To reproduce

on arm64 machine, run `go build -o gogs`

### Expected behavior

build out 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Thanks for the feedback! AFAIK these are just warnings and don't prevent you from using Gogs with SQLite3.
