### ISSUE TITLE
Error on loading dashboard after log-in

### ISSUE THREAD

**Issue by tosate** [gogs/gogs#7197]
**Describe the bug**
The dashboard page for non-administrator users does not load

**Gogs version and commit**
Gogs version: 0.13.0+dev
Build-Commit: [7cbd84d5b3d4af36e4afcf7af9374bc765f6bb9c](https://github.com/gogs/gogs/commit/7cbd84d5b3d4af36e4afcf7af9374bc765f6bb9c)

**Git version**
2.32.4

**Operating system**
docker on Ubuntu 18.04.6 LTS

**Database**
PostgreSQL 15.0

**To Reproduce**

1. Instantiate latest docker image
2. Log-in as non-administrator user

**Can you reproduce the bug at https://try.gogs.io/?**
no

**Expected behavior**
load the page normally

**Actual behavior**
gives the following error:
`template: user/dashboard/dashboard:45:31: executing "user/dashboard/dashboard" at <.ContextUser.HomeLink>: can't evaluate field HomeLink in type interface {}`

**Additional context**
No error logs

**Comment by unknwon** [comment]
Thanks for the feedback!

Introduced this regression in an early PR today and should be fixed in https://github.com/gogs/gogs/pull/7199.
