### ISSUE TITLE
HTTP basic authentication failed when password contains ":"

### ISSUE THREAD

**Issue by Mageti** [gogs/gogs#723]
Hello,
In short, my problem is that i can't "git clone" a git repo hosted with gogs when I use authentification against LDAP. But authentication is ok with the webUI.

Details : 
OS : linux debian wheezy, uptodate
Apache2, to access gogs web interface via port 80
GOGS : lastest installed using the package for debian wheezy found on packager.io (version : "0.5.8.1205 Beta" as shown on webUI). runs on port 6000
Authentication using LDAP. Works when accessing webUI

Symptomes :

```
[mageti@dev_machine /tmp]$ git clone http://styx.domain.com/mageti/test_project.git
Cloning into 'test_project'...
Username for 'http://styx.domain.com': mageti
Password for 'http://mageti@styx.domain.com': <My_Password>
fatal: Authentication failed
```

Same problem when trying to git clone directly from gogs on port 6000, to bypass apache

Gogs logs : 

```
[Macaron] Started GET /mageti/test_project.git/info/refs for 192.168.1.253
[Macaron] Completed /mageti/test_project.git/info/refs 401 Unauthorized in 6.798708ms
[Macaron] Started GET /mageti/test_project.git/info/refs for 192.168.1.253
[Macaron] Completed /mageti/test_project.git/info/refs 401 Unauthorized in 21.429183ms
[Macaron] Started GET /mageti/test_project.git/info/refs for 192.168.1.253
[Macaron] Completed /mageti/test_project.git/info/refs 401 Unauthorized in 22.904621ms
```

Apache conf : 

```
<VirtualHost *:80>
        ProxyPreserveHost On
        ProxyRequests off
        ProxyPass / http://localhost:6000/
        ProxyPassReverse / http://localhost:6000/
        ServerName styx.domain.com
        ServerAlias styx
</VirtualHost>
```

Gogs conf changed after installation:

```
[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true
```

**Comment by kenshinthebattosai** [comment]
I want to chip in here even though this is an old bug.
The correct way to do this in my humble opinion would be to URL ENCODE the username and password, since it appears in the URL http://<username>:<password>@domain.com.

That way, `:` is encoded to `%3A` etc., and the `:` split works, after which you can URL DECODE the username and password separately.

Thanks

**Comment by Unknwon** [comment]
@kenshinthebattosai thanks your info!

But I think you're talking different topics here...

**Comment by kenshinthebattosai** [comment]
Oh, sorry for polluting this thread

**Comment by Unknwon** [comment]
@kenshinthebattosai :D
