### ISSUE TITLE
API Request: ability to create a repo

### ISSUE THREAD

**Issue by michaeldyrynda** [gogs/gogs#726]
Hi there, as part of automation of our development environment we currently configure a new workspace, initialise a local git repository in that workspace, then manually create the remote repo and set the remote tracking branch.

It would be handy if we could make an API request to create a new repository in gogs, so that we can further automate the setup process.

This isn't urgent for us as we can make do without, but would be grateful if it make it into the next iteration of API changes.

Thanks!

**Comment by ccidral** [comment]
Do you have a working example of cURL command? I tried the following but it didn't create the repo and returned no error:

```bash
curl -X POST \
   -H "content-type: application/json" \
   -d '{"name":"foobar"}' \
   http://localhost:3000/api/v1/org/MyOrg/repos
```

**Comment by deringer** [comment]
Sorry @ccidral - I'm not at that company anymore and don't have a record of the command. Make sure you're sending through your API token in the request.

**Comment by Unknwon** [comment]
@ccidral Hi, here is a API client that contains create repository operation: https://github.com/gogits/go-gogs-client

**Comment by nexgenkannan** [comment]
> 
> 
> Do you have a working example of cURL command? I tried the following but it didn't create the repo and returned no error:
> 
> ```shell
> curl -X POST \
>    -H "content-type: application/json" \
>    -d '{"name":"foobar"}' \
>    http://localhost:3000/api/v1/org/MyOrg/repos
> ```

Any update on commands for creating new repos

**Comment by yanggaofeng** [comment]
> > Do you have a working example of cURL command? I tried the following but it didn't create the repo and returned no error:
> > ```shell
> > curl -X POST \
> >    -H "content-type: application/json" \
> >    -d '{"name":"foobar"}' \
> >    http://localhost:3000/api/v1/org/MyOrg/repos
> > ```
> 
> Any update on commands for creating new repos

see      https://discuss.gogs.io/t/create-repo-local-user-and-issue-from-cli/524
