### ISSUE TITLE
Custom CSS Style

### ISSUE THREAD

**Issue by zkvvoob** [gogs/gogs#7295]
### Describe the feature

Add option for an administrator to add custom CSS style site-wide.

### Describe the solution you'd like

A page in the Admin panel whith a text box/area where one could past a CSS style which (for ids/classes that match) overrides the default one.

### Describe alternatives you've considered

Add a custom.css file somewhere in the root directory, the contents of which override the default CSS style.

### Additional context

The reason I'm bringing this up is the lack of a dark mode in Gogs. I love Gogs and I'd rather stick with it and I also thought asking you to implement a dark mode on your own would be too much. Besides, people might complain that this is not exactly the dark mode they had in mind, hence this compromise.

But, if you were interested in adding a dark mode, I've stumbled upon [this user script](https://userstyles.org/styles/167730/gogs-dark-theme), which could turn out to be a good stepping stone.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CiviledCode** [comment]
This is currently possible by editing the `custom/templates` and `custom/public/css` directories from within the root gogs directory. 

Referencing this doc page should get you started: https://gogs.io/docs/features/custom_template

Here is an example of this that might work for what you're looking for: https://github.com/Kos-M/GogsThemes

**Comment by GwynethLlewelyn** [comment]
I have to say, the Kos-M templates are nothing short of extraordinary...

I'm pretty sure that this issue can be **closed** since it is clearly solved!

**Comment by lucascolla** [comment]
> Before closing the issue, could you help me figure out what I'm doing wrong when adding a custom template? I've followed Kos-M's instructions to the letter. Here's my folder structure and Docker compose:
> 
> ```yaml
> version: "3.6"
> services:
>   gogs:
>     container_name: gogs
>     hostname: gogs
>     image: gogs/gogs:latest
>     ports:
>       - 1122:22/tcp
>       - 1120:3000/tcp
>     restart: unless-stopped
>     volumes:
>       - /home/docker/gogs:/data
> ```
> 
> ![SCR-20230313-hjb](https://user-images.githubusercontent.com/7645808/224678330-3e79bc5a-5fec-4acc-b01b-d8638b311f50.png)
> 
> I've restarted the container several times and yet the theme css is not being picked when when looking at the page source code.

in the docker container, the /data folder is the custom folder, you don't need to create a custom folder inside, just create public and templates folder inside /data

**Comment by zkvvoob** [comment]
Brilliant! It worked.
Thank you, @lucascolla!
