### ISSUE TITLE
Can no longer see the GUI

### ISSUE THREAD

**Issue by aminnaggar** [gogs/gogs#7314]
### Discussed in https://github.com/gogs/gogs/discussions/7294

<div type='discussions-op-text'>

<sup>Originally posted by **aminnaggar** December 29, 2022</sup>
I've installed gogs using docker, and had it working while I was setting it up. I was able to create repositories and push commits into them with no problems.

After I restarted my container I lost the ability to view the GUI, but I'm still able to push new commits to the repos. Here's my config, what am I missing?

```
BRAND_NAME = Gogs
RUN_USER   = git
RUN_MODE   = prod

[database]
TYPE     = mysql
HOST     = mariadb
NAME     = gogs
SCHEMA   = public
USER     = gogs
PASSWORD = MY_LONG_PASS
SSL_MODE = disable
PATH     = /app/gogs/data/gogs.db

[repository]
ROOT = /data/git/gogs-repositories

[server]
DOMAIN           = 192.168.40.100
HTTP_PORT        = 8930
EXTERNAL_URL     = http://192.168.40.100:8930/
DISABLE_SSH      = false
SSH_PORT         = 8922
START_SSH_SERVER = false
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[auth]
REQUIRE_EMAIL_CONFIRMATION  = false
DISABLE_REGISTRATION        = true
ENABLE_REGISTRATION_CAPTCHA = false
REQUIRE_SIGNIN_VIEW         = false

[user]
ENABLE_EMAIL_NOTIFICATION = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /app/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = THE_SECRET_KEY
```

tailing the log gives me

```
2022/12/29 15:58:37 [ INFO] Gogs 0.13.0+dev
2022/12/29 15:58:37 [ INFO] Run mode: Production
2022/12/29 15:58:38 [ INFO] Available on http://192.168.40.100:8930/
```</div>

**Comment by enyusmile** [comment]
I had the same problem

**Comment by sethdmoore** [comment]
Likely a dupe of #6626 and #7061  
Usually has to do with `gogs/log/xorm.log` having the wrong permissions.  
Just remove `xorm.log` or `chown` the log file to your configured user.

**Comment by aminnaggar** [comment]
I've removed the `xorm.log` file, I've also set the log mode to `console`. Still get a ERR_CONNECTION_REFUSED

**Comment by aminnaggar** [comment]
Turns out the wrong ports were in the conf (somehow the docker ports were in the conf not the app ports...)
