### ISSUE TITLE
mail config not work

### ISSUE THREAD

**Issue by yunkuangao** [gogs/gogs#7315]
### Gogs version

0.13.0+dev

### Git version

- Server: 2.32.4
- Client: 

I don't think it has anything to do with this question

### Operating system

Docker

### Database

PostgreSQL 15.1

### Describe the bug

After configuring smtp, the page display is still not enabled

![screenshot](https://user-images.githubusercontent.com/40163747/212797775-a77808a9-07e3-4e9d-acc9-cba8e6c62db5.jpg)

I guarantee that this configuration is correct and has been used normally in my other applications.

This is my conf example:

[mailer]
ENABLED = true
HOST    = XXXX.com:587
FROM    = "XXX" <XXX@XXX.com>
USER    = XXX@XXX.com
PASSWD  = XXXX

### To reproduce

all time

### Expected behavior

I want smtp to work normally

### Additional context

I don't know which log is useful. If you need it, you can tell me and I will find it out.

And this is the same problem as [#6738](https://github.com/gogs/gogs/issues/6738).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarushiruDonato** [comment]
As this discussion https://github.com/gogs/gogs/discussions/6959 mentioned, changing the section name from `mailer` to `email` should solve the problem.

**Comment by yunkuangao** [comment]
It works,Thanks to @MarushiruDonato and @zoutao98.
