### ISSUE TITLE
First commit in history page doesn't have link to user profile

### ISSUE THREAD

**Issue by Linaro1985** [gogs/gogs#7404]
### Gogs version

0.13.0

### Git version

- Server: 2.20.1
- Client: 2.20.1

### Operating system

Debian 10

### Database

mysql

### Describe the bug

First commit on history page (page number doesn't matter) doesn't have link to user profile
![commit_history](https://user-images.githubusercontent.com/15726175/227212965-23b21fd8-4977-4da3-be4f-a088d94bf9cf.png)

### To reproduce

1. Create new repository
2. Make several commits
3. Open commit history
4. First commit doesn't have link to user profile

### Expected behavior

First commit on history page (page number doesn't matter) have link to user profile

### Additional context

Maybe this issue because of:

https://github.com/gogs/gogs/commit/ed51686240ff84e3cc12be8bc4311c529d44faee
https://github.com/gogs/gogs/commit/6d220540c15e68196404951e8b67cac8002d1a6f

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JerryLiao26** [comment]
Can confirm it's a bug here
https://github.com/gogs/gogs/blob/7be3ea194f6830532e51badad057e855bfb1870c/internal/route/repo/commit.go#L203
by not giving the value to `u`
Should I start a pull request?

**Comment by njsoftdev** [comment]
Same issue and in commits page avatar and profile link doesn't attached to author. But in 0.13.0 all ok. 

It's bug. Regression after upgrade gogs from 0.13.0+dev to 0.14.0+dev.

**Comment by ivanbogomoloff** [comment]
Is it correct solution ? 
I did it, because in my cases it works.

```go
func matchUsersWithCommitEmails(ctx gocontext.Context, oldCommits []*git.Commit) []*userCommit {
        emailToUsers := make(map[string]*db.User)
        newCommits := make([]*userCommit, len(oldCommits))
        for i := range oldCommits {
                var u *db.User
                if v, ok := emailToUsers[oldCommits[i].Author.Email]; !ok {
                        u , _ = db.Users.GetByEmail(ctx, oldCommits[i].Author.Email) //<-- Fixed here
                } else {
                        u = v
                }

                newCommits[i] = &userCommit{
                        User:   u,
                        Commit: oldCommits[i],
                }
        }
        return newCommits
}

```

**Comment by athoik** [comment]
My guess is that emailToUsers is used as a local cache, to avoid multiple queries to database.
If it's on emailToUsers, don't bother querying db.

So the proper fix would be the following:

```
func matchUsersWithCommitEmails(ctx gocontext.Context, oldCommits []*git.Commit) []*userCommit {
        emailToUsers := make(map[string]*db.User)
        newCommits := make([]*userCommit, len(oldCommits))
        for i := range oldCommits {
                var u *db.User
                if v, ok := emailToUsers[oldCommits[i].Author.Email]; !ok {
                        emailToUsers[oldCommits[i].Author.Email], _ = db.Users.GetByEmail(ctx, oldCommits[i].Author.Email) 
                        u = emailToUsers[oldCommits[i].Author.Email]
                } else {
                        u = v
                }

                newCommits[i] = &userCommit{
                        User:   u,
                        Commit: oldCommits[i],
                }
        }
        return newCommits
}
```

What it's missing is the assignment of user returned from db, both in emailToUsers and in u variable.
