### ISSUE TITLE
Gogs doesn't start as systemd service

### ISSUE THREAD

**Issue by OlyaK95** [gogs/gogs#7410]
### Gogs version

Gogs 0.14.0+dev

### Git version

- Server: git version 2.34.1
- Client: 

### Operating system

Armbian 23.02.2 Jammy with Linux 5.15.93-rockchip64

### Database

mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on aarch64 ((Ubuntu))

### Describe the bug

Gogs can start only manually:

- go version

`go version go1.20.2 linux/arm64`

- cd /opt/gogs/gogs
- ./gogs web

`2023/03/29 01:11:29 [ WARN] Custom config "/opt/gogs/gogs/custom/conf/app.ini" not found. Ignore this warning if you're running for the first time`
`2023/03/29 01:11:29 [TRACE] Log mode: Console (Trace)`
`2023/03/29 01:11:29 [ INFO] Gogs 0.14.0+dev`
`2023/03/29 01:11:29 [TRACE] Work directory: /opt/gogs/gogs`
`2023/03/29 01:11:29 [TRACE] Custom path: /opt/gogs/gogs/custom`
`2023/03/29 01:11:29 [TRACE] Custom config: /opt/gogs/gogs/custom/conf/app.ini`
`2023/03/29 01:11:29 [TRACE] Log path: /opt/gogs/gogs/log`
`2023/03/29 01:11:29 [TRACE] Build time:`
`2023/03/29 01:11:29 [TRACE] Build commit:`
`2023/03/29 01:11:29 [ INFO] Run mode: Development`
`2023/03/29 01:11:30 [ INFO] Available on http://localhost:3000/`

When I try to start Gogs as systemd service gogs.service failed.

- sudo nano /etc/systemd/system/gogs.service

`[Unit]`
`Description=Gogs`
`After=syslog.target`
`After=network.target`
`After=mysql.service`

`[Service]`
`# Modify these two values and uncomment them if you have`
`# repos with lots of files and get an HTTP error 500 because`
`# of that`
`###`
`#LimitMEMLOCK=infinity`
`#LimitNOFILE=65535`
`Type=simple`
`User=gogs`
`Group=gogs`
`WorkingDirectory=/opt/gogs`
`ExecStart=/opt/gogs web`
`Restart=always`
`Environment=USER=gogs HOME=/opt/gogs`

`# Some distributions may not support these hardening directives. If you cannot start the service due`
`# to an unknown option, comment out the ones not supported by your version of systemd.`
`ProtectSystem=full`
`PrivateDevices=yes`
`PrivateTmp=yes`
`NoNewPrivileges=true`

`[Install]`
`WantedBy=multi-user.target`

Directory with Gogs logs is empty.

### To reproduce

- sudo systemctl daemon-reload
- sudo systemctl enable gogs
- sudo systemctl start gogs
- sudo systemctl status gogs

`× gogs.service - Gogs`
`     Loaded: loaded (/etc/systemd/system/gogs.service; enabled; vendor preset: enabled)`
`     Active: failed (Result: exit-code) since Wed 2023-03-29 01:05:17 MSK; 15s ago`
`    Process: 2419 ExecStart=/opt/gogs web (code=exited, status=203/EXEC)`
`   Main PID: 2419 (code=exited, status=203/EXEC)`
`        CPU: 37ms`

`Mar 29 01:05:17 OrangePi systemd[1]: gogs.service: Scheduled restart job, restart counter is at 5.`
`Mar 29 01:05:17 OrangePi systemd[1]: Stopped Gogs.`
`Mar 29 01:05:17 OrangePi systemd[1]: gogs.service: Start request repeated too quickly.`
`Mar 29 01:05:17 OrangePi systemd[1]: gogs.service: Failed with result 'exit-code'.`
`Mar 29 01:05:17 OrangePi systemd[1]: Failed to start Gogs.`

- journalctl -xeul gogs.service

`Mar 29 01:05:17 OrangePi systemd[2419]: gogs.service: Failed to locate executable /opt/gogs: Is a directory`
`░░ Subject: Process /opt/gogs could not be executed`
`░░ Defined-By: systemd`
`░░ Support: http://www.ubuntu.com/support`
`░░`
`░░ The process /opt/gogs could not be executed and failed.`
`░░`
`░░ The error number returned by this process is ERRNO.`
`Mar 29 01:05:17 OrangePi systemd[2419]: gogs.service: Failed at step EXEC spawning /opt/gogs: Is a directory`
`░░ Subject: Process /opt/gogs could not be executed`
`░░ Defined-By: systemd`
`░░ Support: http://www.ubuntu.com/support`
`░░`
`░░ The process /opt/gogs could not be executed and failed.`
`░░`
`░░ The error number returned by this process is ERRNO.`

- cd /opt/gogs/gogs/log
- ls -a

`. ..`

### Expected behavior

Gogs.service running.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bpint** [comment]
I think nothing wrong with gogs. There are some mistakes in your systemd service file. They should be,

```conf
# it seams your installation is in /opt/gogs/gogs/
WorkingDirectory=/opt/gogs/gogs
# your executable binary must be /opt/gogs/gogs/gogs
ExecStart=/opt/gogs/gogs/gogs web
Restart=always
# one environment variable per line
Environment=USER=gogs
Environment=HOME=/opt/gogs/gogs
```
