### ISSUE TITLE
Path Traversal in file editing UI and API (GHSA-r7j8-5h9c-f6fx, GHSA-qf5v-rp47-55gg)

### ISSUE THREAD

**Issue by ManassehZhou** [gogs/gogs#7582]
# Describe the bug

detailed information has been sent to (security@gogs.io)

# Code of Conduct
- [x] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
GHSA created for this report: https://github.com/gogs/gogs/security/advisories/GHSA-r7j8-5h9c-f6fx

It is currently private, will publish soon after 0.13.1 is released.
