### ISSUE TITLE
upgrade to 13.0 from 12.11,but can't startup.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [gogs/gogs#7595]
### Gogs version

13.0

### Git version

- Server:2.39.1 
- Client: n/a

### Operating system

Linux DSM_DSM 3.10.108 #42962 SMP Mon May 29 14:35:41 CST 2023 x86_64 GNU/Linux synology_braswell_716+II

### Database

sqlite

### Describe the bug

Upgrade 12.11 to 13.0, then try start it,but `Gogs: Internal error`.

### To reproduce

use 13.0 version files override 12.11 version files.

### Expected behavior

run normally

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wideweide** [comment]
me too,  my database is mysql

**Comment by 3792274** [comment]
.o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: failed to connect to `host=mysql.home1986.top user=root database=gogs`: failed to receive message (EmptyQueryResponse body must have length of 0, but it is 6)

**Comment by shu7734** [comment]
我也是更新了版本，然后我的custom/conf/app.ini配置是
[database]
DB_TYPE  = sqlite3
PATH     = data/gogs.db

但是
./gogs web
报错如下
`
2023/11/22 14:50:47 [ INFO] Gogs 0.13.0
2023/11/22 14:50:47 [TRACE] Work directory: /opt/gogs
2023/11/22 14:50:47 [TRACE] Custom path: /opt/gogs/custom
2023/11/22 14:50:47 [TRACE] Custom config: /opt/gogs/custom/conf/app.ini
2023/11/22 14:50:47 [TRACE] Log path: /opt/gogs/log
2023/11/22 14:50:47 [TRACE] Build time: 2023-02-25 02:30:34 UTC
2023/11/22 14:50:47 [TRACE] Build commit: 8c21874c00b6100d46b662f65baeb40647442f42
2023/11/22 14:50:47 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: failed to connect to `host=127.0.0.1 user=gogs database=gogs`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
`

**Comment by noogen** [comment]
Lots of breaking changes in the conf file in 13.0 that you should pay attention to, one of which is what @shu7734 reference.  It should be:  TYPE instead of DB_TYPE

See:  https://github.com/gogs/gogs/blob/main/conf/app.ini#L146
