### ISSUE TITLE
unrecognized command '/home/git/gogs/gogs serv key-5'

### ISSUE THREAD

**Issue by sarices** [gogs/gogs#774]
fatal: unrecognized command '/home/git/gogs/gogs serv key-5'
fatal: Could not read from remote repository.

**Comment by ellotheth** [comment]
In English: If you're migrating from an old gitweb or vanilla Git server to `gogs` and you're re-purposing the old Git user, change the login shell from `git-shell` back to Bash:

```
$ sudo usermod -s /bin/bash git
```

**Comment by Unknwon** [comment]
@ellotheth thanks!

**Comment by mlcpap** [comment]
Thank you!
