### ISSUE TITLE
gogs demo site SSL config is wrong and can't be bypassed

### ISSUE THREAD

**Issue by MrSpock** [gogs/gogs#7747]
### Gogs version

unknown

### Git version

n/a

### Operating system

Windows

### Database

n/a

### Describe the bug

Hi,

Demo site is unusable.
By entering try.gogs.io you will see attached error message. Due to use of HSTS you can't bypass this error in any RFC compliant browser so demo site is unavailable.

![hsts-gogs](https://github.com/gogs/gogs/assets/681680/d6b0149c-d5cc-413f-a3bf-df3c3779a3fc)

### To reproduce

Just go to https://demo.gogs.io

### Expected behavior

working demo site

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mh166** [comment]
In the meantime the URL changed to https://try.gogs.io/ The problem, however, remained the same. :(

**Comment by unknwon** [comment]
Hi, thanks for reporting! The demo site should be back to business by now 😁
