### ISSUE TITLE
SQLite driver not compiled in 0.13.1 release archives

### ISSUE THREAD

**Issue by MaxKingPor** [gogs/gogs#7878]
### Gogs version

Gogs 0.13.1

### Git version

- Server: 
git version 2.43.0
- Client: 
git version 2.43.0.windows.1

### Operating system

Ubuntu 24.04.1 LTS

### Database

SQLite 3

### Describe the bug

```text
2024/12/23 12:46:00 [ INFO] Gogs 0.13.1
2024/12/23 12:46:00 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

```

### To reproduce

Gogs 0.13.0 update to 0.13.1 File

### Expected behavior

 ``

### Additional context

```text
2024/12/23 11:51:22 [ INFO] Gogs 0.13.0
2024/12/23 11:51:22 [ INFO] Run mode: Production
2024/12/23 11:51:22 [ INFO] SSH server started on 0.0.0.0:3022
2024/12/23 11:51:23 [ INFO] Available on http://172.16.17.5:3000/
2024/12/23 12:46:00 [ INFO] Gogs 0.13.1
2024/12/23 12:46:00 [FATAL] [...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dafanasiev** [comment]
This is a bug with deps:

`0.13.0`: 
```sh
$ ./gogs --version
Gogs version 0.13.0

$ go version -m ./gogs |grep sqlite
	dep	github.com/mattn/go-sqlite3	v2.0.3+incompatible	h1:gXHsfypPkaMZrKbD5209QV9jbUTJKjyR5WD3HYQSd+U=
	dep	gorm.io/driver/sqlite	v1.4.2	h1:F6vYJcmR4Cnh0ErLyoY8JSfabBGyR0epIGuhgHJuNws=
```

and `0.13.1`:
```sh
$ ./gogs --version
Gogs version 0.13.1

$ go version -m ./gogs |grep sqlite
	dep	github.com/mattn/go-sqlite3	v1.14.24	h1:tpSp2G2KyMnnQu99ngJ47EIkWVmliIizyZBfPrBWDRM=
	dep	gorm.io/driver/sqlite	v1.4.2	h1:F6vYJcmR4Cnh0ErLyoY8JSfabBGyR0epIGuhgHJuNws=
```

because this change: https://github.com/gogs/gogs/commit/bd84b41843dbc5b6c18a3fc481a712022fe3a962#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L108

**Comment by unknwon** [comment]
Thanks for reporting! I will take a look, meanwhile, you can always compile from the source code directly.

**Comment by dafanasiev** [comment]
> Thanks for reporting! I will take a look, meanwhile, you can always compile from the source code directly.

recompile gives the same result, because of version in sum file. I think this is due to dependency solver changes in go.

**Comment by MaxKingPor** [comment]
> > Thanks for reporting! I will take a look, meanwhile, you can always compile from the source code directly.
> 
> recompile gives the same result, because of version in sum file. I think this is due to dependency solver changes in go.

I can use it after recompiling

```
$ go version
go version go1.23.4 linux/amd64
$ git branch
* release/0.13
$ gcc --version
gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by dafanasiev** [comment]
@MaxKingPor it's because auto-calculated CGO_ENABLED env.

But I think that we have two problems: with `go-sqlite3` version (downgraded) and with `CGO_ENABLED` (changed)

```sh
# 0.13.0
$ go version -m ./gogs | grep -P 'sqlite|CGO'
	dep	github.com/mattn/go-sqlite3	v2.0.3+incompatible	h1:gXHsfypPkaMZrKbD5209QV9jbUTJKjyR5WD3HYQSd+U=
	dep	gorm.io/driver/sqlite	v1.4.2	h1:F6vYJcmR4Cnh0ErLyoY8JSfabBGyR0epIGuhgHJuNws=
	build	CGO_ENABLED=1

# 0.13.1
$ go version -m ./gogs | grep -P 'sqlite|CGO'
	dep	github.com/mattn/go-sqlite3	v1.14.24	h1:tpSp2G2KyMnnQu99ngJ47EIkWVmliIizyZBfPrBWDRM=
	dep	gorm.io/driver/sqlite	v1.4.2	h1:F6vYJcmR4Cnh0ErLyoY8JSfabBGyR0epIGuhgHJuNws=
	build	CGO_ENABLED=0

```

**Comment by unknwon** [comment]
This is about `CGO_ENABLED=1` wasn’t explicitly set. SQLite driver isn’t having a downgrade, see its README.

**Comment by unknwon** [comment]
I am working on a new patch release 0.13.2, please follow update there if you're interested https://github.com/gogs/gogs/issues/7879
