### ISSUE TITLE
LDAP/SMTP/HTTPS protocol support

### ISSUE THREAD

**Issue by unknwon** [gogs/gogs#8]
- [x] LDAP protocol support
- [x] SMTP protocol support
- [x] HTTPS protocol support

**Comment by manycoding** [comment]
Hi, does gogs support git:// protocol?

**Comment by Unknwon** [comment]
@manycoding 

No, it does not.

**Comment by stonerl** [comment]
@manycoding not at the moment, but there is an open feature request.
