### ISSUE TITLE
Start server on different port than 3000

### ISSUE THREAD

**Issue by p4r4n0id** [gogs/gogs#97]
Hi There,

i need the option to start the gogs-server on a port of my choice. As many Sysadmins will say is that port 3000 is likely used by different services.
Thank you!

**Comment by ashtonhogan** [comment]
@Unknwon does this mean that you have to build your own? Isn't there an argument you can pass to `./gogs web [port]` instead?

**Comment by Unknwon** [comment]
@ashtonhogan read the very first line of the docs: https://gogs.io/docs/intro/faqs

**Comment by lk0606** [comment]
> https://github.com/gogits/gogs/blob/master/conf/app.ini#L20

I did this, but how pic effect,
port
- 13000:3000
wanna ip:13000, got ip:3000
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/43233310/160318501-978d52e4-7de9-4e5a-9965-ad713fac286f.png">
