### ISSUE TITLE
hooks support

### ISSUE THREAD

**Issue by vtolstov** [gogs/gogs#98]
May be the good think to provide hooks for each repo to get ability to build package or run tests...

**Comment by csu** [comment]
Does anyone know which hosted continuous integration services work with Gogs hooks?

**Comment by vtolstov** [comment]
Drone.io
26 мая 2015 г. 21:28 пользователь "Christopher Su" <notifications@github.com>
написал:

**Comment by csu** [comment]
@vtolstov Thanks!
